restatedev/restate

crates/invoker-api/src/status_handle.rs, crates/invoker-impl/src/invocation_task.rs, crates/invoker-impl/src/lib.rs, crates/invoker-impl/src/status_store.rs, crates/storage-query-datafusion/src/invocation_state/row.rs, crates/storage-query-datafusion/src/invocation_state/schema.rs, crates/storage-query-datafusion/src/status/row.rs, crates/storage-query-datafusion/src/status/schema.rs
[Observability] Extend sys_status and sys_invocation_state with endpoint_id
Summary:
This introduces two new columns in `sys_invocation_state`:
- `next_retry_at` Points to the next retry timestamp if a retry is scheduled for an invocation.
- `last_attempt_endpoint_id` The endpoint ID that was used for the last invocation attempt.
Also, a new column was added in `sys_status`:
- `pinned_endpoint_id` Indicates the endpoint ID that this invocation is _pinned_ to. If set, the invocation must continue to use this endpoint id even if other endpoints were installed that claim to host higher service revisions.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/913).
* #933
* #928
* __->__ #913
=> [Observability] Extend sys_status and sys_invocation_state with endpoint_id

crates/meta-rest-model/src/endpoints.rs, crates/meta/src/rest_api/endpoints.rs, crates/meta/src/service.rs, crates/schema-impl/src/lib.rs, crates/schema-impl/src/schemas_impl.rs, crates/schema-impl/src/service.rs
[Meta] Dry-run discovery and richer discovery response
Summary:
This introduces two important changes to the meta's REST API:
- A new `dry_run` attribute in `POST /endpoints` body to allow discovery without application.
- Response format of discovery to include the set of discovered methods, using the same structure that is returned in `GET services/{name}/`.
The updated response type unblocks the CLI work which visualizes the changes that a potential endpoint discovery will cause.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/928).
* #933
* __->__ #928
=> [Meta] Dry-run discovery and richer discovery response

Cargo.lock, cli/Cargo.toml, cli/src/app.rs, cli/src/commands/examples.rs, cli/src/commands/mod.rs
Command to download examples from the https://github.com/restatedev/examples repo.
The command queries the github latest release of the examples repo, and either uses the example name you manually provide, or starts an interactive prompt to select the example.
For testing I added an artifact to the latest examples release.
=> restate examples command

crates/storage-api/src/inbox_table/mod.rs, crates/storage-rocksdb/src/inbox_table/mod.rs, crates/storage-rocksdb/tests/inbox_table_test/mod.rs, crates/types/src/invocation.rs, crates/worker/src/partition/state_machine/command_interpreter.rs, crates/worker/src/partition/state_machine/effect_interpreter.rs, crates/worker/src/partition/state_machine/effects.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/storage/mod.rs
This PR adds the functionality to kill an inboxed service invocation. The way it works is the following:
1. Check whether an invocation is currently invoked.
2. If not, then check the inbox for the corresponding service invocation
3. If the inbox contains the service invocation, then fail it with a `KILLED_INVOCATION_ERROR` and delete the service invocation from the inbox.
This PR is based on #949.
This fixes #951.
=> Support killing of inboxed service invocations

.github/workflows/binaries.yml, .github/workflows/npm.yml, Cargo.lock, Cross.toml, crates/ingress-kafka/Cargo.toml, justfile, npm/.gitignore, npm/package.json.tmpl, npm/restate-server/package.json, npm/restate-server/src/index.ts, npm/restate-server/tsconfig.json, npm/restate/package.json, npm/restate/src/index.ts, npm/restate/tsconfig.json
Adds npm packages for each target for cli and server, and base packages that import these using optional dependencies (https://blog.orhun.dev/packaging-rust-for-npm/)
Cross.toml had to be set with some particular env vars to get cross compiles working properly (and sccached), and also had to disabvle the experimental cmake build for rdkafka, and ensure libz is statically compiled there too
Will plumb this into the release process as a followup
=> Cross compilation + NPM publish

crates/storage-api/src/journal_table/mod.rs, crates/storage-api/src/outbox_table/mod.rs, crates/storage-proto/proto/dev/restate/storage/v1/domain.proto, crates/storage-proto/src/lib.rs, crates/worker/src/network_integration.rs, crates/worker/src/partition/shuffle.rs, crates/worker/src/partition/state_machine/command_interpreter.rs, crates/worker/src/partition/state_machine/commands.rs, crates/worker/src/partition/state_machine/effects.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/storage/mod.rs, crates/worker/src/services.rs
This commit introduces the killing of child invocations when killing
an invocation. The way it works is by scanning the journal for un-
completed calls and then sending for these calls a kill command to
the corresponding PartitionProcessor.
This fixes https://github.com/restatedev/restate/issues/942.
This PR is based on #951 and #969.
=> Kill child invocations when killing an invocation

Cargo.lock, crates/service-protocol/service-protocol/dev/restate/service/protocol.proto, crates/service-protocol/src/codec.rs, crates/service-protocol/src/lib.rs, crates/service-protocol/src/message/encoding.rs, crates/types/src/journal/entries.rs
This PR requires restatedev/service-protocol#58 to be merged first.
This commit pulls in the latest service protocol changes.
It updates the server to handle GetState, Sleep and
PollInputStreamEntryMessage as fallible (having an error case).
This fixes https://github.com/restatedev/restate/issues/999.
=> Update server to work with new service protocol contract 

crates/base64-util/src/lib.rs, crates/service-protocol/src/awakeable_id.rs
Do not use padding in server-side base64 encoding
And make AwakeableId clone + display
=> Do not use padding in server-side base64 encoding

Cargo.lock, crates/invoker-impl/src/invocation_task.rs, crates/invoker-impl/src/lib.rs, crates/service-protocol/service-protocol/dev/restate/service/protocol.proto, crates/service-protocol/service-protocol/service-invocation-protocol.md, crates/service-protocol/src/message/encoding.rs, crates/service-protocol/src/message/header.rs, crates/service-protocol/src/message/mod.rs, crates/worker/src/partition/services/non_deterministic/mod.rs, crates/worker/src/partition/services/non_deterministic/remote_context.rs, justfile, tools/service-protocol-wireshark-dissector/Cargo.toml, tools/service-protocol-wireshark-dissector/src/lib.rs
Part of https://github.com/restatedev/service-protocol/issues/49
=> End of stream message

cli/src/app.rs, cli/src/cli_env.rs, cli/src/clients/datafusion_http_client.rs, cli/src/clients/metas_client.rs, cli/src/commands/whoami.rs
These are not entirely unrelated, but happy to split into two PRs if we'd rather reflect on how to do auth some more.
I didn't make the request timeout configurable. It seems like this should be passed in via the config file and/or a CLI switch override, but it seems that config file parsing is not implemented yet. Does it seem reasonable to add timeout as another member of `GlobalOpts`?
Should we have separate timeouts for meta requests vs. DataFusion queries? Seems reasonable and we might legitimately have longer-running DataFusion queries (though the open-ended nature of this is concerning in itself).
Auth tokens: it seems reasonable that in any future development, we would have some form of auth. Token auth passed as a bearer token is widespread and likely to continue being in use …
=> Add optional Bearer Token auth and a default HTTP request timeout

crates/storage-proto/proto/dev/restate/storage/v1/domain.proto, crates/storage-proto/src/lib.rs, crates/types/src/identifiers.rs
Storing the SocketAddr as octets instead of Strings will avoid
extra serde costs of allocating and parsing Strings.
This fixes https://github.com/restatedev/restate/issues/1020.
=> Store SocketAddr octets as bytes instead of String

crates/worker/src/partition/mod.rs, crates/worker/src/partition/state_machine/dedup.rs, crates/worker/src/partition/state_machine/effect_interpreter.rs, crates/worker/src/partition/state_machine/effects.rs, crates/worker/src/partition/state_machine/mod.rs
This commit makes the deduplication layer of the PartitionProcessor's state machine the outer layer. That way a sender can now more easily batch commands destined to the same PartitionProcessor with the same deduplication mode.
This fixes #1035.
=> Make deduplication the outer layer of the state machine

Cargo.lock, server/Cargo.toml, server/src/main.rs, server/src/rt.rs
Panics now emit error traces and renames restate threads
This adds a panic handler that attempts to log the panic info to via tracing error (if possible). It'll fallback to existing panic handlers if any.
This sets restate tokio thread names to unique names that becomes handy when debugging `rs:worker-X` where X is a counter.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1041).
* #1046
* __->__ #1041
=> Panics now emit error traces and renames restate threads

.github/workflows/npm.yml, npm/restate-server/package.json, npm/restate/package.json
Node uses x64, not x86_64, and we were neglecting to update the package imports
=> Fix npm automation

crates/timer/src/lib.rs, crates/timer/src/service/mod.rs, crates/timer/src/service/tests.rs, crates/worker/src/partition/leadership/action_collector.rs, crates/worker/src/partition/state_machine/actions.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/command_interpreter/tests.rs, crates/worker/src/partition/state_machine/effect_interpreter.rs, crates/worker/src/partition/types.rs
This commit adds timer::Service::remove_timer which allows to remove a
timer from the TimerService while it is running. Moreover, when cancelling
a timer, we also issue a timer deletion from RocksDB and removal from the
TimerService.
If the TimerService is currently loading new timers, we need to remember the
removed timer for the time of loading new timers to filter them out. After
leaving this state, we can forget the removed timers.
If the TimerSerivce is currently processing timers, we can directly remove
timers from the internal timer queue. If the removed timer is the last timer
in the current batch, then we need to update the batch end to reflect the
new state.
This PR is based on #1034 and fixes https://github.com/restatedev/restate/issues/1029.
=> Allow timers to be removed from running TimerService

crates/worker/src/lib.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/options.rs
This commit introduces an upper limit for the size of command batches that the PartitionProcessor can create and the maximum duration the batching can take before checking again the actuators for signals. This prevents the situation where the PartitionProcessor is starved because of too many commands being applied.
This fixes #1051.
=> Introduce max batch size and duration for PartitionProcessor

Cargo.lock, Cargo.toml, crates/ingress-grpc/src/metric_definitions.rs, crates/invoker-impl/src/lib.rs, crates/invoker-impl/src/metric_definitions.rs, crates/invoker-impl/src/state_machine_manager.rs, crates/node-ctrl/Cargo.toml, crates/node-ctrl/src/handler.rs, crates/node-ctrl/src/lib.rs, crates/node-ctrl/src/options.rs, crates/node-ctrl/src/prometheus_helpers.rs, crates/node-ctrl/src/service.rs, crates/node-ctrl/src/state.rs, crates/storage-rocksdb/src/lib.rs, crates/worker/src/lib.rs, crates/worker/src/metric_definitions.rs, server/src/app.rs
prefix metrics with restate_
We should namespace all our metrics with the application name, additionally, grouping invoker task counters and using status as label instead of a counter per status (better ergonomics)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1077).
* __->__ #1077
* #1073
=> prefix metrics with restate_

Cargo.lock, crates/storage-rocksdb/src/lib.rs, server/Cargo.toml, server/src/config.rs
- Add a new memory options struct at the top level which is a bit of a special case; it needs to load before all other config sources in order to change the defaults for rocksdb caches without overriding user-specified values.
- Add a limit field to this memory options, and default it to 3GiB. We may one day also care about a memory request value here.
- Do math to calculate the two in memory rocksdb caches such that at 3GiB, the values are the same as they were previously hardcoded, but they otherwise scale linearly with the global memory limit
=> Support MEMORY_LIMIT global setting

Cargo.lock, crates/admin/src/rest_api/mod.rs, crates/admin/src/rest_api/services.rs, crates/meta-rest-model/Cargo.toml, crates/meta-rest-model/src/services.rs, crates/storage-api/src/inbox_table/mod.rs, crates/storage-proto/proto/dev/restate/storage/v1/domain.proto, crates/storage-proto/src/lib.rs, crates/storage-query-datafusion/src/inbox/row.rs, crates/storage-query-datafusion/src/inbox/table.rs, crates/storage-rocksdb/Cargo.toml, crates/storage-rocksdb/src/inbox_table/mod.rs, crates/storage-rocksdb/tests/inbox_table_test/mod.rs, crates/storage-rocksdb/tests/integration_test.rs, crates/types/src/state_mut.rs, crates/worker-api/src/lib.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/command_interpreter/tests.rs, crates/worker/src/partition/state_machine/commands.rs, crates/worker/src/partition/state_machine/effect_interpreter.rs, crates/worker/src/partition/state_machine/effects.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/storage/mod.rs, crates/worker/src/services.rs, tools/xtask/src/main.rs
This commit adds support for applying Command::ExternalStateMutation commands
in the PP's state machine. The way it works is the following: Upon receiving
the command, the CommandInterpreter checks whether the service instance is
currently locked. If so, then the ExternalStateMutation is enqueued into the
inbox. If not, then the ExternalStateMutation is directly applied by the
EffectInterpreter. Upon completing an invocation, the EffectInterpreter will
now drain the inbox until it finds the next ServiceInvocation. All encountered
ExternalStateMutations will be applied when searching for the next
ServiceInvocation.
The inbox now needs to be able to store ExternalStateMutations and
ServiceInvocations. That's why this commit updates the InboxEntry type to
support both variants. The …
=> Let PartitionProcessor apply Command::ExternalStateMutation commands 

Cargo.lock, Cargo.toml
This library has an ancient restriction against overriding global malloc in musl targets. This is no longer necessary, so we fork to remove it until upstream considers our change
https://github.com/tikv/jemallocator/pull/70
=> Use forked tikv-jemallocator to support musl fully

docker/Dockerfile
We do not want to have differences between binary releases and docker releases, because we will be more likely to miss bugs that only occur in glibc or musl. One such bug re atomics has already been found!
=> Use musl for binaries in docker containers

crates/worker/src/partition/mod.rs
This is producing massive numbers of backtraces when rust_backtrace=1 which appears slow under musl arm
=> Avoid making error on every actuator output

cli/src/clients/datafusion_helpers.rs
[CLI] BackgroundInvoke icon fix
At the moment, the CLI shows the Background invoke with "paused" icon, background invoke is a non-completable entry and it should appear as "done" when it's journalled.
=> [CLI] BackgroundInvoke icon fix

crates/admin/src/rest_api/error.rs, crates/admin/src/rest_api/subscriptions.rs, crates/ingress-kafka/src/consumer_task.rs, crates/ingress-kafka/src/subscription_controller.rs, crates/meta-rest-model/src/subscriptions.rs, crates/meta/src/service.rs, crates/schema-api/src/lib.rs, crates/schema-impl/src/lib.rs, crates/schema-impl/src/schemas_impl/mod.rs, crates/schema-impl/src/schemas_impl/subscription.rs, crates/schema-impl/src/subscriptions.rs, crates/types/src/id_util.rs, crates/types/src/identifiers.rs, crates/types/src/lib.rs, crates/types/src/macros.rs, crates/types/src/subscription.rs, crates/worker-api/src/lib.rs, crates/worker/src/subscription_integration.rs, tools/xtask/src/main.rs
Subscription ID to follow resource ID scheme
This introduces a formal format for subscription IDs and moves everything to use the `SubscriptionId` newtype (implements ResourceId)
An example subscription id: `sub_15VqmTOnXH3Vv2pl5HOG7Ua` which follows the same scheme.
The most notable change is that we now don't accept `id` from the user when creating subscriptions.
Closes #1117
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1119).
* #1121
* #1120
* __->__ #1119
=> Subscription ID to follow resource ID scheme

cli/src/ui/invocations.rs, crates/service-protocol/src/awakeable_id.rs, crates/service-protocol/src/codec.rs, crates/types/src/id_util.rs, crates/types/src/lib.rs, crates/worker/src/invoker_integration.rs, crates/worker/src/partition/services/deterministic/awakeables.rs, crates/worker/src/partition/services/non_deterministic/remote_context.rs, crates/worker/src/partition/state_machine/command_interpreter/tests.rs
Awakeable ID versioning
Awakeable IDs have special encoding but the prefix now follows the standard `ResourceId` prefix formatting.
The ID is still base64 after the prefix (`prom_1` which includes the version)
Example for how the awakeable id looks like: `prom_1AAAAAAAAAFwBjUHUt83u10Ef50OZUpB9AAAAAg`
Note, this is breaking change and both Java and JavaScript SDKs will be updated accordingly
=> Awakeable ID versioning

Cargo.lock, crates/benchmarks/src/lib.rs, crates/cluster-controller/proto/cluster_controller.proto, crates/cluster-controller/src/handler.rs, crates/cluster-controller/src/proto.rs, crates/node/src/lib.rs, crates/types/src/identifiers.rs, crates/types/src/lib.rs, crates/types/src/node_id.rs, server/src/config.rs
Generational NodeID
This introduces generational node ids. A `NodeId` type can either represent a plain id, or an id with generation.
Nodes with stable ID will get an increasing generation on startup, this will be used to fence off work meant for
older instances of the node (e.g. responses for an older ingress instance), or to ensure we are sending messages
to the correct instance at send time.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1164).
* #1172
* #1171
* #1168
* #1166
* __->__ #1164
=> Generational NodeID

Cargo.lock, crates/benchmarks/src/lib.rs, crates/node-ctrl-proto/build.rs, crates/node-ctrl-proto/proto/node_ctrl.proto, crates/node-ctrl-proto/proto/worker.proto, crates/node-ctrl-proto/src/lib.rs, crates/node-ctrl/src/handler/mod.rs, crates/node-ctrl/src/handler/node_ctrl.rs, crates/node-ctrl/src/handler/worker.rs, crates/node-ctrl/src/options.rs, crates/node-ctrl/src/service.rs, crates/node-ctrl/src/state.rs, crates/node/Cargo.toml, crates/node/src/lib.rs, crates/node/src/options.rs, crates/types/src/nodes_config.rs, server/Cargo.toml, server/src/config.rs, server/src/main.rs
This commit changes the Node implementation to make the worker role optional. This also includes the node-ctrl service which can run a worker grpc service if the worker role is configured. If a node does not run the cluster controller role locally, then one needs to configure it with a cluster_controller_address.
=> Make the worker role optional

crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglets/memory_loglet.rs, crates/bifrost/src/loglets/mod.rs, crates/bifrost/src/options.rs, crates/consensus/src/lib.rs, crates/network/src/lib.rs, crates/network/src/routing/ingress.rs, crates/network/src/routing/mod.rs, crates/network/src/routing/partition_processor.rs, crates/network/src/routing/shuffle.rs, crates/network/src/routing/tests.rs, crates/types/src/message.rs, crates/worker/src/lib.rs, crates/worker/src/network_integration.rs, crates/worker/src/partitioning_scheme.rs, crates/worker/src/services.rs, crates/worker/src/util.rs
Partition Table is not async and routing is based on partition id
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1178).
* __->__ #1178
* #1177
=> Partition Table is not async and routing is based on partition id

Cargo.lock, crates/node-services/proto/cluster_controller.proto, crates/node-services/proto/node_ctrl.proto, crates/node/src/lib.rs, crates/node/src/options.rs, crates/node/src/server/handler/cluster_controller.rs, crates/node/src/server/handler/node_ctrl.rs, crates/pb/src/lib.rs, crates/types/Cargo.toml, crates/types/src/logs.rs, crates/types/src/node_id.rs, crates/types/src/nodes_config.rs
Global access to my NodeId and NodesConfiguration
`NodeId::my_node_id()` and `NodesConfiguration::current()` / `NodesConfiguration::current_version()`
- Stubs out the creation of nodes configuration after attachment until we move that to cluster controller.
- Addeded nodes_config_id and my_node_id in GetIdent
Test Plan:
Tests + grpcurl
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1179).
* #1181
* __->__ #1179
=> Global access to my NodeId and NodesConfiguration

Cargo.lock, Cargo.toml, crates/service-client/Cargo.toml
Relies on a forked aws-sdk-rust to include https://github.com/smithy-lang/smithy-rs/pull/3416
Because aws-sdk-rust has a *massive* repo footprint, i have hosted a truncated-history fork at https://github.com/restatedev/aws-sdk-rust temporarily. It would be nice if Cargo supported shallow clones, but it does not
=> Eks pod identity implementation

Cargo.lock, Cargo.toml, crates/admin/Cargo.toml, crates/admin/src/service.rs, crates/benchmarks/Cargo.toml, crates/benchmarks/benches/throughput_parallel.rs, crates/benchmarks/benches/throughput_sequential.rs, crates/benchmarks/src/lib.rs, crates/cluster-controller/Cargo.toml, crates/cluster-controller/src/service.rs, crates/meta/Cargo.toml, crates/meta/src/service.rs, crates/node/Cargo.toml, crates/node/src/lib.rs, crates/node/src/roles/cluster_controller.rs, crates/node/src/roles/mod.rs, crates/node/src/roles/worker.rs, crates/node/src/server/mod.rs, crates/node/src/server/service.rs, crates/task-center/Cargo.toml, crates/task-center/src/lib.rs, crates/task-center/src/types.rs, crates/wal-protocol/Cargo.toml, crates/worker/src/lib.rs, server/Cargo.toml, server/src/main.rs, server/src/signal.rs
Task Center init
This introduces a central system to manage long-running and background restate async tasks.
The core of this proposal is to help us lean more towards spawning self-contained tasks that
are addressable, trackable, and cancellable, than current deep future poll trees.
It also allows nice possibilities like:
- Limited structured concurrency (no auto-waiting for children though)
- Graceful cancellations/shutdown reduces the risk of cancellation-unsafe drops
- Potentially less memory, deep nested future state machines become shallower.
- A single place where we can auto-propagate tracing context, flag tasks by priority, schedule tasks on different runtime, provide observability of what kind of tasks are running, etc.
- Scoped tasks allow scoped cancellation. (cooperatively …
=> Task Center init

crates/node/src/lib.rs, crates/node/src/options.rs, crates/node/src/roles/admin.rs, crates/node/src/roles/mod.rs, crates/types/src/nodes_config.rs
Rename cluster controller role into admin role
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1198).
* #1200
* __->__ #1198
=> Rename cluster controller role into admin role

Cargo.lock, crates/node-services/Cargo.toml, crates/node-services/build.rs, crates/node-services/proto/cluster_ctrl_svc.proto, crates/node-services/proto/common.proto, crates/node-services/proto/node_svc.proto, crates/node-services/src/lib.rs, crates/node/src/network_server/service.rs, crates/pb/Cargo.toml, crates/pb/build.rs, crates/pb/src/lib.rs
Move common to node-services
node-services protocol is meant for internal restate communication. pb/ appears to go beyond the internal cluster scope.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1211).
* #1214
* #1213
* #1212
* __->__ #1211
=> Move common to node-services

Cargo.lock, crates/tracing-instrumentation/Cargo.toml, crates/tracing-instrumentation/src/lib.rs
This can be used for sending traces to a particular tenant in Tempo
Hoists the logic in https://github.com/open-telemetry/opentelemetry-rust/pull/1377 as this is not released yet
=> Support adding tracing metadata via env var

Cargo.lock, Cargo.toml
https://github.com/restatedev/jemallocator/commit/7c32f6e3d6ad5e4e492cc08d6bdb8307acf9afa0
=> Update pinned tikv-jemallocator to fix CI

crates/meta-rest-model/src/deployments.rs, crates/meta-rest-model/src/services.rs, crates/schema-api/Cargo.toml, crates/schema-api/src/lib.rs, crates/schema-impl/src/deployment.rs, crates/schema-impl/src/lib.rs, crates/schema-impl/src/schemas_impl/mod.rs, crates/schema-impl/src/schemas_impl/service.rs, crates/storage-query-datafusion/src/deployment/table.rs, crates/types/src/identifiers.rs
Fix #1218
`ComponentMetadataResolver#resolve_latest_component_handler` will replace key extraction from now on, and will be used by invoker and ingress to build the `ServiceInvocation` struct.
=> Introduce new API to resolve `ComponentMetadata`

crates/invoker-impl/src/invocation_task.rs, crates/service-protocol/src/message/encoding.rs, crates/service-protocol/src/message/mod.rs, crates/worker/src/partition/services/non_deterministic/remote_context.rs
=> Propagate key in StartMessage

Cargo.lock, crates/service-protocol/Cargo.toml, crates/service-protocol/src/discovery.rs
The TS SDK seems to send incorrect file descriptors for google/protobuf/descriptor.proto and dev/restate/ext.proto. This commit patches these files on the server as a temporary solution until we remove the need for shipping Protobuf file descriptors.
This fixes #1262.
=> Patch google/protobuf/descriptor.proto and dev/restate/ext.proto

Cargo.lock, crates/core/Cargo.toml, crates/core/src/lib.rs, crates/core/src/metadata/manager.rs, crates/core/src/test_env.rs
TestEnv support for mock networking
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1264).
* #1274
* #1269
* #1268
* __->__ #1264
=> TestEnv support for mock networking

crates/ingress-dispatcher/src/dispatcher.rs, crates/ingress-dispatcher/src/lib.rs, crates/ingress-http/src/handler/awakeables.rs, crates/ingress-http/src/handler/component_handler.rs, crates/ingress-http/src/handler/error.rs, crates/ingress-http/src/handler/tests.rs, crates/ingress-http/src/server.rs, crates/ingress-kafka/src/consumer_task.rs, crates/service-protocol/src/codec.rs, crates/service-protocol/src/message/encoding.rs, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-proto/proto/dev/restate/storage/v1/domain.proto, crates/storage-proto/src/lib.rs, crates/storage-rocksdb/tests/integration_test.rs, crates/types/src/invocation.rs, crates/types/src/journal/raw.rs, crates/worker/src/partition/services/deterministic/proxy.rs, crates/worker/src/partition/services/non_deterministic/idempotent_invoker.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/effect_interpreter.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/types.rs
=> Headers passthrough

Cargo.lock, crates/ingress-http/src/handler/error.rs, crates/pb/build.rs, crates/pb/src/lib.rs, crates/types/Cargo.toml, crates/types/src/errors.rs, crates/types/src/invocation.rs, crates/types/src/journal/entries.rs, crates/worker/src/invoker_integration.rs, crates/worker/src/partition/services/deterministic/awakeables.rs, crates/worker/src/partition/services/deterministic/mod.rs, crates/worker/src/partition/services/non_deterministic/mod.rs, crates/worker/src/partition/state_machine/command_interpreter/tests.rs, crates/worker/src/partition/state_machine/mod.rs
Previously the response error codes were related to gRPC status codes. From now on, we allow any HTTP status code as output. Fix #1231
=> Fix Response error code data model

Cargo.lock, cli/src/ui/mod.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/error.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglets/file_loglet.rs, crates/bifrost/src/loglets/memory_loglet.rs, crates/bifrost/src/metadata.rs, crates/bifrost/src/types.rs, crates/bifrost/src/watchdog.rs, crates/core/src/task_center.rs, crates/worker/src/lib.rs, crates/worker/src/partition/mod.rs
Misc Improvements
This covers a pseudo-random number of improvements:
- Some logging changes (especially around leadership changes)
- Change number of default partitions to 64
- Use unix timestamp as temporary leader epoch
- random bits related to this stack of diffs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1301).
* #1302
* __->__ #1301
=> Misc Improvements

Cargo.lock, Cargo.toml, crates/benchmarks/src/lib.rs, crates/core/src/task_center_types.rs, crates/grpc-util/src/lib.rs, crates/metadata-store/Cargo.toml, crates/metadata-store/src/lib.rs, crates/metadata-store/src/local/mod.rs, crates/metadata-store/src/local/options.rs, crates/metadata-store/src/local/store.rs, crates/metadata-store/src/local/tests.rs, crates/node/Cargo.toml, crates/node/src/lib.rs, crates/node/src/options.rs, crates/node/src/roles/worker.rs, crates/types/Cargo.toml, crates/types/src/lib.rs, crates/types/src/metadata_store.rs, crates/types/src/node_id.rs, crates/types/src/nodes_config.rs, crates/types/src/retries.rs, server/src/main.rs, tools/xtask/src/main.rs
This commit integrates the local metadata store into the Node. It achieves it by introducing the MetadataStore role and requiring that the bootstrap node runs it. The role is the first started role. It runs the LocalMetadataStoreService. After starting the MetadataStore, the node tries to upsert the new NodeConfig with which it announces its NodeId, address and roles it runs.
This fixes #1296.
=> Integrate local metadata store into the Node

Cargo.lock, Cargo.toml, crates/benchmarks/src/lib.rs, crates/core/src/task_center_types.rs, crates/grpc-util/src/lib.rs, crates/metadata-store/Cargo.toml, crates/metadata-store/src/lib.rs, crates/metadata-store/src/local/mod.rs, crates/metadata-store/src/local/options.rs, crates/metadata-store/src/local/store.rs, crates/metadata-store/src/local/tests.rs, crates/node/Cargo.toml, crates/node/src/lib.rs, crates/node/src/options.rs, crates/node/src/roles/worker.rs, crates/types/Cargo.toml, crates/types/src/lib.rs, crates/types/src/metadata_store.rs, crates/types/src/node_id.rs, crates/types/src/nodes_config.rs, crates/types/src/retries.rs, crates/worker/src/lib.rs, server/src/main.rs, tools/xtask/src/main.rs
This commit tries to fetch the FixedPartitionTable from the metadata
store. If it is not present, then it will try to store an instance
of it.
This fixes https://github.com/restatedev/restate/issues/1308.
This PR is based on #1307.
=> Fetch or insert fixed partition table

crates/grpc-util/Cargo.toml, crates/ingress-dispatcher/src/dispatcher.rs, crates/storage-api/src/outbox_table/mod.rs, crates/storage-api/src/timer_table/mod.rs, crates/storage-proto/proto/dev/restate/storage/v1/domain.proto, crates/storage-proto/src/lib.rs, crates/storage-rocksdb/src/lib.rs, crates/storage-rocksdb/tests/integration_test.rs, crates/storage-rocksdb/tests/timer_table_test/mod.rs, crates/types/src/invocation.rs, crates/wal-protocol/src/effects.rs, crates/wal-protocol/src/timer.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/services/deterministic/proxy.rs, crates/worker/src/partition/services/non_deterministic/idempotent_invoker.rs, crates/worker/src/partition/services/non_deterministic/mod.rs, crates/worker/src/partition/shuffle.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/command_interpreter/tests.rs, crates/worker/src/partition/state_machine/effects.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/types.rs
=> Move scheduling of delayed ServiceInvocations from caller PP to callee PP.

Cargo.lock, server/Cargo.toml, server/src/config.rs, server/src/main.rs
Enables toml configs
- Use file_exact because file searches parent directories automatically for the config, definitely not the behaviour we want.
- If config file was not found, it silently ignored the supplied --config-file argument, this was fixed
- Support loading toml files
- Makes it clear in logs when we are starting with the built-in default config.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1320).
* #1325
* #1322
* #1321
* __->__ #1320
=> Enables toml configs

Cargo.lock, crates/bifrost/src/loglet.rs, crates/types/src/nodes_config.rs, server/Cargo.toml, server/src/config.rs, server/src/main.rs
[1/n] Use snake_case for all configuration enums
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1321).
* #1328
* #1325
* #1322
* __->__ #1321
=> [1/n] Use snake_case for all configuration enums

crates/types/src/ingress.rs, crates/types/src/invocation.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/services/deterministic/mod.rs, crates/worker/src/partition/services/non_deterministic/idempotent_invoker.rs, crates/worker/src/partition/services/non_deterministic/mod.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/effects.rs, crates/worker/src/partition/types.rs
See `create_response_message` signature. This removes the need to store additional data when implementing #1324
=> Remove FullInvocationId as dependency to send invocation responses

clippy.toml, crates/service-protocol/src/codec.rs, crates/storage-api/src/idempotency_table/mod.rs, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-api/src/lib.rs, crates/storage-proto/proto/dev/restate/storage/v1/domain.proto, crates/storage-proto/src/lib.rs, crates/storage-query-datafusion/src/invocation_status/row.rs, crates/storage-rocksdb/src/idempotency_table/mod.rs, crates/storage-rocksdb/src/lib.rs, crates/storage-rocksdb/tests/idempotency_table_test/mod.rs, crates/storage-rocksdb/tests/integration_test.rs, crates/storage-rocksdb/tests/invocation_status_table_test/mod.rs, crates/types/src/identifiers.rs, crates/types/src/invocation.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/effect_interpreter.rs, crates/worker/src/partition/state_machine/mod.rs
Based on https://github.com/restatedev/restate/pull/1331, This PR performs the required changes to the PP storage to implement the idempotency business logic. Part of #1324.
* `IdempotencyTable`:
* Store the mapping `(PP key + component name + [virtual object key]? + handler name + Idempotency key) -> InvocationId`. The `InvocationMetadata` struct is meant to hold eventual additional metadata in future to validate subsequent invocations to the same idempotency key.
* `InvocationStatusTable`:
* Now `InvocationMetadata` can store multiple response_sinks. This is required to be able to deliver back the response to multiple ingress nodes. The ingress dispatcher themself will handle routing between multiple handlers (next PRs).
* Add `InvocationStatus::Completed` to retain result of the …
=> Add IdempotencyTable and modify InvocationStatus table

crates/storage-api/src/inbox_table/mod.rs, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-proto/proto/dev/restate/storage/v1/domain.proto, crates/storage-proto/src/lib.rs, crates/storage-query-datafusion/src/inbox/row.rs, crates/storage-query-datafusion/src/inbox/schema.rs, crates/storage-query-datafusion/src/invocation_status/row.rs, crates/storage-rocksdb/src/inbox_table/mod.rs, crates/storage-rocksdb/tests/inbox_table_test/mod.rs, crates/storage-rocksdb/tests/integration_test.rs, crates/storage-rocksdb/tests/invocation_status_table_test/mod.rs, crates/types/src/invocation.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/command_interpreter/tests.rs, crates/worker/src/partition/state_machine/effect_interpreter.rs, crates/worker/src/partition/state_machine/effects.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/storage/mod.rs
Store the metadata about the inboxed invocation in the invocation status table.
This simplifies a bunch of problems, such as terminating inboxed invocations and the upcoming issue of inboxed idempoten invocations (described in  https://github.com/restatedev/restate/pull/1326)
=> InvocationStatus::Inboxed

Cargo.lock, Cargo.toml, crates/service-client/Cargo.toml
The AWS libraries now contain my EKS pod identity contribution:
https://github.com/awslabs/aws-sdk-rust/blob/main/CHANGELOG.md#march-13th-2024
So we can update to use them instead of my forked repo
=> Update AWS dependencies

server/src/config_loader.rs
If there is only one service client, we only need to set this once
=> Remove duplicate AWS_EXTERNAL_ID

crates/ingress-dispatcher/src/dispatcher.rs, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-api/src/timer_table/mod.rs, crates/storage-proto/proto/dev/restate/storage/v1/domain.proto, crates/storage-proto/src/lib.rs, crates/storage-query-datafusion/src/invocation_status/row.rs, crates/storage-rocksdb/tests/integration_test.rs, crates/types/src/errors.rs, crates/types/src/invocation.rs, crates/wal-protocol/src/lib.rs, crates/wal-protocol/src/timer.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/leadership/action_collector.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/services/deterministic/proxy.rs, crates/worker/src/partition/services/non_deterministic/idempotent_invoker.rs, crates/worker/src/partition/state_machine/actions.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/command_interpreter/tests.rs, crates/worker/src/partition/state_machine/effect_interpreter.rs, crates/worker/src/partition/state_machine/effects.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/storage/mod.rs, crates/worker/src/partition/types.rs
Part of #1324, based on #1334.
This PR implements the idempotent invocation business logic. This logic is triggered when the field `ServiceInvocation.idempotency` is set.
In a followup PR I'll finally wire-up this field with the ingress and schema registry (to override the default idempotency retention timer).
=> Implement business logic of idempotent invocations

crates/ingress-kafka/src/subscription_controller.rs, crates/node/src/roles/admin.rs, crates/schema-api/src/lib.rs, crates/types/src/config/ingress.rs, crates/types/src/config/kafka.rs, crates/worker/src/lib.rs, crates/worker/src/subscription_integration.rs
Refactor kafka config
Flattens kafka's configuration. The configuration now looks like this:
```
...
[[ingress.kafka_clusters]]
name = "cluster-1"
brokers = ["localhost:9092"]
...
any_additional_option = "value"
[[ingress.kafka_clusters]]
name = "cluster-2"
brokers = ["remote_host:9092"]
```
=> Refactor kafka config

Cargo.lock, crates/admin/src/schema_registry/mod.rs, crates/admin/src/schema_registry/updater.rs, crates/core/src/metadata/manager.rs, crates/core/src/metadata/mod.rs, crates/node-protocol/Cargo.toml, crates/node-protocol/src/metadata.rs, crates/node/src/lib.rs, crates/node/src/roles/worker.rs, crates/schema/Cargo.toml, crates/schema/src/component.rs, crates/schema/src/deployment.rs, crates/schema/src/invocation_target.rs, crates/schema/src/lib.rs, crates/schema/src/subscriptions.rs, crates/worker/src/lib.rs
This commit removes the unnecessary SchemaView indirection that
was part of the WorkerRole. Instead, Metadata now directly offers
an UpdatingSchemaInformation object which an be passed down to
users.
This fixes https://github.com/restatedev/restate/issues/1367.
This PR is based on #1361.
=> Remove unnecessary SchemaView indirection

Cargo.lock, crates/ingress-dispatcher/src/dispatcher.rs, crates/ingress-dispatcher/src/lib.rs, crates/ingress-http/Cargo.toml, crates/ingress-http/src/handler/component_handler.rs, crates/ingress-http/src/handler/error.rs, crates/ingress-http/src/handler/tests.rs
Fix #1235
You can pass a duration as query parameter either as:
`delay={ISO8601 string}` or `delaySec={number}`.
E.g: `delay=PT1H30M` or `delaySec=120`.
=> Support adding delay to send requests through the ingress

crates/service-client/src/http.rs, crates/service-client/src/lib.rs, crates/service-client/src/request_identity/mod.rs, crates/service-client/src/request_identity/v1.rs, crates/types/src/config/common.rs, crates/types/src/config/http.rs
There is no particularly good reason not to just add these JWTs to all types of requests. Yes, in Lambda there is less of a 'public internet exposed' threat model, but still it could be useful defense in depth
Moreover, sdk usability is better if the JWT is sent irrelevant of the channel. For example, switching between GCF (which is over public HTTPs, but still uses the lambdaesque SDK apis) and Lambda should not require you to remove the public key.
Pr just lifts some logic out of http.rs into lib.rs
=> Add request identity v1 to lambda calls

crates/core/src/metadata_store/mod.rs, crates/node/src/lib.rs, crates/types/src/config/common.rs
This commit restricts Nodes to only insert NodesConfiguration, PartitionTable and Logs configuration if in bootstrapping mode. Note that updating an existing NodesConfiguration is still possible if not bootstrapping.
This fixes #1371.
=> Only insert NodesConfiguration, PartitionTable and Logs configuration if bootstrapping

Cargo.lock, crates/bifrost/Cargo.toml, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglets/local_loglet/log_store.rs, crates/bifrost/src/loglets/local_loglet/provider.rs, crates/core/src/task_center_types.rs, crates/node/src/network_server/handler/mod.rs, crates/rocksdb/src/db_manager.rs, crates/rocksdb/src/error.rs, crates/rocksdb/src/lib.rs, crates/types/src/config/common.rs, server/src/main.rs
Better rocksdb shutdown
- Shutdown rocksdb after all server components have finished
- Parallel shutdown requests
- Logging of individual database shutdowns
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1383).
* __->__ #1383
* #1382
=> Better rocksdb shutdown

Cargo.lock, crates/benchmarks/Cargo.toml, crates/benchmarks/benches/throughput_parallel.rs, crates/benchmarks/benches/throughput_sequential.rs, crates/benchmarks/src/lib.rs, crates/bifrost/Cargo.toml, crates/bifrost/src/loglets/local_loglet/log_store_writer.rs, crates/bifrost/src/loglets/local_loglet/metric_definitions.rs, crates/bifrost/src/loglets/local_loglet/mod.rs, crates/bifrost/src/loglets/local_loglet/provider.rs, crates/storage-rocksdb/benches/basic_benchmark.rs, crates/types/src/config/bifrost.rs
Quick patch latency issues
According to my test, this takes a simple wrk load test result from ~10rps to ~700qps
before:
```
~/w/r/sdk-java ❯❯❯ wrk -t 15 -c 25 http://localhost:8080/Counter/my-counter/get
Running 10s test @ http://localhost:8080/Counter/my-counter/get
15 threads and 25 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     1.20s   230.15ms   1.34s    90.68%
Req/Sec     0.14      0.56     4.00     91.53%
118 requests in 10.09s, 26.16KB read
Requests/sec:     11.69
Transfer/sec:      2.59KB
```
after:
```
~/w/r/sdk-java ❯❯❯ wrk -t 15 -c 25 http://localhost:8080/Counter/my-counter/get
Running 10s test @ http://localhost:8080/Counter/my-counter/get
15 threads and 25 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    18.01ms    2.98ms …
```
=> Quick patch latency issues

Cargo.lock, Cargo.toml, crates/ingress-http/Cargo.toml, crates/ingress-http/src/layers/tracing_context_extractor.rs, crates/ingress-kafka/Cargo.toml, crates/ingress-kafka/src/consumer_task.rs, crates/invoker-impl/Cargo.toml, crates/invoker-impl/src/invocation_task.rs, crates/storage-proto/Cargo.toml, crates/storage-proto/src/lib.rs, crates/tracing-instrumentation/Cargo.toml, crates/tracing-instrumentation/src/lib.rs, crates/tracing-instrumentation/src/processor.rs, crates/tracing-instrumentation/src/tracer.rs, crates/types/Cargo.toml, crates/types/src/identifiers.rs, crates/types/src/invocation.rs, crates/worker/Cargo.toml, crates/worker/src/partition/state_machine/effects.rs, server/src/main.rs
otel has been released with the changes we needed, we can now avoid parsing header env var manually.
Fixes #1217
=> Update opentelemetry libraries

crates/invoker-api/src/handle.rs, crates/invoker-impl/src/input_command.rs, crates/invoker-impl/src/invocation_state_machine.rs, crates/invoker-impl/src/invocation_task.rs, crates/invoker-impl/src/lib.rs, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-rocksdb/src/invocation_status_table/mod.rs, crates/storage-rocksdb/tests/invocation_status_table_test/mod.rs, crates/types/src/identifiers.rs, crates/types/src/invocation.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/state_machine/actions.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/effect_interpreter.rs, crates/worker/src/partition/state_machine/effects.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/storage/mod.rs, crates/worker/src/partition/types.rs
Part of #1329
* Removed the usage of FullInvocationId for tracing the state machine effects. We now also try to provide more tracing info whenever possible (e.g. in case there's an InvocationId but not an InvocationTarget available)
* Removed the usage of ServiceId in Action::Invoke
* Now InvocationStatusTable#invoked_invocations returns tuple (invocation_id, invocation_target)
=> More removal of old IDs

crates/invoker-api/src/entry_enricher.rs, crates/invoker-impl/src/invocation_task.rs, crates/invoker-impl/src/lib.rs, crates/storage-rocksdb/tests/invocation_status_table_test/mod.rs, crates/types/src/identifiers.rs, crates/types/src/invocation.rs, crates/worker/src/invoker_integration.rs, crates/worker/src/partition/state_machine/command_interpreter/tests.rs, crates/worker/src/partition/state_machine/mod.rs
With the new `InvocationTarget` introduced with https://github.com/restatedev/restate/issues/1329, we now face the issue that we won't have a `ServiceId` every time for any invocation, even the ones targeting regular services. This means that in case a GetState is sent from the sdk for a service, the runtime won't know what to do with it. This adds a check to verify that no SDK misbehaves, hence in the PartitionProcessor we can assume we always have a `ServiceId` once when we see a state related journal entry.
Also massages a bit the constructors of `InvocationId`.
Related (old) issue: https://github.com/restatedev/restate/issues/287
Based on https://github.com/restatedev/restate/pull/1405
=> Check whether the state entry types are valid for the given InvocationTarget

crates/bifrost/src/loglets/local_loglet/log_store.rs, crates/rocksdb/src/db_manager.rs, crates/rocksdb/src/lib.rs, crates/storage-rocksdb/src/lib.rs, crates/types/src/config/common.rs, crates/types/src/config/rocksdb.rs
[RocksDb] shared env and config updates
- Move rocksdb sizing to the environment instead of per-database control (they used to override each other anyway)
- Enable Direct IO
- StatisticsLevel is configurable
- default column family explicit attachement to global block cache (saves 32MB of RSS per database)
- More configuration keys
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1424).
* #1433
* #1432
* #1431
* #1427
* __->__ #1424
=> [RocksDb] shared env and config updates

Cargo.lock, Cargo.toml, crates/bifrost/src/loglets/local_loglet/log_store.rs, crates/bifrost/src/loglets/local_loglet/log_store_writer.rs, crates/bifrost/src/loglets/local_loglet/mod.rs, crates/metadata-store/src/local/store.rs, crates/node/src/network_server/handler/mod.rs, crates/rocksdb/src/db_manager.rs, crates/rocksdb/src/lib.rs, crates/rocksdb/src/rock_access.rs, crates/storage-rocksdb/src/lib.rs, crates/storage-rocksdb/src/writer.rs
Use restate's rust-rocksdb writebatch by ref
In this PR we start to use our own fork of rust-rocksdb, it seems that the number of changes we will need over time might cause us to diverge significantly, but we will try and contribute back as much as possible. For now, I've added the following optimizations:
- Use writebatch by ref, this enables retries when sync writes might block on IO
- Use parking_lot's RwLock (a couple orders of magnitude faster than std's RwLock in non-contended case which is our common path
- Use smartstring for the BTreeMap, a small allocation optimization but worth doing on this hot access path since we might run a large number of Cfs.
- Allow rocksdb to return the list of open column families to avoid our own copy.
---
Stack created …
=> Use restate's rust-rocksdb writebatch by ref

crates/storage-api/src/invocation_status_table/mod.rs, crates/worker/src/partition/state_machine/effect_interpreter.rs
Fix #1447. Now we update timestamps when:
* transitioning from inboxed to in-flight
* transitioning from in-flight to completed
* adding response sinks
* setting the deployment id
=> Improve modified_at field in invocation status

Cargo.lock, crates/bifrost/src/loglets/local_loglet/log_store.rs, crates/bifrost/src/loglets/local_loglet/log_store_writer.rs, crates/rocksdb/Cargo.toml, crates/rocksdb/src/background.rs, crates/rocksdb/src/db_manager.rs, crates/rocksdb/src/db_spec.rs, crates/rocksdb/src/lib.rs, crates/rocksdb/src/metric_definitions.rs, crates/rocksdb/src/rock_access.rs, crates/types/src/config/bifrost.rs
[RocksDb] Dispatch bifrost writes to bg threads automatically
This introduces the first step to make rocksdb async-friendly. The new RocksDb struct will be the main entry point for future rocksdb access, it
provides _async_ APIs that can perform in-thread blocking or non-blocking IO based on inputs `IoMode`. If the operation needs to happen on the background
thread pool, the `Priority` type specifies which pool to use for that.
Note 1: This PR moves the wal sync to the background, but wal flushes are still required before bifrost writes are acknowleged. Because we dispatch syncs immediately after the write,
it's extremely unlikely to lose the write _after_ bifrost caller has used the acknowledgement to do anything useful. Note that WAL flushes mean that even if the daemon crashed,
the OS …
=> [RocksDb] Dispatch bifrost writes to bg threads automatically

crates/bifrost/src/loglet.rs, crates/bifrost/src/loglets/local_loglet/log_store.rs, crates/bifrost/src/loglets/local_loglet/log_store_writer.rs, crates/bifrost/src/loglets/local_loglet/provider.rs, crates/metadata-store/src/local/service.rs, crates/metadata-store/src/local/store.rs, crates/metadata-store/src/local/tests.rs, crates/node/src/lib.rs, crates/rocksdb/src/db_manager.rs, crates/storage-query-datafusion/src/mocks.rs, crates/storage-rocksdb/benches/basic_benchmark.rs, crates/storage-rocksdb/src/lib.rs, crates/storage-rocksdb/src/writer.rs, crates/storage-rocksdb/tests/integration_test.rs, crates/types/src/config/bifrost.rs, crates/types/src/config/metadata_store.rs, crates/types/src/config/mod.rs, crates/types/src/config/rocksdb.rs, crates/types/src/config/worker.rs, crates/worker/src/lib.rs, crates/worker/src/partition/state_machine/mod.rs, server/src/main.rs
This PR updates the integration of our components with the RocksDbManager.
The PR does a few things:
1. Moves the rocksdb_batch_wal_flushes to the LocalLoglet configuration since not all users want to batch wal flushes
2. Updates the MetadataStore to respect the RocksDbOptions and enables WAL and syncing by default.
3. Updates the RocksDBStorage to respect the RocksDbOptions and to allow configuring the syncing behavior.
=> Update integration with RocksDbManager

crates/worker/src/partition/state_machine/effects.rs
From the RustDocs, apparently we need to set the fields to empty first, before using `Span::record`.
=> Fix little bug when logging state machine effects

crates/storage-query-datafusion/src/idempotency/tests.rs, crates/storage-query-datafusion/src/journal/tests.rs, crates/storage-query-datafusion/src/mocks.rs, crates/storage-query-datafusion/src/tests.rs, crates/storage-rocksdb/benches/basic_benchmark.rs, crates/storage-rocksdb/src/lib.rs, crates/storage-rocksdb/tests/idempotency_table_test/mod.rs, crates/storage-rocksdb/tests/integration_test.rs, crates/storage-rocksdb/tests/state_table_test/mod.rs, crates/worker/src/lib.rs, crates/worker/src/partition/state_machine/mod.rs
Remove RocksDb writer thread and disable WAL
Writes are not "sync" temporarily until we use the new RocksDb async abstraction in the follow up PRs.
WAL is disabled as well, this will be configurable follow up PRs.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1456).
* #1466
* __->__ #1456
=> Remove RocksDb writer thread and disable WAL

crates/invoker-impl/src/lib.rs
Add invocation target logging to invoker events. This is especially helpful when we're on invoker retry loops.
=> Add invocation target to invoker events

crates/types/src/config/mod.rs
Removing unnecessary chdir
Closes #1471
=> Removing unnecessary chdir

Cargo.lock, crates/partition-store/src/keys.rs, crates/partition-store/src/timer_table/mod.rs, crates/partition-store/tests/timer_table_test/mod.rs, crates/storage-api/Cargo.toml, crates/storage-api/proto/dev/restate/storage/v1/domain.proto, crates/storage-api/src/storage.rs, crates/storage-api/src/timer_table/mod.rs, crates/types/src/identifiers.rs, crates/types/src/timer.rs, crates/wal-protocol/src/lib.rs, crates/wal-protocol/src/timer.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/leadership/action_collector.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/state_machine/actions.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/command_interpreter/tests.rs, crates/worker/src/partition/state_machine/effects.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/storage/mod.rs
The TimerKind is used to store differently typed timers. Currently,
we support journal scoped timers that are scoped to a certain journal
entry. Additionally, we support invocation scoped timers that are scoped
to an invocation (e.g. only a single timer for a given wake up time for
a given invocation can exist).
This fixes https://github.com/restatedev/restate/issues/1417.
Only the commits starting from 6ab9fdf are relevant for this PR.
=> Introduce TimerKind to support different types of timers

crates/node/src/network_server/handler/mod.rs, crates/partition-store/src/partition_store_manager.rs, crates/rocksdb/src/db_manager.rs, crates/types/src/config/bifrost.rs, crates/types/src/config/common.rs, crates/types/src/config/rocksdb.rs
Tune rocksdb for multi-cf setup
=> Tune rocksdb for multi-cf setup

Cargo.toml, crates/bifrost/benches/append_throughput.rs, crates/bifrost/src/loglets/local_loglet/log_store.rs, crates/bifrost/src/loglets/local_loglet/log_store_writer.rs, crates/metadata-store/src/local/store.rs, crates/node/src/network_server/handler/mod.rs, crates/node/src/network_server/metrics.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/partition_store_manager.rs, crates/rocksdb/src/background.rs, crates/rocksdb/src/db_manager.rs, crates/rocksdb/src/db_spec.rs, crates/rocksdb/src/lib.rs, crates/rocksdb/src/metric_definitions.rs, crates/rocksdb/src/perf.rs, crates/rocksdb/src/rock_access.rs, crates/types/src/config/common.rs, crates/types/src/config/rocksdb.rs
Tuning and combined improvements for perf and observability
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1493).
* #1514
* #1500
* #1511
* #1497
* __->__ #1493
=> Tuning and combined improvements for perf and observability

Cargo.lock, crates/ingress-dispatcher/src/dispatcher.rs, crates/ingress-dispatcher/src/lib.rs, crates/network/Cargo.toml, crates/network/src/lib.rs, crates/network/src/rpc_router.rs, crates/node-protocol/src/common.rs, crates/node-protocol/src/ingress.rs, crates/node-protocol/src/lib.rs, crates/node-protocol/src/metadata.rs
Unify RpcStyle message routing
Introduces types that makes it easier to perform Rpc-like interactions with Networking.
- `RpcMessage` trait marks messages that carry a `CorrelationId`. A sane default correlation id is provided as `RequestId`.
- `RpcRequest` trait defines request messages and their response types.
- `RpcRouter<T: RpcRequest>` enables sending rpc request and awaiting responses with auto eviction of dropped requests.
- `ResponseTracker` is a helper that manages tracking tokens for in-flight requests, this can be used in the future to replace large portions of IngressDispatcher.
- Macros to help define RPC messages to reduce code noise in node-protocol
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with …
=> Unify RpcStyle message routing

crates/schema-api/src/invocation_target.rs
=> Fix content type checks on input when passing content type arguments

tools/service-protocol-wireshark-dissector/src/lib.rs
The URL was too big to fit into my screen, so I decided to extract the base URL from a lengthy URL for improved reading visibility.
=> Shorten URL Extract base URL from Google redirect

crates/invoker-api/src/entry_enricher.rs, crates/partition-store/src/keys.rs, crates/partition-store/src/lib.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/promise_table/mod.rs, crates/partition-store/tests/integration_test.rs, crates/partition-store/tests/promise_table_test/mod.rs, crates/service-protocol/src/codec.rs, crates/service-protocol/src/message/encoding.rs, crates/service-protocol/src/message/header.rs, crates/storage-api/proto/dev/restate/storage/v1/domain.proto, crates/storage-api/src/lib.rs, crates/storage-api/src/promise_table/mod.rs, crates/storage-api/src/storage.rs, crates/types/src/errors.rs, crates/types/src/identifiers.rs, crates/types/src/journal/entries.rs, crates/types/src/journal/raw.rs, crates/types/src/service_protocol.rs, crates/worker/src/invoker_integration.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/command_interpreter/tests.rs, crates/worker/src/partition/state_machine/effect_interpreter.rs, crates/worker/src/partition/state_machine/effects.rs, crates/worker/src/partition/storage/mod.rs
Fix #1513. This implements the new promises api in the service-protocol
=> Add promises support

crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/lib.rs, crates/storage-query-datafusion/src/promise/mod.rs, crates/storage-query-datafusion/src/promise/row.rs, crates/storage-query-datafusion/src/promise/schema.rs, crates/storage-query-datafusion/src/promise/table.rs
Followup of #1515, adds the `sys_promise` table to help debugging promises
=> Add sys_promise table

cli/src/commands/deployments/register.rs
As -e is now used for environment selection
=> Fix short extra_headers clap arg in CLI

crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/mod.rs
=> Fix issue with submit notification for virtual objects

crates/network/src/rpc_router.rs
This commit resolves the race condition in the ResponseTracer when creating a new token with an existing correlation id and completing the very same correlation id at the same time. The solution is to use the entry method of Dashmap which keeps the lock as long as entry is not dropped.
This fixes #1531.
=> Prevent race condition in ResponseTracker by using entry which holds the lock

crates/node/src/roles/admin.rs
The current 66s is quite long and means you don't see your (generally permanent) error quickly enough
=> Significantly reduce retry duration of service discovery

Cargo.lock, Cargo.toml, crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglets/local_loglet/log_store_writer.rs, crates/bifrost/src/loglets/local_loglet/metric_definitions.rs, crates/bifrost/src/loglets/local_loglet/mod.rs, crates/bifrost/src/loglets/memory_loglet.rs, crates/worker/Cargo.toml, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/leadership/action_collector.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/mod.rs
[Bifrost] Support append_batch
This introduces a new append_batch API to bifrost that accepts a batch of payloads. In addition, we make use of this API to handle batches of action effects when consuming the effect stream. We attempt to batch up to 10 items (hardcoded at the moment) before sending them to bifrost.
Impact: For small invocations, we now average ~4 records (+1 for metadata) per batch since invoker emits input/get_state/output etc. in bursts. This reduces the overhead of handling the happy path of small handlers.
This also address a small issue where the the initial offsets leave an unnecessary gap on re-instantiation.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with …
=> [Bifrost] Support append_batch

crates/ingress-dispatcher/src/dispatcher.rs, crates/ingress-dispatcher/src/lib.rs, crates/ingress-http/src/handler/invocation.rs, crates/ingress-http/src/handler/responses.rs, crates/ingress-http/src/handler/service_handler.rs, crates/ingress-http/src/handler/tests.rs, crates/ingress-http/src/handler/workflow.rs, crates/ingress-http/src/server.rs
Fix #1258
I'm gonna use this header in the java sdk to remove the parsing of the json object for the /send requests.
=> Send x-restate-id header back on each request

cli/src/clients/datafusion_helpers.rs, cli/src/commands/state/clear.rs, cli/src/commands/state/mod.rs
Similar to #1529, part of https://github.com/restatedev/restate/issues/898
=> Add CLI command to clear state of a specific instance or of all instances

Cargo.lock, cli/Cargo.toml, cli/src/commands/cloud/environments/mod.rs, cli/src/commands/cloud/environments/proxy.rs
The goal of this command is to make it appear that a cloud environment is running locally on your machine, by exposing an authenticating proxy on localhost
=> Add cloud CLI proxy command

Cargo.lock, Cargo.toml, crates/bifrost/src/loglets/local_loglet/keys.rs, crates/bifrost/src/loglets/local_loglet/log_store.rs, crates/core/src/task_center.rs, crates/rocksdb/src/db_manager.rs, crates/types/src/config/common.rs, crates/types/src/config/rocksdb.rs, crates/types/src/config/worker.rs, tools/mock-service-endpoint/Cargo.toml, tools/mock-service-endpoint/src/main.rs
Minor config tuning
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1557).
* #1565
* #1563
* #1558
* __->__ #1557
* #1556
=> Minor config tuning

Cargo.lock, Cargo.toml, crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost.rs, crates/bifrost/src/error.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglets/local_loglet/keys.rs, crates/bifrost/src/loglets/local_loglet/log_store.rs, crates/bifrost/src/loglets/local_loglet/mod.rs, crates/bifrost/src/loglets/local_loglet/provider.rs, crates/bifrost/src/loglets/local_loglet/read_stream.rs, crates/bifrost/src/loglets/local_loglet/utils.rs, crates/bifrost/src/loglets/memory_loglet.rs, crates/bifrost/src/read_stream.rs, crates/core/src/task_center.rs, crates/node/Cargo.toml, crates/partition-store/src/partition_store.rs, crates/rocksdb/src/db_manager.rs, crates/rocksdb/src/lib.rs, crates/types/src/config/common.rs, crates/types/src/config/rocksdb.rs, crates/types/src/config/worker.rs, crates/worker/src/partition/mod.rs, tools/bifrost-benchpress/Cargo.toml, tools/bifrost-benchpress/src/write_to_read.rs, tools/mock-service-endpoint/Cargo.toml, tools/mock-service-endpoint/src/main.rs
Attempt the non-blocking write in bg
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1565).
* __->__ #1565
* #1563
* #1558
* #1557
* #1556
=> Attempt the non-blocking write in bg

crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/mod.rs
Just a little case where we returned the wrong invocation id. Followup of https://github.com/restatedev/restate/pull/1559
=> Fix invocation_id returned in case we return the completed result of an already existing invocation

cli/Cargo.toml, cli/src/app.rs, cli/src/commands/sql.rs
Fix #1337, Fix #1554
Also un-hide the sql command
=> Add json output to sql queries

Cargo.lock, crates/core/src/task_center.rs, crates/core/src/task_center_types.rs, crates/core/src/test_env.rs, crates/invoker-impl/src/invocation_task/service_protocol_runner.rs, crates/invoker-impl/src/lib.rs, crates/invoker-impl/src/metric_definitions.rs, crates/invoker-impl/src/quota.rs, crates/node/src/network_server/handler/mod.rs, crates/rocksdb/src/db_manager.rs, crates/rocksdb/src/lib.rs, crates/rocksdb/src/metric_definitions.rs, crates/service-client/src/http.rs, crates/tracing-instrumentation/src/lib.rs, crates/types/src/config/bifrost.rs, crates/types/src/config/common.rs, crates/worker/Cargo.toml, crates/worker/src/metric_definitions.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/state_machine/actions.rs, crates/worker/src/partition/state_machine/command_interpreter/mod.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition_processor_manager.rs
Instrumentation and separate pp, ingress, and default runtimes
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1568).
* __->__ #1568
* #1569
=> Instrumentation and separate pp, ingress, and default runtimes

crates/tracing-instrumentation/src/lib.rs
Disable metric label extraction from tracing due to high cpu cost
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1569).
* #1568
* __->__ #1569
=> Disable metric label extraction from tracing due to high cpu cost

crates/service-client/src/request_identity/v1.rs
One of those cases where rust is very exact but very unhelpful :)
=> Use lossy string to log signing key path, as debug would add quotes/escapes

Cargo.lock, Cargo.toml, crates/benchmarks/src/lib.rs, crates/bifrost/src/loglets/local_loglet/log_store.rs, crates/bifrost/src/loglets/local_loglet/log_store_writer.rs, crates/bifrost/src/loglets/local_loglet/provider.rs, crates/node/src/lib.rs, crates/node/src/network_server/handler/mod.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/partition_store_manager.rs, crates/rocksdb/src/db_manager.rs, crates/types/src/config/bifrost.rs, crates/types/src/config/cli_option_overrides.rs, crates/types/src/config/common.rs, crates/types/src/config/metadata_store.rs, crates/types/src/config/mod.rs, crates/types/src/config/rocksdb.rs, crates/types/src/config/worker.rs, server/src/config_loader.rs, server/src/signal.rs
[Perf] Rocksdb performance tuning
This also introduces a change to how memory budgeting is configured and the default number of partitions is now 24
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1572).
* #1575
* #1573
* __->__ #1572
=> [Perf] Rocksdb performance tuning

crates/partition-store/src/partition_store.rs
Fix total order seek for transaction iterators
=> Fix total order seek for transaction iterators

crates/core/src/task_center.rs, crates/worker/src/partition_processor_manager.rs
reduce logging level of task center
Also removes an incorrect debug "shutting down" log from partition processor manager
=> reduce logging level of task center

crates/bifrost/src/loglets/local_loglet/read_stream.rs
Do not fail iterator on range deletion tombstones
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1576).
* #1575
* __->__ #1576
=> Do not fail iterator on range deletion tombstones

crates/admin/src/rest_api/error.rs, crates/admin/src/rest_api/services.rs
=> Validate that incoming requests to mutate state are sent to keyed services only (virtual objects or workflows)

crates/service-client/src/http.rs, crates/types/src/config/http.rs
The CLI will still time out long before this returns, but at least we will see log lines about the failure, and not waste resources. Currently I think we block forever...
=> Add a HTTP connect timeout - default 10s

crates/bifrost/src/loglets/local_loglet/log_store_writer.rs, crates/bifrost/src/loglets/local_loglet/read_stream.rs, crates/metadata-store/src/local/store.rs, crates/partition-store/src/deduplication_table/mod.rs, crates/partition-store/src/inbox_table/mod.rs, crates/partition-store/src/invocation_status_table/mod.rs, crates/partition-store/src/journal_table/mod.rs, crates/partition-store/src/outbox_table/mod.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/promise_table/mod.rs, crates/partition-store/src/service_status_table/mod.rs, crates/partition-store/src/state_table/mod.rs, crates/partition-store/src/timer_table/mod.rs, crates/rocksdb/src/lib.rs, crates/rocksdb/src/metric_definitions.rs, crates/rocksdb/src/perf.rs, crates/rocksdb/src/rock_access.rs, crates/types/src/config/common.rs, crates/types/src/config/rocksdb.rs
[rocksdb] Make perf level configurable
This is now controlled by `common.rocksdb-perf-level`. Default is `enable-count`
Also adds detailed rocksdb instrumentation
***
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1591).
* #1593
* #1592
* __->__ #1591
* #1588
=> [rocksdb] Make perf level configurable

docs/dev/release.md
Now we don't need the ordered release process anymore.
Also make sure we underline that we must cut release branches, we need those to quickly create patch releases.
=> Update release documentation

crates/invoker-impl/src/invocation_task/service_protocol_runner.rs, crates/service-client/src/http.rs, crates/service-client/src/lambda.rs, crates/service-client/src/lib.rs, crates/service-protocol/src/discovery.rs
=> Use GET for service discovery

crates/node/src/cluster_marker.rs, docs/dev/release.md
Update compatibility map to include 1.0.0 as a new breaking version so that incompatible cluster versions are properly detected.
This fixes #1615.
=> Update compatibility map to include 1.0.0 as a new breaking version

crates/node/src/cluster_marker.rs, crates/node/src/lib.rs, docs/dev/release.md
Now the server checks whether it is backward-compatible with the data
directory. If it encounters a version that either needs migration or
cannot be migrated from, then it fails with a BackwardIncompatibility
error.
This fixes https://github.com/restatedev/restate/issues/1617.
This PR is based on #1616.
=> Check for backward compatibility when validating the cluster marker 

crates/invoker-impl/src/lib.rs, crates/types/src/config/worker.rs
[config] Adds invoker segment queue limit to configuration file
This adds a new configuration key `in-memory-queue-length-limit` under `[worker.invoker]` to enable configuring the segment queue from the configuration file. The default value matches the currently hard coded value.
=> [config] Adds invoker segment queue limit to configuration file

cli/src/commands/invocations/describe.rs, cli/src/ui/console.rs, cli/src/ui/deployments.rs
This is a backport of #1632 to `release-1.0`.
=> [BP] Lazily calculate value when using StyledTable::add_kv_row_if and predicate is true

cli/src/commands/invocations/describe.rs, cli/src/ui/deployments.rs, crates/cli-util/src/ui/console.rs
We use `StyledTable::add_kv_row_if` to check if a value exists. We should only access the value if the predicate passes. That's why this command changes the value parameter into a closure that is evaluated if the predicate is true.
This fixes #1631.
=> Lazily calculate value when using StyledTable::add_kv_row_if and predicate is true

crates/types/src/config/mod.rs, server/src/main.rs
WipeMode::All will now delete the whole node base dir to also
remove a cluster marker file.
This fixes https://github.com/restatedev/restate/issues/1629.
This PR is based on #1628.
=> Delete the node dir when wiping all

Cargo.lock, crates/types/src/config/mod.rs, crates/worker/Cargo.toml, crates/worker/src/partition/shuffle.rs, server/src/main.rs
This commit changes the shuffle to always use get_next_message to read the next outbox message. Before we were using get_message which was only looking at a specific outbox entry. If this outbox entry was empty, then the shuffle assumed that the outbox is empty. This did not work if the outbox contained holes. Now with get_next_message, we always scan until the next outbox message.
The change itself is trivial. In order to ensure that the change works, this commit added a few unit tests to ensure the desired behaviour.
Note: With replacing get_message with get_next_message, the shuffle will perform for every read a RocksDB scan operation. This is highly inefficient and we should replace this logic with a tailing iterator.
This fixes #1639.
=> Let shuffle always use get_next_message to support holey outboxes

Cargo.lock, crates/types/src/config/mod.rs, crates/worker/Cargo.toml, crates/worker/src/partition/shuffle.rs, server/src/main.rs
Backport of #1640 to `release-1.0`.
=> [BP] Let shuffle always use get_next_message to support holey outboxes

Cargo.lock, Cargo.toml, cli/Cargo.toml, crates/cli-util/Cargo.toml, crates/cli-util/src/context.rs, crates/cli-util/src/opts.rs, crates/cli-util/src/ui/console.rs, crates/cli-util/src/ui/mod.rs, crates/cluster-controller/src/lib.rs, crates/node-protocol/proto/common.proto, crates/node-protocol/src/common.rs, crates/node-services/Cargo.toml, crates/node-services/proto/cluster_ctrl_svc.proto, crates/node-services/src/lib.rs, crates/node/Cargo.toml, crates/node/src/network_server/handler/cluster_ctrl.rs, crates/node/src/network_server/service.rs, crates/types/Cargo.toml, crates/types/src/processors/mod.rs, crates/types/src/time.rs, crates/worker/src/partition/mod.rs, tools/restatectl/Cargo.toml, tools/restatectl/src/app.rs, tools/restatectl/src/commands/dump/cluster_state.rs, tools/restatectl/src/commands/dump/mod.rs, tools/restatectl/src/commands/mod.rs, tools/restatectl/src/lib.rs, tools/restatectl/src/util.rs
[restatectl] dump cluster-state
Allow dumping current view of ClusterState in a table format.
```shell
❯ cargo run -q --bin restatectl --  dump cluster-state                                                                                                                                                                                                                                                                                                                                                                                ✘ 1
P-ID  NODE   RUN MODE  REPLAY  APPLIED LSN  PERSISTED LSN  OBSERVED LEADER  # SKIPS  LAST REFRESH
0     N0:24  Leader    Active  494          ??             N0:24 - e24      0        1 second and 56 ms ago
1     N0:24  Leader    Active  554          ??             N0:24 …
```
=> [restatectl] dump cluster-state

cli/src/commands/services/status/agg_status.rs, cli/src/commands/services/status/detailed_status.rs, cli/src/commands/state/util.rs
There is a bug where `state get` doesn't work on workflows. This PR tightens up a few places where we do an equality check instead of a match or using the method on the service type.
=> CLI should respect that not just virtual objects are stateful

cli/src/clients/admin_client.rs, cli/src/clients/admin_interface.rs, crates/storage-query-datafusion/src/table_macro.rs
Backport of #1659 to `release-1.0`.
=> [BP] Only emit admin API incompatibility warning if cluster is running 

crates/types/src/time.rs
Fix underflow in Millis/Nanos SinceEpoch elapsed
=> Fix underflow in Millis/Nanos SinceEpoch elapsed

crates/admin/src/cluster_controller/service.rs, crates/bifrost/benches/append_throughput.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/read_stream.rs, crates/bifrost/src/service.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/shuffle.rs, tools/bifrost-benchpress/src/append_latency.rs, tools/bifrost-benchpress/src/write_to_read.rs, tools/xtask/src/main.rs
[Bifrost] minor cleanups
- Bifrost doesn't need to be mutable for normal appends
- Progress towards removing global access to metadata()
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1664).
* #1671
* #1668
* #1665
* __->__ #1664
=> [Bifrost] minor cleanups

crates/admin/src/cluster_controller/service.rs, crates/bifrost/benches/append_throughput.rs, crates/bifrost/benches/util.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/read_stream.rs, crates/bifrost/src/service.rs, crates/core/src/lib.rs, crates/core/src/metadata/manager.rs, crates/core/src/metadata/mod.rs, crates/core/src/network/networking.rs, crates/core/src/test_env.rs, crates/node/src/lib.rs, crates/types/src/nodes_config.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/shuffle.rs, tools/bifrost-benchpress/src/append_latency.rs, tools/bifrost-benchpress/src/main.rs, tools/bifrost-benchpress/src/write_to_read.rs, tools/xtask/src/main.rs
MetadataBuilder to untangle shared metadata construction
Address a chicken-and-an-egg problem at construction time of the runtime environment. MetadataBuilder helps by allowing the shared metadata object to be constructed early while encapsulating metadata's construction implementation details.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1665).
* #1671
* #1668
* __->__ #1665
* #1664
=> MetadataBuilder to untangle shared metadata construction

Cargo.lock, Cargo.toml
The original revision cannot be used after rebasing that branch.
=> [BP] Update rocksdb dependency

Cargo.lock, Cargo.toml
Primary goal is to remove 'compression' which bundles in various compression libs, one of which appears to be dynamically linked for mac in some cases. We don't need the compression feature
As a extra benefit, we can remove parquet support in the interest of compile time and binary size. I don't really see how this can be used usefully as we have disabled functions that read and write files.
=> Remove two default imports from datafusion dependency

Cargo.lock, crates/admin/src/cluster_controller/service.rs, crates/bifrost/benches/append_throughput.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/error.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglets/local_loglet/mod.rs, crates/bifrost/src/loglets/local_loglet/provider.rs, crates/bifrost/src/loglets/memory_loglet.rs, crates/bifrost/src/provider.rs, crates/bifrost/src/read_stream.rs, crates/bifrost/src/service.rs, crates/bifrost/src/watchdog.rs, crates/ingress-dispatcher/src/dispatcher.rs, crates/node/src/lib.rs, crates/types/Cargo.toml, crates/types/src/config/mod.rs, crates/types/src/live.rs, crates/types/src/logs/metadata.rs, crates/worker/src/partition/shuffle.rs, tools/bifrost-benchpress/src/main.rs, tools/xtask/src/main.rs
[Bifrost] Eager providers initialization
Bifrost providers are now initialized in two stages. An initialization that happens on startup to ensure all critical initialization and validation happens before server startup.
After initialization, loglets will get a notification from watchdog to perform any background lazy initialization work if necessary.
Benefits:
- Removes the need to always "check if initialized" internally, or the use of "OnceLock" and other techniques to check if it's initialized or not.
- Allows a potential validation step before server startup. Potentially fetching the metadata and validating all `LogletParams` for each provider in metadata against providers to reduce the chance of validation errors at construction time.
- Allows construction of providers to be async …
=> [Bifrost] Eager providers initialization

crates/admin/src/cluster_controller/cluster_state.rs, crates/admin/src/cluster_controller/service.rs, crates/node/src/lib.rs, crates/node/src/roles/admin.rs, crates/node/src/roles/worker.rs, crates/types/src/cluster/cluster_state.rs, crates/worker/src/lib.rs, deny.toml
This is a temporary band-aid to solve the problem that at start-up
we might not respond to some invocations if the partition processors
are slow at claiming leadership. See https://github.com/restatedev/restate/issues/1651
for more details.
The band-aid introduces a oneshot which is being completed by the cluster
controller when it has seen for every partition a leader. The ingress will
wait for the oneshot to be completed before starting it. Note, this band-aid
only works for single process setups where the Admin role is colocated with
the Worker role. This should cover the normal deployment right now.
This fixes https://github.com/restatedev/restate/issues/1684.
=> Start ingress only after all partitions have a leader

cli/src/commands/sql.rs
Trivial little fix for something that caught my eye. 
Before:
```
❯ restate sql "select value_utf8 from state limit 1" --jsonl
{"value_utf8":"{\"userId\":\"usr_101\",\"accounts\":[{\"accountId\":\"acc_10uhnxdeyrnKSVnXhgWouLo\",\"name\":\"updated-name\"}]}"}
0 rows. Query took 8.624792ms
```
After:
```
❯ ./target/debug/restate sql "select value_utf8 from state limit 1" --jsonl
{"value_utf8":"{\"accountId\":\"acc_10uhnxddRv3UE4UbJiWqbmi\",\"primaryOwnerUserId\":\"usr_101\",\"environments\":[],\"name\":\"integration-test-account-01j1sw6fqw8tcsn20jmeyrfx3g\"}"}
1 rows. Query took 9.157292ms
```
=> [CLI] Emit correct row count from CLI sql subcommand JSON mode

docs/dev/local-development.md
I was getting started with local development of restate on my fedora setup and it failed to compile 
```bash
error: failed to run custom build command for `restate-core v1.1.0 (/home/aradwan/Documents/repos/restate/crates/core)`
Caused by:
process didn't exit successfully: `/home/aradwan/Documents/repos/restate/target/debug/build/restate-core-6e6184d6ff0d784f/build-script-build` (exit status: 1)
--- stdout
cargo:rerun-if-changed=./protobuf/node_svc.proto
cargo:rerun-if-changed=protobuf
cargo:rerun-if-changed=../types/protobuf
--- stderr
Error: Custom { kind: Other, error: "protoc failed: google/protobuf/empty.proto: File not found.\nnode_svc.proto:12:1: Import \"google/protobuf/empty.proto\" was not found or had errors.\nnode_svc.proto:20:16: \"google.protobuf.Empty\" is not defined.\n" } …
```
=> Add missing fedora local dev env protobuf dependency

cli/src/clients/datafusion_helpers.rs, cli/src/clients/datafusion_http_client.rs, cli/src/ui/invocations.rs, crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/invocation_status/row.rs, crates/storage-query-datafusion/src/invocation_status/schema.rs, crates/storage-query-datafusion/src/table_docs.rs
Fix #1712
Using restate 1.0:
```
❯ [2024-07-18 09:22:21.760 +02:00] inv_1eQGNqArQ5Hz78SmQy5dvDqYgj7lxjQp1L
Target:      WorkflowTest/c/run                                                
Status:      backing-off  (12 minutes, 21 seconds and 606 ms. Retried   
66 time(s). Next retry in in 7 seconds and 134 ms))        
Deployment:  id: dp_13sgmJ9OIJWO79hTDuusMQF, service protocol version: 1       
[ZOMBIE] using restate-sdk-java/1.1.0-SNAPSHOT_fbfb16cc 
Error:       [2024-07-18 09:34:39.353 +02:00]                            
[500] error trying to connect: tcp connect error: Connection  
refused (os error 111)                                         
Caused by:   UNKNOWN                                                           
❯ [2024-07-18 09:21:55.534 +02:00] …
```
=> Show invocation completion in CLI

Cargo.lock, crates/service-client/Cargo.toml, crates/service-client/src/aws_hyper_client.rs, crates/service-client/src/lambda.rs, crates/service-client/src/lib.rs, crates/storage-query-postgres/Cargo.toml
Have to unfortunately inline the hyper 1.0 client pending https://github.com/smithy-lang/smithy-rs/issues/3769
Fixes #1729
=> Update aws deps in service-client

Cargo.lock, Cargo.toml, crates/storage-query-datafusion/Cargo.toml, crates/storage-query-datafusion/src/analyzer.rs, crates/storage-query-postgres/Cargo.toml
Datafusion 35.0.0-object-store is a forked 35.0.0 version which swapped object_store 0.9 with object_store 0.10.2 at the cost of Parquet support.
This fixes #1749.
This temporary fix should no longer be necessary once #1673 gets merged.
=> Bump datafusion dependency to 35.0.0-object-store

Cargo.lock, cli/Cargo.toml, cli/src/commands/cloud/environments/tunnel/local.rs, cli/src/commands/cloud/environments/tunnel/mod.rs, cli/src/commands/cloud/environments/tunnel/remote.rs, cli/src/commands/cloud/environments/tunnel/request_identity.rs, cli/src/commands/cloud/login.rs
I will admit that this PR nearly broke me. Tunnel was *heavily* relying on the tower::Service semantics where poll_ready would be called repeatedly between HTTP requests, to process the trailers handshake that forms part of the protocol. To replace it I have used a tokio RWLock and a cancellation token
=> Update CLI hyper/http dependencies

Cargo.toml, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet/util.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/local_loglet/read_stream.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/types.rs
[Bifrost] Watch tail updates
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1743).
* #1757
* #1753
* #1747
* #1744
* __->__ #1743
* #1742
=> [Bifrost] Watch tail updates

Cargo.lock, Cargo.toml, crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet/util.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/local_loglet/provider.rs, crates/bifrost/src/providers/local_loglet/read_stream.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/read_stream.rs, crates/bifrost/src/types.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/shuffle.rs, tools/bifrost-benchpress/src/write_to_read.rs
[Bifrost] Read stream support multi-segment logs
This introduces a new read stream implementation that operates under a multi-segment bifrost world. Notable features include:
- Support for reading from multiple segments seamlessly
- Reading unsealed segments while watching the tail state to determine the safe boundaries with minimal efficiency loss
- Handling of on-going reconfiguration, the stream waits for the loglet to be sealed.
- Handles prefix trims on metadata-level when detected (partial support, more on that in follow up PRs)
Running bifrost-benchpress read-to-write latency tests show that the new read-stream doesn't introduce any meaningful regression in latency in the the unsealed close-to-tail case (note that P100 should be discarded due to shutdown-related noise) …
=> [Bifrost] Read stream support multi-segment logs

Cargo.lock, Cargo.toml, crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet/provider.rs, crates/bifrost/src/loglet/util.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/local_loglet/provider.rs, crates/bifrost/src/providers/local_loglet/read_stream.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/read_stream.rs, crates/bifrost/src/types.rs, crates/types/src/logs/builder.rs, crates/types/src/logs/metadata.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/shuffle.rs, tools/bifrost-benchpress/src/write_to_read.rs
[Bifrost] Introduces SegmentIndex to identify segments in the log chain
This allows correct handling of sealing empty loglets and support for future reconfiguration operations.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1747).
* #1757
* #1753
* __->__ #1747
* #1744
* #1743
* #1742
=> [Bifrost] Introduces SegmentIndex to identify segments in the log chain

Cargo.lock, Cargo.toml, crates/admin/src/cluster_controller/service.rs, crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/error.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet/provider.rs, crates/bifrost/src/loglet/util.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/local_loglet/provider.rs, crates/bifrost/src/providers/local_loglet/read_stream.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/read_stream.rs, crates/bifrost/src/types.rs, crates/core/src/metadata/mod.rs, crates/core/src/metadata_store/mod.rs, crates/node/src/roles/admin.rs, crates/types/src/config/bifrost.rs, crates/types/src/logs/builder.rs, crates/types/src/logs/metadata.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/shuffle.rs, tools/bifrost-benchpress/src/write_to_read.rs
[Bifrost] Basic BifrostAdmin interface
It now hosts `trim` and introduces the ability to seal and extend the chain with a pre-determined loglet params
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1753).
* #1757
* __->__ #1753
* #1747
* #1744
* #1743
* #1742
=> [Bifrost] Basic BifrostAdmin interface

crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet_wrapper.rs
[Bifrost] Loglet read stream with known tail lsn
Loglet wrapper now limits reads if the loglet sealed tail is known
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1742).
* #1757
* #1753
* #1747
* #1744
* #1743
* __->__ #1742
=> [Bifrost] Loglet read stream with known tail lsn

crates/worker/src/partition/leadership.rs
Fixs SIGSEGV due to missing rocksdb shutdown in leader stepdown test
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1774).
* #1772
* __->__ #1774
=> Fixs SIGSEGV due to missing rocksdb shutdown in leader stepdown test

crates/admin/src/rest_api/invocations.rs, crates/admin/src/rest_api/services.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/ingress-dispatcher/src/dispatcher.rs, crates/types/src/config/bifrost.rs, crates/types/src/logs/builder.rs, crates/types/src/logs/mod.rs, crates/wal-protocol/src/lib.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/shuffle.rs
[Bifrost] Bifrost appends will wait for reconfiguration
Bifrost appends will wait for reconfiguration to complete. Additionally, log metadata will now handle empty segments correctly. An empty segment will be removed from the chain and replaced with the newly created one but with a higher segment index.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1772).
* #1776
* #1775
* __->__ #1772
=> [Bifrost] Bifrost appends will wait for reconfiguration

Cargo.lock, crates/admin/src/rest_api/invocations.rs, crates/admin/src/rest_api/services.rs, crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/read_stream.rs, crates/ingress-dispatcher/src/dispatcher.rs, crates/types/src/config/bifrost.rs, crates/types/src/logs/builder.rs, crates/types/src/logs/metadata.rs, crates/types/src/logs/mod.rs, crates/wal-protocol/src/lib.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/shuffle.rs
[Bifrost] handle prefix-trimmed log chains in reads
`read()` and more importantly ReadStream now handle trimmed segments from the chain correctly by sending the TrimGap to the offset before the next base_lsn.
Also, added a test to validate that on read stream
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1776).
* __->__ #1776
* #1775
* #1772
=> [Bifrost] handle prefix-trimmed log chains in reads

crates/bifrost/src/bifrost.rs, crates/core/src/metadata_store/mod.rs, crates/ingress-kafka/src/subscription_controller.rs, crates/invoker-impl/src/invocation_state_machine.rs, crates/metadata-store/src/local/mod.rs, crates/metadata-store/src/local/tests.rs, crates/node/src/lib.rs, crates/service-protocol/src/discovery.rs, crates/types/src/config/common.rs, crates/types/src/retries.rs
This commit makes the backoff policy in the metadata store client
configurable via the configuration.
This fixes https://github.com/restatedev/restate/issues/1752.
=> Make backoff policy in metadata store client configurable

crates/errors/src/error_codes/META0010.md, crates/errors/src/error_codes/META0011.md, crates/errors/src/error_codes/RT0009.md, server/src/main.rs
Fixes #1650
I think hiding the flag is better than completely removing the code. This this way the user can still does a wipe without the need to actually remote data directories manually which can be error prone (for example removing the wrong files or directories)
=> Hide the `--wipe` flag

cli/Cargo.toml, cli/src/clients/admin_interface.rs, cli/src/commands/services/config/edit.rs, cli/src/commands/services/config/mod.rs, cli/src/commands/services/config/patch.rs, cli/src/commands/services/config/view.rs, cli/src/commands/services/mod.rs, crates/serde-util/src/duration.rs, deny.toml
Fix #1672
This PR adds 3 new commands:
* `restate service config view <SVC>`: View the current service configuration
* `restate service config patch <SVC> --config-entry=new_value`: Patch the service configuration
* `restate service config edit <SVC>`: Patch the service configuration interactively (similar to state edit and config edit) 
Example of the new `view` command:
```
Name:          LoanWorkflowMockBank 
Service type:  Service              
Public:  false 
💡   Whether the service is publicly available or not.                       
If true, the service can be invoked through the ingress.                
If false, the service can be invoked only from another Restate service. 
Idempotent requests retention:  10s 
💡   The retention duration of idempotent requests for this service. …
```
=> Add commands to view and edit/patch service configuration

crates/node/src/lib.rs, crates/types/src/config/common.rs
Fixes #1769
This makes the network error retry policy configurable for the node
=> Configurable network error retry policy

Cargo.lock, crates/core/src/network/connection_manager.rs, crates/core/src/network/handshake.rs, crates/core/src/network/networking.rs, crates/node/src/lib.rs, crates/types/src/config/networking.rs
=> Make networking handshake timeout configurable

Cargo.lock, Cargo.toml, crates/admin/src/cluster_controller/service.rs, crates/bifrost/benches/append_throughput.rs, crates/bifrost/src/appender.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/local_loglet/log_store_writer.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/read_stream.rs, crates/types/src/config/bifrost.rs, crates/types/src/logs/mod.rs, crates/types/src/storage.rs, crates/wal-protocol/src/lib.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/leadership.rs, crates/worker/src/partition/shuffle.rs, tools/bifrost-benchpress/src/append_latency.rs, tools/bifrost-benchpress/src/write_to_read.rs
[Bifrost] New Appender with Keys support
Envelope implements a new trait `HasRecordKeys` to support future matching of records based on a `KeyMatcher`. The new appender is the canonical way to write to a single log. It tries to recycle the write buffer (although it doesn't use freelist which would be a potential future improvement) and it defers serialization to unlock the potential for better serialization write buffer management.
Appender is created by `bifrost.create_appender(log_id)?` and it's the core abstraction that `BackgroundAppender` builds upon (next PR)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1788).
* #1809
* #1808
* #1798
* #1797
* #1794
* #1792
* …
=> [Bifrost] New Appender with Keys support

Cargo.lock, Cargo.toml, crates/admin/src/cluster_controller/service.rs, crates/bifrost/benches/append_throughput.rs, crates/bifrost/src/appender.rs, crates/bifrost/src/background_appender.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/error.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/local_loglet/log_store_writer.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/read_stream.rs, crates/core/src/task_center_types.rs, crates/types/src/config/bifrost.rs, crates/types/src/logs/mod.rs, crates/types/src/storage.rs, crates/wal-protocol/src/lib.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/leadership.rs, crates/worker/src/partition/shuffle.rs, tools/bifrost-benchpress/src/append_latency.rs, tools/bifrost-benchpress/src/write_to_read.rs
[Bifrost] BackgroundAppender implementation
Introduces a new way to enqueue messages to Bifrost. This PR adds `bifrost.create_background_append(...).start()` that starts a background appender. The background appender automatically batches appends and provides flexible control over draining it or auto-destruction when all senders are dropped (see `detach()` on `AppenderHandle`).
With this, `ActionEffectHandler` makes use of this new ability and will not block the partition processor loop when writing effects to bifrost.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1789).
* #1809
* #1808
* #1798
* #1797
* #1794
* #1792
* __->__ #1789
* #1788
=> [Bifrost] BackgroundAppender implementation

Cargo.lock, Cargo.toml, crates/admin/src/cluster_controller/service.rs, crates/bifrost/benches/append_throughput.rs, crates/bifrost/src/appender.rs, crates/bifrost/src/background_appender.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/error.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/payload.rs, crates/bifrost/src/providers/local_loglet/log_store_writer.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/read_stream.rs, crates/bifrost/src/record.rs, crates/core/src/task_center_types.rs, crates/types/src/config/bifrost.rs, crates/types/src/logs/mod.rs, crates/types/src/storage.rs, crates/wal-protocol/src/lib.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/leadership.rs, crates/worker/src/partition/shuffle.rs, tools/bifrost-benchpress/src/append_latency.rs, tools/bifrost-benchpress/src/write_to_read.rs
[Bifrost] Moving Payload to be an internal bifrost type
Hiding the details of Payload. This type will take a different shape in the future.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1792).
* #1809
* #1808
* #1798
* #1797
* #1794
* __->__ #1792
* #1789
* #1788
=> [Bifrost] Moving Payload to be an internal bifrost type

Cargo.lock, Cargo.toml, crates/admin/src/cluster_controller/service.rs, crates/bifrost/benches/append_throughput.rs, crates/bifrost/src/appender.rs, crates/bifrost/src/background_appender.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/error.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/payload.rs, crates/bifrost/src/providers/local_loglet/log_store_writer.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/read_stream.rs, crates/bifrost/src/record.rs, crates/core/src/task_center_types.rs, crates/types/src/config/bifrost.rs, crates/types/src/logs/mod.rs, crates/types/src/storage.rs, crates/wal-protocol/src/lib.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/leadership.rs, crates/worker/src/partition/shuffle.rs, tools/bifrost-benchpress/src/append_latency.rs, tools/bifrost-benchpress/src/write_to_read.rs
[Bifrost] read() now uses LogReadStream internally
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1794).
* #1809
* #1808
* #1798
* #1797
* __->__ #1794
* #1792
* #1789
* #1788
=> [Bifrost] read() now uses LogReadStream internally

crates/invoker-impl/src/invocation_task/mod.rs, crates/invoker-impl/src/invocation_task/service_protocol_runner.rs
When a user service is running behind a gateway it is possible that the gateway returns an http error (like 503) when service is down. We need to handle this correctly in code and return proper error
Fixes #1548
I have tested this fix by running the go example app behind traefik. I first made sure that the setup is working as expected then I shutdown traefik to reproduce the issue.
The logs show the proper error message plus `restate.error.code: RT0010`
=> Correctly handle gateway errors

Cargo.lock, Cargo.toml, crates/admin/Cargo.toml, crates/admin/src/cluster_controller/mod.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service.rs, crates/core/src/lib.rs, crates/core/src/metadata_store/mod.rs, crates/core/src/test_env.rs, crates/node/src/lib.rs, crates/node/src/roles/admin.rs, crates/timer/Cargo.toml, crates/types/src/cluster/cluster_state.rs, crates/types/src/cluster_controller.rs, crates/types/src/config/admin.rs, crates/types/src/lib.rs, crates/types/src/metadata_store.rs, crates/types/src/net/partition_processor_manager.rs, crates/types/src/partition_table.rs
This commit introduces a simple scheduler that monitors the cluster state
and elects new leaders if nodes dies. Moreover, it tries to respect the
configured replication policy by randomly spreading partition processors
out across the available set of nodes.
This fixes https://github.com/restatedev/restate/issues/1703.
=> Implement simple scheduler that watches for leadership and replication 

Cargo.lock, crates/bifrost/src/providers/local_loglet/log_state.rs, crates/metadata-store/src/local/store.rs, crates/storage-api/src/storage.rs, crates/types/Cargo.toml, crates/types/src/logs/mod.rs, crates/types/src/storage.rs
[Bifrost] Make StorageEncode object safe
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1809).
* #1816
* #1813
* __->__ #1809
* #1808
=> [Bifrost] Make StorageEncode object safe

.github/workflows/ci.yml, crates/bifrost/src/bifrost.rs, justfile, tools/restatectl/src/commands/mod.rs
Use "verify" as a single alias for all local verification (format check, linting, tests). My goal is to unify what I do as a developer before I push changes for PR, and what the CI build-and-test target does to validate them. I noticed that we are not running the `doctest` target as part of CI and a recent change got in that broke those.
This PR eliminates the standalone RustFmt CI job as this is already part of the `just verify` target. The `rustfmt` phase itself is very quick so we don't get much by executing this in parallel:
The `cargo deny` action is special-cased as the tool would have to be installed separately, and we have this running via `EmbarkStudios/cargo-deny-action` as part of `deps.yml`. We could do the same for `rustfmt` if preferred.
=> Perform "just verify" on PRs in CI

Cargo.lock, crates/invoker-impl/Cargo.toml, crates/invoker-impl/src/invocation_task/service_protocol_runner.rs
This was currently broken due to use of Span::current() which will at this stage have no useful trace or span id. Instead we should use the parent span context which is durably stored with the invocation.
=> Fix trace HTTP header injection

cli/src/commands/state/edit.rs, cli/src/commands/state/get.rs, cli/src/commands/state/util.rs, crates/admin/src/rest_api/services.rs
This will allow the `state clear` CLI command to work even for services that don't yet exist. We change the state modification API to allow services that don't exist when the request is to remove state (and not insert anything else). This means that it would be a no-op for truly non-existent services, and a useful op for ex-services.
=> Allow state to be deleted from non-existent services

Cargo.lock, crates/admin/Cargo.toml, crates/admin/src/rest_api/deployments.rs, crates/admin/src/rest_api/handlers.rs, crates/admin/src/rest_api/invocations.rs, crates/admin/src/rest_api/mod.rs, crates/admin/src/rest_api/services.rs, crates/admin/src/rest_api/subscriptions.rs, crates/admin/src/service.rs, crates/admin/src/state.rs, crates/errors/src/fmt.rs
Since we are spawning the connection handling of the Admin HTTP server
in the TaskCenter, we no longer need to spawn TaskCenter tasks from
within the REST handlers.
=> Use net_util::run_hyper_server to run admin http server

crates/partition-store/src/invocation_status_table/mod.rs, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-api/src/storage.rs, crates/storage-api/src/timer_table/mod.rs, crates/storage-query-datafusion/src/invocation_status/row.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/delayed_send.rs, crates/worker/src/partition/state_machine/tests/matchers.rs, crates/worker/src/partition/state_machine/tests/mod.rs
Fix #1678
This PR essentially reorganizes the code around handling the folllowing events in the state machine:
* Handle the `Command::invoke`. Now everything is under `handle_service_invocation`. Of the changes within this code, the important ones are:
* I moved the deduplication of workflow calls before the scheduled invocation check
* I now handle the case of SourceTable::New for the scheduled calls
* Fix the case of #1678
* Handle the new `Timer::NeoInvoke`
This also includes:
* Reorganize a bit the code around the inbox handling to unify with the above code
* Add several tests, including one for the inbox
There's also a bit of reorganization of the `NeoInvocationStatus` materialized type, to share the common values of Inboxed/Scheduled in a single data structure.
=> Fix idempotent send with delay

Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/metadata_store/mod.rs, crates/core/src/metadata_store/providers/etcd.rs, crates/core/src/metadata_store/providers/mod.rs, crates/metadata-store/Cargo.toml, crates/metadata-store/src/local/mod.rs, crates/metadata-store/src/local/tests.rs, crates/node/src/lib.rs, crates/types/src/config/common.rs
This PR adds support to external metadata store. Right now we only implement the etcd store. 
Note: 
The Testing above is manual testing that involves an etcd cluster. The etcd nodes are randomly stopped or killed and looks like restate operations resumes normally with no issue. Unless the number of down etcd node is bigger than the quorum then of course it fails to write changes. This is restored once enough nodes are back
Fixes #1829
=> Externa metadata store

Cargo.lock, crates/admin/src/cluster_controller/cluster_state.rs, crates/bifrost/src/background_appender.rs, crates/core/Cargo.toml, crates/core/src/error.rs, crates/core/src/lib.rs, crates/core/src/task_center.rs, crates/core/src/task_center_types.rs, crates/log-server/Cargo.toml, crates/node/Cargo.toml, crates/node/src/network_server/handler/mod.rs, crates/node/src/network_server/prometheus_helpers.rs, crates/rocksdb/src/lib.rs, crates/tracing-instrumentation/Cargo.toml, crates/types/src/config/cli_option_overrides.rs, crates/types/src/logs/mod.rs, tools/bifrost-benchpress/Cargo.toml, tools/bifrost-benchpress/src/append_latency.rs, tools/bifrost-benchpress/src/lib.rs, tools/bifrost-benchpress/src/main.rs, tools/bifrost-benchpress/src/util.rs, tools/bifrost-benchpress/src/write_to_read.rs
Fix rocksdb stall-detector sleep bug
Fixes an errornous use of sleep in a tokio::select, it overloads the timerwheel, wasting previous CPU cycles.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1856).
* #1868
* #1867
* #1864
* #1863
* #1862
* #1861
* __->__ #1856
* #1855
* #1850
=> Fix rocksdb stall-detector sleep bug

Cargo.lock, crates/admin/src/cluster_controller/cluster_state.rs, crates/bifrost/src/background_appender.rs, crates/core/Cargo.toml, crates/core/src/error.rs, crates/core/src/lib.rs, crates/core/src/task_center.rs, crates/core/src/task_center_types.rs, crates/node/src/network_server/handler/mod.rs, crates/node/src/network_server/prometheus_helpers.rs
[TaskCenter] Cleanup of task-center and introduces unmanaged tasks
Cleanup and simplifying the code a litte, removes a few unnecessary clones. And most importantl, introduces `spawn_unmanaged()` that returns a runtime-agnostic TaskHandle<T>.
Unmanaged tasks:
- Created with an automatic cancellation token, code running in the task would still use the cancellation watcher as per usual
- Tasks that return a value
- Owner of TaskHandle can decide to cancel gracefully or abort.
- Choice of runtime is still encapsulated within TaskCenter
Other changes:
- Important: Scheduling now works differently. Spawned tasks by default "inherit"s the parent's runtime. This reduces remote tokio scheduling and scopes partition processor workloads more accurately to their respective runtimes.
- Direct and fast …
=> [TaskCenter] Cleanup of task-center and introduces unmanaged tasks

crates/core/src/task_center_types.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/mod.rs, tools/bifrost-benchpress/src/write_to_read.rs
Minor tweaks for perf purposes
- Reduce background appender buffering window to limit tail latency
- Makes sure we run ingress requests on ingress runtime
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1863).
* #1875
* #1864
* __->__ #1863
=> Minor tweaks for perf purposes

crates/bifrost/Cargo.toml, crates/bifrost/src/providers/mod.rs, crates/bifrost/src/service.rs, crates/core/src/task_center_types.rs, crates/node/Cargo.toml, crates/node/src/lib.rs, crates/types/Cargo.toml, crates/types/src/logs/metadata.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/mod.rs, server/Cargo.toml, tools/bifrost-benchpress/Cargo.toml, tools/bifrost-benchpress/src/write_to_read.rs
Control memory-loglet with dedicated feature flag
This allows us to use memory-loglet in performance testing without enabling test mode
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1864).
* #1875
* __->__ #1864
* #1863
=> Control memory-loglet with dedicated feature flag

crates/bifrost/Cargo.toml, crates/bifrost/src/providers/mod.rs, crates/bifrost/src/service.rs, crates/core/src/task_center_types.rs, crates/node/Cargo.toml, crates/node/src/lib.rs, crates/partition-store/tests/integration_test.rs, crates/types/Cargo.toml, crates/types/src/logs/metadata.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/mod.rs, server/Cargo.toml, tools/bifrost-benchpress/Cargo.toml, tools/bifrost-benchpress/src/write_to_read.rs
Fix shutdown warning in partition-store tests
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1875).
* __->__ #1875
* #1864
* #1863
=> Fix shutdown warning in partition-store tests

crates/core/src/task_center.rs, crates/core/src/task_center_types.rs, crates/tracing-instrumentation/src/pretty.rs, crates/worker/src/partition_processor_manager.rs
[TaskCenter] PP runtimes with localset support
TaskCenter now supports creating managed runtimes that runs a localset by default.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1867).
* #1880
* #1879
* __->__ #1867
=> [TaskCenter] PP runtimes with localset support

benchmarks/src/lib.rs, crates/admin/protobuf/cluster_ctrl_svc.proto, crates/admin/src/cluster_controller/scheduler.rs, crates/bifrost/benches/append_throughput.rs, crates/bifrost/benches/util.rs, crates/bifrost/src/bifrost.rs, crates/node/src/lib.rs, crates/partition-store/Cargo.toml, crates/partition-store/benches/basic_benchmark.rs, crates/partition-store/src/deduplication_table/mod.rs, crates/partition-store/src/fsm_table/mod.rs, crates/partition-store/src/keys.rs, crates/partition-store/src/outbox_table/mod.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/scan.rs, crates/partition-store/src/timer_table/mod.rs, crates/storage-api/Cargo.toml, crates/storage-api/src/timer_table/mod.rs, crates/types/protobuf/restate/cluster.proto, crates/types/src/config/common.rs, crates/types/src/config/worker.rs, crates/types/src/identifiers.rs, crates/types/src/logs/builder.rs, crates/types/src/logs/metadata.rs, crates/types/src/logs/mod.rs, crates/types/src/partition_table.rs, crates/wal-protocol/Cargo.toml, tools/bifrost-benchpress/src/main.rs, tools/restatectl/src/commands/dump/cluster_state.rs, tools/restatectl/src/commands/log/describe_log.rs
Resizing PartitionId and LogId and types
This PR reduces the size of PartitionId to a conservative u16 and LogId to u32. This attempts to fix a category of problems we often see when working with those generously-sized types. We would like to have tighter control on how many one of the types would fit into the other, for instance, we can share a bifrost log-id space with multiple clusters. Additionally, with a small partition-id space, we always have the option to expand it later, but with the current u64, it'd be very difficult to go the other way around.
This PR comes with a small risk of incompatibility if anyone has was able to run with more than 65k partitions on a single node. I don't think that's feasible with the amount of resources that it'd require, so, I deem this transition as …
=> Resizing PartitionId and LogId and types

Cargo.lock, Cargo.toml, crates/rocksdb/src/db_manager.rs
The [rust-rocksdb](https://crates.io/crates/rust-rocksdb) crate is a fork of rocksdb which is actively maintained. For example, it depends on the latest RocksDB version 9.5.2 whereas rocksdb depended on RocksDB 9.0.0.
RocksDB 9.5.2 no longer allows to disable the WAL and have `set_recycle_log_file_num` set to > 0. Therefore, we set `set_recycle_log_file_num = 0` if WAL is disabled. This, however, will prevent a dynamic switch between enabling/disabling of the WAL.
The PR picks `rust-rocksdb` from https://github.com/restatedev/rust-rocksdb/tree/next-0.29 which has the additional fixes from https://github.com/restatedev/rust-rocksdb/tree/next ported to https://github.com/zaidoon1/rust-rocksdb/tree/v0.29.0. Once we merge this PR we can remove …
=> Replace rocksdb with rust-rocksdb dependency

Cargo.lock, Cargo.toml, crates/bifrost/src/providers/local_loglet/log_store.rs, crates/metadata-store/src/local/store.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/partition_store_manager.rs, crates/rocksdb/src/db_manager.rs, crates/rocksdb/src/db_spec.rs, crates/rocksdb/src/lib.rs, crates/rocksdb/src/rock_access.rs
This commit replaces the OptimisticTransactionDB with the normal DB
and using WriteBatchWithIndex instead of `Transactions`.
This fixes https://github.com/restatedev/restate/issues/1428.
This PR is based on #1886.
What did not come true is that the performance of Restate would improve with this change. Even though, we should be doing less work when it comes to writing the `WriteBatchWithIndex` and the same when reading, I observed a slight regression in throughput with this change on my machine (might be related to variance). @AhmedSoliman it would be great if you could double check this with your benchmark setup. I cannot really explain why this change (which on the paper removes work) ends up reducing throughput.
=> Replace OptimisticTransactionDB with DB and WriteBatchWithIndex 

crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service.rs, crates/core/src/metadata/manager.rs, crates/core/src/network/connection_manager.rs, crates/core/src/test_env.rs, crates/node/src/lib.rs, crates/types/src/config/common.rs, crates/types/src/logs/metadata.rs, crates/types/src/nodes_config.rs
[Bifrost] Backward-friendly log-server role
- Allow the server to parse the role "log-server" but it doesn't enable this as a default role when generating config. This allows next version to rollback without requiring manual nodes_config edits.
- Adds new (backward-compatible) LogServerConfig stanza in nodes configuration with default `Provisioning` if unset.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1895).
* #1896
* __->__ #1895
=> [Bifrost] Backward-friendly log-server role

Cargo.lock, crates/bifrost/src/providers/local_loglet/log_state.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/local_loglet/record_format.rs, crates/types/Cargo.toml, crates/types/src/storage.rs, crates/wal-protocol/src/lib.rs, crates/worker/src/partition/action_effect_handler.rs, crates/worker/src/partition/cleaner.rs, crates/worker/src/partition/leadership.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/shuffle.rs
[Compat] Fixes for a variety of backward compatibility issues
Addresses the known backward incompatibility issues with v1.0 including the issue introduced in #1692
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1920).
* #1917
* __->__ #1920
=> [Compat] Fixes for a variety of backward compatibility issues

cli/src/clients/datafusion_helpers.rs, cli/src/ui/invocations.rs, crates/storage-query-datafusion/src/journal/row.rs, crates/storage-query-datafusion/src/journal/schema.rs
Fix #1918, show get promise similarly to how we show awakeables.
This is the output when using Restate 1.1:
```
!10908 ➜ just run -- invocations describe inv_1jmqQq8C3SKv5Qv9OMX5i3Icx9uIWrM7Nn                                                                       ~/projects/work/restate (issues/1918) ✗
cargo run  -- invocations describe inv_1jmqQq8C3SKv5Qv9OMX5i3Icx9uIWrM7Nn
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.28s
Running `target/debug/restate invocations describe inv_1jmqQq8C3SKv5Qv9OMX5i3Icx9uIWrM7Nn`
📜 Invocation Information:
――――――――――――――――――――――――――
Created at:   2024-09-03 14:29:54.322 +02:00 (2 minutes ago)                                                                  
Target:       LoanWorkflow/my-loan/run …
```
=> Show GetPromise in CLI, together with promise name

crates/invoker-impl/src/invocation_task/service_protocol_runner.rs, crates/service-protocol/src/message/encoding.rs, crates/service-protocol/src/message/mod.rs
What happened here is that in the original design this was not a relative duration, but an absolute duration from the UNIX_EPOCH... When I switched that I forgot to change this line of code filling the field :)
=> Fix bug when filling StartMessage.duration_since_last_stored_entry

crates/node/src/cluster_marker.rs
This PR updates the version compatibility tuple for the Restate 1.1.0 release. 
- Since we are not introducing new default features that break backwards compatibility with prior releases, the minimum forwards-compatible version remains at `1.0.0`.
- Since we are remain backwards-compatible with older versions' data stores, the minimum version which we can open with the new release also remains at `1.0.0`.
I updated some comments which I feel make them easier to understand.
Fixes #1924
=> Update ClusterMarker doc strings to clarify versioning requirements

crates/metadata-store/src/local/service.rs, crates/node/src/lib.rs
A rejected conditional operation is still a success from the server's point of view. This avoid unnecessary noise on startup, e.g. when the log or partition configuration is loaded.
Without this change, `restate-server` always prints the following error after the initial bootstrap startup:
```
2024-09-08T11:26:13.201071Z ERROR tower_http::trace::on_failure
response failed
classification: Code: 9
latency: 0 ms
on rs:worker-7
in tower_http::trace::make_span::request
method: POST
uri: http://127.0.0.1:5123/dev.restate.metadata_store_svc.MetadataStoreSvc/Put
version: HTTP/2.0
headers: {"te": "trailers", "content-type": "application/grpc", "user-agent": "tonic/0.12.1"}
```
This happens because we were leaning on metadata store preconditions and always attempting to insert a default scheduling …
=> Classify Metadata Store failed precondition as successful

Cargo.lock, deny.toml, tools/service-protocol-wireshark-dissector/Cargo.toml
Address proc-macro-error advisory RUSTSEC-2024-0370
The only dependency that currently needs `proc-macro-error` is `err-derive` used by `arrow_convert` which has not been updated yet. For our use, we only rely on it for restate's CLI so the risk is minimal but we will upgrade when a fix is available upstream. For the time being, we'll ignore this advisory` is `err-derive` used by `arrow_convert` which has not been updated yet. For our use, we only rely on it for restate's CLI so the risk is minimal but we will upgrade when a fix is available upstream. For the time being, we'll ignore this advisory.
=> Address proc-macro-error advisory RUSTSEC-2024-0370

Cargo.toml, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet/util.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/local_loglet/keys.rs, crates/bifrost/src/providers/local_loglet/log_state.rs, crates/bifrost/src/providers/local_loglet/log_store_writer.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/local_loglet/read_stream.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/record.rs, crates/bifrost/src/types.rs, crates/log-server/src/metadata.rs, crates/log-server/src/rocksdb_logstore/keys.rs, crates/types/Cargo.toml, crates/types/src/logs/mod.rs, crates/types/src/net/log_server.rs, crates/types/src/node_id.rs
[Bifrost] Moves LogletOffset to restate-types
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1927).
* #1935
* #1933
* #1929
* #1928
* __->__ #1927
=> [Bifrost] Moves LogletOffset to restate-types

Cargo.toml, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet/util.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/local_loglet/keys.rs, crates/bifrost/src/providers/local_loglet/log_state.rs, crates/bifrost/src/providers/local_loglet/log_store_writer.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/local_loglet/read_stream.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/record.rs, crates/bifrost/src/types.rs, crates/core/src/network/types.rs, crates/log-server/src/metadata.rs, crates/log-server/src/rocksdb_logstore/keys.rs, crates/types/Cargo.toml, crates/types/src/logs/mod.rs, crates/types/src/net/log_server.rs, crates/types/src/node_id.rs
[Networking] Allow sending messages through Outgoing<M>
Allows Outgoing<M> values to be sent directly if they were reciprocal to Incoming.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1928).
* #1935
* #1933
* #1929
* __->__ #1928
* #1927
=> [Networking] Allow sending messages through Outgoing<M>

Cargo.toml, crates/bifrost/src/appender.rs, crates/bifrost/src/background_appender.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet/util.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/local_loglet/keys.rs, crates/bifrost/src/providers/local_loglet/log_state.rs, crates/bifrost/src/providers/local_loglet/log_store_writer.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/local_loglet/read_stream.rs, crates/bifrost/src/providers/local_loglet/record_format.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/record.rs, crates/bifrost/src/types.rs, crates/core/src/network/types.rs, crates/log-server/src/metadata.rs, crates/log-server/src/rocksdb_logstore/keys.rs, crates/types/Cargo.toml, crates/types/src/logs/mod.rs, crates/types/src/logs/record.rs, crates/types/src/net/log_server.rs, crates/types/src/node_id.rs
[Bifrost] Move Record to restate-types
Another mechanical change to make this type available to log-server in future PRs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1929).
* #1935
* #1933
* __->__ #1929
* #1928
* #1927
=> [Bifrost] Move Record to restate-types

.github/workflows/binaries.yml
Replace `addnab/docker-run-action` with a plain `docker run` invocation.
Test run: https://github.com/restatedev/restate/actions/runs/10777696866
=> Replace docker-run-action with plain docker run call

crates/worker/src/partition/state_machine/tests/delayed_send.rs, crates/worker/src/partition/state_machine/tests/idempotency.rs, crates/worker/src/partition/state_machine/tests/kill_cancel.rs, crates/worker/src/partition/state_machine/tests/workflow.rs
Fix state_machine teardown in tests
Correctly shutdown rocksdb manager in those tests. This fixes the occasional segfaults in CI tests
=> Fix state_machine teardown in tests

README.md, docs/dev/release.md
Minor tidy-up:
- remove SDK release requirement
- add explicit service protocol release requirement
=> Update release checklist doc

crates/core/src/test_env.rs
[TestEnv] supporting routing responses back to callers
Summary:
This is a small improvement over the existing TestCoreEnvBuilder networking
by supporting routing responses back to RpcRouter when they make a call over the
NetworkSender.
This only works if the target component you are calling is registered against the same
RouterBuilder as the client.
=> [TestEnv] supporting routing responses back to callers

crates/core/src/network/connection.rs, crates/core/src/network/message_router.rs, crates/types/src/replicated_loglet/mod.rs, crates/types/src/replicated_loglet/params.rs, crates/types/src/replicated_loglet/replication_property.rs
[ReplicatedLoglet] ReplicationProperty is failure-domain-aware
Defines a `ReplicationProperty` struct that represents the failure-domain-aware replication property
Example:
```json
{
"region": 3,
"node": 5,
}
```
Which means that the data is replicated across 5 nodes distributed across 3 regions
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1959).
* __->__ #1959
* #1957
=> [ReplicatedLoglet] ReplicationProperty is failure-domain-aware

Cargo.lock, crates/worker/Cargo.toml, crates/worker/src/partition_processor_manager.rs
The MultiplexedInvokerStatusReader now shares the ChannelStatusReader via an Arc<Mutex<>>.
This fixes #1961.
=> Let MultiplexedInvokerStatusReader share state

Cargo.lock, deny.toml
Security update: https://github.com/restatedev/restate/security/dependabot/8
=> [Security] Bump quinn crate version

crates/core/src/network/connection.rs, crates/core/src/network/message_router.rs
[Networking Add ability to register raw handlers in message router
Also, this introduces a mechanism to subscribe to connection closed events via ConnectionSender
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1957).
* #1959
* __->__ #1957
=> [Networking Add ability to register raw handlers in message router

Cargo.lock, crates/ingress-kafka/Cargo.toml, crates/ingress-kafka/src/consumer_task.rs, crates/ingress-kafka/src/metric_definitions.rs, crates/ingress-kafka/src/subscription_controller.rs
This is the result of investigating the Kafka ingress performance.
Before:
After:
Red line is _Bifrost append_ thpt, green line is _PP Invoke command_ thpt. The kafka load tool generates as much load as possible (around 25k/s records on my machine).
In both situations the initial slow section seems to be caused by the load tool, which takes a good amount of my cpu. After it finishes producing, restate takes all the CPU.  
In the after case, the kafka container OOMs before finishing (probably caused by the high load generated by the consumer), so I cut the section afterwards.
I ran this test using Rust SDK and a virtual object as target, and the following subscription:
```
http localhost:9070/subscriptions source="kafka://my-cluster/test-topic" sink="service://Greeter/greet" \ …
```
=> Kafka perf improvements

crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/mod.rs
=> Make sure we don't send the awakeable completion twice

crates/node/Cargo.toml, crates/node/src/lib.rs, crates/types/src/config/common.rs, server/Cargo.toml
This change disables the log-server role by default to avoid breaking. Additionally, if log-server role is enabled, log-server will not start unless the binary is built with `-F replicated-loglet` to protect the public release from starting the server. This change is necessary to maintain compatibility with v1.0.x.
This change also attempts to detect the presence of log-store and asks the user to remove it manually. We don't remove it automatically to avoid accidental data wipes if accidental rollbacks took place from future versions back to this.
=> Disable log-server role by default to fix v1.0.x compatibility

Cargo.lock, crates/bifrost/Cargo.toml, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/replication/mod.rs, crates/bifrost/src/providers/replicated_loglet/test_util.rs, crates/types/src/nodes_config.rs, crates/types/src/replicated_loglet/params.rs
This introduces ReplicationChecker utility that performs write and f-majority quorum checks. Note that the current implementation is not LocationScope aware and will only consider node-level scope.
The utility is designed to allow attaching any attribute type to nodes in the nodeset and run the check against the set of nodes that match a predicate against those attributes.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1975).
* #1976
* __->__ #1975
=> [Bifrost] Initial NodeSetChecker implementation

Cargo.lock, crates/bifrost/Cargo.toml, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/replication/mod.rs, crates/bifrost/src/providers/replicated_loglet/replication/spread_selector.rs, crates/bifrost/src/providers/replicated_loglet/test_util.rs, crates/types/src/nodes_config.rs, crates/types/src/replicated_loglet/mod.rs, crates/types/src/replicated_loglet/params.rs, crates/types/src/replicated_loglet/spread.rs
Implements a flood selector (selects all writeable nodes in the effective nodeset).
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1976).
* __->__ #1976
* #1975
=> [Bifrost] SpreadSelector initial implementation

crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/mod.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/providers/replicated_loglet/rpc_routers.rs
The new structure `LogServersRpc` is passed down to all loglets to facilitate sending and receiving network messages to logservers.
=> [Bifrost] Add RPC routers for bifrost to logserver communication

crates/admin/src/cluster_controller/service.rs, crates/bifrost/src/providers/local_loglet/mod.rs, tools/restatectl/src/commands/log/mod.rs, tools/restatectl/src/commands/log/trim_log.rs
This PR just wires the existing trim command into the restatectl CLI, with only some minor logging adjustments on the backend.
=> Add restatectl logs trim subcommand

Cargo.lock, crates/bifrost/Cargo.toml, crates/bifrost/src/loglet/util.rs, crates/bifrost/src/providers/replicated_loglet/replication/spread_selector.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/append.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/mod.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/node.rs, crates/types/src/config/bifrost.rs, crates/types/src/time.rs
scaffolding leader Sequencer
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1982).
* __->__ #1982
* #1977
=> scaffolding leader Sequencer

Cargo.lock, Cargo.toml, crates/partition-store/Cargo.toml, crates/partition-store/src/lib.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/partition_store_manager.rs, crates/partition-store/src/snapshots.rs, crates/partition-store/tests/integration_test.rs, crates/partition-store/tests/snapshots_test/mod.rs, crates/rocksdb/src/background.rs, crates/rocksdb/src/error.rs, crates/rocksdb/src/lib.rs, crates/rocksdb/src/rock_access.rs, crates/storage-api/src/lib.rs, crates/types/src/id_util.rs, crates/types/src/identifiers.rs
With this change we add the basic ability for the PartitionProcessor to export
its state into a snapshot, and later re-create this by importing the same
snapshot.
1. **this PR** https://github.com/restatedev/restate/pull/1954
2. https://github.com/restatedev/restate/pull/1981
3. https://github.com/restatedev/restate/pull/1991
4. https://github.com/restatedev/restate/pull/1992
=> [Snapshots] 1: Introduce partition store snapshotting support

crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/append.rs, crates/types/src/live.rs, crates/types/src/logs/tail.rs
The test runs a log-server and a replicated loglet on the same node, sets up replication to 1 and performs a couple of appends.
This also fixes a bug in offset calculation in sequencer
=> [Bifrost] smoke testing single-node append path for replicated loglet

crates/bifrost/src/providers/replicated_loglet/log_server_manager.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/mod.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/append.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/mod.rs, crates/core/src/task_center_types.rs
- Makes LogServerManager shared across components in replicated loglet, not just sequencer.
- Networking is passed in when needed to unnecessary clones, and fewer generic types
- StoreTask now holds references instead of clones
=> [Bifrost] Make LogServerManager shared across components in replicated loglet

crates/core/src/task_center_types.rs, crates/core/src/worker_api/partition_processor_manager.rs, crates/partition-store/src/snapshots.rs, crates/rocksdb/src/rock_access.rs, crates/types/src/config/mod.rs, crates/types/src/config/worker.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/snapshot_producer.rs, crates/worker/src/partition_processor_manager.rs
This component can create online partition snapshots at runtime, building on #1954.
1. https://github.com/restatedev/restate/pull/1954
2. **this PR** https://github.com/restatedev/restate/pull/1981
3. https://github.com/restatedev/restate/pull/1998
4. https://github.com/restatedev/restate/pull/1999
Closes: https://github.com/restatedev/restate/issues/1894
=> [Snapshots] Introduce a Snapshot Producer component

crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/mod.rs
Loglet::enqueue_batch should return OperationError
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2009).
* #2003
* __->__ #2009
=> Loglet::enqueue_batch should return OperationError

crates/core/src/network/net_util.rs, crates/core/src/network/transport_connector.rs, crates/metadata-store/src/local/grpc/client.rs, crates/metadata-store/src/local/tests.rs, tools/restatectl/src/commands/log/dump_log.rs
When the entry is occupied, we were trying to read with a mutable reference held. I've also changed it slightly such that in the case where the channel already exists, we only take a read reference, and only fall back to a write lock when its not present.
=> Fix networking deadlock caused by hanging mutable reference

crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/log-server/src/loglet_worker.rs, crates/log-server/src/metadata.rs, crates/log-server/src/network.rs, crates/log-server/src/rocksdb_logstore/store.rs, crates/log-server/src/rocksdb_logstore/writer.rs, crates/types/src/net/log_server.rs
This introduces `LogServerRequestHeader` and ensures we exchange `known_global_tail` on log-server responses. Additionally, we removed the dedicated tracking map for the global tail and it's now part of the `LogletState`. This simplifies the code and paves the way for a future optimization where we periodically persist the last known global tail on log-servers for more efficient tail repair in edge cases.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2008).
* #2019
* #2012
* __->__ #2008
=> [Bifrost] Unify log-server request headers and global_tail exchange in log-server responses

crates/bifrost/src/loglet/util.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/log-server/src/loglet_worker.rs, crates/log-server/src/metadata.rs, crates/log-server/src/network.rs, crates/log-server/src/rocksdb_logstore/store.rs, crates/log-server/src/rocksdb_logstore/writer.rs, crates/types/protobuf/restate/common.proto, crates/types/src/net/log_server.rs
A new message that allows Bifrost to wait for a logserver to catch up to a certain local/global tail, or for the node to be sealed.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2012).
* #2019
* __->__ #2012
* #2008
=> [Bifrost] WaitForTail message implementation

Cargo.lock, Cargo.toml, crates/admin/build.rs, crates/core/build.rs, crates/metadata-store/build.rs, crates/metadata-store/src/local/service.rs, crates/node/src/network_server/service.rs
Summary: Fixes the RUSTSEC-2024-0376 vulnerability by upgrading tonic to 0.12.3
Test Plan: CI
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2020).
* #2019
* __->__ #2020
=> Fix for RUSTSEC-2024-0376 by upgrading tonic to 0.12.3

.github/workflows/ci.yml, .github/workflows/docker.yml
This takes about 40s, and we have a lot more storage space on warp than we did on github
=> Free disk space action not needed any more

crates/admin/protobuf/cluster_ctrl_svc.proto, crates/node/src/network_server/handler/cluster_ctrl.rs, tools/restatectl/src/commands/log/describe_log.rs
While testing snapshots, I realized we don't currently have a good way to query the trim position for a log.
This is what the tool output looks like now:
```
> restatectl logs list
📋 Logs:
――――――――
Metadata version  v1
Logs
LOG-ID  SEGMENTS  TAIL BASE LSN  KIND
0       1         1              Local
> restatectl logs describe -l 0
📋 Log 0:
―――――――――
Metadata version  v1
Trim point        9640
Segments
SEGMENT  STATE  BASE LSN  TAIL LSN  KIND
0        OPEN   1         9642      Local
```
=> restatectl describe log reports log trim point

crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
[Sequencer] Appender aborts if majority of nodes are sealed
=> [Sequencer] Appender aborts if majority of nodes are sealed

crates/bifrost/src/providers/replicated_loglet/error.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/rpc_routers.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/mod.rs, crates/types/src/config/bifrost.rs
Implementation of the find-tail process in case we are don't have a leader sequencer.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2019).
* #2028
* __->__ #2019
=> [Bifrost] FindTail task in replicated loglet

crates/bifrost/src/loglet/error.rs, crates/bifrost/src/loglet/mod.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/mod.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/core/src/network/rpc_router.rs, crates/types/Cargo.toml, crates/types/src/net/replicated_loglet.rs
[ReplicatedLoglet] Remote append
Summary:
Implements a remote loglet append calls to leader sequencer
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2003).
* #2017
* __->__ #2003
=> [ReplicatedLoglet] Remote append

crates/local-cluster-runner/examples/two_nodes_and_metadata.rs, crates/local-cluster-runner/src/cluster/mod.rs, crates/local-cluster-runner/src/node/mod.rs, server/tests/cluster.rs
For the time being we only want to run admin on the metadata node, which will also be allowed to bootstrap.
=> Avoid admin roles in local cluster runner

crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/providers/replicated_loglet/record_cache.rs, crates/types/src/config/bifrost.rs
Add support to disable record cache
Summary:
Since record cache will be used in multiple places. It's possible
to disable it by setting the memory budget to None. This way code
can still use the cache normally but no records will be cached.
All calls to Get will always return None if cache is disabled
=> Add support to disable record cache

crates/admin/src/cluster_controller/scheduler.rs, crates/types/src/cluster/cluster_state.rs, crates/types/src/config/bifrost.rs
Fix marking the SchedulingPlan wrongly as modified if no leadership change happened.
=> Fix marking the SchedulingPlan wrongly as modified if no leadership change happened

Cargo.lock, crates/bifrost/Cargo.toml, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet/util.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/providers/replicated_loglet/log_server_manager.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/metric_definitions.rs, crates/bifrost/src/providers/replicated_loglet/mod.rs, crates/bifrost/src/providers/replicated_loglet/read_path/mod.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/record_cache.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/record.rs, crates/core/src/network/connection.rs, crates/core/src/network/networking.rs, crates/core/src/network/rpc_router.rs, crates/core/src/network/types.rs, crates/core/src/task_center_types.rs, crates/log-server/src/loglet_worker.rs, crates/log-server/src/service.rs, crates/types/src/replicated_loglet/params.rs
This also modifies the log-server startup to ensure provisioning happens before other components start.
Test Plan:
Uses the existing test in loglet_tests.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2039).
* __->__ #2039
* #2028
=> [Bifrost] Test for sealing empty replicated loglet on single node

crates/bifrost/src/providers/replicated_loglet/sequencer/mod.rs, crates/log-server/src/loglet_worker.rs, crates/log-server/src/logstore.rs, crates/log-server/src/network.rs, crates/log-server/src/rocksdb_logstore/store.rs, crates/types/protobuf/restate/common.proto, crates/types/src/net/log_server.rs
Digest as a summary of offset-range presence on a certain node. A a new request message `GetDigest` is introduced to the log-server to allow an efficient scanning of a range of offsets to check which offsets reside on this server. This process will be used as part of the tail repair to determine (a) whether a record meets the replication requirements and (b) where to fetch a certain record if we need to re-replicate.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2042).
* #2046
* __->__ #2042
=> [Bifrost] GetDigest message in replicated loglets

Cargo.lock, crates/metadata-store/src/local/mod.rs, tools/restatectl/Cargo.toml, tools/restatectl/src/app.rs, tools/restatectl/src/commands/log/dump_log.rs, tools/restatectl/src/commands/metadata/get.rs, tools/restatectl/src/commands/metadata/mod.rs, tools/restatectl/src/commands/metadata/patch.rs, tools/restatectl/src/commands/mod.rs, tools/restatectl/src/environment/metadata_store.rs, tools/restatectl/src/environment/mod.rs, tools/restatectl/src/environment/task_center.rs
This PR introduces a new `metadata` subcommand with options to retrieve and update values in both "direct" mode working on a `local-metadata-store` or remotely against both the Restate-native metadata service and Etcd.
The FlexBuffers-encoded values are rendered to the user as JSON. This allows us to use JSON Patch to succinctly express modifications.
Here is how it looks in action:
```
> restatectl metadata get -k "schema_registry"
{
"version": 9,
"deployments": [
[
"dp_11Oa6uG2mNPjTYcD03AFgnn",
{
"metadata": {
"created_at": 1727447806006,
"delivery_options": {
"additional_headers": {}
},
"supported_protocol_versions": {
"end": 2,
"start": 1
},
...
> restatectl metadata patch --access-mode direct --config-file config.toml --key "schema_registry" \
--patch '[{"op": "replace", "path": …
```
=> Add metadata get/patch subcommands to restatectl

crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/log-server/src/loglet_worker.rs, crates/log-server/src/rocksdb_logstore/record_format.rs, crates/log-server/src/rocksdb_logstore/store.rs, crates/log-server/src/rocksdb_logstore/writer.rs, crates/types/src/net/log_server.rs
Use `Arc<[Record]>` instead of `Vec<Record>` for `Store` messages
Summary:
Using `Arc` to avoid copying record batches when sending a store wave
to mutiple log server.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2049).
* #2050
* __->__ #2049
=> Use `Arc<[Record]>` instead of `Vec<Record>` for `Store` messages

crates/types/src/logs/builder.rs, tools/restatectl/src/commands/log/gen_metadata.rs, tools/restatectl/src/commands/log/mod.rs
Generates a JSON formatted log metadata for replicated-loglet.
```console
cargo run --bin restatectl -- logs generate-metadata -r 2 -n 2 -s N1:2 --nodeset N1,N2,N3 --pretty
```
```
{
"version": 2,
"logs": [
[
0,
{
"chain": [
[
1,
{
"kind": "replicated",
"params": "{\"loglet_id\":1,\"sequencer\":\"N1:2\",\"replication\":{\"node\":2},\"nodeset\":[\"N1\",\"N2\",\"N3\"]}",
"index": 0
}
]
]
}
],
[
1,
{
"chain": [
[
1,
{
"kind": "replicated",
"params": "{\"loglet_id\":4294967297,\"sequencer\":\"N1:2\",\"replication\":{\"node\":2},\"nodeset\":[\"N3\",\"N1\",\"N2\"]}",
"index": 0
}
]
]
}
]
]
}
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2051).
* #2052
* __->__ #2051
=> [Bifrost] restatectl logs generate-metadata command

tools/restatectl/src/app.rs, tools/restatectl/src/commands/partitions/gen_metadata.rs, tools/restatectl/src/commands/partitions/mod.rs
Generates partition table metadata (version 2 by default)
```console
cargo run --bin restatectl -- partitions generate-metadata -n 5 --pretty
```
```
{
"version": 2,
"num_partitions": 5,
"partitions": [
[
0,
{
"key_range": {
"start": 0,
"end": 3689348814741910323
}
}
],
[
1,
{
"key_range": {
"start": 3689348814741910324,
"end": 7378697629483820646
}
}
],
[
2,
{
"key_range": {
"start": 7378697629483820647,
"end": 11068046444225730969
}
}
],
[
3,
{
"key_range": {
"start": 11068046444225730970,
"end": 14757395258967641292
}
}
],
[
4,
{
"key_range": {
"start": 14757395258967641293,
"end": 18446744073709551615
}
}
]
]
}
```
=> restatectl command to generate partition table

Cargo.lock, tools/restatectl/Cargo.toml, tools/restatectl/src/commands/metadata/mod.rs, tools/restatectl/src/commands/metadata/patch.rs, tools/restatectl/src/commands/metadata/put.rs
This commit adds support for put operations for metadata It is just a convenience around patch.
```
./target/debug/restatectl metadata get --key "partition_table" > foo.json
```
Either:
```
restatectl metadata put --key "partition_table" foo.json
```
Or:
```
cat foo.json | restatectl metadata put --key "partition_table" --path foo.json -
```
=> [restatectl] Support metadata Put

Cargo.lock, crates/local-cluster-runner/Cargo.toml, crates/local-cluster-runner/src/cluster/mod.rs, crates/local-cluster-runner/src/node/mod.rs, server/tests/cluster.rs, server/tests/common/replicated_loglet.rs
We have seen at least one flake  where the cluster wasn't ready in time. This could be some subtle race condition. To help find it we will print out logs from the node that isn't up. Also some tests just didn't have logging enabled.
=> Make it easier to debug failing local cluster runner tests

crates/admin/protobuf/cluster_ctrl_svc.proto, crates/admin/src/cluster_controller/service.rs, crates/node/src/network_server/handler/cluster_ctrl.rs, crates/types/protobuf/restate/common.proto, crates/types/src/net/partition_processor_manager.rs, crates/worker/src/lib.rs, crates/worker/src/partition_processor_manager.rs, tools/restatectl/src/app.rs, tools/restatectl/src/commands/snapshot/create_snapshot.rs, tools/restatectl/src/commands/snapshot/mod.rs
Stacked PRs:
* #1999
* __->__#1998
--- --- ---
=> Expose a partition worker CreateSnapshot RPC

crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/rpc_router.rs, crates/core/src/network/types.rs
Expose peer metdata version through incoming messagtes
Summary:
This allows incoming messages to expose metadata of remote peer
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2061).
* #2062
* __->__ #2061
=> Expose peer metdata version through incoming messagtes

crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/replication/spread_selector.rs, crates/bifrost/src/providers/replicated_loglet/rpc_routers.rs, crates/bifrost/src/providers/replicated_loglet/tasks/digests.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/mod.rs, crates/bifrost/src/providers/replicated_loglet/tasks/repair_tail.rs, crates/types/src/replicated_loglet/params.rs, crates/types/src/replicated_loglet/spread.rs
This puts together the design and implementation of the tail repair procedure that's required when FindTail cannot establish a consistent durable tail from log-servers. The details are described as comments in code.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2046).
* #2064
* #2056
* __->__ #2046
=> [Bifrost] RepairTail task for replicated loglet

crates/bifrost/src/appender.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/replication/spread_selector.rs, crates/bifrost/src/providers/replicated_loglet/rpc_routers.rs, crates/bifrost/src/providers/replicated_loglet/tasks/digests.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/mod.rs, crates/bifrost/src/providers/replicated_loglet/tasks/periodic_tail_checker.rs, crates/bifrost/src/providers/replicated_loglet/tasks/repair_tail.rs, crates/core/src/metadata/manager.rs, crates/core/src/network/networking.rs, crates/log-server/src/rocksdb_logstore/builder.rs, crates/types/src/config/networking.rs, crates/types/src/net/metadata.rs, crates/types/src/replicated_loglet/params.rs, crates/types/src/replicated_loglet/spread.rs, crates/worker/src/partition_processor_manager.rs, tools/mock-service-endpoint/Cargo.toml
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2064).
* __->__ #2064
* #2056
* #2046
=> [Bifrost] Periodic tail checker

server/tests/replicated_loglet.rs
Three sets up a bit of a tricky situation where all three nodes need to be up all the time.
=> Set replication property to two in replicated loglet tests

.github/workflows/ci.yml, tools/scripts/verify-ui-artifact
- Adds a script to verify the committed ui artifact is matches the published one in restate-web-ui repo
- Runs the script in github workflows
=> Verify the committed UI artifact matches the published artifact

crates/admin/src/cluster_controller/cluster_state.rs, tools/restatectl/src/app.rs, tools/restatectl/src/commands/dump/cluster_state.rs, tools/restatectl/src/commands/dump/mod.rs, tools/restatectl/src/commands/partitions/mod.rs, tools/restatectl/src/commands/partitions/status.rs
This change fixes a trivial issue in the dump cluster sub-command where it would only print the partition processor status for one node rather than all nodes scheduler to run a given partition.
It also renames the tool from its original `dump cluster-status` subcommand to `partitions status`, which reflects much better what it's doing.
The server-side change is purely a cosmetic refactoring replacing an early if/continue with a two-arm match.
Example from a local three-worker / 4 partitions cluster:
```
> restatectl partitions status --cluster-controller $RESTATE_CLUSTER_CONTROLLER_ADDRESS
Alive partition processors (nodes config v7, partition table v1)
P-ID  NODE  RUN-MODE          REPLAY  APPLIED-LSN  PERSISTED-LSN  OBSERVED-LEADER  #-SKIPS  LAST-SEEN
0     N2:1  Leader …
```
=> Fix: restatectl dump cluster renders status for all live nodes

crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/mod.rs, crates/core/src/task_center.rs, crates/types/src/node_id.rs, crates/types/src/replicated_loglet/params.rs
This hunts for signals to tell us if there is an ongoing seal or not. It's not used as a source of truth for whether a loglet is sealed or not, but it's important to detect an externally started seal operation that the sequencer was not aware of.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2066).
* #2094
* #2076
* #2075
* __->__ #2066
=> [Bifrost] CheckSeal task for replicated loglet

crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/mod.rs, crates/core/src/task_center.rs, crates/log-server/src/loglet_worker.rs, crates/types/src/node_id.rs, crates/types/src/replicated_loglet/params.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2075).
* #2094
* #2076
* __->__ #2075
* #2066
=> [Bifrost] Support repair store in log-server

crates/bifrost/benches/util.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/mod.rs, crates/core/src/metadata/manager.rs, crates/core/src/metadata/mod.rs, crates/core/src/network/connection_manager.rs, crates/core/src/task_center.rs, crates/core/src/test_env.rs, crates/log-server/src/loglet_worker.rs, crates/node/src/lib.rs, crates/types/src/node_id.rs, crates/types/src/replicated_loglet/params.rs, tools/bifrost-benchpress/src/main.rs, tools/restatectl/src/commands/log/dump_log.rs
MetadataManager no long needs `Networking` as dependency. It'll keep track of the WeakConnection of where we observed the updated version, then it'll attempt to use this connection to fetch the update (no need to re-establish the connection with the peer, or block the metadata manager loop). If fetching from this connection fails, metadata manager falls back to syncing from metadata store as usual.
This also sets a timeout while waiting for metadata store fetches to allow the system to recover by letting other nodes share their metadata before the next tick comes in.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2076).
* #2094
* __->__ #2076
* #2075
* #2066
=> Networking is no longer a dependency for MetadataManager

crates/admin/protobuf/cluster_ctrl_svc.proto, crates/node/src/network_server/handler/cluster_ctrl.rs, crates/types/src/replicated_loglet/params.rs, crates/types/src/replicated_loglet/replication_property.rs, tools/restatectl/src/app.rs, tools/restatectl/src/commands/log/describe_log.rs, tools/restatectl/src/commands/log/list_logs.rs, tools/restatectl/src/commands/metadata/mod.rs
Example with a 4-partition replicated loglet.
- we now support multiple logs including ranges of ids
- support head/tail/all to control the displayed segments per log (tail -25 by default)
```
> restatectl logs describe 0-3 --extra --tail 1
Log Id: 0 (v11)
IDX  FROM-LSN  KIND        LOGLET-ID  REPLICATION  SEQUENCER  EFF-NODESET   PARAMS
▶︎ 6    142       Replicated  6          {node: 2}    N2:1       [N2, N3, N4]  {"loglet_id":6,"sequencer":"N2:1","replication":{"node":2},"nodeset":["N3","N2","N4"]}
---
1/5 segments shown.
Log Id: 1 (v11)
IDX  FROM-LSN  KIND        LOGLET-ID             REPLICATION  SEQUENCER  EFF-NODESET   PARAMS
▶︎ 3    66        Replicated  14232785765231168648  {node: 2}    N2:1       [N2, N3, N4]  {"loglet_id":14232785765231168648,"sequencer":"N2:1","replication":{"n …
```
=> Enhance the `restatectl describe log` command

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service.rs, crates/core/src/metadata_store/mod.rs, crates/node/src/lib.rs, crates/types/src/config/cli_option_overrides.rs, crates/types/src/config/common.rs
Adds a feature to disable the auto-provisioning of partitions by the cluster controller. To disable the auto-provisioning, you can set the `auto-provision-partitions = false` in the configuration or on the CLI via `--auto-provision-partitions=false`.
This PR is based on #2053
=> Auto provision

crates/admin/src/cluster_controller/logs_controller.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/log-server/src/loglet_worker.rs, crates/log-server/src/rocksdb_logstore/keys.rs, crates/log-server/src/rocksdb_logstore/store.rs, crates/types/src/logs/metadata.rs, crates/types/src/replicated_loglet/params.rs, server/tests/common/replicated_loglet.rs, tools/restatectl/src/commands/log/gen_metadata.rs, tools/restatectl/src/commands/log/reconfigure.rs
This commits makes the ReplicatedLogletId generation deterministic as
it now composes from the LogId + SegmentIndex.
This fixes https://github.com/restatedev/restate/issues/2086.
This PR is based on #2058.
=> Compose ReplicatedLogletId out of LogId + SegmentIndex 

crates/local-cluster-runner/README.md, crates/local-cluster-runner/examples/three_nodes_and_metadata.rs, justfile
Also sets default logging to debug for Restate, and bootstrap partitions to 2.
=> Update local-cluster example to start a 3+1 node cluster

crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/deployment/row.rs, crates/storage-query-datafusion/src/deployment/schema.rs, crates/storage-query-datafusion/src/invocation_status/row.rs, crates/storage-query-datafusion/src/invocation_status/schema.rs, crates/storage-query-datafusion/src/table_docs.rs
Fix #1993, this is generally useful, and could have helped to write a migration script that interacts with protocol versions.
=> Add service protocol version in SQL shell for sys_deployment and sys_invocation

crates/worker/src/partition/mod.rs, crates/worker/src/partition_processor_manager.rs
This commit solves a problem where the PartitionProcessorManager thinks that
its PartitionProcessor can still win the leadership even though the PP has
lost its leadership to another PP.
This fixes https://github.com/restatedev/restate/issues/2112.
=> Fix leadership deadlock by checking whether our attempt is still valid

crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/providers/replicated_loglet/rpc_routers.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/types/src/net/replicated_loglet.rs
For non-sequencer nodes, we'll attempt to contact the sequencer first if possible (no higher generation exists, and it's network-reachable) before trying to perform quorum check to determine the global tail.
Validated on a test cluster.
=> [Bifrost] FindTail tries the sequencer node first

Cargo.lock, crates/admin/Cargo.toml, crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service.rs, crates/types/src/cluster_controller.rs, crates/types/src/nodes_config.rs
Let Scheduler respect replicated loglet placements
Let LogsController respect the preferred sequencer node
This fixes #2081.
=> Add support for co-locating sequencers and partition processor leaders

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/observed_cluster_state.rs
This fixes https://github.com/restatedev/restate/issues/2116 and is based on #2115.
=> Consider generational aspect of sequencer when deciding whether reconfiguration is needed

crates/admin/protobuf/cluster_ctrl_svc.proto, crates/bifrost/src/bifrost_admin.rs, crates/node/src/network_server/handler/cluster_ctrl.rs, tools/restatectl/src/commands/log/describe_log.rs, tools/restatectl/src/commands/log/find_tail.rs, tools/restatectl/src/commands/log/mod.rs
[restatectl] Implementing `logs find-tail` subcommand
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2118).
* #2109
* #2106
* __->__ #2118
=> [restatectl] Implementing `logs find-tail` subcommand

crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/core/src/metadata/manager.rs, crates/core/src/network/rpc_router.rs, crates/core/src/network/types.rs, crates/ingress-dispatcher/src/dispatcher.rs, crates/types/src/net/metadata.rs, crates/worker/src/partition_processor_manager.rs
Generic `Reciprocal` type to avoid responding with wrong message
Summary:
After I made a mistake of responding to an incoming message with the
wrong resposne type. I think a Reciprocal should be typed with the
expected response message.
After changing this the compiler didn't pass the code where the bug was
=> Generic `Reciprocal` type to avoid responding with wrong message

crates/admin/src/cluster_controller/logs_controller.rs
[LogController] debounce on failure to avoid busy loops
Summary:
Track "trials" to write logs to avoid getting stuck in a busy
loop. This is solved by introduction a counter that is incremented
on trial.
If counter is not zero, a delay is introduced before retyring
Fixes #2079
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2109).
* #2106
* __->__ #2109
=> [LogController] debounce on failure to avoid busy loops

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/observed_cluster_state.rs, crates/local-cluster-runner/src/node/mod.rs, crates/node/src/lib.rs, crates/node/src/network_server/handler/cluster_ctrl.rs, crates/node/src/network_server/mod.rs, crates/node/src/network_server/service.rs, crates/node/src/roles/admin.rs, crates/types/src/config/admin.rs, server/tests/common/replicated_loglet.rs
The replicated loglet cluster tests assume that they are in control
of configuring the loglet. This only works if the cluster does not
start a `LogsController`. This is achieved by starting these tests w/o
Role::Admin. With the `LogController`, it happened that the log was
automatically reconfigured since the configured sequencer did not 
respond to heartbeats.
=> Don't start admin node for replicated loglet cluster tests 

crates/core/src/task_center_types.rs, crates/worker/src/partition/leadership.rs
In order to not block the PP while writing the announce_leadership message to Bifrost, this commit moves it into the background.
This is a temporary solution until we have a better approach.
This fixes #2133.
=> Move announce_leadership message into the background

crates/admin/src/rest_api/invocations.rs, crates/admin/src/rest_api/services.rs, crates/ingress-dispatcher/src/dispatcher.rs, crates/wal-protocol/src/lib.rs, crates/worker/src/partition/cleaner.rs, crates/worker/src/partition/shuffle.rs
With this commit we will indefinitely retry a failed write attempt to Bifrost
until we succeed.
=> Add simple retry mechanism in Shuffle if writing to Bifrost fails

cli/src/clients/datafusion_helpers.rs
Fix #2137. This still doesn't allow the old CLI to talk with the fixed runtime (we can fix this as followup if we want to)
=> Fix `restate invocation ls` issue with `full_count` field

crates/admin/protobuf/cluster_ctrl_svc.proto, crates/admin/src/cluster_controller/logs_controller.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet_wrapper.rs, crates/node/src/network_server/handler/cluster_ctrl.rs, crates/types/src/logs/metadata.rs, tools/restatectl/src/commands/log/reconfigure.rs
[restatectl] Show result of `logs reconfigure`
```
restatectl log reconfigure --log-id 0 --provider replicated
✅ Log reconfiguration
└ Segment Index: 2
Sealed segment
├ Index: 1
├ Tail LSN: 2
├ Provider: replicated
├ Loglet ID: 0_1
├ Sequencer: N0:1
├ Replication: {node: 1}
└ Node Set: [N0]
```
=> [restatectl] Show result of `logs reconfigure`

cli/src/commands/services/config/edit.rs, cli/src/commands/services/config/patch.rs, cli/src/commands/services/config/view.rs, crates/admin-rest-model/src/services.rs, crates/admin/src/rest_api/services.rs, crates/admin/src/schema_registry/mod.rs, crates/admin/src/schema_registry/updater.rs, crates/ingress-http/src/lib.rs, crates/invoker-impl/src/invocation_task/mod.rs, crates/invoker-impl/src/lib.rs, crates/types/src/schema/service.rs
Fix #1994
Some screenshots:
* get the default configuration:
* Use the `conf edit` command with the editor:
* After the edit of the configuration:
=> Allow users to customize inactivity_timeout and abort_timeout on a service basis.

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/service.rs, crates/types/src/config/admin.rs
[LogController] Detect log being sealed
Summary:
Detect if a log is sealed (or being sealed).
This is done by periodically running find-tail on all logs and change the state
if a sealed tail is found
Fixes #2083
=> [LogController] Detect log being sealed

tools/restatectl/src/commands/node/list_nodes.rs
A new optional argument augments the node list table with additional metadata from all reachable nodes obtained from the NodeSvc::GetIdent operation.
Sample output:
```
> restatectl nodes list --extra
Node Configuration (v11)
NODE  GEN  NAME           ADDRESS                                                                 ROLES                  UPTIME   STATUS   ADMIN  WORKER  LOG-SVR  META   NODES-V  LOGS-V  SCHEMA-V  PART-V
N1    2    metadata-node  unix:/Users/pavel/restate/restate/restate-data/metadata-node/node.sock  Admin | MetadataStore  5 hours  Alive    Ready  -       -        Ready  11       6       0         1
N2    2    node-1         unix:/Users/pavel/restate/restate/restate-data/node-1/node.sock         LogServer | Worker     5 hours  Alive    -      Ready   Ready    - …
```
=> Add restatectl nodes --extra mode with GetIdent server info

tools/restatectl/src/commands/cluster/overview.rs, tools/restatectl/src/commands/partition/list.rs
The loglet segment is inferred by the admin node based on the reported applied LSN from the partition.
`restatectl partitions list` now:
- includes the loglet sequencer node id, if the partition processor is using a replicated loglet and its applied LSN is in the tail segment
- highlights when the given node is the leader for the partition, and when the sequencer in use matches the PP node id (leaders only)
- de-emphasized active followers (no longer green)
- supports ordering the partition table display by partition id (default), or node id, or leadership status (active > follower)
`restatectl status` will also get these improvements.
Sample output:
=> Display sequencer node in partition processors table

crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/admin/src/cluster_controller/service.rs, crates/core/src/network/connection_manager.rs, crates/core/src/worker_api/partition_processor_manager.rs, crates/node/src/lib.rs, crates/node/src/roles/base.rs, crates/node/src/roles/mod.rs, crates/node/src/roles/worker.rs, crates/types/protobuf/restate/common.proto, crates/types/src/net/mod.rs, crates/types/src/net/node.rs, crates/worker/src/lib.rs, crates/worker/src/partition_processor_manager.rs
Node base Role that runs on all nodes to
Summary:
Introduce a new `base` role that is hosted
by all nodes. This allows to handle common
node related messages like `GetNodeState`
Fixes #2082
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2157).
* #2158
* __->__ #2157
=> Node base Role that runs on all nodes to

crates/types/protobuf/restate/common.proto, crates/types/src/net/partition_processor_manager.rs, crates/worker/src/partition_processor_manager.rs
Deprecate GetProcessorsState
Summary:
This is now handled by the GetNodeState which is more generic and is
supported by all nodes regardless if they are Workers or not
=> Deprecate GetProcessorsState

Cargo.lock, crates/core/Cargo.toml, crates/core/src/network/connection_manager.rs, crates/core/src/network/types.rs, crates/tracing-instrumentation/src/lib.rs, crates/types/protobuf/restate/node.proto, crates/types/src/protobuf.rs
Enable Restate runtime to trace across processes
Summary:
Handle propagation of span context across nodes
Fixes #2155
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2167).
* #2168
* __->__ #2167
=> Enable Restate runtime to trace across processes

Cargo.lock, crates/storage-query-postgres/Cargo.toml
Hello team,
This patch includes an upgrade of my pgwire library, from 0.23 to 0.25, including a few key issue fixes:
- SASL authentication message decoding
- Busy loop with direct SSL handshake (introduced in 0.24)
=> chore: update pgwire to 0.25

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/types/src/config/worker.rs, crates/types/src/invocation.rs, crates/worker/Cargo.toml, crates/worker/src/ingress_integration.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/idempotency.rs, crates/worker/src/partition/state_machine/tests/mod.rs, crates/worker/src/partition/state_machine/tests/workflow.rs
* Re-implement the deduplication code path for idempotent requests/workflow requests, by using the new deterministic id
* Handle deterministic ID for attach/get output
* Add disable_idempotency_table experimental feature, such that on Restate 1.2 we'll still write the idempotency table and the virtual object lock table (for workflow runs), but we'll stop using it in restate 1.3
* Added rstest for matrix testing the unit tests with the different features enabled/disabled.
Fix https://github.com/restatedev/restate/issues/1989
=> Deterministic invocation ID part 2

Cargo.lock, crates/core/Cargo.toml, crates/core/src/lib.rs, crates/core/src/metadata/manager.rs, crates/core/src/routing_info/mod.rs, crates/core/src/task_center.rs, crates/node/src/lib.rs, crates/types/src/cluster_controller.rs
New approach as an alternative to https://github.com/restatedev/restate/pull/2149, which exposes a dedicated `PartitionRouting` lookup interface. Its implementation is initially backed by the Metadata Store but it is not expected to stay that way for long.
=> Add a PartitionRouting partition-id-to-node mapping holder and background refresher

Cargo.lock, crates/core/src/network/types.rs, crates/node/Cargo.toml, crates/node/src/lib.rs, crates/tracing-instrumentation/Cargo.toml, crates/tracing-instrumentation/src/exporter.rs, crates/tracing-instrumentation/src/lib.rs, crates/types/src/protobuf.rs, server/Cargo.toml
Tracing improvments
Summary:
This include
- Show the node.id always in traces (service.instance.id)
- Alwasy send the span_context across processes. The is_sampled flag is
already sent over in the traceparent
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2170).
* #2171
* __->__ #2170
=> Tracing improvments

crates/core/src/worker_api/partition_processor_manager.rs, crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/idempotency/table.rs, crates/storage-query-datafusion/src/inbox/table.rs, crates/storage-query-datafusion/src/invocation_status/table.rs, crates/storage-query-datafusion/src/journal/table.rs, crates/storage-query-datafusion/src/keyed_service_status/table.rs, crates/storage-query-datafusion/src/lib.rs, crates/storage-query-datafusion/src/mocks.rs, crates/storage-query-datafusion/src/promise/table.rs, crates/storage-query-datafusion/src/remote_invoker_status_handle.rs, crates/storage-query-datafusion/src/remote_query_scanner_manager.rs, crates/storage-query-datafusion/src/state/table.rs, crates/types/src/partition_table.rs, crates/worker/src/lib.rs, crates/worker/src/partition_processor_manager.rs
By not requiring a dependency on the PartitionStoreManager, we can now create the QueryContext on nodes which don't run the Worker role. This will allow us to use the QueryContext in the Admin component and to remove the unnecessary indirection of an additional grpc call.
=> Decouple the QueryContext from a hard dependency on the PartitionStoreManager

Cargo.lock, Cargo.toml, crates/admin/Cargo.toml, crates/admin/src/schema_registry/error.rs, crates/admin/src/schema_registry/updater.rs, crates/ingress-http/src/handler/tests.rs, crates/ingress-http/src/lib.rs, crates/types/src/schema/invocation_target.rs, crates/types/src/schema/service.rs, deny.toml
Fix #2178
Now when registering, you'll see this info:
And this is the output of the Admin API:
@igalshilman the schema here is only for the input, because the output of the `greet` in the screen above is `str` in the code. For Json primitive types, right now on python SDK we don't send any schema info, perhaps that's an easy fix you can do looking at the type info at runtime, without pydantic.
=> Expose handlers input/output schema in admin API

crates/local-cluster-runner/examples/three_nodes_and_metadata.rs, crates/local-cluster-runner/src/lib.rs, crates/local-cluster-runner/src/node/mod.rs
This fixes an issue where no log lines matching the metadata sever output prevents the
signal handler from being awaited, blocking clean shutdown.
I also made the node naming 0-based so that we don't have confusing mismatches like `N0` actually being `node-1`.
Finally, this PR fixes a problem where the test runner would panic and leave _other_ server processes running, if one of the PIDs is already terminated by the time it tries to shut down. This could also also have occurred under a race condition where if SIGTERM was sent, timeout expires, but the server process exited on its own just before we could send it SIGKILL.
Testing:
```
> cargo run --example three_nodes_and_metadata -- --nocapture
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.64s
Running …
```
=> [Local Cluster Example] Await shutdown signal concurrently with startup

crates/core/src/network/net_util.rs, crates/core/src/network/rpc_router.rs
The ConnectionAwareRpcRouter adds support for monitoring the connection on which messages are sent. If the recipient uses the same channel to send responses, it can be used to monitor whether a response can still arrive or not.
=> Introduce ConnectionAwareRpcRouter

docs/dev/local-development.md
noticed that build command is outdated 
```shell
just build --bin restate-cli --release
>>cargo build   --bin restate-cli --release
error: no bin target named `restate-cli`
Did you mean `restatectl`?
```
`cargo run --bin restate --release` worked as expected
=> update build restate cli command

Cargo.lock, crates/admin/Cargo.toml, crates/admin/src/storage_query/query.rs
- Providing Accept: application/json to the /query endpoint should work
- We used to have to replace LargeUtf8/Binary -> the non large version as Arrow JS didn't support the Large versions. This is no longer needed, as Arrow JS added support some time ago now.
=> Support JSON in storage query responses, and remove unneeded conversion

Cargo.lock, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/log-server/Cargo.toml, crates/log-server/build.rs, crates/log-server/protobuf/log_server_svc.proto, crates/log-server/src/grpc_svc_handler.rs, crates/log-server/src/lib.rs, crates/log-server/src/protobuf.rs, crates/log-server/src/service.rs, crates/node/src/lib.rs
This introduces as new gRPC service stub for logservers, the service interface is only a stub at the moment, future PRs will include the implementation and the concrete message formats.
LogServerSvc is registered as expected. This doesn't have access to the request pump at the moment. I expect us to create a channel between the grpc handler and RequestPumb to request access to LogletWorkers and such.
```console
2024-10-24T15:57:07.926744Z DEBUG restate_core::network::server_builder
Registering gRPC service to node-rpc-server
svc: "restate.log_server.LogServerSvc"
```
=> LogServer observability gRPC service stub

crates/invoker-impl/src/invocation_state_machine.rs, crates/invoker-impl/src/invocation_task/mod.rs, crates/invoker-impl/src/lib.rs
Now it won't count anymore failures that happen before the retry attempt "hits" the endpoint.
=> Fix the StartMessage retry count

crates/core/src/network/partition_processor_rpc_client.rs, crates/types/src/net/partition_processor.rs
When ingress makes a partition routing decision and gets an error that indicates it is operating with stale information, propagate this signal to the partition routing component.
Closes: #2215
=> Ingress explicitly detects PP routing decision errors

crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/admin/src/cluster_controller/service.rs, crates/core/src/metadata/mod.rs, crates/core/src/network/partition_processor_rpc_client.rs, crates/core/src/task_center.rs, crates/node/src/roles/base.rs, crates/service-client/src/http.rs, crates/types/src/cluster/cluster_state.rs, crates/types/src/net/node.rs, crates/types/src/net/partition_processor.rs, crates/types/src/net/partition_processor_manager.rs, crates/worker/src/partition_processor_manager.rs
Avoid blocking in the PartitionProcessorManager when being in the control loop
Summary:
- Improve tracing of ControlProcessors commands
- Run the spawn of partition processors concurrently
- Avoid blocking partition processor manager main loop
While testing I noticed that InvokerService creations takes
around 25ms (on my machine) to be created with `InvokerService::from_options`
I traced the delay to a single line of code here
https://github.com/restatedev/restate/blob/1cb01203f18bfc6ddb5fe4c45f6697799a79c27e/crates/service-client/src/http.rs#L73
My first thought was to cache the `HttpsConnectorBuilder` but this won't work because `HttpsConnectorBuilder` is not
clonable.
Fixes #2146
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with …
=> Avoid blocking in the PartitionProcessorManager when being in the control loop

crates/types/src/net/partition_processor.rs
Fix broken main
Summary:
A merge conflict was not detected whcih caused the build
to fail only after merging
=> Fix broken main

crates/worker/src/partition_processor_manager.rs
Let PartitionProcessors failures propagate to the PartitionProcessorManager
Summary:
When PP crashes (returns an error) we should update it's status instead
of panicing
Fixes #2147
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2214).
* #2228
* __->__ #2214
=> Let PartitionProcessors failures propagate to the PartitionProcessorManager

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/service.rs, crates/admin/src/schema_registry/mod.rs, crates/bifrost/benches/util.rs, crates/bifrost/src/bifrost_admin.rs, crates/core/src/metadata/manager.rs, crates/core/src/metadata/mod.rs, crates/core/src/test_env.rs, crates/log-server/build.rs, crates/log-server/protobuf/log_server_svc.proto, crates/log-server/src/grpc_svc_handler.rs, crates/log-server/src/loglet_worker.rs, crates/log-server/src/logstore.rs, crates/log-server/src/metadata.rs, crates/log-server/src/network.rs, crates/log-server/src/rocksdb_logstore/store.rs, crates/log-server/src/service.rs, crates/node/src/lib.rs, crates/types/build.rs, crates/types/protobuf/restate/log_server_common.proto, crates/types/src/net/log_server.rs, crates/types/src/net/metadata.rs, crates/types/src/protobuf.rs, tools/bifrost-benchpress/src/main.rs
MetadataContainer enum was ~450 bytes and it's being used often. It also forces users to clone input which is not great. The PR contains mostly mechanical changes.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2229).
* #2257
* #2256
* #2231
* #2230
* __->__ #2229
* #2222
=> MetadataContainer now holds Arcs

crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/mod.rs, crates/core/src/task_center_types.rs
This PR pins some tasks to the default tokio runtime in case they need to be independent from any PP runtime. This addresses a bug where a sequencer appender is aborted leaving a gap in the offset space. Future appends after this point will never succeed because log-servers' local commit offset will always be behind this point.
=> Pin critical replicated loglet tasks to default runtime

crates/core/src/task_center_types.rs, crates/worker/src/partition/leadership.rs, crates/worker/src/partition/mod.rs
In order to make sure that rpc responses originating from the PartitionProcessor are being sent even if the PartitionProcessor runtime is being shut down, this commit changes the PartitionProcessor to use the TaskKind::RpcResponse for sending rpc responses back. The TaskKind::RpcResponse runs on the default runtime.
An alternative could have been to await that all spawned tasks complete before shutting down the partition processor runtime. But there was no easy way to do this for non-local tasks. Also it creates the risk that we prevent the shut down from happening if one of those tasks does not react to the shut down signal.
This fixes #2270.
=> Introduce TaskKind::RpcResponse which runs on the default runtime

Cargo.lock, crates/admin/src/cluster_controller/scheduler.rs, crates/core/src/network/partition_processor_rpc_client.rs, crates/core/src/task_center.rs, crates/core/src/task_center_types.rs, crates/invoker-impl/src/lib.rs, crates/tracing-instrumentation/src/exporter.rs, crates/types/src/net/partition_processor.rs, crates/types/src/net/partition_processor_manager.rs, crates/worker/Cargo.toml, crates/worker/src/partition/mod.rs, crates/worker/src/partition_processor_manager/message_handler.rs, crates/worker/src/partition_processor_manager/mod.rs, crates/worker/src/partition_processor_manager/persisted_lsn_watchdog.rs, crates/worker/src/partition_processor_manager/processor_state.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs
This PR consists of a few initial commits that split the `PartitionProcessorManager` into more manageable modules. It also fixes some minor things like improving the error handling for partition processor rpcs. The main change is the last commit which tries to fix the lifecycle management of partition processors. The idea is that we are awaiting the termination of the runtime root task (the one running the partition processor) before removing the partition processor from the `processor_states` map maintained by the `PartitionProcessorManager`. That way we avoid creating multiple partition processor runtimes for the same `PartitionId`.
This fixes https://github.com/restatedev/restate/issues/2258.
=> Make PartitionProcessorManager asynchronous and handle shut down of PPs 

crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/worker/src/partition/mod.rs, server/tests/cluster.rs
Remove infinite retry policy from find tail in partition processor which is a problem in case that the PP wants to shut down. In this case it can happen that the `find_tail` operation also fails with a `ShutDown` error which we shouldn't retry.
=> Remove infinite retry policy from find tail in partition processor

crates/bifrost/src/appender.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/core/src/task_center_types.rs
Also RemoteSequencer now runs append responses handler on default runtime
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2279).
* #2281
* #2280
* __->__ #2279
=> [Bifrost] Appender should retry on retryable errors

crates/ingress-kafka/src/consumer_task.rs
Again for https://github.com/restatedev/restate/issues/2269
=> Even better log statement in Kafka

crates/admin/src/cluster_controller/logs_controller.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/read_stream.rs, crates/bifrost/src/types.rs, crates/types/src/replicated_loglet/params.rs, crates/worker/src/partition/mod.rs, server/tests/common/replicated_loglet.rs, tools/restatectl/src/commands/log/dump_log.rs, tools/restatectl/src/commands/log/gen_metadata.rs, tools/restatectl/src/commands/log/reconfigure.rs
Summary:
Removes `FindTailAttributes` since it was never actually needed and `write_set` from ReplicatedLogletParams which wasn't necessary/needed.
Test Plan:
Tests
=> [Bifrost] Remove unused structures

crates/tracing-instrumentation/src/lib.rs, crates/types/src/config/cli_option_overrides.rs, crates/worker/src/partition/state_machine/mod.rs
1. Remove unnecessary duplicate names eg 'sleep sleep'
2. Emit spans for Run entries
3. Clap env var RESTATE_SERVICES_RUNTIME_ENDPOINT -> RESTATE_TRACING_SERVICES_ENDPOINT
=> Otel papercut fixes

crates/invoker-api/src/entry_enricher.rs, crates/service-protocol/src/codec.rs, crates/service-protocol/src/message/encoding.rs, crates/service-protocol/src/message/header.rs, crates/storage-api/proto/dev/restate/storage/v1/domain.proto, crates/storage-api/src/outbox_table/mod.rs, crates/storage-api/src/storage.rs, crates/types/service-protocol/dev/restate/service/protocol.proto, crates/types/src/errors.rs, crates/types/src/invocation.rs, crates/types/src/journal/entries.rs, crates/types/src/journal/raw.rs, crates/types/src/service_protocol.rs, crates/worker/src/invoker_integration.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/idempotency.rs, crates/worker/src/partition/state_machine/tests/matchers.rs, crates/worker/src/partition/state_machine/tests/mod.rs, crates/worker/src/partition/state_machine/tests/workflow.rs, crates/worker/src/partition/types.rs
=> Implement Attach/Get output in service-protocol

crates/types/src/identifiers.rs, crates/worker/src/partition/leadership.rs, crates/worker/src/partition/mod.rs
It is important to always fail the pending rpcs if the partition processor
stops. Otherwise the ingress might be hanging because a partition processor
failure does not entail a process crash. 
The very concrete problem that I observed was when shutting down a PP, we are also shutting down the corresponding invoker. If shutting down the invoker completes first, then we would fail when `become_follower` where we check the `abort_handle` and never complete the pending rpcs.
=> Always clean up leadership state if the partition processor stops

Cargo.lock, crates/ingress-http/src/lib.rs, crates/ingress-http/src/rpc_request_dispatcher.rs, crates/ingress-http/src/server.rs, crates/local-cluster-runner/src/node/mod.rs, crates/node/Cargo.toml, crates/node/src/lib.rs, crates/node/src/roles/ingress.rs, crates/node/src/roles/mod.rs, crates/node/src/roles/worker.rs, crates/types/protobuf/restate/common.proto, crates/types/src/config/common.rs, crates/types/src/config/ingress.rs, crates/types/src/health.rs, crates/types/src/nodes_config.rs, crates/worker/src/lib.rs
This commit separates the ingress from the worker role. To support backward compatibility this feature is not yet turned on by default and users need to enable it explicity via `experimental-feature-enable-separate-ingress-role` to be able to configure the ingress role separately. When enabled, users can place the ingress role on a set of freely chosen nodes.
This fixes #1312.
=> Separate Ingress from Worker role

crates/admin/src/web_ui.rs
In order to run ServiceWorkers in web-ui in browser the scope needs to be defined via `Service-Worker-Allowed` header from the web server serving the document.
=> Add ServiceWorker scope header to web-ui response

crates/core/src/network/connection.rs, crates/core/src/network/error.rs, crates/core/src/network/rpc_router.rs, crates/types/src/net/mod.rs
Summary:
Helps when logging the error to know how much time was spent.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2300).
* #2304
* #2301
* __->__ #2300
=> Timeout error includes the total time spent

crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/tasks/get_trim_point.rs, crates/bifrost/src/providers/replicated_loglet/tasks/mod.rs, crates/bifrost/src/providers/replicated_loglet/tasks/trim.rs, crates/bifrost/src/providers/replicated_loglet/tasks/util.rs, crates/core/src/network/connection.rs, crates/core/src/network/error.rs, crates/core/src/network/rpc_router.rs, crates/log-server/src/rocksdb_logstore/store.rs, crates/types/src/net/log_server.rs, crates/types/src/net/mod.rs
Summary:
This introduces an implementation for `trim()` and `get_trim_point()` for replicated loglets. It also introduces an abstraction for sending messages on nodes `RunOnSingleNode`. At the moment it's used for TrimTask/GetTrimPointTask but in future PRs more tasks will be refactored to benefit from it.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2301).
* #2304
* __->__ #2301
* #2300
=> [Bifrost] Trim implementation for replicated loglet

crates/types/src/config/cli_option_overrides.rs, crates/types/src/nodes_config.rs, docker/debug.Dockerfile, justfile
Summary:
This allows us to quickly build debug docker images, perhaps we can use those in CI as well in the near future.
Test Plan:
```
just docker-build
...
~ ❯❯❯ docker image ls
REPOSITORY                               TAG             IMAGE ID       CREATED          SIZE
localhost/restatedev/restate             unknown         f8bd3765f210   14 seconds ago   1.5GB
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2320).
* __->__ #2320
* #2319
=> Introduces docker-debug to justfile

crates/admin/src/cluster_controller/cluster_controller_state.rs, crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/admin/src/cluster_controller/mod.rs, crates/admin/src/cluster_controller/service.rs, crates/core/src/worker_api/partition_processor_manager.rs
Soft-leader election mechanism for cc based on observed cluster state
Fixes #2238
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2252).
* #2325
* __->__ #2252
=> Soft-leader election mechanism for cc based on observed cluster state

crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/admin/src/cluster_controller/mod.rs, crates/admin/src/cluster_controller/observed_cluster_state.rs, crates/admin/src/cluster_controller/service.rs, crates/admin/src/cluster_controller/service/state.rs, crates/core/src/network/error.rs, crates/types/protobuf/restate/cluster.proto, crates/types/src/cluster/cluster_state.rs, tools/restatectl/src/commands/partition/list.rs
Handle stale metadata version when starting a CC leader
Summary:
In some situation, when a Cluster Controller leader is starting again
some or all of the nodes in the cluster can have an outdated version of
the metadata that has the new leader generational id
This causes some of the "get state" requests to fail, which causes the CC
to think the nodes are dead and does an unnecessary reschedule of PPs
To avoid this, we introduces a third state "Suspect" node. Which is
dead and alive until we can be sure
=> Handle stale metadata version when starting a CC leader

cli/src/commands/invocations/list.rs, cli/src/commands/invocations/mod.rs
Fix #2312
To show the completed invocations, the user can simply run:
```
restate invocation ls --status=completed
```
=> Don't show completed invocations by default

crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/admin/src/cluster_controller/observed_cluster_state.rs
Follow Up: Stale Metadata #2325
=> Follow Up: Stale Metadata #2325

crates/admin/src/cluster_controller/scheduler.rs
This commit adds an periodic SchedulingPlan check which allows multiple Schedulers to eventually agree on the same SchedulingPlan. Before, it could happen that there are two Schedulers that have different SchedulingPlans (e.g. one still having an older version). If those plans are contradicting, then the Schedulers would instruct nodes differently. The periodic update helps preventing this situation.
Note: This logic can be removed once we allow the scheduler to accept equivalent partition processor placements. See #2242.
=> Harden scheduler to converge on common SchedulingPlan

crates/admin/src/schema_registry/updater.rs, crates/types/src/schema/openapi.rs, crates/types/src/schema/service.rs
For now we put this cache inside the `ServiceSchemas` data structure, but in future we should move it somewhere else (perhaps in `Schemas`)
=> Don't store the OpenAPI contract anymore, rather just cache it

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/service.rs, crates/admin/src/cluster_controller/service/state.rs
To avoid losing progress, this commit runs all cluster controller leader tasks that are not cancellation safe as part of the top-level select expression instead of a select arm. Select arms can be cancelled and therefore we would lose progress in this case. This applies to trimming the logs and updating scheduler when there is a logs or partition table update.
=> Run non-cancellation safe cluster controller leader tasks in select expression

crates/bifrost/src/background_appender.rs, crates/worker/src/partition/leadership.rs, crates/worker/src/partition/leadership/leader_state.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/leadership/self_proposer.rs, crates/worker/src/partition/mod.rs
Instead of retrying infinitely in the LeadershipState, we are now spawning a
background appender and hand the announce leadership message over. Additionally,
we are now monitoring the health of the appender task to escalate potential
failures which would then result in shutting the PP down and let the PPM handle
the situation.
This fixes https://github.com/restatedev/restate/issues/2333.
The second commit is only moving code into separate modules.
=> Remove infinite retry policy when announcing the leadership

Cargo.lock, Cargo.toml, benchmarks/src/lib.rs, crates/bifrost/benches/append_throughput.rs, crates/bifrost/benches/util.rs, crates/core/Cargo.toml, crates/core/src/metadata/manager.rs, crates/core/src/metadata/mod.rs, crates/core/src/task_center/extensions.rs, crates/core/src/task_center/mod.rs, crates/core/src/task_center/task.rs, crates/core/src/task_center/task_kind.rs, crates/ingress-http/Cargo.toml, crates/metadata-store/src/local/tests.rs, crates/node/src/network_server/grpc_svc_handler.rs, crates/partition-store/benches/basic_benchmark.rs, crates/partition-store/src/tests/mod.rs, crates/service-client/Cargo.toml, crates/storage-query-datafusion/src/mocks.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition_processor_manager/mod.rs, crates/worker/src/partition_processor_manager/persisted_lsn_watchdog.rs, server/src/main.rs, server/tests/common/replicated_loglet.rs, tools/bifrost-benchpress/Cargo.toml, tools/bifrost-benchpress/src/main.rs, tools/bifrost-benchpress/src/write_to_read.rs
- Adds `in_tc(&TaskCenter)` and `in_current_tc()` to scope a future to run in a task-center if it'll be dispatched as a task
- Introduces a root task (TaskId(0)) in TaskCenter that's used as a default parent/source of task context
- Removes unnecessary args from block_on, run_in_scope_sync. (some of those will be changed in future PRs)
- Introduces `Metadata::current()` and `Metadata::with_current(F)`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2339).
* #2355 (2 commits)
* #2352
* #2344
* #2343
* __->__ #2339
=> [TaskCenter][2/n] Introduces TaskCenterFuture extensions traits

crates/core/src/lib.rs, crates/core/src/task_center.rs, crates/core/src/task_center/handle.rs, crates/core/src/task_center/monitoring.rs, crates/core/src/task_center/runtime.rs, crates/worker/src/partition_processor_manager/mod.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs
This lets task center request the graceful cancellation of the root-future of managed runtimes. Note that it'll not wait for the shutdown to complete. If this is needed, then partition-processor managed will need to wait for the result to come when it receives the cancellation signal on its own cancellation token.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2364).
* #2365
* __->__ #2364
=> [TaskCenter] Requests cancellation of managed runtimes

crates/core/src/lib.rs, crates/core/src/task_center.rs, crates/core/src/task_center/handle.rs, crates/core/src/task_center/monitoring.rs, crates/core/src/task_center/runtime.rs, crates/partition-store/src/partition_store_manager.rs, crates/rocksdb/src/lib.rs, crates/worker/src/partition_processor_manager/mod.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2365).
* __->__ #2365
* #2364
=> Enable partition-store db flush on shutdown

docs/dev/local-development.md
I had this issue 
``` shell   
Compiling restate-fs-util v1.1.4 (/home/ahmedradwan/Documents/learning/repos/restate/crates/fs-util)
error: failed to run custom build command for openssl-sys v0.9.103
Caused by:
process didn't exit successfully: /home/ahmedradwan/Documents/learning/repos/restate/target/debug/build/openssl-sys-037951741050b993/build-script-main (exit status: 101)
--- stdout
cargo:rustc-check-cfg=cfg(osslconf, values("OPENSSL_NO_OCB", "OPENSSL_NO_SM4", "OPENSSL_NO_SEED", "OPENSSL_NO_CHACHA", "OPENSSL_NO_CAST", "OPENSSL_NO_IDEA", "OPENSSL_NO_CAMELLIA", "OPENSSL_NO_RC4", "OPENSSL_NO_BF", "OPENSSL_NO_PSK", "OPENSSL_NO_DEPRECATED_3_0", "OPENSSL_NO_SCRYPT", "OPENSSL_NO_SM3", "OPENSSL_NO_RMD160", "OPENSSL_NO_EC2M", "OPENSSL_NO_OCSP", "OPENSSL_NO_CMS", "OPENSSL_NO_COMP", …
```
=> add perl to local dev env

crates/core/src/task_center.rs, crates/core/src/task_center/handle.rs, crates/worker/src/partition_processor_manager.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs
The actual reason why we were blocking tokio was that we were opening the partition_store inline (on the caller's thread), this quickly saturates all workers in default tokio threads (in joinset)
The fix is to move opening the partition store into the newly created runtime. A longer-term fix to address the slow creation of column-families is to batch open them instead of doing so one by one. Rocksdb has a long-standing issue with  column-family creation performance, but this requires that we expose `rocksdb_create_column_families()` from C binding to rust.
=> Remove unnecessary spawn_blocking_unmanaged from task-center

crates/tracing-instrumentation/src/exporter.rs, crates/tracing-instrumentation/src/lib.rs
Use hostname as service name in traces, rather than generational id
Summary:
Fixes #2262
=> Use hostname as service name in traces, rather than generational id

crates/worker/src/partition/leadership/leader_state.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/shuffle.rs
Handle shuffler errors
Propagate shuffler error to PP instead of
crashing the entire node
Fixes #2148
=> Handle shuffler errors

Cargo.lock, Cargo.toml
We now have 0.6 of jemalloc which includes our patches, so we don't need the fork any more. And we can enable the feature on rust-rocksdb, which also uses 0.6. This feature will means that rocksdb is informed that jemalloc is present
=> Enable jemalloc feature on rocksdb

.github/workflows/ci.yml, Cargo.lock, cli/src/clients/datafusion_helpers.rs, cli/src/ui/invocations.rs, crates/invoker-api/src/handle.rs, crates/invoker-api/src/lib.rs, crates/invoker-impl/src/input_command.rs, crates/invoker-impl/src/lib.rs, crates/partition-store/src/invocation_status_table/mod.rs, crates/partition-store/src/tests/invocation_status_table_test/mod.rs, crates/storage-api/proto/dev/restate/storage/v1/domain.proto, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-api/src/storage.rs, crates/storage-api/src/timer_table/mod.rs, crates/storage-query-datafusion/src/invocation_status/row.rs, crates/storage-query-datafusion/src/invocation_status/schema.rs, crates/types/src/config/worker.rs, crates/worker/Cargo.toml, crates/worker/src/partition/cleaner.rs, crates/worker/src/partition/leadership/leader_state.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/state_machine/actions.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/idempotency.rs, crates/worker/src/partition/state_machine/tests/kill_cancel.rs, crates/worker/src/partition/state_machine/tests/matchers.rs, crates/worker/src/partition/state_machine/tests/mod.rs, crates/worker/src/partition/state_machine/tests/workflow.rs
Fix #2331. While at it I did some lil' refactorings + fixed killing/cancelling scheduled invocations
=> Introduce InvocationStatus::Killed

crates/partition-store/src/partition_store_manager.rs, crates/rocksdb/src/error.rs, crates/rocksdb/src/rock_access.rs, crates/worker/Cargo.toml, crates/worker/src/lib.rs, crates/worker/src/partition/snapshots/repository.rs, crates/worker/src/partition_processor_manager.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs
With this change, Partition Processor startup now checks the snapshot repository
for a partition snapshot before creating a blank store database. If a recent
snapshot is available, we will restore that instead of replaying the log from
the beginning.
This PR builds on https://github.com/restatedev/restate/pull/2310
Closes: https://github.com/restatedev/restate/issues/2000
---
Created snapshot by running `restatectl create-snapshot -p 0`, then dropped the partition CF with `rocksdb_ldb drop_column_family --db=./restate-data/.../db data-0`.
Running `restate-server` correctly restores the most recent available snapshot:
```
2024-11-27T18:43:40.042527Z TRACE restate_worker::partition_processor_manager::spawn_processor_task: Looking for snapshot to bootstrap partition store …
```
=> Implement partition store restore-from-snapshot

crates/partition-store/src/invocation_status_table/mod.rs, crates/storage-api/proto/dev/restate/storage/v1/domain.proto, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-api/src/storage.rs
This avoids loading the full InvocationStatus in memory, only to read invocation target and status. Depends on https://github.com/restatedev/restate/pull/2335, only the last commit is relevant to this PR
=> Side quest: Optimize ReadOnlyInvocationStatusTable#all_invoked_or_killed_invocations

crates/types/src/schema/openapi.rs
Example of output operation:
Fix #2356
=> Add attach/get output to openapi and reorganize tags to improve UI visualization

Cargo.lock, crates/tracing-instrumentation/src/lib.rs
Fix outdate dependency version
Summary:
- Make sure we have latest version of `idna`
- Fix deprecated code
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2395).
* #2374
* #2351
* __->__ #2395
=> Fix outdate dependency version

Cargo.lock, crates/node/Cargo.toml, crates/node/src/network_server/mod.rs, crates/node/src/network_server/pprof.rs, crates/node/src/network_server/service.rs, server/src/main.rs
Provide a mechanism of obtaining pprof-format heap dumps
On linux (easiest on musl build ):
```
curl localhost:5122/debug/pprof/heap/activate
... do some work that will lead to allocations
curl localhost:5122/debug/pprof/heap > heap.pb.gz
pprof -http=:9090 ./restate-server  heap.pb.gz
```
=> Add pprof heap endpoints to node api

.github/workflows/docker.yml, .github/workflows/release.yml, docker/Dockerfile
We will benefit both when uploading heaps/profiles to polar signals, but we also have our own debuginfod endpoint so tools like perf will be able to magically find the debug symbols for a given binary
=> Split debuginfo out in release builds and upload to polarsignals

Cargo.lock, Cargo.toml, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/tracing-instrumentation/Cargo.toml, crates/tracing-instrumentation/src/lib.rs, server/src/main.rs
- NOTE: Disables hot-reload of log-filters, this is due to a RwLock contention, albeit it gets less severe after cold start, it's still a major hurdle to achieving max throughput.
- Removes lock contention on the underlying RwLock, this brings significant (~4.5x) throughput gain on darwin.
- NonBlocking writer will drop log lines if underlying pipe is full, this makes tokio less likely to block on stderr locks or if the underlying storage (if logging to a file) needs a flush.
- Kept rebuilding the interest index in tracing_core when configuration is updated, this improves performance by up to 20% for a warm system. There is an underlying issue in tracing-core that'll hopefully be addressed in 0.2 when it's released.
- Disables distributed tracing feature due to a severe lock contention on …
=> Async Logger and remove reload handle

crates/admin/protobuf/cluster_ctrl_svc.proto, crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/lib.rs, tools/restatectl/src/commands/log/reconfigure.rs
force reconfiguration of a loglet with `restatectl logs reconfigure`
Summary:
when calling `restatectl logs reconfigure` without a `provider`
the reconfigure will instead schedule the loglet to be sealed
and then the system will reconfigure it with cluster configuration
=> force reconfiguration of a loglet with `restatectl logs reconfigure`

crates/core/Cargo.toml, crates/core/src/network/connection_manager.rs, crates/core/src/network/net_util.rs, crates/core/src/network/transport_connector.rs, crates/core/src/task_center/task_kind.rs, crates/node/src/network_server/service.rs, crates/storage-query-postgres/src/pgwire_server.rs, crates/types/src/config/networking.rs
h2 keep-alive is very important to detect frozen streams, we only had this enabled on client-side of connections so we didn't always detect broken network or frozen processes. This also tunes the default such that we can detect frozen processes in 5-10s. The biggest impact comes from bifrost's remote sequencers being able to detect that their in-flight appends can/should be retried, otherwise the'll be stuck indefinitely even if the loglet has been sealed already (albeit this happens on a higher level).
- Changes the max frame size to 32MB (default is 4MB) to allow for larger batches
- Fixes a small lineage issue in tracing individual connection tasks (more to follow on the larger issue in subsequent PRs)
- Changes how shutdown is designed for connections. Connections now wait for 5 …
=> [Networking] Enable and tune h2 keep-alive on the server-end of connections

Cargo.lock, crates/bifrost/Cargo.toml, crates/bifrost/src/providers/replicated_loglet/log_server_manager.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/core/Cargo.toml, crates/core/src/network/connection_manager.rs, crates/core/src/network/net_util.rs, crates/core/src/network/networking.rs, crates/core/src/network/transport_connector.rs, crates/core/src/task_center/handle.rs, crates/core/src/task_center/task_kind.rs, crates/node/src/network_server/service.rs, crates/storage-query-postgres/src/pgwire_server.rs, crates/types/src/config/bifrost.rs, crates/types/src/config/networking.rs, crates/types/src/replicated_loglet/params.rs
This change ensures that when using spawn_child or spawn_unmanaged, futures carry the parent span automatically. for spawn(), it's up to the caller to `.instrument(Span::current())` their futures if similar behaviour is needed since `spawn()` is considered as a detached task.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2424).
* #2427
* #2426
* __->__ #2424
* #2423
* #2422
=> [TaskCenter] maintain tracing lineage for child/unmanaged tasks

crates/bifrost/src/loglet.rs, crates/bifrost/src/providers/replicated_loglet/mod.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
- Move loglet mod to follow new file-style module as it contains type defs and logic
- Removal of dead_code attribute and cleanup of unused types/structs/vars/etc.
```
// left intentionally to make sapling+github happy
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2426).
* #2440
* #2439
* #2427
* __->__ #2426
=> [chore] mechanical cleanup

benchmarks/Cargo.toml, cli/Cargo.toml, crates/bifrost/src/loglet.rs, crates/bifrost/src/providers/replicated_loglet/mod.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/core/src/metadata_store.rs, server/Cargo.toml, tools/restatectl/Cargo.toml
At the moment, this is an opt-in feature (build with `-F no-trace-logging` to enable). We might decide to filter trace logging from our docker builds after experimenting with this.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2427).
* #2440
* #2439
* __->__ #2427
* #2426
=> Compile-time feature no-trace-logging to filter trace logging

crates/types/src/net/log_server.rs, crates/types/src/net/replicated_loglet.rs
Using `#[serde(flatten)]` in network messages can be problematic since some serializers don't support it and it doesn't actually add any value even with our existing one (i.g. bincode doesn't support it). Removing it to prevent future trap-door.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2439).
* #2440
* __->__ #2439
=> [Bifrost] Remove serde flatten from network types

crates/admin/src/cluster_controller/service.rs, crates/bifrost/Cargo.toml, crates/bifrost/src/appender.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/lib.rs, crates/bifrost/src/read_stream.rs, crates/wal-protocol/src/lib.rs, crates/worker/src/partition/leadership/self_proposer.rs, server/tests/replicated_loglet.rs, tools/bifrost-benchpress/src/append_latency.rs, tools/bifrost-benchpress/src/write_to_read.rs
This PR introduces the new parameter to appender's API to let API users control the behaviour when appends to the current loglet face persistent failures. There is a new feature (`auto-extend` in restate-bifrost which controls the default behaviour).
No logic changes happen in this PR, in future PRs, bifrost will respect this input and will configure its behaviour accordingly.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2446).
* #2451
* #2450
* __->__ #2446
=> [Bifrost] Introduce ErrorRecoveryStrategy control

Cargo.lock, crates/types/src/config/worker.rs, crates/worker/src/lib.rs, crates/worker/src/partition/snapshots/repository.rs, server/Cargo.toml, server/tests/snapshots.rs
Discovered a regression in the snapshot restore path which prevents it from working currently.
This also adds a basic snapshot roundtrip smoke test.
=> Fix: Ensure local snapshot staging directory exists for restore

crates/types/src/config/worker.rs
This was previously across all partitions, but since 1.1 its per partition. And it is 350M per partition. Those entries are not initially used, but as you scale to 1m invocations per partition, all the memory pages in the queue's ring buffer are dirtied and contribute to RSS. This leads to 9G of usage on a 24 partition node.
This PR reduces the limit by 16x to 21M per partition, or 562M on a 24 partition node, which it will reach after 1.5 million invocations. A more manageable figure, even if it still appears as a 'leak' until that amount is reached.
=> Reduce in memory queue limit by 16x

crates/core/src/task_center.rs, crates/core/src/task_center/handle.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition_processor_manager.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs
Closes: https://github.com/restatedev/restate/issues/2247
=> Add Bifrost trim gap handling support by fast-forwarding to the latest partition snapshot

crates/service-client/src/http.rs, crates/service-client/src/lib.rs, crates/service-protocol/src/discovery.rs
* Add response headers to bad discovery response. Fix https://github.com/restatedev/restate/issues/2369
* Improve connect error in ServiceClient
=> Improve error messages

Cargo.lock, crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/service.rs, crates/bifrost/Cargo.toml, crates/bifrost/src/appender.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/error.rs, crates/bifrost/src/loglet/provider.rs, crates/bifrost/src/providers/local_loglet/provider.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/providers/replicated_loglet/mod.rs, crates/bifrost/src/providers/replicated_loglet/nodeset_selector.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/core/src/metadata/manager.rs, crates/types/src/config/common.rs, crates/types/src/logs/metadata.rs, tools/restatectl/src/commands/cluster/config.rs, tools/restatectl/src/commands/cluster/config/set.rs, tools/restatectl/src/commands/log/list_logs.rs
- BifrostAdmin can now init empty logs configuration
- BifrostAdmin can now auto extend the chain
- Providers now have control over suggesting a new segment configuration
- Introduces a temporary copy of NodeSetSelector into bifrost until log-controller is removed
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2451).
* #2458
* #2457
* __->__ #2451
=> [Bifrost] Let providers propose their own parameters

crates/node/src/network_server/grpc_svc_handler.rs, crates/types/src/net/metadata.rs
Make the conversion of metadata kind failable to tolerate invalid GetMetadataRequests.
This fixes #2465.
=> Temporary band aid: Harden NodeCtlSvcHandler::GetMetadata

crates/core/protobuf/node_ctl_svc.proto, crates/types/protobuf/restate/common.proto, crates/types/protobuf/restate/node.proto, crates/types/src/net/metadata.rs
Move MetadataKind from node.proto to common.proto. With this change, users of the node_ctl_svc.proto only
need to import the common.proto
=> Move MetadataKind from node.proto to common.proto

Cargo.lock, Cargo.toml, crates/node/src/lib.rs, crates/types/src/cluster/cluster_state.rs, crates/types/src/net/log_server.rs, crates/types/src/net/metadata.rs
prost-dto 0.0.3 renames IntoProto/FromProto to `IntoProst/FromProst` and all macro attributes accordingly. It also removes the auto skipping of fields, only fields marked with `#[prost(skip)]` are now skipped.
=> [Mechanical] Upgrade prost-dto to 0.0.3

Cargo.lock, crates/types/Cargo.toml, crates/types/src/config_loader.rs, workspace-hack/Cargo.toml
Handle config file replacement by some editors
Summary:
We are switching mainly to notify-debounce-full to fix an issue
with detecting file changes. This also gave us better control over
the file watch and allows us to handle config file replacement.
Also Some editors replace the file on save like what vim does.
=> Handle config file replacement by some editors

crates/core/src/metadata_store/providers/etcd.rs
Use the `VersionedValue` version in etcd metdata store
Summary:
Avoid etcd version misalignment with `VersionedValue` by storing the
version separately in its own key
Fixes #2204
=> Use the `VersionedValue` version in etcd metdata store

crates/worker/src/partition/snapshots/repository.rs
=> Flush local filesystem snapshot IO

Cargo.lock, crates/cli-util/Cargo.toml, crates/cli-util/src/context.rs, crates/cli-util/src/opts.rs, crates/core/src/network/net_util.rs, crates/core/src/network/transport_connector.rs, crates/local-cluster-runner/src/node/mod.rs, crates/metadata-store/src/local/grpc/client.rs, server/tests/trim_gap_handling.rs, tools/restatectl/src/commands/cluster/config/get.rs, tools/restatectl/src/commands/cluster/config/set.rs, tools/restatectl/src/commands/cluster/provision.rs, tools/restatectl/src/commands/log/describe_log.rs, tools/restatectl/src/commands/log/find_tail.rs, tools/restatectl/src/commands/log/list_logs.rs, tools/restatectl/src/commands/log/reconfigure.rs, tools/restatectl/src/commands/log/trim_log.rs, tools/restatectl/src/commands/node/list_nodes.rs, tools/restatectl/src/commands/partition/list.rs, tools/restatectl/src/commands/replicated_loglet/digest.rs, tools/restatectl/src/commands/replicated_loglet/info.rs, tools/restatectl/src/commands/snapshot/create_snapshot.rs, tools/restatectl/src/util.rs
Eliminates some duplication across test and prod code for creating GRPC channels.
=> [Refactoring] Consolidate multiple create Tonic channel functions

Cargo.lock, Cargo.toml, crates/types/Cargo.toml, crates/types/src/partition_table.rs, crates/utoipa/Cargo.toml
Adding placements to partition table
Summary:
Partition table now includes the placement of each partition. PartitionPlacement, representing the set of nodes where the partition should run, with the first node in the group designated as the leader.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2464).
* #2479
* __->__ #2464
=> Adding placements to partition table

.gitignore, Cargo.lock, crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service.rs, crates/bifrost/src/providers/replicated_loglet/test_util.rs, crates/core/src/metadata/manager.rs, crates/core/src/network/connection_manager.rs, crates/core/src/test_env.rs, crates/node/src/init.rs, crates/node/src/lib.rs, crates/types/Cargo.toml, crates/types/src/config/common.rs, crates/types/src/lib.rs, crates/types/src/locality/location_scope.rs, crates/types/src/locality/mod.rs, crates/types/src/locality/node_location.rs, crates/types/src/nodes_config.rs, crates/worker/src/partition_processor_manager.rs
This introduces a new configuration option to specify the node location in the following format `region.zone`. The location is optional and details are documented in the configuration key and parsing details are covered by tests.
More details in code comments.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2480).
* #2498
* __->__ #2480
=> Introduces NodeLocation as part of the locality module

Cargo.lock, crates/admin/Cargo.toml, crates/admin/src/lib.rs, crates/admin/src/metadata_api/mod.rs, crates/admin/src/service.rs, crates/core/src/metadata_store.rs, server/Cargo.toml
Metadata HTTP API
Summary:
An interface that exposes Metadata via a REST API.
Is mainly used for testing and not enabled by default
Only enabled with `metadata-api` build flag
Usage:
The API is served by the admin port under `/metadata/<key>`
GET, and HEAD operations always populates the `ETag` header
if a value is found.
PUT and DELETE operations both require a `If-Match` header.
If the precondition is not met, the operation fails with (412 Precondition Failed)
PUT operation requires a header `ETag` which sets the version
of the new value
=> Metadata HTTP API

crates/node/src/init.rs, crates/types/src/config/cli_option_overrides.rs
Location of the node is now committed to nodes configuration on cluster join. Location is also accepted as command line parameter in the format of `--location=region.zone`. The following rules apply:
- Node location is not set if it is not provided as command line parameter. (empty by default)
- Node location can be changed, but we'll print a warning.
- Node location cannot be set back to empty after setting it to a concrete value before. (warning will be printed)
The node location is now also printed in the `My Node ID` log line for visibility.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2498).
* #2500
* __->__ #2498
=> [Locality] Set node location on cluster join

crates/types/src/config/bifrost.rs, crates/types/src/logs/metadata.rs
Add hidden config option to configure the default replication property of a replicated loglet.
=> Add hidden config option to configure the default replication property of a replicated loglet

Cargo.lock, cli/Cargo.toml, cli/src/clients/admin_client.rs, cli/src/clients/admin_interface.rs, cli/src/clients/datafusion_helpers.rs, cli/src/clients/datafusion_http_client.rs, cli/src/commands/deployments/register.rs, cli/src/commands/services/describe.rs, crates/admin-rest-model/src/converters.rs, crates/admin-rest-model/src/lib.rs, crates/admin-rest-model/src/version.rs, crates/admin/src/rest_api/deployments.rs, crates/admin/src/rest_api/services.rs, crates/admin/src/rest_api/version.rs, crates/admin/src/service.rs, crates/admin/src/storage_query/convert.rs, crates/admin/src/storage_query/mod.rs, crates/admin/src/storage_query/query.rs, crates/storage-query-datafusion/src/deployment/schema.rs, crates/storage-query-datafusion/src/inbox/schema.rs, crates/storage-query-datafusion/src/invocation_state/schema.rs, crates/storage-query-datafusion/src/invocation_status/schema.rs, crates/storage-query-datafusion/src/journal/schema.rs, crates/storage-query-datafusion/src/table_macro.rs, crates/storage-query-postgres/src/pgwire_server.rs, deny.toml
Currently there are 2 ways that old CLIs will break against 1.2
1. COUNT(*) queries no longer return nullable values. The old CLI expects that they do for a particular field.
2. We no longer convert LargeUtf8 and LargeBinary to their non large equivalents. The old CLI expects that we do.
And i want to introduce a new way, by encoding our timestamp data correctly instead of as date64. 
To cover these 3 breaking changes, I have added a mechanism to convert schemas on the fly based on negotiated version. CLI clients will start providing their negotiated version as a header `x-restate-admin-api-version`. CLI user-agent clients that don't do so will be presumed to be on version 1. Other clients that don't do so will be presumed to be happy with the latest version. This is still a slight …
=> Add a mechanism for converting SQL schemas based on negotiated version

crates/types/src/config/mod.rs, server/src/main.rs
Intorduce `--production` flag and profile
Summary:
Support a `--production` flag that when enabled, overrides the
default configuration with a production ready values
So far the `--production` flag:
- disables `allow-bootstrap`
- sets the default provider to `replicated`
Fixes #2410
=> Intorduce `--production` flag and profile

Cargo.lock, crates/admin/src/cluster_controller/logs_controller/nodeset_selection.rs, crates/bifrost/Cargo.toml, crates/bifrost/src/providers/replicated_loglet/nodeset_selector.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/replication/mod.rs, crates/bifrost/src/providers/replicated_loglet/replication/spread_selector.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/digests.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/get_trim_point.rs, crates/bifrost/src/providers/replicated_loglet/tasks/mod.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/trim.rs, crates/types/src/nodes_config.rs, crates/types/src/replicated_loglet/params.rs, crates/types/src/replicated_loglet/replication_property.rs
This introduces a new sophisticated and performance-optimized nodeset checker for bifrost flexible quorums. It pre-computes aggregates to reduce the cost of repeatative quorum checks.
The new nodeset checker has extensive test coverage
=> [Locality] Location-aware NodeSetChecker

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/observed_cluster_state.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/core/src/partitions.rs, crates/log-server/src/metadata.rs, crates/log-server/src/network.rs, crates/types/src/logs/metadata.rs, crates/types/src/logs/record_cache.rs, crates/types/src/nodes_config.rs, crates/types/src/partition_table.rs, crates/types/src/replicated_loglet/params.rs
I ran some benches to estimate the benefit of the currently used `Xxh3Builder` for int-keyed maps/sets and it has performed a lot worse than the default hasher. On the other hand, `Xxh3DefaultBuilder` performed a lot better but it was comparable to the default hasher which didn't make it compelling enough to use. I kept `Xxh3DefaultBuilder` (not `Xxh3Builder`) for the string-keyed map.
=> Remove xxh3builder where its out-performed by default hasher

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/service.rs
Instead of escalating errors from the ClusterController service which ultimately leads to a panic, this commit catches those errors and logs them on warning in the hope that a retry will fix the problem. The down- side is that a buggy cluster controller will never step down so that another cluster controller can take over as the leader.
This is more of a band-aid which helps tolerating failed writes to the metadata store.
This fixes #2276.
=> Harden ClusterController by not panicking on errors

Cargo.lock, crates/types/Cargo.toml, crates/types/src/lib.rs, crates/types/src/replicated_loglet/log_nodeset.rs, crates/types/src/replicated_loglet/params.rs, crates/types/src/replicated_loglet/spread.rs, crates/types/src/replication/mod.rs, crates/types/src/replication/nodeset.rs
This new NodeSet type is designed to maintain its internal order of nodes and will replace both NodeSet of replicated loglet and placement in partition table.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2521).
* #2524
* #2522
* __->__ #2521
=> [1/n] Unified and faster nodeset type

crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service.rs, crates/core/protobuf/node_ctl_svc.proto, crates/local-cluster-runner/src/node/mod.rs, crates/node/src/lib.rs, crates/node/src/network_server/grpc_svc_handler.rs, crates/types/protobuf/restate/cluster.proto, crates/types/src/config/admin.rs, crates/types/src/logs/metadata.rs, crates/types/src/partition_table.rs, crates/types/src/protobuf.rs, server/tests/cluster.rs, tools/restatectl/src/commands/cluster/config.rs, tools/restatectl/src/commands/cluster/config/set.rs, tools/restatectl/src/commands/cluster/provision.rs
Introduce `PartitionReplication` and remove `ReplicationStrategy`
Summary:
The idea here is that we can't use `ReplicationStategy`
because it's not location aware and instead we should describe
placement in terms of `ReplicationProperty`.
If partition replication is not set the system assume placement is `Everywhere`,
otherwise the num of copies is limited by the provided replication property.
> Right now the placement is still not location aware but this will
most probably change in the future
=> Introduce `PartitionReplication` and remove `ReplicationStrategy`

crates/types/src/locality/location_scope.rs, crates/types/src/replicated_loglet/mod.rs, crates/types/src/replication/mod.rs, crates/types/src/replication/replication_property.rs
ReplicationProperty is no longer tied to replicated loglet, partition_table also uses it to define partition_replication. This PR promotes it and merges NodeLocationScope with LocationScope.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2526).
* #2541
* #2539
* #2537
* #2530
* __->__ #2526
=> [4/n] Promote ReplicationProperty to replication module

crates/node/src/lib.rs
Fix race condition between provision step and BifrostService::start
Summary:
During initialization of metadata. Try to resolve conflict with bifrost initialization
by recreating the logs iff it still at MIN version and has an empty chains
Fixes #2486
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2533).
* #2532
* __->__ #2533
=> Fix race condition between provision step and BifrostService::start

crates/metadata-store/proto/metadata_store_svc.proto, crates/metadata-store/src/grpc/mod.rs, crates/metadata-store/src/lib.rs, crates/metadata-store/src/raft/kv_memory_storage.rs, crates/metadata-store/src/raft/store.rs
A more efficient serialization format for raft metadata store
Summary:
When applicable, use protobuf instead of flexbuffers for
message types. This include (so far):
- WriteRequest
- KvSnapshot
=> A more efficient serialization format for raft metadata store

crates/metadata-store/src/lib.rs
Follow up #2544
Summary:
Follow up to PR #2544. Avoid unrwap() when decoding a value
=> Follow up #2544

crates/metadata-store/proto/metadata_store_svc.proto, crates/metadata-store/src/grpc/client.rs, crates/metadata-store/src/lib.rs, crates/metadata-store/src/network/networking.rs, crates/metadata-store/src/raft/kv_memory_storage.rs, crates/metadata-store/src/raft/mod.rs, crates/metadata-store/src/raft/store.rs, tools/restatectl/src/commands/cluster/provision.rs, tools/restatectl/src/commands/metadata/status.rs
This commit adds version and member information to Raft configuration changes
so that we can check for members that have lost their disks and improve
observability.
This PR is based on #2544.
=> Attach version and member information to Raft configuration changes 

crates/rocksdb/src/error.rs
See https://github.com/restatedev/restate/issues/2505
=> Improved notification for direct-io logging

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service.rs, crates/admin/src/cluster_controller/service/state.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2564).
* #2570
* #2566
* __->__ #2564
=> Avoid unnecessary metadata read in cluster controller

Cargo.lock, crates/futures-util/Cargo.toml, crates/futures-util/src/lib.rs, crates/futures-util/src/overdue.rs
For futures where we want to observe if the are too slow or overdue, this extension trait adds the ability to log with automatic exponential backoff on a certain tracing level, then optionally upgrade the level and reports once it crosses the "overdue" threshold.
```rust
use restate_futures_util::overdue::OverdueLoggingExt;
let result = my_future
.log_slow_after(
Duration::from_secs(1),
tracing::Level::INFO,
"Doing something important.",
)
// optional
.with_overdue(
Duration::from_secs(30),
tracing::Level::WARN
).await;
// prints
// INFO "[slow] Doing something important. elapsed=1s");
// INFO "[slow] Doing something important. elapsed=2s");
// INFO "[slow] Doing something important. elapsed=4s");
// INFO "[slow] Doing something important. elapsed=8s");
// ...
// WARN "[overdue] Doing …
```
=> Utility for logging slow or overdue futures

crates/bifrost/src/bifrost_admin.rs, crates/core/src/metadata_store.rs, crates/core/src/metadata_store/providers/etcd.rs, crates/core/src/metadata_store/providers/objstore/glue.rs, crates/core/src/metadata_store/providers/objstore/optimistic_store.rs, crates/local-cluster-runner/src/node/mod.rs, crates/metadata-server/src/grpc/client.rs, crates/metadata-server/src/lib.rs, crates/metadata-server/src/local/mod.rs, crates/metadata-server/src/local/store.rs, crates/metadata-server/src/local/tests.rs, crates/metadata-server/src/raft/storage.rs, crates/metadata-server/src/raft/store.rs, crates/metadata-server/src/util.rs, crates/node/src/init.rs, crates/node/src/lib.rs, crates/types/src/config/metadata_server.rs, crates/types/src/config/mod.rs, crates/types/src/config/rocksdb.rs, crates/types/src/errors.rs, server/src/main.rs, tools/restatectl/src/commands/log/dump_log.rs, tools/restatectl/src/commands/metadata/get.rs, tools/restatectl/src/commands/metadata/patch.rs, tools/restatectl/src/environment/metadata_store.rs
Transport errors result in a Status error with an Unknown code. Since a transport
error is a retryable error, this commit updates the classification in the
GrpcMetadataServerClient accordingly.
=> Classify Unknown statuses as retryable 

crates/core/src/metadata_store.rs, crates/metadata-server/src/grpc/client.rs
Instead of letting the client retry, it is now the responsibility of the
user to retry if she wants. This gives more flexibility and avoids the negative
effet of prolonged retry delays if there is a nesting of retry policies. Only
if the response let's us learn about a known leader, we will retry immediately.
This PR is based on #2581.
=> Remove inner retry mechanism from GrpcMetadataServerClient

crates/admin/src/cluster_controller/logs_controller.rs, crates/bifrost/src/providers/replicated_loglet/mod.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs
Re-implemented the logic to propose new loglet configurations directly on any bifrost node. This unlocks the next PR which will use the auto_extend feature to auto-recover.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2586).
* #2589
* #2587
* __->__ #2586
=> [Bifrost] Replicated loglet provider uses nodeset selector

Cargo.lock, crates/admin/src/cluster_controller/logs_controller.rs, crates/bifrost/Cargo.toml, crates/bifrost/src/appender.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/providers/replicated_loglet/mod.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/log-server/src/loglet_worker.rs, crates/types/src/config/bifrost.rs, crates/types/src/config/common.rs, crates/types/src/config/networking.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2589).
* __->__ #2589
* #2587
* #2586
=> Adjust metadata networking options

crates/invoker-impl/src/error.rs, crates/invoker-impl/src/lib.rs, crates/service-protocol-v4/src/entry_codec.rs, crates/tracing-instrumentation/src/lib.rs, crates/tracing-instrumentation/src/pretty.rs, crates/types/src/errors.rs, crates/types/src/service_protocol.rs, service-protocol/dev/restate/service/protocol.proto
=> Move the stacktrace we get from the SDK to the bottom

crates/ingress-http/src/handler/error.rs, crates/ingress-http/src/handler/invocation.rs, crates/ingress-http/src/handler/workflow.rs, crates/invoker-impl/src/error.rs, crates/types/src/schema/openapi.rs
This should cover some common mistakes when using the ingress.
=> Improve few ingress errors

crates/metadata-server/src/raft/store.rs
Before, we stopped joining the cluster if were a member and had an ongoing join
operation in flight. This was clearly wrong. This is no changed to only stop
joining if one is no longer a member.
=> Fix Raft metadata join logic 

crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/core/src/metadata_store.rs, crates/log-server/src/service.rs, crates/node/src/lib.rs, crates/node/src/roles/base.rs
In the presence of network errores, mark_the_node_as_writeable must be able to
tolerate retry attempts. This commit changes the behvaiour of this method to
only fail on the first attempt if the StorageState is not Provisioning. Moreover,
it adds a basic retry policy for retryable errors.
This fixes https://github.com/restatedev/restate/issues/2563.
=> Allow mark_the_node_as_writeable to tolerate retry attempts 

crates/ingress-http/src/handler/service_handler.rs, crates/ingress-http/src/handler/tests.rs, crates/storage-api/src/invocation_status_table/mod.rs, crates/types/src/net/partition_processor.rs, crates/worker/src/partition/leadership/leader_state.rs, crates/worker/src/partition/state_machine/actions.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/delayed_send.rs, crates/worker/src/partition/state_machine/tests/idempotency.rs
=> Fix incorrect execution_time sent back in the send response

crates/admin-rest-model/src/version.rs, crates/admin/src/rest_api/version.rs, crates/types/src/config/admin.rs
To configure via env var: `RESTATE_ADMIN__ADVERTISED_INGRESS_ENDPOINT="http://localhost:8081/"`
=> Add config option to configure the ingress_endpoint in the admin configuration. This will be used by the Web UI.

Cargo.lock, crates/admin/protobuf/cluster_ctrl_svc.proto, crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/core/protobuf/node_ctl_svc.proto, tools/restatectl/Cargo.toml, tools/restatectl/src/app.rs, tools/restatectl/src/commands/cluster/config/get.rs, tools/restatectl/src/commands/cluster/config/set.rs, tools/restatectl/src/commands/cluster/overview.rs, tools/restatectl/src/commands/cluster/provision.rs, tools/restatectl/src/commands/log/describe_log.rs, tools/restatectl/src/commands/log/find_tail.rs, tools/restatectl/src/commands/log/list_logs.rs, tools/restatectl/src/commands/log/reconfigure.rs, tools/restatectl/src/commands/log/trim_log.rs, tools/restatectl/src/commands/metadata/get.rs, tools/restatectl/src/commands/metadata/mod.rs, tools/restatectl/src/commands/metadata/patch.rs, tools/restatectl/src/commands/metadata/put.rs, tools/restatectl/src/commands/metadata/status.rs, tools/restatectl/src/commands/node/list_nodes.rs, tools/restatectl/src/commands/partition/list.rs, tools/restatectl/src/commands/replicated_loglet/digest.rs, tools/restatectl/src/commands/replicated_loglet/info.rs, tools/restatectl/src/commands/snapshot/create_snapshot.rs, tools/restatectl/src/connection.rs, tools/restatectl/src/lib.rs
Streamline restatectl connection to cluster
Summary:
Make it easier and cleaner to run the restatectl command
by accepting the restate nodes addresses via a unified argument `--address`
- Support passing multiple addresses
- The command will try to fetch the nodes configuration from the first reachable node
- All other subcommands can then use the connection info to use the nodes configuration directly
or to connect to a specific node role
=> Streamline restatectl connection to cluster

.github/workflows/docker-release.yml, .github/workflows/notarize.yml, .github/workflows/npm.yml, .github/workflows/release.yml, dist-workspace.toml, npm/restate/src/index.ts, npm/restatectl/package.json, npm/restatectl/src/index.ts, npm/restatectl/tsconfig.json, tools/restatectl/Cargo.toml
1. Add restatectl npm package
2. Add restatectl brew formula
3. Fix broken restate-cli dockerfile, and also include restatectl in this image (you would have to specify this entrypoint separately though)
4. Distribute restatectl as part of release artifacts
5. Notarize apple binaries
=> Distribute restatectl

.github/workflows/homebrew.yml, .github/workflows/npm.yml, .github/workflows/release.yml, .github/workflows/scarf-release-notes.yml, cli/Cargo.toml, crates/types/src/config/common.rs, crates/types/src/config_loader.rs, dist-workspace.toml, npm/restate-server/package.json, npm/restate/package.json, npm/restatectl/package.json
1. Use scarf urls in homebrew
2. Use scarf urls in release notes install instructions
3. Include scarf dependency in binary NPM packages
4. Publish npm (under 'next' tag) and docker ('latest' will not be set) when pre-releasing, but not homebrew (as this basically doesn't have versions)
5. Tell dist to create an npm installer, just so it mentions it in the release notes.
=> Use scarf urls for downloading binaries

crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/service.rs, crates/bifrost/src/providers/replicated_loglet/log_server_manager.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/get_trim_point.rs, crates/bifrost/src/providers/replicated_loglet/tasks/periodic_tail_checker.rs, crates/bifrost/src/providers/replicated_loglet/tasks/repair_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/trim.rs, crates/bifrost/src/providers/replicated_loglet/tasks/util.rs, crates/types/src/config/bifrost.rs, crates/types/src/net/replicated_loglet.rs, tools/restatectl/src/commands/log/find_tail.rs
This PR introduces a few changes resulting in significant improvements in failover time, and performance of common operation like find_tail().
The result is failover time that in the hundreds of milliseconds in the happy path and in the order of a couple of seconds in the unhappy path. `find_tail()` is
also now significantly cheaper to run if the sequencer is running, this enables parallelization of `find_tail()` runs in logs controller (and more frequent as well). The latter comment will be reflected in a separate PR.
This also includes a new implementation of the seal task that reuses the `RunOnSingleNode` utility and that doesn't continue attempts once f-majority is sealed to reduce overloading the cluster. This can be reconsidered if we observed issues.
---
[//]: # (BEGIN SAPLING …
=> [Bifrost] Design improvements for find_tail

scripts/loadtest-environment/package.json
Fixes https://github.com/restatedev/restate/security/dependabot/16
This is a trivial dependency bump - we don't actually run this anywhere, it's just here as a reference.
=> Bump CDK dependency in load-test template

Cargo.lock, Cargo.toml, benchmarks/benches/throughput_parallel.rs, crates/admin/Cargo.toml, crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/rest_api/cluster_health.rs, crates/bifrost/benches/replicated_loglet_serde.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/replication/spread_selector.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/digests.rs, crates/cli-util/src/opts.rs, crates/core/src/network/connection_manager.rs, crates/local-cluster-runner/src/lib.rs, crates/metadata-server/src/grpc/client.rs, crates/metadata-server/src/raft/store.rs, crates/node/src/network_server/prometheus_helpers.rs, crates/partition-store/src/timer_table/mod.rs, crates/types/src/identifiers.rs, crates/types/src/invocation.rs, crates/types/src/logs/metadata.rs, crates/types/src/replicated_loglet/log_nodeset.rs, crates/types/src/replication/nodeset.rs, crates/types/src/retries.rs, scripts/loadtest-environment/bin/loadtest-env.ts, scripts/loadtest-environment/package.json, server/tests/raft_metadata_cluster.rs, tools/restatectl/src/connection.rs, workspace-hack/Cargo.toml
Not targeted at anything in particular; I did this with `cargo update` from the root and then fixed up the issues that arose.
The one major exclusion from this update is `googletest` which causes quite a long list of issues due to some matcher changes; I'll update that separately.
=> Mass dependency update

crates/types/src/config/bifrost.rs, tools/restatectl/src/connection.rs
Minor improvements
* Unhide default-replication-property
* Update Rustdocs in ConnectionInfo to be more explanatory
* Make cluster state logging less chatty
=> Minor improvements

crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/types/src/nodes_config.rs
This fixes a nasty correctness bug where provisioning node is considered empty(). empty nodes are implicitly authoritative but provisioning nodes are not authoritative since they can later join the write-set. I've also increased the checkSeal requirement to avoid mismarking a loglet as sealed as we don't want to violate the invariant: a sealed loglet must remain sealed, always.
```
```
=> [Bifrost] Provisioning nodes are not authoritative empty

crates/types/src/config/worker.rs
There was a dangling sentence, which was an opportunity to tidy up the language in the doc comments overall.
=> Minor snapshot destination comment update

tools/restatectl/src/app.rs, tools/restatectl/src/commands/cluster/config/set.rs, tools/restatectl/src/commands/cluster/mod.rs, tools/restatectl/src/commands/cluster/provision.rs, tools/restatectl/src/commands/mod.rs, tools/restatectl/src/commands/provision.rs
Instead of calling restatectl cluster provision one now can call
restatectl provision to provision a Restate cluster.
=> Make provision a top-level command 

Cargo.lock, Cargo.toml, crates/admin/Cargo.toml, crates/admin/src/lib.rs, crates/admin/src/service.rs, crates/admin/src/state.rs, crates/admin/src/storage_query/mod.rs, crates/admin/src/storage_query/query.rs, crates/bifrost/Cargo.toml, crates/node/Cargo.toml, crates/node/src/roles/admin.rs, crates/rocksdb/Cargo.toml, server/Cargo.toml, tools/xtask/src/main.rs, workspace-hack/Cargo.toml
This PR reduces release build time of restatectl *when restate-server build is cached* from 9 minutes to 3 minutes, via various otherwise-generally-sensible changes:
1. Don't include datafusion in restatectl, by making storage query a feature of restate-admin
2. Set the "profiling" feature on jemalloc-sys always, not just in server, as otherwise we have to rebuild jemalloc-sys and rocksdb-sys for restatectl
3. Disallow jsonschema from making outbound http/file requests, which means it doesn't need the reqwest 'blocking' feature, which differed from other binaries. This is also probably a security catch cc @slinkydeveloper 
NB: in CI builds, we are *currently* unifying all features anyway, although we need to change this. So, unifying a little bit in our Cargo.toml just lessens the impact …
=> Restatectl unification

Cargo.lock, crates/bifrost/src/providers/replicated_loglet/metric_definitions.rs, crates/core/src/metadata_store.rs, crates/core/src/metric_definitions.rs, crates/core/src/task_center.rs, crates/metadata-server/Cargo.toml, crates/metadata-server/src/grpc/handler.rs, crates/metadata-server/src/lib.rs, crates/metadata-server/src/metric_definitions.rs, crates/metadata-server/src/raft/network/connection_manager.rs, crates/metadata-server/src/raft/store.rs
Implement Telemetry Metrics for Metadata Server
Summary:
This pull request introduces telemetry metrics to the metadata server, enhancing monitoring and performance analysis capabilities.
Fixes #2605
=> Implement Telemetry Metrics for Metadata Server

docker/Dockerfile
That explains why the docker cache was so large on release builds now! restatectl binary with symbols is 600Meg...
=> Remember to strip debuginfo from restatectl and restate bins

crates/core/src/metadata_store/providers/etcd.rs, crates/core/src/metadata_store/providers/objstore/mod.rs, crates/core/src/metadata_store/providers/objstore/object_store_version_repository.rs, crates/core/src/metadata_store/providers/objstore/optimistic_store.rs, crates/core/src/network/net_util.rs, crates/local-cluster-runner/src/node/mod.rs, crates/metadata-server/src/grpc/client.rs, crates/metadata-server/src/grpc/handler.rs, crates/metadata-server/src/grpc/mod.rs, crates/metadata-server/src/lib.rs, crates/metadata-server/src/local/mod.rs, crates/metadata-server/src/local/server.rs, crates/metadata-server/src/local/tests.rs, crates/metadata-server/src/raft/mod.rs, crates/metadata-server/src/raft/network/handler.rs, crates/metadata-server/src/raft/network/mod.rs, crates/metadata-server/src/raft/server.rs, crates/metadata-server/src/raft/store.rs, crates/node/src/lib.rs, crates/types/src/config/common.rs, crates/types/src/config/metadata_server.rs, server/tests/common/replicated_loglet.rs, server/tests/raft_metadata_cluster.rs, server/tests/trim_gap_handling.rs, tools/restatectl/src/commands/log/dump_log.rs, tools/restatectl/src/commands/metadata/get.rs, tools/restatectl/src/commands/metadata/mod.rs, tools/restatectl/src/commands/metadata/patch.rs, tools/restatectl/src/environment/metadata_store.rs
[Rename serialized MetadataServerKind::Raft variant to replicated](https://github.com/restatedev/restate/commit/e77d90c1fcf2ae92f81d299172547d3e4c7e465c) 
With this commit, the default way to configure the Raft based metadata server
is to configure metadata-server.type = "replicated".
[Rename MetadataStoreClientOptions into MetadataClientOptions](https://github.com/restatedev/restate/commit/7492101c1639fbed4d2a82cc3b5be06f6c3076a9) 
This commit also moves some of the metadata client specific options back
under the [metadata-client] key. It tries to achieve backwards compatibility
with the previous configuration names. The metadata client used with the local
and the replicated metadata server is now called "native" ("embedded" still works
as an alias).
=> Rename serialized MetadataServerKind::Raft variant to replicated and MetadataStoreClientOptions into MetadataClientOptions

.github/workflows/ci.yml, .github/workflows/docker-release.yml, .github/workflows/docker.yml, .github/workflows/release.yml, .github/workflows/steps/release-build-setup.yml, docker/Dockerfile, docker/debug.Dockerfile
Currently we have hakari unification for some targets, and we also are unifying in restate-local-cluster-runner unnecessarily in docker builds.
Also, we can ensure that in release docker builds, we actually build the 3 binaries individually, instead of feature unifying them
=> Avoid (some) feature unification in CI builds

Cargo.lock, crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/providers/replicated_loglet/error.rs, crates/bifrost/src/providers/replicated_loglet/log_server_manager.rs, crates/bifrost/src/providers/replicated_loglet/metric_definitions.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/types/src/logs/metadata.rs, crates/types/src/replication/nodeset.rs, tools/restatectl/src/commands/cluster/config.rs
Key changes:
- Using JoinSet instead of unordered futures to perform store tasks to avoid some of its tricky lockup scenarios
- Store tasks are free to use whatever connection is available, this over-indexes over the current design that serializes all writes in a one-at-a-time fashion, but removes a lock, and simplifies the logic.
- Extra in-flight stores are aborted after an append is complete to avoid overloading
- Timeout store tasks only on the basis of their network operation and not on the time they're waiting for the tail to move
- Cache nodeset checker across waves
- Better logging on failures, it reports the nodeset status with the number of attempts per node
- Adds a new metric to latency of appends
Performance testing shows no regression and reliability testing appears to show …
=> [Bifrost] Sequencer updates

crates/types/src/logs/metadata.rs, tools/restatectl/src/commands/cluster/config.rs
Previously, setting target nodeset size with restatectl would tell you that "No change"
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2645).
* #2654
* #2651
* #2650
* #2649
* #2638
* #2646
* __->__ #2645
=> Fixes restatectl setting target nodeset size

Cargo.lock, crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/providers/replicated_loglet/error.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/types/src/logs/metadata.rs, crates/types/src/replication/nodeset.rs, tools/restatectl/src/commands/cluster/config.rs
The PR also uses it in CheckSeal. This utility `DecoratedNodeSet` can be used when you want to add a nugget of information next to every node. It prints the nodeset sorted as well.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2646).
* #2654
* #2651
* #2650
* #2649
* #2638
* __->__ #2646
* #2645
=> `DecoratedNodeSet` Utility to display decorated nodesets

Cargo.lock, crates/admin/src/cluster_controller/service.rs, crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/error.rs, crates/bifrost/src/providers/replicated_loglet/error.rs, crates/bifrost/src/providers/replicated_loglet/log_server_manager.rs, crates/bifrost/src/providers/replicated_loglet/metric_definitions.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/types/src/logs/metadata.rs, crates/types/src/replication/nodeset.rs, crates/types/src/retries.rs, tools/restatectl/src/commands/cluster/config.rs
Those find_tail operations are only used by the partition_processor on startup and we don't want it to fail unnecessarily, this gives it a good chance to succeed unless the underlying error is not retryable.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2649).
* #2654
* #2651
* #2650
* __->__ #2649
* #2638
* #2646
* #2645
=> [Bifrost] Allow top-level find_tail to auto-retry

Cargo.lock, crates/admin/src/cluster_controller/service.rs, crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/error.rs, crates/bifrost/src/providers/replicated_loglet/error.rs, crates/bifrost/src/providers/replicated_loglet/log_server_manager.rs, crates/bifrost/src/providers/replicated_loglet/metric_definitions.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/metadata-server/src/raft/server.rs, crates/metadata-server/src/raft/storage.rs, crates/types/src/logs/metadata.rs, crates/types/src/replication/nodeset.rs, crates/types/src/retries.rs, tools/restatectl/src/commands/cluster/config.rs
- Always flush metadata-server CFs on shutdown
- INFO logging for leadership changes events
```
// intentionally left empty
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2650).
* #2654
* #2651
* __->__ #2650
* #2649
* #2638
* #2646
* #2645
=> [MetadataServer] minor changes

Cargo.lock, crates/admin/src/cluster_controller/service.rs, crates/bifrost/Cargo.toml, crates/bifrost/src/bifrost.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/error.rs, crates/bifrost/src/providers/replicated_loglet/error.rs, crates/bifrost/src/providers/replicated_loglet/log_server_manager.rs, crates/bifrost/src/providers/replicated_loglet/metric_definitions.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/log-server/src/service.rs, crates/metadata-server/src/raft/server.rs, crates/metadata-server/src/raft/storage.rs, crates/node/src/cluster_marker.rs, crates/node/src/init.rs, crates/node/src/lib.rs, crates/rocksdb/src/db_manager.rs, crates/types/src/config_loader.rs, crates/types/src/logs/metadata.rs, crates/types/src/replication/nodeset.rs, crates/types/src/retries.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs, server/tests/cluster.rs, server/tests/trim_gap_handling.rs, tools/restatectl/src/commands/cluster/config.rs
Also shutdown, logs are ever so slightly better now
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2651).
* #2654
* __->__ #2651
* #2650
* #2649
* #2638
* #2646
* #2645
=> Improve info level logging for first run

crates/local-cluster-runner/src/node/mod.rs, crates/metadata-server/src/lib.rs, crates/metadata-server/src/raft/server.rs, crates/types/src/config/common.rs, crates/types/src/config/metadata_server.rs, server/tests/raft_metadata_cluster.rs
Fix configuration compatibility issues
Summary:
Making sure a single node server v1.2 can still work
with a v1.1.6 config
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2648).
* #2652
* __->__ #2648
=> Fix configuration compatibility issues

crates/local-cluster-runner/src/node/mod.rs, crates/types/src/config/common.rs, crates/types/src/config/worker.rs
Hide empty sections
Summary:
Avoid dumping empty sections in config files.
I think they look weird in config
```toml
[tracing-headers]
[worker.snaphosts]
```
=> Hide empty sections

.github/workflows/release-notes.yml, README.md
While it does work, I think the repo name redirecting is going to be a source of weird bugs :(
=> Use full repo name in scarf docker urls :(

crates/admin/src/cluster_controller/service.rs, crates/core/src/metadata.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/transport_connector.rs, crates/core/src/network/types.rs, crates/core/src/task_center/task_kind.rs, crates/log-server/src/loglet_worker.rs, crates/types/src/config/networking.rs, crates/types/src/node_id.rs
This enables nodes to maintain concurrent connections across different actual TCP connections to increase message processing concurrency. This is controlled by a new configuration option in `[networking]` section.
This also tags a few operations with `tokio::task::unconstrained` to reduce unnecessary coop-driven yields that happen at some hot-paths.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2664).
* #2672
* #2670
* #2669
* #2665
* __->__ #2664
* #2654
=> [Core] Enable concurrent connections between nodes

crates/admin/src/cluster_controller/service.rs, crates/core/src/metadata.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/message_router.rs, crates/core/src/network/metric_definitions.rs, crates/core/src/network/transport_connector.rs, crates/core/src/network/types.rs, crates/core/src/task_center/task_kind.rs, crates/log-server/src/loglet_worker.rs, crates/types/src/config/networking.rs, crates/types/src/node_id.rs
Introducing histograms and per-message counters. Histograms for processing duration per message are only enabled in debug builds but this decision can change if we found the need to use them for release build
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2665).
* #2672
* #2670
* #2669
* __->__ #2665
* #2664
* #2654
=> [Core] Network Telemetry improvements

.cargo/config.toml, .github/workflows/release.yml, .github/workflows/steps/release-build-setup.yml, crates/admin/src/cluster_controller/service.rs, crates/core/src/metadata.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/message_router.rs, crates/core/src/network/metric_definitions.rs, crates/core/src/network/transport_connector.rs, crates/core/src/network/types.rs, crates/core/src/task_center/task_kind.rs, crates/log-server/src/loglet_worker.rs, crates/types/src/config/networking.rs, crates/types/src/node_id.rs
Debug assertions are not meant to be used in release builds, most crates use `cfg(debug_assertions)` as a proxy to detect whether they are built in debug mode or not, this include `tracing` among many others. The side effect of having debug_assertions enabled is (a) performance penalty and (b) TRACE level being enabled in release build because `tracing` can't respect the release max logging filter feature flag if it doesn't know we are building in release mode.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2669).
* #2672
* #2670
* __->__ #2669
* #2665
* #2664
* #2654
=> Disable debug_assertions in release builds

.cargo/config.toml, .github/workflows/release.yml, .github/workflows/steps/release-build-setup.yml, crates/admin/src/cluster_controller/service.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/tasks/periodic_tail_checker.rs, crates/core/src/metadata.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/message_router.rs, crates/core/src/network/metric_definitions.rs, crates/core/src/network/transport_connector.rs, crates/core/src/network/types.rs, crates/core/src/task_center/task_kind.rs, crates/log-server/src/loglet_worker.rs, crates/types/src/config/networking.rs, crates/types/src/node_id.rs, crates/types/src/nodes_config.rs, crates/worker/src/partition/mod.rs
Among other small bits and bobs
```
intentionally empty
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2670).
* #2672
* __->__ #2670
* #2669
* #2665
* #2664
* #2654
=> Fix checker display output

.cargo/config.toml, .github/workflows/release.yml, .github/workflows/steps/release-build-setup.yml, crates/admin/src/cluster_controller/service.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/tasks/periodic_tail_checker.rs, crates/core/src/metadata.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/message_router.rs, crates/core/src/network/metric_definitions.rs, crates/core/src/network/transport_connector.rs, crates/core/src/network/types.rs, crates/core/src/task_center/task_kind.rs, crates/log-server/src/loglet_worker.rs, crates/types/src/config/networking.rs, crates/types/src/node_id.rs, crates/types/src/nodes_config.rs, crates/worker/src/partition/mod.rs
Those requests are really important to be handled quickly, we are doing two changes in this PR:
- Making expensive to run GetSequencerState operations not block the network loop
- Give priority to handling those request vs appends
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2672).
* __->__ #2672
* #2670
* #2669
* #2665
* #2664
* #2654
=> [Bifrost] Sequencer gives priority to GetSequencerState requests

crates/metadata-server/src/raft/storage/keys.rs
This commit fixes the problem that we don't read the log entry prefix if debug assertions are disabled.
=> Don't read log entry key prefix in debug_assert statement

tools/restatectl/src/commands/cluster/config.rs, tools/restatectl/src/commands/log/list_logs.rs, tools/restatectl/src/util.rs
Minor restatectl improvements
This fixes the `logs list` view and shows the configuration in a proper way
```
Log Configuration (v3)
└ Logs Provider: replicated
├ Log replication: {node: 2}
└ Nodeset size: 0
L-ID  FROM-LSN  KIND        LOGLET-ID  REPLICATION  SEQUENCER  NODESET
0     2         Replicated  0_1        {node: 2}    N1:2       [N1, N2, N3]
1     1         Replicated  1_1        {node: 2}    N3:1       [N1, N2, N3]
2     2         Replicated  2_1        {node: 2}    N1:2       [N1, N2, N3]
3     1         Replicated  3_1        {node: 2}    N3:1       [N1, N2, N3]
```
instead of
```
Log Configuration (v3)
Default Provider Config: Replicated(ReplicatedLogletConfig { replication_property: {node: 2}, target_nodeset_size: NodeSetSize(0) })
L-ID  FROM-LSN  KIND        LOGLET-ID …
```
=> Minor restatectl improvements

crates/bifrost/src/providers/replicated_loglet/sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2673).
* #2690
* #2689
* #2683
* #2682
* #2681
* #2680
* #2677
* #2676
* __->__ #2673
=> Fix sequencer drain in challenging situations

crates/bifrost/src/appender.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglet/error.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/core/src/network/connection_manager.rs, crates/types/src/net/replicated_loglet.rs, server/tests/replicated_loglet.rs
This also adds a little bit more stress to the tests to help them fail more often if there is an issue
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2676).
* #2690
* #2689
* #2683
* #2682
* #2681
* #2680
* #2677
* __->__ #2676
* #2673
=> Remote sequencer now handle cancelled/gone sequencers

crates/bifrost/src/appender.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglet/error.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/core/src/network/connection_manager.rs, crates/types/src/net/replicated_loglet.rs, crates/types/src/nodes_config.rs, server/tests/common/replicated_loglet.rs, server/tests/replicated_loglet.rs
This fixes mishandling of deleted and unknown nodes in the config in f-majority checks. Integration tests were misconfigured where the nodeset was [N2..N4] where N4 didn't actually exist in config. In this case we should not accept f-majority seal if only one node is sealed (replication=2)
Although this bug wouldn't impact us immediately, it's best to fix this condition and I took it as an opportunity to update the semantics of provisioning state to match the latest design direction. Documentation has also been updated to reflect the correct semantics.
Summary:
- Nodes observed in node-set but not in nodes-config is treated as "provisioning" rather than "disabled"
- Nodes that are "deleted" in config (tombstone exists) are treated as "disabled"
- Nodes in provisioning are fully …
=> Fix treatment of not-found nodes and update provisioning semantics

crates/bifrost/src/appender.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglet/error.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/get_trim_point.rs, crates/bifrost/src/providers/replicated_loglet/tasks/trim.rs, crates/core/src/network/connection_manager.rs, crates/types/src/net/replicated_loglet.rs, crates/types/src/nodes_config.rs, server/tests/common/replicated_loglet.rs, server/tests/replicated_loglet.rs
- Trim operation will wait for f-majority before reporting success to increase reliability of subsequent get_trim_point
- Adds protection against a dangerous scenario if the loglet over-reported its trim point in a sealed loglet case. The loglet might have more records than the effective sealed tail, it should never report a trim point beyond that (if this happens, the system will believe that the subsequent segment is missing records)
- Remove superfluous check. The trim task already checks that trim point is clamped to the known global tail
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2680).
* #2690
* #2689
* #2683
* #2682
* #2681
* …
=> [Bifrost] Trim improvements

crates/bifrost/src/appender.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglet/error.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/get_trim_point.rs, crates/bifrost/src/providers/replicated_loglet/tasks/repair_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/trim.rs, crates/core/src/network/connection_manager.rs, crates/types/src/net/replicated_loglet.rs, crates/types/src/nodes_config.rs, server/tests/common/replicated_loglet.rs, server/tests/replicated_loglet.rs, tools/restatectl/src/commands/replicated_loglet/digest.rs, tools/restatectl/src/commands/replicated_loglet/digest_util.rs, tools/restatectl/src/commands/replicated_loglet/info.rs
- `restatectl replicated-loglet info` now prints a table with info from every node in the nodeset
- `restatectl replicated-loglet digest` doesn't require --from/--to to function, and fixes for overblown memory usage if the supplied range is unnecessarily large
- For both commands, lots of UI improvements. Some screenshots will be attached in comments.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2681).
* #2690
* #2689
* #2683
* #2682
* __->__ #2681
* #2680
* #2677
* #2676
* #2673
=> Improve replicated-loglet restatectl commands

crates/admin/src/cluster_controller/service.rs, crates/admin/src/cluster_controller/service/state.rs, crates/bifrost/src/appender.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglet/error.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/get_trim_point.rs, crates/bifrost/src/providers/replicated_loglet/tasks/repair_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/trim.rs, crates/core/src/network/connection_manager.rs, crates/log-server/src/loglet_worker.rs, crates/types/src/config/admin.rs, crates/types/src/config/worker.rs, crates/types/src/net/replicated_loglet.rs, crates/types/src/nodes_config.rs, crates/worker/src/partition_processor_manager/persisted_lsn_watchdog.rs, server/tests/common/replicated_loglet.rs, server/tests/replicated_loglet.rs, tools/restatectl/src/commands/replicated_loglet/digest.rs, tools/restatectl/src/commands/replicated_loglet/digest_util.rs, tools/restatectl/src/commands/replicated_loglet/info.rs
The main fixes:
- It was not actually possible to disable those two intervals, the configuration fails to parse the empty string that was suggested in docs. This is now replaced by `0s` or `0ms` (unfortunately only `0` will still fail, but can be fixed by custom serde_as which I don't have time for)
- Fixed how `OptionFuture` is being used, select! in a loop will run indefinitely if OptionFuture contains None because it's always poll::Ready with value None. This is a critical bug that we didn't hit because it wasn't possible to disable those intervals before
- Added jitter with `with_jitter()`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2683).
* #2690
* #2689
* …
=> Fixes for trim interval and persisted lsn watcher

crates/bifrost/src/appender.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglet/error.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/bifrost/src/providers/replicated_loglet/sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/get_trim_point.rs, crates/bifrost/src/providers/replicated_loglet/tasks/repair_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/trim.rs, crates/core/src/network/connection_manager.rs, crates/log-server/src/loglet_worker.rs, crates/types/src/net/replicated_loglet.rs, crates/types/src/nodes_config.rs, server/tests/common/replicated_loglet.rs, server/tests/replicated_loglet.rs, tools/restatectl/src/commands/replicated_loglet/digest.rs, tools/restatectl/src/commands/replicated_loglet/digest_util.rs, tools/restatectl/src/commands/replicated_loglet/info.rs
This was overly/incorrectly protective. We'll see those errors when often because we only need to seal f-majority, subsequent tail repair operations on restarts should still succeed on this log-server. A future follow-up (was already planned) is to lazily seal the loglet once we observe this operation on this log-server, but I didn't think that doing it in this time frame is necessary.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2682).
* #2690
* #2689
* #2683
* __->__ #2682
* #2681
* #2680
* #2677
* #2676
* #2673
=> [Bifrost] Allow repair stores on unsealed log-server

crates/log-server/src/rocksdb_logstore/store.rs
The issue happens when attempting to trim a loglet that's been already trimmed (fully or partially). If the global offset is unknown, find_tail on those old loglets will run on the background (periodic tail checker) to try and figure if they are sealed or not, this triggers a tail repair since records in the range [1..max-local] are trimmed/under-replicated. That wouldn't have been the case if the global tail was known.
The error itself is benign but it prints a message like this:
```
2025-02-09T17:18:58.181838Z ERROR restate_bifrost::providers::replicated_loglet::tasks::repair_tail
Couldn't repair the tail! We have records to repair **and** enough nodes to repair, but we couldn't find any node with copies for the oldest record within the repair range. We'll not be able to re-replicate …
```
=> [Bifrost] Fix for tail-repair on previously trimmed logs

crates/bifrost/src/providers/replicated_loglet/sequencer.rs, crates/log-server/src/rocksdb_logstore/store.rs
The soft-limit is i32::MAX (2B records) to give sufficient slop for race scenarios with reasonable coverage. The loglet's will drain itself once it reaches this soft limit and Bifrost appender will use this a signal for the auto-recovery mechanism to seal and extend the chain.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2690).
* #2691
* __->__ #2690
* #2689
=> [Bifrost] auto-drain the sequencer on exhausting offset limit

crates/metadata-server/src/raft/mod.rs, crates/metadata-server/src/raft/network/connection_manager.rs, crates/metadata-server/src/raft/network/handler.rs, crates/metadata-server/src/raft/network/mod.rs, crates/metadata-server/src/raft/network/networking.rs, crates/metadata-server/src/raft/server.rs, crates/types/src/net/node.rs
This should improve the log output to use the PlainNodeId formatting.
=> Use PlainNodeId in networking layer of replicated metadata server

crates/bifrost/benches/replicated_loglet_serde.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/rpc_router.rs, crates/types/protobuf/restate/common.proto, crates/types/protobuf/restate/log_server_common.proto, crates/types/protobuf/restate/node.proto, crates/types/src/net/codec.rs, crates/types/src/net/mod.rs, crates/types/src/node_id.rs, crates/types/src/protobuf.rs
Minor changes:
- Adds new GenerationalNodeId native protobuf message
- Renames the network protocol to V1 since it might not strictly be all in flexbuffers
- Minor changes in types of WireEncode to reduce the number of refcounts in refcounted buffers
- Marks the node_id as optional in Hello message, this is to allow (in the future) connections to be initiated by anonymous clients (the opposite direction will not be allowed)
```
intentionally empty
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2691).
* #2697
* #2694
* __->__ #2691
=> [Core] Future-proofing for anonymous connections

crates/bifrost/benches/replicated_loglet_serde.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/rpc_router.rs, crates/log-server/src/rocksdb_logstore/writer.rs, crates/types/protobuf/restate/common.proto, crates/types/protobuf/restate/log_server_common.proto, crates/types/protobuf/restate/node.proto, crates/types/src/logs/record_cache.rs, crates/types/src/net/codec.rs, crates/types/src/net/mod.rs, crates/types/src/node_id.rs, crates/types/src/protobuf.rs, crates/types/src/storage.rs
We were swapping records in the record cache with serialized ones, that hurts the use-case where the sequencer and the reader are co-located. The reason this was happening was because after the sequencer adds the "Typed" variant of the entry into cache, the co-located log-server would overwrite it.
This lets us gain 10-20% more throughput (YMMV).
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2694).
* #2697
* __->__ #2694
* #2691
=> [Bifrost] RecordCache record swap efficiency

crates/bifrost/benches/replicated_loglet_serde.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/sequencer.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/rpc_router.rs, crates/log-server/src/rocksdb_logstore/writer.rs, crates/types/protobuf/restate/common.proto, crates/types/protobuf/restate/log_server_common.proto, crates/types/protobuf/restate/node.proto, crates/types/src/logs/record.rs, crates/types/src/logs/record_cache.rs, crates/types/src/net/codec.rs, crates/types/src/net/mod.rs, crates/types/src/node_id.rs, crates/types/src/protobuf.rs, crates/types/src/storage.rs
The impact is limited due to how serialization is designed, but it pushes throughput on mac for 2 copies from ~9k to 10k messages per second. We still have long way to go to make serialization efficient but it's a step in this direction.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2697).
* __->__ #2697
* #2694
* #2691
=> [Bifrost] Reduce serialization overhead for replication

crates/node/src/lib.rs, crates/types/src/config/ingress.rs, crates/types/src/nodes_config.rs, server/tests/trim_gap_handling.rs
This change also makes it impossible to use the role without the experimental flag that enables it.
After the change:
```
% restate-server --help
...
--roles [<ROLES>...]
Defines the roles which this Restate node should run, by default the node starts with all roles.
Roles can be comma-separated list without spaces (`--roles=worker,admin,log-server`), or a repeated option like `--roles=worker --roles=admin`.
Possible values:
- worker:          A worker runs partition processor (journal, state, and drives invocations)
- admin:           Admin runs cluster controller and user-facing admin APIs
- metadata-server: Serves the metadata store
- log-server:      [PREVIEW FEATURE] Serves a log-server for replicated loglets
- http-ingress:    [EXPERIMENTAL FEATURE] Serves HTTP ingress requests …
```
=> Document the http-ingress role as experimental

cli/Cargo.toml, cli/src/app.rs, crates/types/src/net/mod.rs, tools/restatectl/Cargo.toml, tools/restatectl/src/app.rs, tools/restatectl/src/commands/provision.rs, tools/restatectl/src/connection.rs
- Advertised address now uses `http` by default if scheme is now supplied, so addresses like `localhost:5122` will now be accepted
- Added description to Restatectl and restate cli for `--help`
- Orders commands and options in help (more important commands and options first)
- feature unification for clap
=> [restatectl] rename --addresses to --address or -s

crates/admin/src/rest_api/version.rs, crates/admin/src/service.rs, crates/types/src/config/admin.rs, crates/types/src/config/ingress.rs, crates/types/src/config_loader.rs, server/src/main.rs
Add optional `advertised_admin_endpoint`
Summary:
Adding `advertised_admin_endpoint` mainly to show to the
user while the node is starting
By default uses the admin bind address
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2700).
* #2703
* __->__ #2700
=> Add optional `advertised_admin_endpoint`

crates/bifrost/benches/replicated_loglet_serde.rs, crates/types/protobuf/restate/node.proto, crates/types/src/protobuf.rs
- Non-optional fields first for more compact encoding
- BinaryMessage is always at the far-end to (a) make deprecation easier and (b) make out-of-band decoding possible
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2704).
* #2706
* __->__ #2704
=> [Core] reordering protobuf fields

crates/bifrost/benches/replicated_loglet_serde.rs, crates/core/src/network/connection.rs, crates/core/src/network/rpc_router.rs, crates/types/protobuf/restate/node.proto, crates/types/src/net/codec.rs, crates/types/src/net/mod.rs, crates/types/src/protobuf.rs
- Network messages now perform one less memory copy during serialization
- One step closer to allowing some messages to be native proto types
More follow ups are incoming.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2706).
* __->__ #2706
* #2704
=> [1/n] Remove one memory copy from network serialization

crates/core/src/metadata_store/providers/objstore/mod.rs, crates/core/src/network/connection_manager.rs, crates/core/src/task_center/task_kind.rs, crates/metadata-server/src/local/server.rs, crates/metadata-server/src/local/tests.rs, crates/node/src/lib.rs, crates/types/src/config/mod.rs, crates/types/src/config_loader.rs, crates/types/src/node_id.rs, crates/types/src/nodes_config.rs, tools/restatectl/src/environment/metadata_store.rs
[Forbid forcing node id 0](https://github.com/restatedev/restate/commit/b834250dc2260a0e9ee96a9bd560096b0fbe030e) 
With this commit we no longer allow users to set the node id to 0 since it is a reserved value
now. In case the user forces this node id, we will fail with an explanatory error message.
[Auto migrate PlainNodeId 0 to the forced node id or the next available PlainNodeId](https://github.com/restatedev/restate/commit/b8ed192fd54dfc5aa36c13d0386c07e674c2aabb) 
This commit adds a migration path for the LocalMetadataServer which updates a 0 PlainNodeId to a
non-zero value in the NodesConfiguration. If the node that runs the local metadata server had the
node id 0, then the migration path will respect a potentially forced node id if it is set and not
yet taken. Otherwise, the …
=> Forbid using node id zero and add auto migration path

tools/restatectl/src/commands/metadata/patch.rs, tools/restatectl/src/commands/metadata/put.rs
Conflicting restatectl flags
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2719).
* #2714
* #2721
* __->__ #2719
=> Conflicting restatectl flags

tools/restatectl/src/commands/log/reconfigure.rs, tools/restatectl/src/commands/metadata/patch.rs, tools/restatectl/src/commands/metadata/put.rs
Reconfigure respect `--sequencer` and `--nodeset` if provider is not supplied
Summary:
Respect both the sequencer and nodeset flag if provider is not supplied
as long as the loglet is already using replicated provider.
Also make sure there is noway you can go back to local or in-memory provider
once you go replicated
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2721).
* #2714
* __->__ #2721
* #2719
=> Reconfigure respect `--sequencer` and `--nodeset` if provider is not supplied

crates/core/src/metadata_store/providers/objstore/mod.rs, crates/local-cluster-runner/src/node/mod.rs, crates/metadata-server/src/lib.rs, crates/metadata-server/src/local/mod.rs, crates/metadata-server/src/local/server.rs, crates/metadata-server/src/local/storage.rs, crates/metadata-server/src/local/tests.rs, crates/metadata-server/src/raft/mod.rs, crates/metadata-server/src/raft/server.rs, crates/metadata-server/src/raft/storage/rocksdb.rs, crates/metadata-server/src/raft/tests.rs, crates/node/src/lib.rs, crates/types/src/config/metadata_server.rs, crates/types/src/node_id.rs, server/Cargo.toml, server/src/main.rs
This commit adds an automatic migration path from a local to a replicated metadata
server. To make use of it, users need to set
metadata-server.type = replicated
metadata-server.migrate_from_local_metadata_server = true
If the replicated metadata server hasn't provisioned before, then it will read the
key-value pairs from the local metadata store and initialize its own storage with it.
It will also run the migration logic for older NodesConfiguration versions (those
that might still have a node id of 0 configured).
=> Add automatic migration path from local to replicated metadata server 

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/service.rs
This commit allows users to change the default log provider to replicated even if the
cluster has been fully provisioned. This allows users to migrate from a single node
deployment with a local loglet to a replicated loglet and then a multi node deployment.
Additionally, this commit enables the LogsController to react to default provider changes.
If the new default provider is the replicated loglet, then the logs controller will reconfigure
all logs.
=> Allow to change the default provider to replicated

Cargo.lock, Cargo.toml
This brings in updated rust-librocksdb-sys @ v0.32.0+9.10.0.restate-1, which includes updated rocksdb @ v9.10.0.restate-1 rebased on the upstream RocksDB v9.10.0 release.
See: https://github.com/restatedev/rust-rocksdb/tree/v0.36.0-restate.1
=> Update rust-rocksdb to v0.36.0-restate.1

crates/ingress-http/src/handler/service_handler.rs, crates/invoker-impl/src/invocation_task/service_protocol_runner.rs, crates/invoker-impl/src/invocation_task/service_protocol_runner_v4.rs
This commit tunes down the logging of the service_protocol_runner and the service_handler. Instead of logging invocations on the info level, we are now logging it on debug level.
=> Avoid per invocation info logging

tools/restatectl/src/commands/log/describe_log.rs, tools/restatectl/src/commands/log/find_tail.rs, tools/restatectl/src/commands/log/mod.rs, tools/restatectl/src/commands/log/reconfigure.rs, tools/restatectl/src/commands/log/trim_log.rs, tools/restatectl/src/commands/snapshot/create_snapshot.rs, tools/restatectl/src/util.rs
Unify the `range input` for some ids
Summary:
- Support parsing an "range" input.
- Handle id range in some common operations
- `logs describe`
- `logs find-tail`
- `logs reconfigure`
- `snapshots create-snapshot`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2723).
* #2714
* __->__ #2723
=> Unify the `range input` for some ids

crates/core/src/network/net_util.rs, crates/core/src/network/server_builder.rs, crates/local-cluster-runner/src/node/mod.rs, crates/metadata-server/src/grpc/client.rs, crates/metadata-server/src/lib.rs, crates/metadata-server/src/local/server.rs, crates/metadata-server/src/local/tests.rs, crates/metadata-server/src/raft/mod.rs, crates/metadata-server/src/raft/server.rs, crates/metadata-server/src/raft/tests.rs, crates/node/src/lib.rs, crates/types/src/config/common.rs, server/tests/raft_metadata_cluster.rs, server/tests/trim_gap_handling.rs, tools/restatectl/src/commands/log/dump_log.rs, tools/restatectl/src/commands/metadata/get.rs, tools/restatectl/src/commands/metadata/mod.rs, tools/restatectl/src/commands/metadata/patch.rs, tools/restatectl/src/environment/metadata_store.rs
This is probably for after the release of 1.2.0.
This commit removes the grpc interface from the LocalMetadataServer so
that it is no longer reachable from outside of the process. This is a
precaution to prevent users from using the LocalMetadataServer across
multiple processes.
This fixes https://github.com/restatedev/restate/issues/2717.
=> Make LocalMetadataServer not reachable from outside of the process 

crates/log-server/src/service.rs, crates/metadata-server/src/raft/server.rs
- Log-server auto-transitions into `data-loss` if it detected that its marker is lost
- log-server rejects to start if the not has lost its marker and not in provisioning state
Note that this still doesn't mark the node as data-loss if corruption was detected in rocksdb. Current behaviour is that the log-server will fail to start but the node remains in read-write.
If the node detected marker loss, this is what it prints on the log
```
on rs:worker-8
2025-02-14T09:40:24.606443Z WARN restate_log_server::service
Detected data loss for log-server of my node N1. The log-server marker is missing, storage-state was read-write, will transition into `data-loss`
on rs:worker-11
in restate_log_server::service::provision_node
2025-02-14T09:40:24.609743Z ERROR restate_core::task_center
Shutting down: …
```
=> [LogServer] Support for data-loss transition

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/service.rs
Ensure a correct loglet id when switching from local loglet
Summary:
Ensure that the replicated loglet-id is constructed from (log-id + segment-id)
when switching over from a local/memory loglet
=> Ensure a correct loglet id when switching from local loglet

crates/types/src/config/worker.rs, crates/worker/src/partition/snapshots/repository.rs, crates/worker/src/partition/snapshots/snapshot_task.rs
This change enables a separate profile - or granular explicit configuration - to be used with the snapshot repository. This is helpful when using a non-AWS S3-compatible object store and in particular, helps avoid interfering with the AWS configuration needed by the Lambda invoker.
```toml
[worker.snapshots]
aws_profile = "profile"
aws_allow_http = true
aws_region = "..."
aws_access_key_id = "..."
aws_secret_access_key = "..."
```
The logic here will be to either use whatever creds are available, in the conventional order of precedence (env vars, config profile, EC2 metadata service, ...).
=> Add pass-through parameters for S3 client configuration

crates/worker/src/partition_processor_manager.rs
This change prevents enabling of periodic snapshots by config reload; instead the server has to be restarted for the repository to be configured upfront.
=> Avoid periodic snapshotting if no repository is available

crates/types/src/logs/metadata.rs, crates/types/src/nodes_config.rs, tools/restatectl/src/commands/replicated_loglet/mod.rs, tools/restatectl/src/commands/replicated_loglet/storage_state.rs
- adds `replicated-loglet servers` or (list-servers)
- adds `replicated-loglet set-storage-state --node-id=4 --storage-state=read-only`
Note that this is restrictive at the moment, except that it liberally allows transition from `read-write` into `read-only` even if this leads the cluster in a state where no further nodesets with enough writeable nodes to generate nodesets. A check for this will in a future follow-up
Screenshots with the behaviour in comments.
```
```
=> [restatectl] Support for setting/viewing log-server storage-state

Cargo.lock, crates/cli-util/src/opts.rs, tools/restatectl/Cargo.toml, tools/restatectl/src/commands/log/list_logs.rs, tools/restatectl/src/commands/log/reconfigure.rs, tools/restatectl/src/commands/metadata_server/status.rs, tools/restatectl/src/connection.rs
This PR aims to improve the overall responsiveness of `restatectl` with clusters that are still busy provisioning or otherwise only partially connected to the host running the tool.
- iterating over the nodes for nodes config or metadata remembers unresponsive nodes
- Metadata status polls the known metadata role servers concurrently, respecting unreachable nodes flagged by prior connections
- overall CLI connect timeout is reduced to 3s (from 5s)
- we now print a heading for the Metadata section of `restatectl status` to visually separate it from the others
- general sprinkling of debug logging
Further work:
- update `get_latest_metadata` to gather `IdentResponse`s concurrently and cache them (so they can be reused between get nodes and logs)
- be smarter with contacting nodes based on …
=> [restatectl] Improve performance and information display with unprovisioned clusters or under partial node connectivity

crates/worker/src/partition/mod.rs, crates/worker/src/partition_processor_manager.rs
=> Trim gap encountered errors include LSN

crates/admin/protobuf/cluster_ctrl_svc.proto, crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/service.rs, crates/core/src/worker_api/partition_processor_manager.rs, crates/types/src/net/partition_processor_manager.rs, crates/worker/src/partition_processor_manager.rs, crates/worker/src/partition_processor_manager/message_handler.rs, server/tests/trim_gap_handling.rs, tools/restatectl/src/commands/snapshot/create_snapshot.rs
This enables the restatectl tool to print the minimum included LSN when ad-hoc snapshots are created.
This also enables the trim gap test to trim right up to the snapshotted LSN.
=> CreateSnapshot RPC returns min applied LSN

crates/admin/protobuf/cluster_ctrl_svc.proto, crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/core/src/worker_api/partition_processor_manager.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/snapshots.rs, crates/partition-store/src/tests/snapshots_test/mod.rs, crates/types/src/logs/mod.rs, crates/types/src/net/partition_processor_manager.rs, crates/worker/src/partition/snapshots/repository.rs, crates/worker/src/partition/snapshots/snapshot_task.rs, crates/worker/src/partition_processor_manager.rs, crates/worker/src/partition_processor_manager/message_handler.rs, server/tests/trim_gap_handling.rs, tools/restatectl/src/commands/snapshot/create_snapshot.rs
Follow up to https://github.com/restatedev/restate/pull/2743 adding explicit log ids to the CreateSnapshot response path - and adding an option for storing these in the snapshot metadata we publish to object stores.
In the future, only `PartitionStore::create_snapshot` needs to change to provide an explicit log id (of which presumably `PartitionStore` will be aware), if that differs from the `partition_id` from which it us currently derived.
=> Return explicit log id in CreatePartitionSnapshotResponse

tools/restatectl/src/commands/log/list_logs.rs, tools/restatectl/src/commands/node/list_nodes.rs, tools/restatectl/src/commands/node/mod.rs, tools/restatectl/src/commands/status.rs, tools/restatectl/src/connection.rs
This change improves the rendering of nodes during cluster provisioning.
Both the `status` and `nodes list` can now render a partial nodes list based on just the `GetIdentResponse`s received during the attempt to obtain metadata. If we detect that the metadata services are in provisioning status, this is a strong signal that the cluster as a whole may not be provisioned yet so we'll print a hint about `restatectl provision`.
```
❯ restatectl status -s node1.cluster.orb.local:5122,node2.cluster.orb.local:5122,node3.cluster.orb.local:5122
Error: Encountered multiple errors:
- http://node1.cluster.orb.local:5122/ -> status: Unavailable, message: "tcp connect error: deadline has elapsed", details: [], metadata: MetadataMap { headers: {} }
- http://node2.cluster.orb.local:5122/ -> status: …
```
=> [restatectl] Improve status display during cluster provisioning

crates/admin/protobuf/cluster_ctrl_svc.proto, crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/service.rs, tools/restatectl/src/commands/log/reconfigure.rs
Harden `restatectl reconfigure` and avoid sending full LogletParams
Summary:
- Arguments provided to this command (in case of replicated provider) act as "hints" to
the node to consider during replication. It still possible that the node decides to
use more nodes or different than the provided nodeset
- `sequencer` can also be a PlainNodeId
- Most arguments are optional in case previous loglet is a replicated loglet, Otherwise the user needs
to provide most arguments
=> Harden `restatectl reconfigure` and avoid sending full LogletParams

crates/types/src/nodes_config.rs, tools/restatectl/src/commands/replicated_loglet/storage_state.rs
Noticed the error is wrong while testing https://github.com/restatedev/documentation/pull/540. Also includes some opportunistic rustdoc cleanup.
=> Fix a typo in set_storage_state error text

crates/types/src/config/worker.rs
This reverts commit 33fd35e7ee877f216896200af6aa817142dd3eb6.
=> Revert "Set the default concurrent_invocations_limit to None"

crates/core/src/network/rpc_router.rs
=> Prevent overflowing durations when calculating remaining time

tools/restatectl/src/commands/replicated_loglet/list_servers.rs, tools/restatectl/src/commands/replicated_loglet/mod.rs, tools/restatectl/src/commands/replicated_loglet/storage_state.rs
This introduces the ability to set-storage-state on multiple node-ids at once, it'll also perform safety-check when switching to a storage-state that may cause the node to be excluded from new nodesets. The safety check validates that we can still generate valid nodesets when those nodes are excluded.
Example usage in comments.
```
```
=> [restatectl] set-storage-state supports multiple nodes and safety checking

.github/workflows/deps.yml
Rustup 1.28 has been released and it disables toolchain auto installation. See [rust-lang/rustup#3985], cargo-deny-action has released a fix on v2 at https://github.com/EmbarkStudios/cargo-deny-action/pull/92
=> [CI] Upgrade cargo-deny-action to fix rustup

crates/core/src/network/grpc/connector.rs, crates/core/src/network/grpc/mod.rs, crates/core/src/network/grpc/svc_handler.rs, crates/core/src/network/mod.rs, crates/core/src/network/transport_connector.rs, crates/node/src/network_server/grpc_svc_handler.rs, crates/node/src/network_server/service.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2817).
* #2820
* #2818
* __->__ #2817
=> Move NodeSvcHandle into core networking

crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/service.rs, crates/bifrost/src/bifrost.rs, crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/loglet.rs, crates/bifrost/src/loglet/loglet_tests.rs, crates/bifrost/src/loglet_wrapper.rs, crates/bifrost/src/providers/local_loglet/mod.rs, crates/bifrost/src/providers/memory_loglet.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/periodic_tail_checker.rs, crates/bifrost/src/read_stream.rs, crates/worker/src/partition/mod.rs, server/tests/replicated_loglet.rs, tools/restatectl/src/commands/log/dump_log.rs
Add FindTailAttr for configurable find_tail behavior
Summary:
FindTailAttr allows find_tail users to adjust durability and accuracy. Currently, two modes are supported:
Approximate: A fast check that usually returns immediately with the last known tail.
Durable (default): Ensures a reliable tail find.
Loglet implementations can choose to always run Durable find_tail.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2781).
* #2779
* #2755
* __->__ #2781
=> Add FindTailAttr for configurable find_tail behavior

crates/bifrost/src/providers/replicated_loglet/tasks/periodic_tail_checker.rs, crates/worker/src/metric_definitions.rs, crates/worker/src/partition/leadership/leader_state.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition_processor_manager.rs, server/tests/raft_metadata_cluster.rs, tools/restatectl/src/commands/partition/list.rs
PP <-> Bifrost lag observability
This PR improves only on the PP <-> Bifrost observability.
We already collect meterics for both PP and Bifrost but I think
those extra metrics can be useful
- Utilization of the PP requests queue. Once full
the PP will start dropping requests as 'Busy' and I thought
it's important to measure how utilized this queue is
- Commit to read latency of records. Measures the
latency between the moment a record is committed until
it's read by the PP
- LSN lag (applied to the log tail) This is also shown in `resatectl partition list`
Fixes #2756
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2755).
* #2779
* __->__ #2755
=> PP <-> Bifrost lag observability

crates/bifrost/src/providers/replicated_loglet/tasks/periodic_tail_checker.rs, crates/invoker-impl/src/lib.rs, crates/invoker-impl/src/metric_definitions.rs, crates/invoker-impl/src/quota.rs, crates/queue/src/segmented_queue.rs, crates/worker/src/metric_definitions.rs, crates/worker/src/partition/leadership/leader_state.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition_processor_manager.rs, server/tests/raft_metadata_cluster.rs, tools/restatectl/src/commands/partition/list.rs
Improve invoker observability
Add few extra metrics to measure number of queued commands,
and number of in flight invocation tasks
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2779).
* __->__ #2779
* #2755
=> Improve invoker observability

crates/admin/src/cluster_controller/service.rs, crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/digests.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/get_trim_point.rs, crates/bifrost/src/providers/replicated_loglet/tasks/repair_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/trim.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/grpc/connector.rs, crates/core/src/network/grpc/svc_handler.rs, crates/core/src/network/network_sender.rs, crates/core/src/network/networking.rs, crates/core/src/network/partition_processor_rpc_client.rs, crates/core/src/network/transport_connector.rs, crates/core/src/test_env.rs, crates/ingress-http/src/rpc_request_dispatcher.rs, crates/node/src/lib.rs, crates/node/src/network_server/service.rs
Most of the PR is mechanical, the highlights of the changes:
- Removes <T> from ConnectionManager.
- Remove redundant Metadata copies in Networking and ConnectionManager
- Use live configuration values for networking operations
This is a baby-step towards evolving this design towards a more ergonomic interface.
=> [Core] connection manager without TransportConnect

Cargo.lock, crates/core/Cargo.toml, crates/core/src/identification.rs, crates/core/src/lib.rs, crates/node/src/network_server/grpc_svc_handler.rs, crates/node/src/network_server/metrics.rs, crates/node/src/network_server/service.rs, crates/types/build.rs
This commit adds a very simple /health handler that returns 200 if the server is running. This allows to check whether the node server is running.
This fixes #2461.
=> Add /health handler to node server

crates/core/src/protobuf.rs, tools/restatectl/src/commands/metadata/get.rs, tools/restatectl/src/commands/metadata/mod.rs, tools/restatectl/src/commands/metadata/patch.rs, tools/restatectl/src/commands/node/disable_node_checker.rs, tools/restatectl/src/commands/node/remove_nodes.rs, tools/restatectl/src/commands/replicated_loglet/storage_state.rs, tools/restatectl/src/connection.rs
Use the metadata proxy in restatectl
Summary:
Always use the metadata proxy in restatectl instead
of the metadata client. This way metadata operation
is always agnostic to the actual store kind that is
being used by the server(s)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2825).
* __->__ #2825
* #2848
=> Use the metadata proxy in restatectl

charts/restate-helm/README.md, charts/restate-helm/replicated-values.yaml, charts/restate-helm/templates/service.yaml, charts/restate-helm/templates/servicemonitor.yaml, charts/restate-helm/templates/statefulset.yaml
1. pods need to advertise their own ip
2. pods need a way of reaching 'another' restate server so they can bootstrap into the metadata cluster. we could hardcode restate-0 headless dns name, but http://restate:5122/ (a cluster ip that randomly picks an underlying healthy restate pod to route to) seems to work fine
3. pods need to run the logserver and metadata-server roles and have the correct metadata server type set
4. pods need to have auto provision turned off. technically its possible to have it turned on and just set up with one node before turning it off and scaling, and technically its also possible to have it be set to true for restate-0 only, but really its a lot easier if its just off.
=> Add helm example for replicated cluster

crates/admin/protobuf/cluster_ctrl_svc.proto, crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/service.rs, crates/admin/src/cluster_controller/service/state.rs, crates/core/src/worker_api/partition_processor_manager.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/partition_store_manager.rs, crates/partition-store/src/snapshots.rs, crates/partition-store/src/tests/snapshots_test/mod.rs, crates/types/src/net/partition_processor_manager.rs, crates/worker/src/partition/snapshots/snapshot_task.rs, crates/worker/src/partition_processor_manager.rs, crates/worker/src/partition_processor_manager/message_handler.rs, server/tests/trim_gap_handling.rs, tools/restatectl/src/commands/log/describe_log.rs, tools/restatectl/src/commands/snapshot/create_snapshot.rs
I've deferred the following work for future PRs:
- Better safety shared with auto-trim - this is currently as safe as the cluster auto-trim, in the sense that we know that we've got a certain archived LSN for a given partition before we would proceed to trim - and then only up to the minimum snapshotted LSN
- Backoff and retry the applied LSN to target LSN comparison if we're close
- We're retry-safe but we don't re-join a pending export snapshot task; while that's running retries will get a different error indicating snapshot is underway
- https://github.com/restatedev/restate/issues/2852
It is an error to try to create a snapshot when the applied LSN is below target LSN. Repeating the call with the same (or lower) LSN will return the last known snapshot now:
```
❯ rc snap …
```
=> Extend CreatePartitionSnapshot operation to support target LSN + trim

deny.toml
https://github.com/stepancheg/rust-protobuf/issues/749 No fix yet. The issue would impact our metadata-server if access by untrusted sources (stackoverflow when parsing deeply nested messages)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2868).
* #2867
* #2860
* #2846
* __->__ #2868
=> CI to disable protobuf-rs on cargo deny

crates/local-cluster-runner/src/node/mod.rs
Dropping the file alone, does not guarantee that the file content is written to disk and the file being closed immediately. If the config file is not written when starting the Restate process, then it will start with the default configuration which causes the raft_metadata_cluster_chaos_test to fail every now and then.
This fixes #2828.
=> Flush config file to disk before starting Restate process

.config/nextest.toml
This will help us debug hanging local cluster tests because it will force the printing of stderr/logs of the node processes when terminating the tests.
This PR should help us debug #2862.
=> Set an upper bound of 180s for the runtime tests to complete

crates/worker/src/partition/state_machine/entries/mod.rs, deny.toml
Only print ignoring effects on debug level since it's not really actionable for users any way.
=> Reduce noise level of state_machine

crates/object-store-util/src/lib.rs
It's easy to miss a warning in the startup logs; since this could lead to data loss, I thought it's better to complain loudly and stop:
```
~/restate/restate chore/support-global-aws-env-defaults* ❯ AWS_ENDPOINT_URL_S3=http://minio:9000 RESTATE_WORKER__SNAPSHOTS__DESTINATION=s3://bucket/snapshots restate-server --default-num-partitions 1
...
2025-03-10T12:18:32.403583Z INFO restate_server
Starting Restate Server 1.2.2-dev (debug) (7eeb6143c aarch64-apple-darwin 2025-03-10)
node_name: "Pavels-MacBook-Pro-2.local"
config_source: [default]
base_dir: /Users/pavel/restate/restate/restate-data/Pavels-MacBook-Pro-2.local/
on main
2025-03-10T12:18:32.591063Z ERROR restate_server
Restate application failed
error: building worker failed: failed creating worker: failed constructing partition …
```
=> Treat invalid HTTP S3 endpoint overrides as a startup configuration error

crates/object-store-util/src/lib.rs
Fixes an error introduced by #2858 which only recognizes the global AWS_ALLOW_HTTP setting, and not the snapshots/metadata store client-specific config section keys.
C/f https://github.com/restatedev/e2e-verification-runner/actions/runs/13801005766/job/38603269652
=> Fix allow-HTTP logic

crates/metadata-server/src/raft/network/networking.rs
For logging purposes we try to obtain the result of the connection attempt in a synchronous function if the connection attempt task has finished. Unfortunately, we cannot rely on TaskHandle::is_finished for task_handle.now_or_never() to always return Some(...). The problem is that the underlying Tokio JoinHandle participates in the cooperative task scheduling and if we ran out of budget, then it would return Poll::Pending. That's why we ignore the result in this case and continue.
This fixes #2879.
=> Don't panic if we cannot obtain connection attemp result

.github/workflows/ci.yml, crates/admin/src/schema_registry/error.rs, crates/admin/src/schema_registry/mod.rs, crates/admin/src/schema_registry/updater.rs, crates/admin/src/service.rs, crates/ingress-kafka/src/consumer_task.rs, crates/ingress-kafka/src/dispatcher.rs, crates/ingress-kafka/src/subscription_controller.rs, crates/node/src/roles/admin.rs, crates/types/src/config/ingress.rs, tools/xtask/src/main.rs
This PR should still allow to skip from 1.1 straight to 1.3 even when using kafka, but it won't allow to rollback from 1.3 to 1.2 after registering a new kafka subscription in 1.3
=> Remove `experimental_feature_kafka_ingress_next`

.github/workflows/ci.yml, crates/types/src/config/worker.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/idempotency.rs, crates/worker/src/partition/state_machine/tests/workflow.rs
With this PR it should still be possible to skip from 1.1 straight to 1.3, but it won't allow 1.3 to be rolled back to 1.1 because it would break idempotent requests created in 1.3
=> Remove `ExperimentalFeature::DisableIdempotencyTable`

crates/partition-store/proto/dev/restate/storage/v1/domain.proto, crates/partition-store/src/protobuf_types.rs
Reverts restatedev/restate#2872
To merge for 1.3
=> Revert "Fix GenerationalNodeId should still be written."

.github/workflows/ci.yml, cli/src/clients/datafusion_helpers/mod.rs, cli/src/ui/invocations.rs, crates/invoker-api/src/handle.rs, crates/invoker-api/src/lib.rs, crates/invoker-impl/src/input_command.rs, crates/invoker-impl/src/lib.rs, crates/partition-store/proto/dev/restate/storage/v1/domain.proto, crates/partition-store/src/invocation_status_table/mod.rs, crates/partition-store/src/protobuf_types.rs, crates/partition-store/src/tests/invocation_status_table_test/mod.rs, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-query-datafusion/src/invocation_status/row.rs, crates/storage-query-datafusion/src/invocation_status/schema.rs, crates/types/src/config/worker.rs, crates/worker/src/partition/cleaner.rs, crates/worker/src/partition/leadership/leader_state.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/state_machine/actions.rs, crates/worker/src/partition/state_machine/lifecycle/cancel.rs, crates/worker/src/partition/state_machine/lifecycle/resume.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/kill_cancel.rs
This was supposed to be used for restart, but as described here https://github.com/restatedev/restate/issues/2890#issuecomment-2717274073 we now got a new solution.
First part of #2890
=> Removed InvocationStatus::Killed

cli/src/commands/services/status/agg_status.rs, cli/src/commands/services/status/detailed_status.rs, cli/src/commands/services/status/mod.rs
fix: https://github.com/restatedev/restate/issues/1764
```
Arguments:
[SERVICE]
Service name, prints all services if omitted
Options:
--locked-keys-limit <LOCKED_KEYS_LIMIT>
[default: 5]
-v, --verbose...
Increase logging verbosity
--locked-key-held-threshold-second <LOCKED_KEY_HELD_THRESHOLD_SECOND>
[default: 5]
```
=> feat(1764): add locked key threshold seconds option

.github/workflows/cla.yml, docs/dev/cla.md
This commit adds a Github workflow that enforces the signing of our CLA
before being able to merge the PR. This PR is based on #2902.
This fixes https://github.com/restatedev/restate/issues/2901.
=> Add automatic contributor license agreement signing 

.github/workflows/ci.yml
=> Disable running Jepsen tests on PR when PR originates from a fork

.github/workflows/ci.yml
This avoids the dynamic bucket showing up in the stack as to-be-deleted, even though it was never created by us.
=> Set reusable cluster bucket for destroy-cluster step

crates/core/src/metadata_store/providers/objstore/object_store_version_repository.rs, crates/object-store-util/src/lib.rs, crates/types/src/config/common.rs, crates/types/src/config/object_store.rs, crates/types/src/config/worker.rs, crates/types/src/retries.rs, crates/worker/src/partition/snapshots/repository.rs
Expose the object store retry policy to be configurable via Restate config.
This change also revises the default object store max attempts from 8 to 10, to be more in line with ObjectStore's own defaults. We may want to use different defaults for different parts of the config however - e.g. the default snapshot retry policy might be quite different from metadata or other use cases.
This was [recently exposed by our e2e tests failing](https://github.com/restatedev/e2e-verification-runner/actions/runs/13578683032/job/37960529900#step:5:305) due to slow minio startup; the default retry policy gives up very quickly: 
> Error after 8 retries in 1.726268511s, max_retries:8, 
---
**Testing**
Defaults:
```
% restate-server --dump-config
...
[worker.snapshots.object-store-retry-policy]
type = …
```
=> Add support for configuring object store access retry policies

crates/bifrost/src/bifrost_admin.rs, crates/core/src/metadata_store.rs, crates/log-server/src/service.rs, crates/metadata-server/src/grpc/client.rs, crates/node/src/lib.rs, crates/types/src/metadata.rs, server/tests/raft_metadata_cluster.rs
The RetryingMetadataStoreClient automatically retries retryable errors according to the configured RetryPolicy.
=> Introduce RetryingMetadataStoreClient

crates/admin/src/cluster_controller/logs_controller.rs, crates/bifrost/src/providers/replicated_loglet/tasks/check_seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/digests.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/get_trim_point.rs, crates/bifrost/src/providers/replicated_loglet/tasks/repair_tail.rs, crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/bifrost/src/providers/replicated_loglet/tasks/trim.rs, crates/bifrost/src/service.rs, crates/bifrost/src/watchdog.rs, crates/ingress-kafka/src/subscription_controller.rs, crates/invoker-impl/src/lib.rs, crates/rocksdb/src/db_manager.rs, crates/worker/src/partition_processor_manager.rs
Assign task names to JoinSet tasks. Unfortunately, it does not solve the problem of init tasks being reported as continuously polled via tokio-console but it's an improvement anyway.
=> Assign task names to JoinSet tasks

crates/core/src/task_center/handle.rs
When using TaskCenter::run_sync it can happen that we are not running in a Tokio task. In that case tokio::runtime::Handle::current panics. Therefore, we use the default Tokio runtime when there is no current handle. This fixes the partition-store benchmarks.
=> Update TaskCenter::run_sync docs to reflect panic conditions

crates/types/src/config/cli_option_overrides.rs
Currently when we start restate-server with `--help`，the `location` args output is:
```
```
it's `newline` is missing, add `verbatim_doc_comment` to keep it, now output is:
```
- `us-west` -- the node is in the `us-west` region.
- `us-west.a1` -- the node is in the `us-west` region and in the `a1` zone.
- `` -- [default] the node is in the default location
```
=> chore(*): add location args examples with newline

Cargo.lock, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/core/src/metadata.rs, crates/core/src/metadata/manager.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/error.rs, crates/core/src/network/io/egress_sender.rs, crates/core/src/network/message_router.rs, crates/core/src/network/mod.rs, crates/core/src/network/networking.rs, crates/core/src/network/protobuf.rs, crates/core/src/network/rpc_router.rs, crates/core/src/network/transport_connector.rs, crates/core/src/network/types.rs, crates/log-server/src/loglet_worker.rs
Removes WeakConnection as it's not needed after having tighter control over the egress sender's lifecycle. This is a critical step towards simpler interfaces. It also gets us closer to the ability of sending responses/messages during drain. The behaviour of the reactor and drain will change in the next set of PRs.
- Removes extra indirections, upgrades, etc.
- Minor changes to the MessageRouter, more to come.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2894).
* #2907
* __->__ #2894
=> [Core] Remove WeakConnection

Cargo.lock, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/core/protobuf/restate/network.proto, crates/core/src/metadata.rs, crates/core/src/metadata/manager.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/error.rs, crates/core/src/network/io/egress_sender.rs, crates/core/src/network/io/mod.rs, crates/core/src/network/io/reactor.rs, crates/core/src/network/message_router.rs, crates/core/src/network/mod.rs, crates/core/src/network/net_util.rs, crates/core/src/network/networking.rs, crates/core/src/network/protobuf.rs, crates/core/src/network/rpc_router.rs, crates/core/src/network/tracking.rs, crates/core/src/network/transport_connector.rs, crates/core/src/network/types.rs, crates/core/src/task_center.rs, crates/log-server/src/loglet_worker.rs
This allows the reactor to be used without connection manager
Note that the mechanics of how we connect to peers will change in the future as well (including preemption).
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2907).
* __->__ #2907
* #2894
=> New connection reactor implementation

.github/workflows/ci.yml
You can still run Jepsen using the Docker artifact produced by the PR branch via the restatev/jepsen workflow.
To trigger a Jepsen test run of an open PR, you can execute the test flow manually from https://github.com/restatedev/jepsen/actions/workflows/jepsen.yml - as long as the Docker image tarball artifact is still available, just entering the PR number will suffice.
=> Don't run Jepsen tests on PR branches

Cargo.lock, crates/storage-query-datafusion/Cargo.toml, crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/lib.rs, crates/storage-query-datafusion/src/node/mod.rs, crates/storage-query-datafusion/src/node/row.rs, crates/storage-query-datafusion/src/node/schema.rs, crates/storage-query-datafusion/src/node/table.rs
Datafusion nodes table
Summary:
Expose nodes configuration over datafusion
> NOTE: This does not show the liveness of nodes yet (observed node status)
which will be eventually added as a separate table
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2913).
* #2945
* #2944
* #2938
* #2925
* #2924
* __->__ #2913
=> Datafusion nodes table

Cargo.lock, crates/storage-query-datafusion/Cargo.toml, crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/lib.rs, crates/storage-query-datafusion/src/partition/mod.rs, crates/storage-query-datafusion/src/partition/row.rs, crates/storage-query-datafusion/src/partition/schema.rs, crates/storage-query-datafusion/src/partition/table.rs
Datafusion partitions table
Summary:
Expose the partitions metadata over datafusion
> NOTE: This does not show the status of the partitions yet (observed partition status)
which will be eventually added as a sepaerate table
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2924).
* #2945
* #2944
* #2938
* #2925
* __->__ #2924
=> Datafusion partitions table

benchmarks/benches/throughput_sequential.rs, server/tests/cluster.rs, server/tests/raft_metadata_cluster.rs
The test creates a 3 node Restate cluster using the replicated loglet and the replicated metadata store. It registers the mock service endpoint and then continously invokes the service while the test kills a random Restate node every second.
=> Add simple chaos cluster test

charts/restate-helm/README.md, charts/restate-helm/replicated-values.yaml, charts/restate-helm/templates/service.yaml, charts/restate-helm/templates/statefulset.yaml, charts/restate-helm/values.yaml
W/o stable network identifier, it is not possible that the replicated metadata cluster survives a crash of multiple pods (N/2 + 1) because they would be restarted with a different IP which makes them no longer reachable by the other nodes (based on the advertised address stored before in the NodesConfiguration). As a result, the metadata cluster would lose write availability because it can no longer form a majority quorum.
To solve this problem, we are now using the stable network identifier provided by the stateful set. It requires to run a headless service with the same name as the one configured as the serviceName in the stateful set spec. Now, all Restate pods are started with this stable network identifier as their advertised address. Additionally, we set the podManagementPolicy to …
=> Use stable network identifier when starting a K8s based Restate cluster

crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/lib.rs, crates/storage-query-datafusion/src/log/mod.rs, crates/storage-query-datafusion/src/log/row.rs, crates/storage-query-datafusion/src/log/schema.rs, crates/storage-query-datafusion/src/log/table.rs
Datafusion logs table
Summary:
Expose the logs metadata over datafusion
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2925).
* #2945
* #2944
* #2938
* __->__ #2925
=> Datafusion logs table

Cargo.lock, cli/Cargo.toml, crates/admin/protobuf/cluster_ctrl_svc.proto, crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/service.rs, crates/admin/src/storage_query/mod.rs, crates/admin/src/storage_query/query.rs, crates/node/src/roles/admin.rs, crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/lib.rs, crates/storage-query-datafusion/src/log/mod.rs, crates/storage-query-datafusion/src/log/row.rs, crates/storage-query-datafusion/src/log/schema.rs, crates/storage-query-datafusion/src/log/table.rs, tools/restatectl/Cargo.toml, tools/restatectl/src/app.rs, tools/restatectl/src/commands/mod.rs, tools/restatectl/src/commands/sql.rs
Cluster controller `query` gRPC handler
Summary:
- Add a `query` grpc handler for cluster controller service to query
cluster state with datafusion sql.
- Expose the functionality via the `restatectl sql` command
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2938).
* #2945
* #2944
* __->__ #2938
* #2925
=> Cluster controller `query` gRPC handler

crates/types/src/identifiers.rs
Fix: https://github.com/restatedev/restate/issues/2492
After fix:
```
curl "http://localhost:9070/deployments/dp_11nGQpCRmau6ypL82KH2TnP"
{"message":"The requested deployment 'dp_11nGQpCRmau6ypL82KH2TnP' does not exist","restate_code":null}
curl "http://localhost:9070/deployments/dp_11nGQpCRmau6ypL82KH2TnP123456"
Invalid URL: bad length
```
=> fix(2492): report error when resource id is too long

crates/core/src/task_center/handle.rs
Letting Tokio tasks inherit the span of the spawning task messes up the
reporting of Tokio task metrics when using tokio-console since it seems
to rely on the tracing information. That's why this commit removes the
in_current_span() instrumentation for child, unmanaged and local tasks.
=> Don't let Tokio tasks inherit span of spawning task

crates/metadata-server/src/raft/kv_memory_storage.rs, crates/metadata-server/src/raft/server.rs
During a leadership change a new leader might not have fully re-established what the latest commit index is. To do this, a new leader upon winning the leadership writes an empty entry. In order to avoid stale reads during this time, read-index requests are silently ignored by RawNode. If this is not correctly handled, it can lead to unanswered metadata requests. To solve the problem, we are comparing the previous pending reads and ready reads with the same values after calling RawNode::read_index. If they are still the same, then we faill the request with RequestError::Unavailable (as if we aren't the leader yet). It's then the responsibility of the client to retry the operation.
This fixes #2947.
=> Fail read-only requests that get silently dropped by Raft

crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service.rs, crates/core/src/metadata/manager.rs, crates/core/src/network/partition_processor_rpc_client.rs, crates/core/src/partitions.rs, server/tests/cluster.rs
The Scheduler updates the PartitionTable whenever it updates the partition placement. Once it decides on a new PartitionTable, it tries to store it in the metadata store. If the write fails because of a precondition violation, we were accidentally publishing the rejected PartitionTable. This can lead to cluster nodes operating on different partition tables. One symptom of it is that an ingress becomes unresponsive because the CC selected a different leader than what the ingress believes is the current leader. Therefore, the ingress sends the ingress invocation to the wrong partition processor where it gets rejected.
Additionally, to speed up convergence when detecting a concurrent write to the partition table, we are trying to sync the metadata based on the expected version + 1 instead of …
=> Only update metadata manager if metadata was actually written to the metadata store

crates/core/protobuf/node_ctl_svc.proto, tools/restatectl/src/commands/node/list_nodes.rs
After fix:
```
❯ restatectl nodes ls
The cluster metadata service was unavailable but the following node(s) from the address list responded directly
NODE  GEN  NAME  ADDRESS                 ROLES
n/a        -     http://localhost:5122/  worker
Error: Could not retrieve cluster metadata. Has the cluster been provisioned yet?
```
Fixes #2946
=> Fix panic in restatectl listing nodes outside cluster

benchmarks/src/lib.rs, server/tests/cluster.rs, server/tests/trim_gap_handling.rs, tools/mock-service-endpoint/src/listener.rs, tools/mock-service-endpoint/src/main.rs
This commit hardens the tests that depend on the mock service endpoint by adding a callback to await until the mock service endpoint has bound to a socket address.
=> Harden tests that depend on mock service endpoint

crates/local-cluster-runner/src/node/mod.rs, crates/types/src/config/common.rs, crates/types/src/config/mod.rs, crates/types/src/config_loader.rs, crates/types/src/net/mod.rs
This change updates the implied bind-address logic to default to 5122 if only a hostname is
specified, without a protocol or port.
In cases where a protocol is specified, the specific protocol determines the actual bind port - we
print a startup warning when this happens as this might be surprising. HTTPS is an exception since
restate-server does not natively support this; it's not an error to advertise an https:// address
but it's probably a misconfiguration not to specify a bind-address also.
Fixes #2940
---
Tests are a bit ugly but I think this is much more sane now:
```toml
advertised-address = "127.0.0.1"               # will bind to :5122
advertised-address = "localhost"               # will bind to :5122
advertised-address = "http://127.0.0.1"        # will bind to :80 - and print …
```
=> Default bind port to 5122 when inferring from ambiguous advertised-address

crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/bifrost/src/loglet/error.rs, crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs, crates/bifrost/src/providers/replicated_loglet/replication/checker.rs, crates/core/build.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection/throttle.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/error.rs, crates/core/src/network/grpc/connector.rs, crates/core/src/network/grpc/svc_handler.rs, crates/core/src/network/handshake.rs, crates/core/src/network/io/egress_sender.rs, crates/core/src/network/io/reactor.rs, crates/core/src/network/mod.rs, crates/core/src/network/networking.rs, crates/core/src/network/rpc_router.rs, crates/core/src/network/transport_connector.rs, crates/core/src/network/types.rs, crates/core/src/task_center.rs, crates/core/src/task_center/task_kind.rs, crates/core/src/test_env.rs, crates/log-server/src/loglet_worker.rs, crates/log-server/src/network.rs, crates/types/src/nodes_config.rs, crates/types/src/retries.rs, crates/worker/src/lib.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs, tools/restatectl/src/commands/node/disable_node_checker.rs
- Connection attempt throttling with exponential backoff
- In-flight connection attempts are auto-coalesced for (managed) connections
- Major cleanup of network error types
- Uses Forward connections by default (1.2 will treat this as bidirectional which is okay)
- Reduces default number of connections to 3 (since we'll have 3 in each direction)
- Better logging of connection lifecycle events
- Uses `NodeIsGone` state in situations where we know the node is never coming back (node was superceeded or deleted)
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2939).
* #2961
* __->__ #2939
=> [Core] Connection throttling and coalescing

Cargo.lock, tools/restatectl/Cargo.toml, tools/restatectl/src/lambda.rs, tools/restatectl/src/lib.rs, tools/restatectl/src/main.rs
This makes it possible to literally use restatectl as the bootstrap binary for a lambda function, such that you can expose its operations over lambda without having to deploy any other code.
=> restatectl built in lambda handler

crates/node/src/network_server/metrics.rs, crates/tracing-instrumentation/src/prometheus_metrics.rs
Fix: https://github.com/restatedev/restate/issues/2716
After this:
```
curl "http://127.0.0.1:5122/metrics" | grep -v cluster | grep -v '#' | grep -v '^$'
```
show nothing. Some example metrics output:
```
restate_rocksdb_num_immutable_mem_table_count{cluster_name="localcluster",node_name="MRXNC2FQJ9",db="log-server",cf="metadata"} 0
restate_partition_record_committed_to_read_latency_seconds{cluster_name="localcluster",node_name="MRXNC2FQJ9",partition="9",quantile="0.5"} 0.0010970834519333842
```
=> fix(2716): add cluster name and node name to all metrics

crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/admin/src/cluster_controller/service.rs, crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/lib.rs, crates/storage-query-datafusion/src/node_state/mod.rs, crates/storage-query-datafusion/src/node_state/row.rs, crates/storage-query-datafusion/src/node_state/schema.rs, crates/storage-query-datafusion/src/node_state/table.rs, crates/types/src/cluster/cluster_state.rs
Datafusion node_state table
Summary:
The `node_state` reflects the actual observed node state
as seen by this cluster controller node
A quick view of the cluster node can be retrieved as
```
restatectl sql "select n.*,s.* from nodes as n left join node_state s on n.plain_node_id=s.plain_node_id order by n.plain_node_id"
PLAIN_NODE_ID  GEN_NODE_ID  NAME    ADDRESS                 LOCATION  HAS_ADMIN_ROLE  HAS_WORKER_ROLE  HAS_METADATA_SERVER_ROLE  HAS_LOG_SERVER_ROLE  HAS_INGRESS_ROLE  STORAGE_STATE  METADATA_SERVER_STATE  PLAIN_NODE_ID  GEN_NODE_ID  STATUS  UPTIME  LAST_SEEN_TS   LAST_ATTEMPT_TS
N1             N1:31        node-1  http://127.0.0.1:5122/            true            true             true                      true                 false             read-write     member …
```
=> Datafusion node_state table

crates/core/src/metadata.rs, crates/core/src/metadata/manager.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs, crates/core/src/network/io/egress_sender.rs, crates/core/src/network/io/mod.rs, crates/core/src/network/io/reactor.rs, crates/core/src/network/mod.rs, crates/core/src/network/types.rs
This removes the validation on the "accept" path. At the moment we reject connections from node ids that we don't fully recognize. This removes this check in favour of:
1. Rejecting connections from nodes at which we believe have been preempted in the past (either from nodes config, or from our observations)
2. Letting nodes send us their version of nodes configuration via metadata sync mechanism
With this change, we'll use the metadata version information exchanged in hello/welcome message to initiate the metadata sync from this peer. The change to use `UnboundedEgressSender` ensures that we won't lose those requests if the bounded channel is too small. Additionally, it's aligned with upcoming changes in network API design.
```
```
---
[//]: # (BEGIN SAPLING …
=> [Core] Allow unknown/future nodes to connect to us

crates/metadata-server/src/raft/network/connection_manager.rs
This commit prevents a node from panicking if a Raft metadata node receives messages that were destined for a different node. Instead, we are terminating the connection now. The problem can occur if one adds a new node to the cluster that is reusing an existing address.
Hopefully, we can remove the Raft specific networking component once the network stack rework has been completed.
This fixes #2963.
=> Don't panic node on incorrectly destined Raft packages

crates/types/src/logs/builder.rs
Currently we can thrash the log version when trying to trim the same lsn repeatedly; as long as that lsn is inside an untrimmed segment, we will keep doing bifrost_config writes, with the same data.
~As another nice to have, lets use ordered map for the logs, so that the serialised logs is an ordered array instead of a random array on every update.~
=> Avoid unnecessary log rewrites

Cargo.lock, crates/bifrost/src/error.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/core/Cargo.toml, crates/core/src/network/connection.rs, crates/core/src/network/grpc/connector.rs, crates/core/src/network/grpc/svc_handler.rs, crates/core/src/network/net_util.rs, crates/core/src/network/transport_connector.rs, crates/log-server/src/service.rs, crates/types/src/logs/builder.rs, crates/types/src/logs/metadata.rs, crates/types/src/nodes_config.rs, tools/restatectl/src/commands/node/disable_node_checker.rs, tools/restatectl/src/commands/replicated_loglet/mod.rs, workspace-hack/Cargo.toml
This front-loads necessary work to allow future versions to set a chain to be permanently sealed. This is currently not used and in v1.3, restate will respect if a chain is sealed but it'll not attempt to seal a chain. This work is intended to ensure v1.3 doesn't clobber this field if written by future versions.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2993).
* __->__ #2993
* #2984
* #2860
=> [Bifrost] Front-loading serde work for sealed chains

Cargo.lock, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/core/Cargo.toml, crates/core/src/network/connection.rs, crates/core/src/network/grpc/connector.rs, crates/core/src/network/grpc/svc_handler.rs, crates/core/src/network/net_util.rs, crates/core/src/network/transport_connector.rs, crates/log-server/src/service.rs, crates/types/src/nodes_config.rs, tools/restatectl/src/commands/node/disable_node_checker.rs, tools/restatectl/src/commands/replicated_loglet/mod.rs, workspace-hack/Cargo.toml
This introduces a new storage state "gone" that's logically equivalent to read-only in this release. It's not meant to be used until v1.4 is released, so avoid clobbering by previous versions.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2984).
* #2993
* __->__ #2984
* #2860
=> [LogServer] Introduce "Gone" storage state

scripts/loadtest-environment/README.md, scripts/loadtest-environment/lib/loadtest-environment-stack.ts
The grafana node cloud-init script doesn't work correctly, but running `/var/lib/cloud/instance/scripts/part-002` by hand once will fix it for now.
=> Add basic Grafana + Prometheus cloud init script

crates/invoker-impl/src/invocation_task/service_protocol_runner_v4.rs
Child calls should be in a parent relationship with their originating invocation and not only be linked to each other. This makes the traces more meaningful.
=> Establish parent relationship between an invocation and child calls

crates/log-server/src/rocksdb_logstore/builder.rs, crates/partition-store/src/partition_store.rs
In benchmarks, zstd added ~2-3% CPU but cut disk throughput by 50% and 30-40% less IOPS. It's a good trade-off for our use case. Additionally, this enables rocksdb to perform "trivial move" compactions across all levels.
=> [RocksDB] Use zstd compression for all levels

crates/service-client/src/lambda.rs
Currently there are multiple layers of retries, one inside the service client, then again at the invocation level. This differs from HTTP and is unnecessary.
=> Avoid AWS lambda retries

Cargo.lock, Cargo.toml, crates/queue/Cargo.toml, crates/types/Cargo.toml, crates/types/src/storage.rs, crates/types/src/storage/decode.rs, crates/types/src/storage/encode.rs
Adds support for decoding bincode 2.0 (it's finally released) and json. Encoding is still with the normal flexbuffers but this enables v1.3 to decode those in the future.
Also removed some unnecessary checks that were meaningful when Encode/Decode traits were not dyn-compatible. Right now, we only accept BytesMut.
For all codec types, deserialization requires contiguous buffers which is already the case for rocksdb slices and our network message decoding. In the future, the API will be updated to reflect this.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3007).
* #3031
* #3030
* #3029
* #3028
* __->__ #3007
=> [Storage] Forward compatibility with other codecs

Cargo.lock, Cargo.toml, crates/queue/Cargo.toml, crates/types/Cargo.toml, crates/types/src/nodes_config.rs, crates/types/src/storage.rs, crates/types/src/storage/decode.rs, crates/types/src/storage/encode.rs
This fixes a bug at which we didn't correctly remove the deleted node names from the lookup table. The lookup table will grow unboundedly and in theory it can prevent the node names from being reused after a node has been deleted from config.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3028).
* #3031
* #3030
* #3029
* __->__ #3028
* #3007
=> Allow deleted node names to be reused

Cargo.lock, Cargo.toml, crates/queue/Cargo.toml, crates/types/Cargo.toml, crates/types/src/nodes_config.rs, crates/types/src/storage.rs, crates/types/src/storage/decode.rs, crates/types/src/storage/encode.rs
This is the bare minimum to allow v1.3 from clobbering by future versions' RMW nodes config updates. The fingerprint will be a simple non-zero random numeric value. Zero is reserved to indicate that the value is unset/none without occupying extra space for the tag.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3029).
* #3031
* #3030
* __->__ #3029
* #3028
* #3007
=> Forward compatibility support for cluster_fingerprint

Cargo.lock, Cargo.toml, crates/bifrost/src/providers/replicated_loglet/metric_definitions.rs, crates/core/src/network/grpc/connector.rs, crates/invoker-impl/src/lib.rs, crates/invoker-impl/src/metric_definitions.rs, crates/invoker-impl/src/quota.rs, crates/queue/Cargo.toml, crates/types/Cargo.toml, crates/types/src/nodes_config.rs, crates/types/src/storage.rs, crates/types/src/storage/decode.rs, crates/types/src/storage/encode.rs
Now we are reporting the concurrency limits and the available slots correctly
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3031).
* __->__ #3031
* #3030
* #3029
* #3028
* #3007
=> Correctly report invoker concurrency limits

cli/src/clients/datafusion_helpers/v2.rs
ServiceStatusQueryResult expects a target_service_name and target_handler_name field to be present for deserialization.
=> Fix names of columns to align with ServiceStatusQueryResult

cli/src/commands/whoami.rs
Fix: https://github.com/restatedev/restate/issues/2955
After fix:
```
Git SHA              9c28cba6
Git Commit Date      2025-03-20
Git Commit Branch    fix-2955
❌ Maybe cannot connect to Admin Service 'http://localhost:9070/':
>> Unable to connect to the Restate server 'http://localhost:9070/'. Please make sure that it is running and reachable.
```
=> fix(2955): report err when cannot connect to admin service

crates/futures-util/src/overdue.rs
Under extreme load, the deadline might have already passed by the time we schedule the timer, in this case, we must wake up the task again immediately to avoid being stuck for long time.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3057).
* #3059
* #3058
* __->__ #3057
=> [fix] Fix `overdue` not being woken up under extreme load conditions

crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/provider.rs, crates/bifrost/src/service.rs, crates/bifrost/src/watchdog.rs, crates/core/src/task_center.rs, crates/core/src/task_center/task_kind.rs, crates/futures-util/src/overdue.rs, crates/log-server/src/loglet_worker.rs, crates/log-server/src/network.rs, crates/log-server/src/rocksdb_logstore/writer.rs
This PR is another step towards better graceful shutdown. We'll ask Bifrost's watchdog to shutdown before we terminate connections to give it a chance to cleanly seal all local sequencers. This also fixes a bug where the rocksdb writer might get terminated before the loglet workers, causing the loglet workers to spew errors on shutdown and not cleanly draining up.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3058).
* #3059
* __->__ #3058
* #3057
=> [Bifrost] auto-seal sequencers on graceful shutdown

crates/admin/src/cluster_controller/scheduler.rs, crates/node/src/lib.rs, crates/node/src/network_server/grpc_svc_handler.rs, crates/types/src/config/admin.rs, crates/types/src/config/bifrost.rs, crates/types/src/config/common.rs, crates/types/src/config/mod.rs, crates/types/src/logs/metadata.rs, crates/types/src/partition_table.rs, crates/types/src/replication/replication_property.rs, server/tests/cluster.rs, server/tests/trim_gap_handling.rs, tools/restatectl/src/main.rs
Default global replication property
Summary:
A default global replication property can be used for both
logs and partition replication.
The user still can fine tune his replication property for both logs
and partition as needed
We also deprecation the option to set partitin replication to `everywhere`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3025).
* #3001
* __->__ #3025
=> Default global replication property

crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/service.rs, crates/core/protobuf/node_ctl_svc.proto, crates/local-cluster-runner/src/node/mod.rs, crates/node/src/network_server/grpc_svc_handler.rs, crates/types/src/protobuf.rs, server/tests/cluster.rs, server/tests/trim_gap_handling.rs, tools/restatectl/src/commands/config/set.rs, tools/restatectl/src/commands/provision.rs
Properly handle unset partition-replication in restatectl
Summary:
Ensure correct behavior when the partition-replication flag is omitted in both provision and config set.
Previously, an unset flag defaulted to everywhere, which was incorrect.
- In provision, if the flag is omitted, the cluster defaults to the configured default-partition-replication.
The user can override this by specifying a valid replication property.
- In config set, omitting the flag leaves the current cluster configuration unchanged.
=> Properly handle unset partition-replication in restatectl

crates/worker/src/partition/snapshots/snapshot_task.rs, crates/worker/src/partition_processor_manager.rs
This commit also limits the maximum number of in-flight _scheduled_ snapshot requests to 4.
This PR precedes https://github.com/restatedev/restate/pull/3061, see for testing notes.
=> Jitter scheduled snapshot creation by 0-10s

crates/worker/src/partition/snapshots/repository.rs, crates/worker/src/partition_processor_manager.rs
This change stops partition processors from always creating a snapshot on startup regardless of how close their applied LSN is to the archived LSN.
In addition, the first round of scheduled snapshots checks only begins 30-60s after startup to avoid synchronizing with other nodes if an entire cluster starts up at the same time.
This PR is based on https://github.com/restatedev/restate/pull/3060.
---
Testing:
- Check desired startup and concurrency limit behavior via `restatectl partitions list` archived LSN output
- Test with pre-existing snapshots in repository
- Test manually requesting snapshots during the startup "quiescent" phase
- Test concurrently requesting multiple snapshots outside of scheduled snapshots
=> Update archived LSN before taking snapshot

crates/log-server/src/rocksdb_logstore/builder.rs, crates/log-server/src/rocksdb_logstore/writer.rs, crates/rocksdb/src/db_manager.rs, crates/types/src/config/log_server.rs
In conjunction with pipedlined writes, this improves latency under extreme load conditions, a long-standing improvement that I had locally for some time.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3062).
* #3071
* __->__ #3062
* #3070
=> [RocksDb] Enable write batch insertion hints for log-servers

crates/log-server/src/rocksdb_logstore/builder.rs, crates/rocksdb/src/db_manager.rs, crates/types/src/config/log_server.rs
This adds a new option `rocksdb-max-wal-size` in `[log-server]` with hidden default (0) that controls the maximum size of the WAL in bytes. If the WAL size exceeds this limit, the server will force a flush to the SST files. This is useful to prevent the WAL from growing indefinitely and consuming disk space.
The default (0) will use 6 times the total size allocated to memtables for log-server by default.
With this change, there is no need for atomic_flushes anymore, so I've removed it.
Manually tested, old WAL files are removed as expected.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3070).
* #3071
* #3062
* __->__ #3070
=> [LogServer] Add `rocksdb-max-wal-size` to `[log-server]` to limit WAL size

crates/types/src/logs/metadata.rs
Fix `target_nodeset_size` not set on cluster config get
=> Fix `target_nodeset_size` not set on cluster config get

crates/admin/src/cluster_controller/protobuf.rs, crates/log-server/src/protobuf.rs, server/tests/trim_gap_handling.rs
Instead of relying on fine-grained timeouts which might be wrong in constrained
environments as our CI runners, we rely on the global nextest timeout of 180s to
catch hanging tests.
This fixes https://github.com/restatedev/restate/issues/2973.
=> Remove too tight timeouts from fast_forward_over_trim_gap 

server/tests/cluster.rs
Increasing the log level of the cluster_chaos_test to restate=debug allows us hopefully to find out why the test got stuck (concretely why a newly started process did not go beyond the "Starting Restate Server" log statement.
This fixes #3072.
=> Increase log level of cluster_chaos_test to restate=debug

crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/table_docs.rs, crates/storage-query-datafusion/src/table_macro.rs
Add missing column `invoked_by_subscription_id` to `sys_invocation` view
Fix discrepancy between the view docs and actual view columns
=> Add missing column `invoked_by_subscription_id` to `sys_invocation` view

crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection_manager.rs
This commit reduces the log level from info to debug for most of the network related log statements as well as when loglets are sealed since the information does not seem actionable by users.
=> Reduce logging originating from network and loglet sealing

tools/restatectl/src/commands/log/mod.rs
Hide the `logs dump` command for now
Summary:
Related to #3080
=> Hide the `logs dump` command for now

crates/local-cluster-runner/src/node/mod.rs, server/tests/cluster.rs
In order to deal with slower test infrastructure, we increase the retry count for StartedNode::provision_cluster to ~60s. If the node does not allow to provision the cluster within this duration, the operation will fail.
This fixes #3052.
=> Increase retry count for StartedNode::provision_cluster

docker/Dockerfile, docker/debug.Dockerfile
JQ is helpful for health checks and parsing ECS task metadata
=> Add jq to our docker images

Cargo.lock, crates/metadata-server/Cargo.toml, crates/metadata-server/src/local/mod.rs, crates/metadata-server/src/local/server.rs, crates/metadata-server/src/local/storage.rs, crates/metadata-server/src/raft/server.rs
To properly migrate from the local to the replicated metadata server, we need to prevent the local metadata server from being used once the migration starts. This is done by sealing the local metadata server's storage so that it tells users to use the replicated metadata type. Once the storage is sealed, users can only use the replicated metadata server which prevents a split brain scenario where switching between configurations/versions one is using the migrated replicated metadata server and the other configuration/version is using the local metadata server and thereby having diverging metadata.
One problem with first sealing and then doing the migration is that users can be stuck if the migration fails. In order to avoid this situation I've implemented a slightly different flavor where …
=> Add forward compatible way to migrate from local to replicated metadata server

benchmarks/src/lib.rs, crates/local-cluster-runner/src/node/mod.rs, crates/metadata-server/Cargo.toml, crates/metadata-server/src/lib.rs, crates/metadata-server/src/local/mod.rs, crates/metadata-server/src/local/storage.rs, crates/metadata-server/src/raft/server.rs, crates/metadata-server/src/raft/tests.rs, crates/types/src/config/admin.rs, crates/types/src/config/common.rs, crates/types/src/config/metadata_server.rs, crates/types/src/config/mod.rs, server/tests/cluster.rs, server/tests/raft_metadata_cluster.rs
With this commit we are going to automatically switch to use the replicated metadata server
if we detect that the local metadata server has been sealed (migrated).
=> Automatically switch using the replicated metadata store after successful migration

benchmarks/Cargo.toml, cli/Cargo.toml, crates/admin/Cargo.toml, crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/service.rs, crates/bifrost/Cargo.toml, crates/node/Cargo.toml, crates/node/src/lib.rs, crates/types/Cargo.toml, crates/types/src/logs/metadata.rs, server/Cargo.toml, server/tests/common/mod.rs, server/tests/replicated_loglet.rs, tools/restatectl/Cargo.toml, tools/restatectl/src/util.rs
The replicated-loglet has now become the defacto recommended loglet to use. Therefore,
we can simplify our feature matrix a little bit by letting all crates except for
restate-bifrost activate this feature by default (and removing the option to not
activate it).
=> [Chore] Remove replicated loglet feature

crates/bifrost/Cargo.toml
before fix:
```
cargo clippy --manifest-path crates/bifrost/Cargo.toml --all-features
error[E0599]: no variant or associated item named `TestRunner` found for enum `restate_core::TaskKind` in the current scope
--> crates/bifrost/src/loglet/loglet_tests.rs:127:47
|
127 |         TaskCenter::spawn_unmanaged(TaskKind::TestRunner, "read", {
|                                               ^^^^^^^^^^ variant or associated item not found in `TaskKind`
```
=> fix: make bifrost compile with all features

Cargo.lock, crates/invoker-impl/Cargo.toml
```
cargo clippy --manifest-path crates/invoker-impl/Cargo.toml --all-features
29 | use restate_service_protocol::codec::ProtobufRawEntryCodec;
|                               ^^^^^ could not find `codec` in `restate_service_protocol`
|
note: found an item that was configured out
```
=> fix: make invoker-impl compile with all-features

crates/tracing-instrumentation/Cargo.toml
```
cargo clippy --manifest-path crates/tracing-instrumentation/Cargo.toml --no-default-features --features prometheus
--> crates/tracing-instrumentation/src/prometheus_metrics.rs:87:30
|
87  |                 tokio::task::Builder::new()
|                              ^^^^^^^ could not find `Builder` in `task`
|
note: found an item that was configured out
```
=> fix: make tracing-instrumentation compile with features prometheus

crates/service-protocol/Cargo.toml
Before this pr:
```
cargo clippy --manifest-path crates/service-protocol/Cargo.toml --all-features
crates/service-protocol/src/codec.rs:253:55
|
253 |                     let invocation_id = InvocationId::mock_random();
|                                                       ^^^^^^^^^^^ function or associated item not found in `InvocationId`
```
=> fix: make service-protocol compile with --all-features

tools/restatectl/src/environment/task_center.rs
Fix: https://github.com/restatedev/restate/issues/3004
=> fix(3004): use scope for async function

crates/wal-protocol/Cargo.toml, crates/wal-protocol/src/lib.rs
Before this pr:
```
error: cannot find attribute `serde` in this scope
--> crates/wal-protocol/src/lib.rs:88:11
|
88 |         #[serde(default)]
|           ^^^^^
|
= note: `serde` is in scope, but it is a crate, not an attribute
```
=> fix: make wal-protocol compile with feature options_schema

crates/rocksdb/src/db_manager.rs
This has been the default in RocksDB for over a year now:
https://github.com/facebook/rocksdb/commit/bfd00bba9c75fffc95d53c741c6939c2ba5223f3
=> [chore] Use latest RocksDB table format version

tools/restatectl/src/commands/config/set.rs, tools/restatectl/src/commands/node/disable_node_checker.rs, tools/restatectl/src/commands/provision.rs
before fix:
```
cargo clippy --manifest-path tools/restatectl/Cargo.toml --no-default-features --features no-trace-logging
error[E0599]: no variant or associated item named InMemory found for enum restate_types::logs::metadata::ProviderKind in the current scope
--> tools/restatectl/src/commands/config/set.rs:78:27
|
78 |             ProviderKind::InMemory | ProviderKind::Local => {
|                           ^^^^^^^^ variant or associated item not found in ProviderKind
```
cc @tillrohrmann
=> fix: make restatectl compile with feature no-tracing-logging

crates/types/src/config/common.rs, crates/types/src/config/metadata_server.rs, crates/types/src/config/mod.rs, crates/types/src/config/rocksdb.rs, crates/types/src/config/util.rs, crates/types/src/config_loader.rs, crates/types/src/retries.rs, crates/worker/src/partition_processor_manager/persisted_lsn_watchdog.rs
This is a backport of #3153 to `release/1.2`.
=> [BACKPORT] Set default values for deprecated options 

Cargo.lock, crates/admin/src/rest_api/invocations.rs, crates/admin/src/rest_api/services.rs, crates/bifrost/src/lib.rs, crates/ingress-kafka/src/dispatcher.rs, crates/wal-protocol/Cargo.toml, crates/wal-protocol/src/lib.rs, crates/worker/src/partition/cleaner.rs, crates/worker/src/partition/shuffle.rs
Fix: https://github.com/restatedev/restate/issues/3036
before fix:
```
cargo clippy --manifest-path crates/wal-protocol/Cargo.toml --no-default-features
error[E0277]: the trait bound `Envelope: serde::ser::Serialize` is not satisfied
--> crates/wal-protocol/src/lib.rs:61:1
|
61 | flexbuffers_storage_encode_decode!(Envelope);
```
=> fix: make wal-protocol compile with no features

crates/bifrost/src/providers/replicated_loglet/loglet.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/types/src/config/bifrost.rs, server/tests/replicated_loglet.rs
We have an assertion for it in debug, but better change the config parsing to reflect this.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3163).
* #3164
* #3162
* #3159
* #3165
* #3167
* __->__ #3163
=> [bifrost] Limit readahead records to u16 in configuration

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.63
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.63/ui-v0.0.63.zip
=> [Restate UI] Update to v0.0.63

crates/invoker-impl/src/lib.rs
Since the retry logic also tracks notification proposals in the JournalTracker, we need to handle notifications as retry events because they can unblock a waiting for retry invocation. This commit changes the behavior accordingly.
=> Handle notifications as retry events in the invoker

crates/types/src/config/bifrost.rs, crates/types/src/config/metadata_server.rs
- Auto-recovery needs to be higher than http2 keep-alive timeout
- Shorter raft election timeout (~1-ish second)
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3165).
* #3164
* #3162
* #3159
* __->__ #3165
=> [Core] Tuning failover config defaults

cli/src/commands/cloud/login.rs
Instead of failing we are asking the user to open the URL manually.
This fixes #3179.
=> Don't fail cloud login if we cannot open the browser

crates/node/src/lib.rs, crates/node/src/network_server/grpc_svc_handler.rs, crates/node/src/network_server/service.rs
When provisioning the cluster we are writing some metadata to the metadata store.
In case that the write succeeds, we should be able to directly update the
MetadataManager to avoid having to fetch it from the metadata store. This is a
minor optimization.
This fixes https://github.com/restatedev/restate/issues/3170.
This PR is based on #3164.
=> Use global metadata wrapper when writing metadata for provisioning the cluster

Cargo.lock, Cargo.toml, crates/encoding/Cargo.toml, crates/encoding/derive/Cargo.toml, crates/encoding/derive/src/bilrost.rs, crates/encoding/derive/src/lib.rs, crates/encoding/derive/src/net.rs, crates/encoding/src/lib.rs, crates/encoding/tests/net_serde.rs, crates/types/Cargo.toml, crates/types/src/net/codec.rs, crates/types/src/net/dto.rs, crates/types/src/net/metadata.rs, crates/types/src/net/mod.rs, crates/types/src/version.rs, workspace-hack/Cargo.toml
Add support for protocol version Bilrost (v2)
Also introduce two new derive macros:
- `BilrostNewType` to use with all ID types or any tuple with a single item. This will
effectively flatten this tuple to its inner type. Given that the inner field is bilrost serializable
- `NetworkMessage` which must be derived for each message that is going to be send over the network
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3190).
* #3176
* #3172
* __->__ #3190
=> Add support for protocol version Bilrost (v2)

Cargo.lock, crates/local-cluster-runner/src/cluster/mod.rs, crates/local-cluster-runner/src/node/mod.rs, crates/metadata-server/Cargo.toml, crates/metadata-server/proto/metadata_server_network_svc.proto, crates/metadata-server/proto/metadata_server_svc.proto, crates/metadata-server/src/grpc/handler.rs, crates/metadata-server/src/lib.rs, crates/metadata-server/src/raft/mod.rs, crates/metadata-server/src/raft/network/handler.rs, crates/metadata-server/src/raft/server.rs, crates/metadata-server/src/raft/storage/rocksdb.rs, server/tests/raft_metadata_cluster.rs, tools/restatectl/src/app.rs, tools/restatectl/src/commands/metadata_server/list_servers.rs, tools/restatectl/src/commands/metadata_server/mod.rs, tools/restatectl/src/commands/metadata_server/nodes.rs, tools/restatectl/src/commands/status.rs
This commit adds restatectl metadata-server add-node/remove-node to add and remove nodes to and from the metadata cluster. Internally, an add command instructs the joining node to reach out to the leader to ask for a reconfiguration. A remove command is sent to the leader where it triggers a reconfiguration to remove the given node. To also stop removed metadata cluster members that have missed the configuration change, we are using the MetadataServerState stored in the NodesConfiguration as an additional signal. If a node detects that its MetadataServerState is set to Standby while it is running as a Member, then it will step down. Likewise, if a Standby node detects that its MetadataServerState is Member, then it will try to join the cluster because it might mean that it tried joining …
=> Add support for removing/adding metadata server nodes

crates/bifrost/benches/replicated_loglet_serde.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/core/protobuf/restate/network.proto, crates/core/src/network/connection_manager.rs, crates/core/src/network/io/egress_stream.rs, crates/core/src/network/io/reactor.rs, crates/core/src/network/protobuf.rs, crates/core/src/network/types.rs
Leveraging the fact the Version::INVALID is 0 to pack the metadata versions better in memory. Version needs 4 bytes (u32) while Option<Version> needs 8. `PeerMetadataVersion` now needs 16 bytes instead of 32, same for `Header`.
The other change is to let `MetadataVersions` keep track of the actual observed version of the peer as this might come handy for introspection later. This doesn't impact performance as we still only notify if the version is higher than our latest local view.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3196).
* #3200
* #3199
* __->__ #3196
=> Efficiently pack metadata versions in network structs

crates/bifrost/benches/replicated_loglet_serde.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/core/protobuf/restate/network.proto, crates/core/src/network/connection_manager.rs, crates/core/src/network/error.rs, crates/core/src/network/io/egress_stream.rs, crates/core/src/network/io/reactor.rs, crates/core/src/network/protobuf.rs, crates/core/src/network/types.rs, crates/node/src/init.rs, crates/node/src/lib.rs, crates/node/src/network_server/service.rs, crates/node/src/roles/base.rs
This also removes the need for TonicServiceFilter for core networking. With the new service design, individual services will respond with SvcNotReady if they received requests before they're started. Moreover, this introduces a check when accepting connections to ensure we return ServiceUnavailable if we received connections before acquiring our node id. This is a transitional step until we can allow core networking to accept connections before the node id is acquired.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3199).
* #3200
* __->__ #3199
* #3196
=> [Core] Enable failure detector to start earlier

crates/bifrost/benches/replicated_loglet_serde.rs, crates/bifrost/src/providers/replicated_loglet/network.rs, crates/core/protobuf/restate/network.proto, crates/core/src/network/connection_manager.rs, crates/core/src/network/error.rs, crates/core/src/network/io/egress_stream.rs, crates/core/src/network/io/reactor.rs, crates/core/src/network/protobuf.rs, crates/core/src/network/types.rs, crates/node/src/failure_detector.rs, crates/node/src/init.rs, crates/node/src/lib.rs, crates/node/src/network_server/service.rs, crates/node/src/roles/base.rs, crates/node/src/roles/mod.rs
Upcycling `BaseRole` to serve as the home of the WIP failure detector. This PR does not change any behaviour.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3200).
* __->__ #3200
* #3199
* #3196
=> [mechanical] Rename BaseRole into FailureDetector

crates/types/src/net/mod.rs, crates/types/src/net/node.rs
Bilrost only wire codec macro
Summary:
This is needed for new message types that don't need to
have v1 backward compatibility
=> Bilrost only wire codec macro

crates/core/src/network/incoming.rs, crates/types/src/net/codec.rs, crates/types/src/net/metadata.rs, crates/types/src/net/mod.rs
This is necessary to allow `Box<dyn WireEncode>` to be used in the next PR. This also aligns with how most serialization libraries work, there is no need to send the owned value. I've temporarily disabled bilrost's IntoDto until we can get it to work with this design. Additionally. I didn't change the API of the send() API in network code to avoid making this as a sweeping change. If the need for passing the message by reference on that layer rises, we can change it.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3214).
* #3215
* #3213
* __->__ #3214
=> [Core] WireEncode accepts a reference instead of an owned value

Cargo.lock, crates/core/src/worker_api/mod.rs, crates/core/src/worker_api/partition_processor_rpc_client.rs, crates/ingress-http/Cargo.toml, crates/ingress-http/src/handler/invocation.rs, crates/ingress-http/src/handler/responses.rs, crates/ingress-http/src/handler/tests.rs, crates/ingress-http/src/handler/workflow.rs, crates/ingress-http/src/lib.rs, crates/ingress-http/src/rpc_request_dispatcher.rs, crates/ingress-http/src/server.rs, crates/node/src/roles/ingress.rs, crates/types/src/invocation/client.rs, crates/types/src/invocation/mod.rs, crates/types/src/net/partition_processor.rs, crates/worker/src/partition/leadership/leader_state.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/state_machine/actions.rs, crates/worker/src/partition/state_machine/lifecycle/cancel.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/idempotency.rs, crates/worker/src/partition/state_machine/tests/kill_cancel.rs, crates/worker/src/partition/state_machine/tests/mod.rs, crates/worker/src/partition/state_machine/tests/workflow.rs
The `InvocationClient` should be completely orthogonal from the transport, and should be easy to mock.
We're gonna use this same client in the Admin API soon for #3186 followups, for propagating errors in the admin api.
=> Move `PartitionProcessorRpcClient` in `restate_types`, and rename it `InvocationClient`.

crates/invoker-api/src/invocation_reader.rs, crates/invoker-api/src/lib.rs, crates/invoker-impl/src/error.rs, crates/invoker-impl/src/invocation_task/mod.rs, crates/worker/src/partition/invoker_storage_reader.rs
This is safe under the following assumptions:
* For a given invocation instance, the invocation id doesn't change. This means that there's two possible situations:
* Either the invocation is present -> in this case the invocation instance must be always the same.
* Or the invocation is absent -> in this case the invocation either:
* Was removed -> the bug we wanna fix here
* not yet written. But this case cannot happen, because of another invariant: invoker gets the invoke command iff the rocksdb transaction was committed for that invocation instance.
=> [invoker] Stop retrying when the invocation is not there anymore.

crates/bifrost/benches/replicated_loglet_serde.rs, crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs, crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs, crates/log-server/src/loglet_worker.rs, crates/types/src/logs/loglet.rs, crates/types/src/logs/mod.rs, crates/types/src/logs/record.rs, crates/types/src/net/log_server.rs, crates/types/src/storage.rs, crates/types/src/time.rs
LogServer Bilrost (v2) message types
Move log server messages to Bilrost v2 by either derive bilrost::Message
or implement a DTO
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3176).
* #3222
* __->__ #3176
=> LogServer Bilrost (v2) message types

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.67
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.67/ui-v0.0.67.zip
=> [Restate UI] Update to v0.0.67

crates/encoding/derive/src/bilrost.rs, crates/encoding/src/bilrost_as.rs, crates/encoding/src/common.rs, crates/encoding/src/lib.rs, crates/types/src/identifiers.rs, crates/types/src/lib.rs, crates/types/src/net/codec.rs, docs/dev/README.md, docs/dev/bilrost-migration-guidelines.md
Bilrost fast encoding + more common helper types
Summary:
- Switch to Birlost fast encoding with ReverseBuffer
- Introduce changes to the BilrostAs that allows us to implement
Generic typed messages.
- Create an EnumSet wrapper type that can serialize itself as Birlost
- Create a RangeInclusive wrapper type that can serialize itself as Birlost
message.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3222).
* #3212
* __->__ #3222
=> Bilrost fast encoding + more common helper types

crates/core/src/cluster_state.rs, crates/core/src/lib.rs, crates/core/src/task_center.rs, crates/core/src/task_center/handle.rs
ClusterState is task-center-level structure providing downstream users access to liveness information about cluster peers. The ClusterState will be populated and controlled by failure detector but may also be updated in the future by other means.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3226).
* #3230
* #3229
* #3228
* __->__ #3226
=> [Core] Introducing global ClusterState view

Cargo.lock, crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/admin/src/cluster_controller/service.rs, crates/core/src/network/connection.rs, crates/core/src/network/connection/throttle.rs, crates/core/src/network/io/egress_stream.rs, crates/core/src/network/lazy_connection.rs, crates/core/src/network/mod.rs, crates/core/src/task_center/task_kind.rs, crates/node/Cargo.toml, crates/node/src/failure_detector.rs, crates/node/src/failure_detector/fd_state.rs, crates/node/src/failure_detector/node_state.rs, crates/node/src/lib.rs, crates/node/src/metric_definitions.rs, crates/types/src/net/node.rs
A new failure detector system based on a custom gossip protocol design. The failure detector service uses an exclusive connection in `Gossip` swimlane to exchange a new `Gossip` unary message between nodes.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3230).
* #3241
* __->__ #3230
=> [FailureDetector] Gossip-based failure detection system

crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/observed_cluster_state.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service/state.rs, crates/core/src/partitions.rs, crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/node_state/row.rs, crates/storage-query-datafusion/src/partition/table.rs, crates/types/protobuf/restate/cluster.proto, crates/types/src/cluster/cluster_state.rs, crates/types/src/identifiers.rs, crates/types/src/partition_table.rs, crates/worker/src/partition_processor_manager.rs, tools/restatectl/src/commands/partition/list.rs, tools/restatectl/src/commands/snapshot/create_snapshot.rs, tools/restatectl/src/commands/status.rs
Bringing PartitionTable up to standard
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3243).
* __->__ #3243
* #3241
=> [minor] Improve PartitionTable naming and style

crates/admin/src/cluster_controller/cluster_state_refresher.rs, crates/admin/src/cluster_controller/observed_cluster_state.rs, crates/admin/src/cluster_controller/service/state.rs, crates/storage-query-datafusion/src/node_state/row.rs, crates/types/protobuf/restate/cluster.proto, crates/types/src/cluster/cluster_state.rs, tools/restatectl/src/commands/partition/list.rs, tools/restatectl/src/commands/status.rs
It's effectively unused and clashes (semantically) with the future of cluster controller and failure detector
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3241).
* #3243
* __->__ #3241
=> Removes SuspectNode from old ClusterState

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.68
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.68/ui-v0.0.68.zip
=> [Restate UI] Update to v0.0.68

Cargo.lock, crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/service.rs, crates/node/src/failure_detector.rs, crates/node/src/failure_detector/fd_state.rs, crates/node/src/failure_detector/node_state.rs, crates/node/src/lib.rs, crates/node/src/roles/admin.rs, crates/node/src/roles/worker.rs, crates/types/Cargo.toml, crates/types/src/lib.rs, crates/types/src/net/node.rs, crates/types/src/partitions.rs, crates/types/src/partitions/configuration.rs, crates/types/src/partitions/state.rs, crates/types/src/version.rs, crates/worker/src/lib.rs, crates/worker/src/partition_processor_manager.rs
Introducing gossip-driven dissemination of partition replica-set states through selective gossip messaging. This also introduces base data structures for `PartitionConfiguration` that will be eventually stored into `EpochMetadata`.
=> [FailureDetector] PartitionReplicaSetStates in FailureDetector

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.69
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.69/ui-v0.0.69.zip
=> [Restate UI] Update to v0.0.69

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.70
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.70/ui-v0.0.70.zip
=> [Restate UI] Update to v0.0.70

server/tests/common/replicated_loglet.rs, server/tests/replicated_loglet.rs
This commit ensures that the test runner sees the manually written Logs configuration by awaiting its version. Otherwise, there was a risk that an empty Logs configuration with Version::MIN was received by a peer, which cause the test to fail with an unknown log '0' error.
This fixes #3265
=> Harden three_logserver_append_after_seal_concurrent

charts/restate-helm/templates/statefulset.yaml
If `restate-data` contains another directory, then Restate won't start if the node name is not specified. This commit solves this problem.
=> Set RESTATE_NODE_NAME in helm charts

crates/core/src/task_center/task_kind.rs
We want to ensure that SequencerAppender tasks complete to update the sequencer state. Therefore, we run the tasks in the default runtime to avoid not completing them if they run as part of the partition processor runtime.
Before, it could happen that a SequencerAppender did not finish (because the corresponding partition processor runtime was shut down) and did not update the sequencer shared state once the store succeeded. This would prevent subsequent append operations to hang for as long as the periodic tail check needs to learn about the local tails of the log servers (~15s).
I have to admit that this bug almost broke me. I started running into with #3233 when all of a sudden the e2e tests became super unstable. The symptoms of this problem were that it looked as if the network layer …
=> Run SequencerAppender tasks in default runtime

crates/metadata-server/src/raft/server.rs, crates/types/src/nodes_config.rs
Since we are currently using the MetadataServerState::Member for nodes that have successfully
joined a metadata server cluster as well as for newly started Restate servers that are supposed
to join the metadata cluster, we can't unconditionally set the MetadataServerState to Standby
for nodes that are not part of the metadata cluster configuration. Instead, we now only do it
if the node has been part of the previous configuration.
This fixes https://github.com/restatedev/restate/issues/3275.
=> Only transition node's MetadataServerState from Member to Standby if node was member before

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/observed_cluster_state.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service.rs, crates/admin/src/cluster_controller/service/state.rs, crates/types/src/cluster/cluster_state.rs, crates/types/src/node_id.rs
This PR changes how the ClusterController learns about alive/dead nodes. Now
it uses the restate_core::cluster_state::ClusterState to update the ObservedClusterState
which is used by the LogsController and the Scheduler.
As part of this commit, we hide the implementation details of the ObservedClusterState
to allow for easier evolutions of it. Moreover, it simplifies the error handling of the
LogsController by panicking if the loglet params cannot be parsed because it is a
situation from which the Restate server cannot recover until the metadata gets fixed.
This PR is based on #3281, #3282, #3279, #3276 (in short only the last commit is relevant for this PR).
=> Integrate restate_core::cluster_state::ClusterState into the ClusterController

Cargo.lock, crates/admin/Cargo.toml, crates/bifrost/Cargo.toml, crates/bifrost/benches/replicated_loglet_serde.rs, crates/encoding/src/lib.rs, crates/partition-store/src/lib.rs, crates/partition-store/src/protobuf_types.rs, crates/types/Cargo.toml, crates/types/src/errors.rs, crates/types/src/identifiers.rs, crates/types/src/invocation/mod.rs, crates/types/src/journal_v2/notification.rs, crates/types/src/journal_v2/types.rs, crates/types/src/storage.rs, crates/types/src/storage/decode.rs, crates/types/src/storage/encode.rs, crates/wal-protocol/Cargo.toml, crates/wal-protocol/src/lib.rs, workspace-hack/Cargo.toml
WAL: Custom Encoding for `Envelope`
This PR enables `Envelope` to apply custom encoding strategies for individual Command variants, selecting the most efficient encoding available for each case.
The design is forward-compatible, allowing future changes to the encoding of specific variants without breaking backward compatibility.
Benchmarks shows a big improvement for variants that uses protobuf (e.g invoke-cmd in this example).
While also unfortunately shows a small regression in performance for variants that still uses flexbuffers internally.
Those variants will eventually switch to bilrost overtime, so I think even if we have a slight decrease in performance right now
this changeset will allow us to improve this later on.
*NOTE:* To run the benchmarks locally make sure to modify the …
=> WAL: Custom Encoding for `Envelope`

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.72
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.72/ui-v0.0.72.zip
=> [Restate UI] Update to v0.0.72

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.73
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.73/ui-v0.0.73.zip
=> [Restate UI] Update to v0.0.73

crates/core/src/metadata.rs, crates/core/src/metadata/update_task.rs, crates/core/src/network/connection.rs, crates/core/src/network/io/egress_sender.rs, crates/core/src/network/io/mod.rs, crates/core/src/network/io/reactor.rs, crates/core/src/network/mod.rs
Since the metadata syncing is now properly non-blocking, it's best to use normal connection abstraction for this. This closes the last gap in graceful connection drains as previously it was possible for a connection to hang at drain time when if it waited for the metadata update rpc response for too long.
```
// intentionally left empty
```
=> Metadata sync messages to use normal connection abstractions

crates/admin/src/cluster_controller/logs_controller.rs, crates/admin/src/cluster_controller/scheduler.rs, crates/admin/src/cluster_controller/service.rs, crates/admin/src/cluster_controller/service/state.rs
Move UpdateClusterConfiguration and TrimLog RPC handling to separate tasks. We eliminated the `SchedulingPlan` in the 1.2.0 release; I believe these are all the remaining paths that could significantly block the ClusterController select loop.
Fixes: https://github.com/restatedev/restate/issues/2601
=> Move some long-running ClusterContoller select arms to background tasks

crates/invoker-impl/src/error.rs, crates/invoker-impl/src/invocation_task/service_protocol_runner_v4.rs
In service to service communication, validate when the user provides a key calling a regular service. In that case, a retryable error is generated.
Fix #3246
=> [invoker] Validate when user incorrectly provides key

crates/service-protocol-v4/src/entry_codec.rs, crates/storage-query-datafusion/src/journal/row.rs, crates/storage-query-datafusion/src/journal/schema.rs, crates/types/src/journal_v2/encoding.rs, crates/types/src/journal_v2/lite.rs, crates/types/src/journal_v2/mod.rs, crates/types/src/journal_v2/notification.rs
=> EntryLite data model to avoid sending entry payloads around when rendering the invocation timeline

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.74
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.74/ui-v0.0.74.zip
=> [Restate UI] Update to v0.0.74

crates/types/src/config/worker.rs
Remove invoker concurrency limit
Summary:
Make sure default concurrency limit value is set to None `==unlimited`
=> Remove invoker concurrency limit

crates/core/src/cluster_state.rs, crates/node/src/failure_detector.rs, crates/node/src/failure_detector/fd_state.rs, crates/node/src/failure_detector/node_state.rs, crates/types/src/net/node.rs
We broadcast GetClusterState on startup and drop the rest of requests once we get the first good response.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3313).
* #3318
* #3309
* #3307
* __->__ #3313
=> [FailureDetector] Seed FD with cluster-state from peer on startup

crates/admin/src/cluster_controller/observed_cluster_state.rs, crates/admin/src/cluster_controller/scheduler.rs
This commit improves the leader selection mechanism of the scheduler. The preference is now
the following:
1. Try to keep the observed leader
2. Prefer worker nodes that are caught up
2.1 Choose the current target leader
2.2 Choose the preferred leader
2.3 Pick any of the nodes in the current partition configuration
3. Pick worker nodes that are alive
3.1 Choose the current target leader
3.2 Choose the preferred leader
3.3 Pick any of the nodes in the current partition configuration
=> Prefer worker nodes that are caught up when selecting leaders

Cargo.lock, Cargo.toml, crates/encoding/src/bilrost_encodings/display_from_str.rs, workspace-hack/Cargo.toml
the only functional change since rc.4 is the removal of `Proxiable::new_proxy` in lieu of using `ForOverwrite` in the destination encoding, which should pretty much always exist already.
=> bilrost 0.1013 is released 😌

Cargo.lock, Cargo.toml, crates/bifrost/benches/replicated_loglet_serde.rs, crates/node/Cargo.toml, crates/partition-store/proto/dev/restate/storage/v1/domain.proto, crates/partition-store/src/protobuf_types.rs, crates/partition-store/src/tests/invocation_status_table_test/mod.rs, crates/partition-store/src/tests/mod.rs, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/invocation_status/row.rs, crates/storage-query-datafusion/src/invocation_status/schema.rs, crates/storage-query-datafusion/src/table_docs.rs, crates/types/Cargo.toml, crates/types/src/invocation/mod.rs, crates/worker/src/partition/state_machine/entries/call_commands.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/fixtures.rs, crates/worker/src/partition/state_machine/tests/idempotency.rs, crates/worker/src/partition/state_machine/tests/mod.rs
Fix #3197.
This adds two metadata in sys_invocation exposing the restate version the invocation was created in, and the version it was last modified in.
=> Add restate_version in ServiceInvocation

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/commands/services/config/patch.rs, cli/src/commands/services/config/view.rs, crates/admin-rest-model/src/services.rs, crates/admin/Cargo.toml, crates/serde-util/Cargo.toml, crates/serde-util/src/duration.rs, crates/types/src/schema/service.rs, crates/worker/src/partition/snapshots/repository.rs
This commit replaces humantime with jiff::fmt::friendly to avoid ambiguous unit conversions. The result of this is that we no longer accept inputs such as `P1M`, `1 month`, `P1Y` or `1 year`. It makes sense to me to accept this tradeoff for the sake of more consistent conversions - alternatively, we could define our own conversion ratios for the number of days in a month/year as outlined here https://github.com/restatedev/restate/issues/2259#issuecomment-2726754029.
See `jiff`'s [Comparison with the `humantime` crate](https://docs.rs/jiff/latest/jiff/fmt/friendly/index.html#comparison-with-the-humantime-crate) for a more detailed discussion about the problems with its implementation.
There's an opportunity for eliminating `DurationString` in favor of using `jiff`'s serde feature directly, …
=> Switch to jiff for parsing for human-friendly durations

Cargo.lock, cli/Cargo.toml, cli/src/commands/state/mod.rs, cli/src/commands/state/patch.rs
I built this for some ops work I needed elsewhere - I think it's pretty useful for scripting small changes!
Example usage:
```
~ % cargo run --bin restate state patch Accounts acc_100 \
--patch '[ { "op": "replace", "path": "/state/environments", "value": [] } ]'
```
This tool is analogous to the existing `restatectl metadata patch` subcommand, but for service state.
=> [CLI] Add a `state patch` subcommand

LICENSE
Make it clear that it is ok to build your own abstractions on top of Restate and offer them as a managed service as long as you don't simply offer a managed Restate service as is.
=> Clarify definition of application platform service in additional usage grant

crates/admin/src/cluster_controller/grpc_svc_handler.rs, crates/admin/src/cluster_controller/service.rs, crates/admin/src/cluster_controller/service/trim_logs_task.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/snapshots.rs, crates/partition-store/src/tests/mod.rs, crates/partition-store/src/tests/snapshots_test/mod.rs, crates/types/src/logs/mod.rs, crates/types/src/partition_table.rs, crates/worker/src/partition/leadership/self_proposer.rs, crates/worker/src/partition/snapshots/repository.rs, crates/worker/src/partition/snapshots/snapshot_task.rs, crates/worker/src/partition_processor_manager.rs
Per title, replace `LogId::from(PartitionId)` with partition table log id lookups in the snapshot creation path.
=> Replace snapshot implicit log ids with partition table lookup

crates/worker/src/partition/cleaner.rs
Ported from https://github.com/restatedev/restate/pull/3360, just hardens the code and adds a test.
=> Fix bug in cleaner with overflows

crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs
This addresses the case where partition processors are stuck on startup waiting to find the tail, no active sequencer, and the tail is inconsistent. No processor will attempt to fix-up the log as none has attempted to become a leader at this point.
=> [Bifrost] Find tail will seal if the sequencer is gone or long dead

.github/workflows/ci.yml, crates/invoker-api/src/invocation_reader.rs, crates/invoker-impl/src/invocation_state_machine.rs, crates/invoker-impl/src/lib.rs, crates/partition-store/proto/dev/restate/storage/v1/domain.proto, crates/partition-store/src/protobuf_types.rs, crates/partition-store/src/tests/journal_table_v2_test/mod.rs, crates/service-protocol-v4/src/entry_codec.rs, crates/types/Cargo.toml, crates/types/build.rs, crates/types/protobuf/restate/journal_events.proto, crates/types/src/config/worker.rs, crates/types/src/journal_v2/command.rs, crates/types/src/journal_v2/event.rs, crates/types/src/journal_v2/mod.rs, crates/types/src/journal_v2/raw/events.rs, crates/types/src/journal_v2/raw/mod.rs, crates/worker/src/partition/invoker_storage_reader.rs, crates/worker/src/partition/state_machine/entries/event.rs, crates/worker/src/partition/state_machine/entries/mod.rs, crates/worker/src/partition/state_machine/tests/mod.rs, workspace-hack/Cargo.toml
See individual commits. The final result:
[data(1).json](https://github.com/user-attachments/files/20439341/data.1.json)
To enable it: `RESTATE_WORKER__INVOKER__experimental_features_propose_events=true`
=> Store Transient errors in journal events

crates/local-cluster-runner/src/node/mod.rs, crates/storage-query-postgres/src/service.rs, crates/types/src/config/admin.rs, crates/types/src/config/query_engine.rs, crates/worker/src/lib.rs
Fix: https://github.com/restatedev/restate/issues/3088
when configuration it in `config.toml`, a log was printed：
```
Using the deprecated config option 'admin.query-enging.pgsql-bind-address'.
```
=> fix(3088): disable pgsql endpoint by default

crates/admin/src/cluster_controller/service/scheduler.rs, crates/types/src/epoch.rs, crates/types/src/partitions/state.rs
By setting the initial current partition configuration version to be equal to the EpochMetadata's version we ensure that clobbering the EpochMetadata (e.g. during a rolling upgrade) won't cause a diverging view on the cluster's ReplicaSetState. W/o this fix, it was possible that the system was reusing versions for different partition configurations which would have caused the system to end up with a divergent view on which node is running which partition processors.
=> Set the initial current partition configuration version to be equal to the EpochMetadata's version

crates/types/src/net/codec.rs, crates/types/src/net/replicated_loglet.rs
flexbuffers backward compatibility for replicated_loglet messages
Building this on top of https://github.com/restatedev/restate/pull/3365 to restore
backward compatibility
=> flexbuffers backward compatibility for replicated_loglet messages

crates/service-client/src/http.rs
[tracing] improve http client errors
Summary:
This make sure that the entire chain of causes is printed
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3394).
* #3396
* __->__ #3394
=> [tracing] improve http client errors

crates/service-client/src/http.rs, crates/storage-query-datafusion/src/remote_query_scanner_client.rs, crates/storage-query-datafusion/src/remote_query_scanner_server.rs, crates/types/src/net/remote_query_scanner.rs
[bilrost] migrate remote scanner types to bilrost
Summary:
Migrate all datafusion related scanner messages to use bilrost
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3396).
* __->__ #3396
* #3394
=> [bilrost] migrate remote scanner types to bilrost

crates/storage-query-datafusion/src/invocation_state/table.rs, crates/storage-query-datafusion/src/partition_store_scanner.rs, crates/storage-query-datafusion/src/remote_query_scanner_client.rs, crates/storage-query-datafusion/src/remote_query_scanner_manager.rs, crates/storage-query-datafusion/src/remote_query_scanner_server.rs, crates/storage-query-datafusion/src/table_providers.rs, crates/types/src/net/remote_query_scanner.rs
Most datafusion providers seem to use these limits. In my testing they don't get enforced by df itself (only top-level output limits are.)
=> Support pushed-down limits in datafusion

crates/core/src/worker_api/partition_processor_rpc_client.rs, crates/types/src/net/partition_processor.rs
The variant was previously removed in 9fd454d1235e7d271569a0e6ae1a2fa39c792180. When running a mixed cluster with <= 1.3.2 nodes, a `Busy` response from a peer can cause a newer node to panic without this variant.
I was able to get this a few times on ECS, but can't repro it locally from a `main` ingress node talking to a `1.3.2` worker. I am a bit puzzled about how this happened in the first place because the newer node sees older workers as "dead" due to their lack of gossip support, so it won't even try talk to them. What am I missing?
```
{
"timestamp": "2025-06-13T12:47:03.107615Z",
"level": "DEBUG",
"fields": {
"message": "Processing ingress request"
},
"target": "restate_ingress_http::handler::service_handler",
"span": {
"restate.invocation.id": …
```
=> fix: restore PartitionProcessorRpcError::Busy variant

crates/object-store-util/src/lib.rs
This was leading to red herring loglines like:
```
{"timestamp":"2025-06-17T08:09:17.464985Z","level":"WARN","fields":{"message":"failed to load region from IMDS","err":"failed to load IMDS session token: dispatch failure: timeout: client error (Connect): HTTP connect timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: hyper_util::client::legacy::Error(Connect, HttpTimeoutError { kind: \"HTTP connect\", duration: 1s }), connection: Unknown } }) }))"},"target":"aws_config::imds::region"}
```
even when aws_region is provided
=> Don't try and load region from AWS sdk if its been provided

Cargo.lock, crates/service-client/src/http.rs
More importantly, fixes a bug where h2 was miscounting the number of open streams causing h2 servers to kill connections (fixed in https://github.com/hyperium/h2/pull/833)
=> Enable http2 adaptive window and upgrade h2

crates/bifrost/src/bifrost_admin.rs, crates/bifrost/src/service.rs, crates/node/src/lib.rs, crates/types/src/config/bifrost.rs
Automatically migrates logs metadata to replicated loglet in single-node configuration. This will cause Bifrost to extend the chain with new replicated loglet segments. The commit also removes an old logs initialization path which has sinced been replaced by the provisioning task.
Closes #3129
---
Testing notes
✅ Starts with replicated loglet as expected:
```
% restatectl logs ls
Logs v25
└ Logs Provider: replicated
├ Log replication: {node: 1}
└ Nodeset size: 0
L-ID  FROM-LSN  KIND        LOGLET-ID  REPLICATION  SEQUENCER  NODESET
0     1         Replicated  0_0        {node: 1}    N1:2       [N1]
1     1         Replicated  1_0        {node: 1}    N1:2       [N1]
2     1         Replicated  2_0        {node: 1}    N1:2       [N1]
3     1         Replicated  3_0        {node: 1}    N1:2 …
```
=> Use ReplicatedLoglet by default

crates/types/src/config/worker.rs
Set default concurrent invocation limit to 1000
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3422).
* #3424
* __->__ #3422
=> Set default concurrent invocation limit to 1000

crates/types/src/journal_v2/raw/mod.rs, crates/worker/src/partition/state_machine/lifecycle/migrate_journal_table.rs
Because of the journal migration from V1 to V2, `InputCommand` currently has an `append_time` that is always equal or after the first entry.
=> Fix `append_time` of the `InputCommand`

Cargo.lock, crates/partition-store/src/idempotency_table/mod.rs, crates/partition-store/src/journal_table/mod.rs, crates/partition-store/src/journal_table_v2/mod.rs, crates/storage-api/Cargo.toml, crates/storage-api/src/deduplication_table/mod.rs, crates/storage-api/src/idempotency_table/mod.rs, crates/storage-api/src/inbox_table/mod.rs, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-api/src/journal_table/mod.rs, crates/storage-api/src/journal_table_v2/mod.rs, crates/storage-api/src/outbox_table/mod.rs, crates/storage-api/src/promise_table/mod.rs, crates/storage-api/src/service_status_table/mod.rs, crates/storage-api/src/state_table/mod.rs, crates/storage-api/src/timer_table/mod.rs, crates/storage-query-datafusion/src/idempotency/table.rs, crates/storage-query-datafusion/src/journal/table.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3429).
* #3436
* #3433
* #3432
* #3431
* __->__ #3429
=> [DataFusion] Move journal and idempotency tables to background iterators

Cargo.lock, crates/partition-store/src/idempotency_table/mod.rs, crates/partition-store/src/inbox_table/mod.rs, crates/partition-store/src/invocation_status_table/mod.rs, crates/partition-store/src/journal_table/mod.rs, crates/partition-store/src/journal_table_v2/mod.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/promise_table/mod.rs, crates/partition-store/src/tests/invocation_status_table_test/mod.rs, crates/storage-api/Cargo.toml, crates/storage-api/src/deduplication_table/mod.rs, crates/storage-api/src/idempotency_table/mod.rs, crates/storage-api/src/inbox_table/mod.rs, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-api/src/journal_table/mod.rs, crates/storage-api/src/journal_table_v2/mod.rs, crates/storage-api/src/outbox_table/mod.rs, crates/storage-api/src/promise_table/mod.rs, crates/storage-api/src/service_status_table/mod.rs, crates/storage-api/src/state_table/mod.rs, crates/storage-api/src/timer_table/mod.rs, crates/storage-query-datafusion/Cargo.toml, crates/storage-query-datafusion/src/idempotency/table.rs, crates/storage-query-datafusion/src/inbox/table.rs, crates/storage-query-datafusion/src/invocation_status/table.rs, crates/storage-query-datafusion/src/journal/table.rs, crates/storage-query-datafusion/src/promise/table.rs, crates/worker/src/partition/cleaner.rs, crates/worker/src/partition/leadership/mod.rs
This also comes with two important benefits:
1. The Cleaner now uses the background iterators to avoid blocking the partiton runtime
2. Resuming invoked invocations when switching into leader state will also perform the scan in the background. This was one of the main reasons why the partition processor was running on its own runtime
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3432).
* #3436
* #3433
* __->__ #3432
* #3431
* #3429
=> [DataFusion] Move invocation_status table to use background iterators

crates/tracing-instrumentation/src/prometheus_metrics.rs
Set histogram quantiles to [50, 90, 99, and 100%]
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3425).
* #3426
* #3424
* __->__ #3425
=> Set histogram quantiles to [50, 90, 99, and 100%]

crates/cli-util/Cargo.toml, crates/wal-protocol/src/control.rs
At https://github.com/restatedev/restate/actions/runs/15790044676/job/44514156585#step:12:515 ，it failed with:
```
error[E0433]: failed to resolve: could not find `process` in `tokio`
Error:    --> crates/cli-util/src/lambda.rs:51:38
|
51  |                 let mut cmd = tokio::process::Command::new(state.exe.as_os_str());
|                                      ^^^^^^^ could not find `process` in `tokio`
```
=> fix: make clippy works

Cargo.lock, tools/restatectl/Cargo.toml, tools/restatectl/src/commands/log/list_logs.rs, tools/restatectl/src/commands/partition/list.rs, workspace-hack/Cargo.toml
Includes:
- Minor cosmetic changes (small-caps loglet kind), shorter headers
- Removed SKIPPED and other non-commonly used columns from the partition list
Screenshot attached in comments
=> [restatectl] compacting partition list/logs tables

crates/node/src/lib.rs, crates/types/src/config/common.rs, crates/types/src/config/ingress.rs, crates/types/src/config/metadata_server.rs, crates/types/src/nodes_config.rs, server/src/main.rs
This takes a slightly different approach than #3140 as it'll still start ingress even if the role `http-ingress` is not set. A notice message will be printed for nodes running with `worker` and without `http-ingress` to ease users into the change. In v1.5, http-ingress will not automatically start with worker and it'll require the role to be set explicitly.
In v1.4.0 the role `http-ingress` is added to the default set of roles so users starting with the default configuration will not see the notice.
=> Enable http-ingress role by default

charts/restate-helm/templates/serviceaccount.yaml
ServiceAccount metadata has `namespace` and other resources don't have it, just for consistency, maybe it should be in all of them or in none of them.
=> [helm] Add namespace to metadata of remaining resources

crates/types/src/journal_v2/raw/mod.rs
This fixes a bug where restate v1.4.0 would fail to deserialize old invoker effects from bifrost.
Example error:
```
2025-06-24T10:51:30.432763Z ERROR run: restate_types::storage::decode: Flexbuffers error at field command.InvokerEffect.kind.JournalEntryV2.entry.inner.Command.command_specific_metadata.CallOrSend err=command.InvokerEffect.kind.JournalEntryV2.entry.inner.Command.command_specific_metadata.CallOrSend: Serde Error: missing field `journal_retention_duration` partition_id=5
2025-06-24T10:51:30.432772Z ERROR run: restate_wal_protocol::envelope: FlexbuffersSerde decode failure (decoding Envelope) err=decoding failed: Serde Error: missing field `journal_retention_duration` partition_id=5
2025-06-24T10:51:30.432788Z  WARN run: restate_worker::partition: Shutting partition processor …
```
=> [fix] Default journal_retention to zero when reading old invoker effects

crates/types/src/journal_v2/command.rs
Without default serialization deserializing a CallRequest which does not have this value will fail.
=> [fix] Add default serialization for CallRequest::journal_retention_duration

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.80
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.80/ui-v0.0.80.zip
=> [Restate UI] Update to v0.0.80

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.83
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.83/ui-v0.0.83.zip
=> [Restate UI] Update to v0.0.83

cli/src/commands/cloud/environments/tunnel/local.rs, crates/cloud-tunnel-client/src/client.rs
The CLI tunnel doesn't need to use this as availability isn't critical, but a standalone tunnel client will want to be notified when the server is going away.
=> Tunnel client should support new drain functionality

charts/restate-helm/templates/statefulset.yaml, charts/restate-helm/values.yaml
Additional volumes and their mounts can now be specified on deployments of the Helm chart. This enables users to mount additional secrets or config maps as they desire.
=> Add 'extraVolumes' and 'extraVolumeMounts' to Helm chart values

crates/bifrost/benches/replicated_loglet_serde.rs, crates/invoker-api/src/effects.rs, crates/invoker-api/src/invocation_reader.rs, crates/invoker-impl/src/invocation_state_machine.rs, crates/invoker-impl/src/invocation_task/service_protocol_runner_v4.rs, crates/invoker-impl/src/lib.rs, crates/partition-store/src/journal_table_v2/mod.rs, crates/partition-store/src/tests/journal_table_v2_test/mod.rs, crates/service-protocol-v4/src/entry_codec.rs, crates/storage-api/src/journal_table_v2/mod.rs, crates/storage-api/src/protobuf_types.rs, crates/storage-query-datafusion/src/journal/row.rs, crates/storage-query-datafusion/src/journal/table.rs, crates/types/src/journal_v2/raw/mod.rs, crates/types/src/storage.rs, crates/worker/src/partition/state_machine/entries/event.rs, crates/worker/src/partition/state_machine/entries/mod.rs, crates/worker/src/partition/state_machine/lifecycle/migrate_journal_table.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/fixtures.rs, crates/worker/src/partition/state_machine/tests/matchers.rs
Currently, journal entries derived from signals use now as the append time for the created
RawEntryHeader. This is unlike other journal entries which set create the RawEntryHeader before
writing the journal entry to Bifrost. Due to this, the append time of signals is set at
application time which can be different than the other journal entries' append time. To ensure
that the append time is monotonoically increasing, this commit overwrites the RawEntry's append
time with Bifrost's record creation time.
This fixes https://github.com/restatedev/restate/issues/3487.
=> Explicitly set journal append_time based on Bifrost's record creation time

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.90
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.90/ui-v0.0.90.zip
=> [Restate UI] Update to v0.0.90

.cargo/config.toml, .github/workflows/release.yml, .github/workflows/steps/release-build-setup.yml, Cargo.toml, crates/core/Cargo.toml, crates/core/src/task_center.rs, crates/core/src/task_center/handle.rs, docker/Dockerfile, docker/scripts/download-restate-debug-symbols.sh, docs/dev/profiling-debugging.md, server/src/main.rs, server/src/signal.rs
In Linux, we can catch a signal and dump all tokio tasks to stderr. We use usr2 to this, moving the existing usr2 handler (compaction) to sighup. Note, by catching sighup, i think that it means that user logouts will not exit a running restate process in their shell. Which isn't necessarily a bad thing.... I often run `nohup restate-server &` anyway.
This relies somewhat on the ability to create good backtraces via the backtrace crate, which we do not have right now in release docker images as we strip all the symbols out and upload to polar signals. cargo build --release also does not appear to give enough debug info for tokio dump. Without the symbols, we still get tasks, but it loses loads of detail including whole paths, eg in a select, you will typically just see the cancellation …
=> Tokio task dump

Cargo.lock, crates/core/src/task_center/task_kind.rs, crates/types/src/config/worker.rs, crates/types/src/time.rs, crates/worker/Cargo.toml, crates/worker/src/partition/leadership/leader_state.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/leadership/trim_queue.rs, crates/worker/src/partition/mod.rs
NOTE: This is current unused but will be used in a future PR when trims are executed by the partition leader.
The design approach:
1. The partition stores the last partition durability point in FSM + timestamp (when it was declared as durable).
2. The partition (will) issue a trim for the log up to the last durable point periodically. (e.g. every 1 minute)
Now, to add support for delayed trims. The approach I'm taking here is to only trim if the durability point is X seconds old. This value is configurable.
The trim queue is a best-effort approach to keep information about the older durability points in the partition, this allows us to still execute older durability before the cutoff point when the latest durability point is not old enough to get trimmed.
The downside of this approach is …
=> Adds per-partition trim queue tracking

Cargo.lock, crates/core/src/task_center/task_kind.rs, crates/partition-store/src/fsm_table/mod.rs, crates/partition-store/src/tests/barrier_test.rs, crates/partition-store/src/tests/durable_lsn_tracking_test.rs, crates/storage-api/src/fsm_table/mod.rs, crates/types/src/config/worker.rs, crates/types/src/time.rs, crates/worker/Cargo.toml, crates/worker/src/partition/leadership/leader_state.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/leadership/trim_queue.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/state_machine/lifecycle/version_barrier.rs
This change suggests that we should start splitting operations that require partition-store (read committed) access from operations that operate on the write batch. In fact, I'm hoping that at
some point we'll have a much narrower surface area for write-batch based reads.
The current trait design leads a lot of duplicated code and blurs the line between what needs to operate on an open transaction data vs. operating on the committed data. I'm hoping we can change that over time.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3525).
* #3526
* __->__ #3525
* #3524
=> Restrict FSM table reads to PartitionStore only

Cargo.lock, crates/core/src/task_center/task_kind.rs, crates/partition-store/src/durable_lsn_tracking.rs, crates/partition-store/src/fsm_table/mod.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/partition_store_manager.rs, crates/partition-store/src/tests/barrier_test.rs, crates/partition-store/src/tests/durable_lsn_tracking_test.rs, crates/storage-api/src/fsm_table/mod.rs, crates/types/src/config/worker.rs, crates/types/src/time.rs, crates/worker/Cargo.toml, crates/worker/src/partition/leadership/leader_state.rs, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/leadership/trim_queue.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/state_machine/lifecycle/version_barrier.rs, crates/worker/src/partition_processor_manager.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs
This change gives us a reliable way to be sure that we are reading the applied_lsn from the durable storage (flushed to disk) when it's needed. This
fixes the potential issue that can happen if we close and re-open a partition store without flushing.
Note: this doesn't remove the benefit of having the event listener on rocksdb, the event listener allows us to know the latest durable_lsn without
constantly forcing a read from the durable storage. In practice, we only need to read the durable_lsn (the durably stored applied_lsn) once when opening the partition_store.
Additionally:
- Moves reporting of durable_lsn to the partition processor instead of partition procesosr manager.
- Introduce a watch for durable LSN, the primary use at the moment is to detect if durable_lsn has changed or not …
=> Force loading durable_lsn from persistent storage on store open

Cargo.lock, crates/core/src/task_center.rs, crates/metadata-server/src/local/storage.rs, crates/metadata-server/src/raft/server.rs, crates/metadata-server/src/raft/storage/rocksdb_builder.rs, crates/node/src/network_server/metrics.rs, crates/partition-store/src/partition_store.rs, crates/partition-store/src/partition_store_manager.rs, crates/rocksdb/Cargo.toml, crates/rocksdb/src/db_manager.rs, crates/rocksdb/src/lib.rs, crates/rocksdb/src/rock_access.rs, server/src/main.rs, server/src/signal.rs
- Remove unnecessary dynamic dispatch of rocksdb.
- Remove the extra pointer indirection to the raw database.
- Opening the database now happens in the background thread pool
- Background operations that need to own Arc<RocksDb> now take `self: Arc<RocksDb>` explicitly.
- The RocksDb now tracks the database lifetime. `Arc<RocksDb>` cleanly closes the
database when the last reference is dropped. But explicit `RocksDb::close()` is
available for "waiting" for clean close if needed.
- On shutdown, RocksDb manager now waits for rocksdb threads to finish (Probably not needed, but just in case)
- On shutdown, RocksDb manager waits for previously dropped rocksdb database to close, and and closes the rest of the open databases. This in combination with the auto-close on drop allows for some …
=> Refactoring of RocksDb manager for a better ownership model

crates/types/src/logs/builder.rs, crates/types/src/logs/metadata.rs
This fixes a couple of bugs in lookup index management in the log chain, the only impact in production code is that the index for a loglet might remain present after the loglet has been trimmed, the other issues do not impact current production code.
Test Plan:
Added unit tests to cover the lookup index management code.
=> [fix] Fixes lookup index management of replicated loglet

crates/admin/src/cluster_controller/service/scheduler.rs, crates/metadata-server/src/grpc/handler.rs, crates/metadata-server/src/lib.rs, crates/metadata-server/src/raft/server.rs, crates/metadata-server/src/raft/storage/rocksdb.rs, crates/node/src/init.rs, crates/types/src/config/metadata_server.rs
This commit adds MetadataServerOptions::auto_join which controls whether a node tries to auto join the metadata cluster when being started for the first time. Auto join is enabled by default.
=> Add MetadataServerOptions::auto_join to control whether node joins metadata cluster on start

crates/service-client/src/http.rs
=> Fix error detection when mixing up HTTP/1.1 and HTTP/2

charts/restate-helm/templates/statefulset.yaml
This allows us to specify clever entrypoint scripts that can do things like fetch the AZ from AWS.
=> Add command and args to helm chart

crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs, crates/log-server/src/rocksdb_logstore/store.rs, crates/types/src/config/bifrost.rs
The new configuration option `bifrost.replicated-loglet.read-batch-size` will set (in bytes) the budget for every read batch request bifrost client will make to a log-server. The log-server will send at-least a single record even if it exceeds this budget.
The option is set by default to 32KiB.
Additionally:
- Default value of `bifrost.replicated-loglet.readahead-records` is reduced from 100 to 20 to reduce the potential memory ballooning during backfilling. As consequence, backfills will be slower.
Note: this doesn't address all potential memory ballooning issues, there is still a risk of ballooning during massive backfills depending on how many readers and how many loglets are being backfilled at the same time. The risk of ballooning is increased on the log-server side due to the …
=> [Bifrost] Introduce read batch limit in configuration

crates/core/src/task_center.rs, crates/core/src/task_center/handle.rs, crates/core/src/task_center/task.rs, crates/core/src/task_center/task_kind.rs, crates/invoker-impl/src/lib.rs, crates/node/src/lib.rs, crates/node/src/roles/worker.rs, crates/worker/src/lib.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs
Cleans up worker tasks and adds a new feature for task center to get a TaskGuard for unmanaged tasks that should be cancelled on drop.
This also waits for worker shutdown explicitly before shutting down the rest of the system to allow partitions to drain cleanly with potential improvement in a follow-up PR that would let rocksdb flush to happen once PartitionStoreManager is dropped.
Bonus: This includes a minor fix to let PPM cancel processors while they are still starting up, if they are still opening partition store or mid-initialization delay.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3601).
* #3609
* #3607
* #3605
* #3610
* #3604
* __->__ #3601
=> [minor] Worker task management cleanup

crates/core/src/task_center.rs, crates/core/src/task_center/handle.rs, crates/core/src/task_center/task.rs, crates/core/src/task_center/task_kind.rs, crates/invoker-impl/src/lib.rs, crates/node/src/lib.rs, crates/node/src/roles/worker.rs, crates/partition-store/src/durable_lsn_tracking.rs, crates/partition-store/src/partition_store_manager.rs, crates/worker/src/lib.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs
Durability tracker shouldn't hold a strong reference for PartitionStoreManager. It's a minor step towards the worker taking full control over PSM.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3604).
* #3609
* #3607
* #3605
* #3610
* __->__ #3604
* #3601
=> [minor] Durability tracker shouldn't pin partition store manager

crates/core/src/task_center.rs, crates/core/src/task_center/handle.rs, crates/core/src/task_center/task.rs, crates/core/src/task_center/task_kind.rs, crates/invoker-impl/src/lib.rs, crates/node/src/lib.rs, crates/node/src/roles/worker.rs, crates/partition-store/src/durable_lsn_tracking.rs, crates/partition-store/src/error.rs, crates/partition-store/src/partition_store_manager.rs, crates/partition-store/src/snapshots/snapshot_task.rs, crates/storage-api/src/lib.rs, crates/worker/src/lib.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs, server/tests/common/replicated_loglet.rs
- _Actually_ cancel in-flight snapshots on worker shutdown.
- Fix error logging that didn't show the underlying error in log messages and make it stylistically consistent with the other errors.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3605).
* #3609
* #3607
* __->__ #3605
* #3610
* #3604
* #3601
=> [minor] Minor improvements to partition snapshotting task

crates/core/derive/src/tc_test.rs, crates/core/src/task_center.rs, crates/core/src/task_center/builder.rs, crates/core/src/task_center/handle.rs, crates/core/src/task_center/monitoring.rs, crates/core/src/task_center/task.rs, crates/core/src/task_center/task_kind.rs, crates/invoker-impl/src/lib.rs, crates/node/src/lib.rs, crates/node/src/roles/worker.rs, crates/partition-store/src/durable_lsn_tracking.rs, crates/partition-store/src/error.rs, crates/partition-store/src/partition_store_manager.rs, crates/partition-store/src/snapshots/snapshot_task.rs, crates/storage-api/src/lib.rs, crates/worker/src/lib.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs, server/tests/common/replicated_loglet.rs, tools/restatectl/src/commands/log/dump_log.rs
This PR removes the dedicated ingress runtime and allows ingress to share the runtime with `default`. This is a step towards reducing the number of runtimes, threads, and metric dimensions. In my testing, the impact of this change is negligible and in all cases we'd be improving poll latencies in default runtime by avoiding sync IO operations from log-server and metadata server soon.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3607).
* #3609
* __->__ #3607
* #3605
* #3610
* #3604
* #3601
=> Remove ingress dedicated runtime

crates/core/derive/src/tc_test.rs, crates/core/src/task_center.rs, crates/core/src/task_center/builder.rs, crates/core/src/task_center/handle.rs, crates/core/src/task_center/monitoring.rs, crates/core/src/task_center/task.rs, crates/core/src/task_center/task_kind.rs, crates/invoker-impl/src/lib.rs, crates/node/src/lib.rs, crates/node/src/roles/worker.rs, crates/partition-store/src/durable_lsn_tracking.rs, crates/partition-store/src/error.rs, crates/partition-store/src/partition_store_manager.rs, crates/partition-store/src/snapshots/snapshot_task.rs, crates/storage-api/src/lib.rs, crates/types/src/config/common.rs, crates/worker/src/lib.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs, server/tests/common/replicated_loglet.rs, tools/restatectl/src/commands/log/dump_log.rs
In recent restate release we changed the default idle timeout of histograms to 3 minutes, this caused some of the histograms to drop after being idle and never appearing again due to this issue in metrics-rs https://github.com/metrics-rs/metrics/issues/372.
The issue happens for histograms that we keep a stable handle for, we keep those handles to avoid the repetitive heap allocation in our hot paths. Although we are disabling the default idle timeout, users will still see the issue if they are setting this value in configuration files.
This should be considered as a short-term mitigation, we'll need a longer-term solution still.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with …
=> [observability] Disable histogram idle timeout by default

crates/core/src/task_center.rs, crates/core/src/task_center/handle.rs, crates/core/src/task_center/task.rs, crates/core/src/task_center/task_kind.rs, crates/invoker-impl/src/lib.rs, crates/node/src/lib.rs, crates/node/src/roles/worker.rs, crates/partition-store/src/durable_lsn_tracking.rs, crates/partition-store/src/partition_store_manager.rs, crates/worker/src/lib.rs, crates/worker/src/partition_processor_manager/spawn_processor_task.rs, server/tests/common/replicated_loglet.rs
Should fix the flaky three-node trim test
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3610).
* #3609
* #3607
* #3605
* __->__ #3610
* #3604
* #3601
=> Disable auto-improvement in replicated-loglet integration tests

crates/types/src/net/node.rs
This was not correct. is_alive() should strictly return true if the node is alive and not failing-over. This fix improves cluster controller's failover response time, and allows it to fail-over leader partitions as soon as it observes that a node shutdown has _started_.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3618).
* #3620
* #3619
* #3613
* #3612
* #3611
* __->__ #3618
=> [ClusterState] Fixing is_alive() reporting true for failing-over nodes

Cargo.toml, crates/core/src/task_center.rs, crates/core/src/task_center/handle.rs, crates/core/src/task_center/task_kind.rs, crates/local-cluster-runner/examples/three_nodes.rs, crates/rocksdb/src/db_manager.rs, crates/types/src/net/node.rs, crates/worker/src/partition_processor_manager.rs, server/src/main.rs
This introduces a few crucial changes to how we handle panics in restate. Prior to this change, we would abort the process at panic time without considering a clean shutdown nor rocksdb wal fsync.
The summary of changes is as follows:
- We now always unwind the stack on panics. TaskCenter is designed to catch panics of important tasks and trigger a clean shutdown and reports a non-zero exit code.
- Ensure that on graceful shutdown timeout that we attempt to cleanly flush/shutdown rocksdb manager. This is important to avoid massive backfills of lost memtables on unclean shutdown.
- Catch panics at top-level task-center runtime control loop and trigger an emergency rocksdb WAL fsync to ensure that we flush the WAL to avoid loss of in-memory WAL buffer if/when we add support to manual wal …
=> [Core] Always unwind and ensure rocksdb's WAL is flushed on panics

.github/workflows/npm.yml, .github/workflows/release.yml, npm/restate-server/package.json, npm/restate/package.json, npm/restatectl/package.json, scripts/loadtest-environment/package.json
Updates references of the [setup-node](https://github.com/actions/setup-node) action in workflow files to use v22 (current LTS) rather than older v18 & v20 references.
Also bumps the npm packages to reflect via `@types/node` and `typescript`.
Resolves #3142
=> Upgrade to NodeJS 22 (LTS)

crates/rocksdb/src/db_manager.rs
I think this was missed in the original change. Without saving the new options, changing them again works only as long as the new values are not reverted to the originally loaded values. E.g. changing `rocksdb-enable-stall-on-memory-limit` from `false` to `true` works, but cannot be reverted back to `false` without a restart. It also incorrectly reports settings as changed if unrelated options change.
=> Update currently applied DB configuration values after reload

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.94
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.94/ui-v0.0.94.zip
=> [Restate UI] Update to v0.0.94

crates/service-protocol/src/discovery.rs, crates/types/src/service_protocol.rs
Part of #3184.
This won't affect already registered endpoints, nor in-flight invocations, this will only prevent registration of SDKs using protocol <= 4.
=> Disable registration of old SDKs

Cargo.lock, Cargo.toml, crates/core/src/network/incoming.rs, crates/ingress-http/Cargo.toml, crates/types/src/invocation/mod.rs, crates/types/src/net/partition_processor.rs, crates/worker/Cargo.toml, crates/worker/src/partition/leadership/mod.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/rpc/append_invocation.rs, crates/worker/src/partition/rpc/append_invocation_response.rs, crates/worker/src/partition/rpc/append_signal.rs, crates/worker/src/partition/rpc/cancel_invocation.rs, crates/worker/src/partition/rpc/get_invocation_output.rs, crates/worker/src/partition/rpc/kill_invocation.rs, crates/worker/src/partition/rpc/mod.rs, crates/worker/src/partition/rpc/purge_invocation.rs, crates/worker/src/partition/rpc/purge_journal.rs
This PR reorganizes the code of the PP RPC handlers in a more modular way, to enable unit testing those. No fundamental changes.
This is in preparation of the work for restart as new.
=> PartitionProcessor RPC handlers reorganization

.github/workflows/ci.yml, Cargo.lock, cli/src/commands/services/config/edit.rs, cli/src/commands/services/config/patch.rs, cli/src/commands/services/config/view.rs, crates/admin-rest-model/src/services.rs, crates/admin/src/rest_api/services.rs, crates/ingress-http/src/handler/service_handler.rs, crates/ingress-kafka/Cargo.toml, crates/ingress-kafka/src/dispatcher.rs, crates/serde-util/Cargo.toml, crates/serde-util/src/duration.rs, crates/types/src/config/admin.rs, crates/types/src/config/invocation.rs, crates/types/src/config/mod.rs, crates/types/src/schema/metadata/mod.rs, crates/types/src/schema/metadata/serde_hacks.rs, crates/types/src/schema/metadata/updater.rs, crates/types/src/schema/service.rs
Fix #3557, fix #3558.
Based on #3550
=> [RIP0001] Journal retention knobs and Admin API to mutate it

crates/storage-query-datafusion/src/context.rs
This prevents memory issues when using topk, as it likes to keep references to a lot of batches, coalesce batch turning batches into size 8192 proves to be an issue.
=> Change default df batch size to 64

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.95
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.95/ui-v0.0.95.zip
=> [Restate UI] Update to v0.0.95

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.97
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.97/ui-v0.0.97.zip
=> [Restate UI] Update to v0.0.97

crates/storage-query-datafusion/src/context.rs, crates/storage-query-datafusion/src/deployment/table.rs, crates/storage-query-datafusion/src/invocation_state/table.rs, crates/storage-query-datafusion/src/log/table.rs, crates/storage-query-datafusion/src/node/table.rs, crates/storage-query-datafusion/src/partition/table.rs, crates/storage-query-datafusion/src/partition_replica_set/table.rs, crates/storage-query-datafusion/src/partition_state/table.rs, crates/storage-query-datafusion/src/partition_store_scanner.rs, crates/storage-query-datafusion/src/remote_query_scanner_client.rs, crates/storage-query-datafusion/src/remote_query_scanner_manager.rs, crates/storage-query-datafusion/src/scanner_task.rs, crates/storage-query-datafusion/src/service/table.rs, crates/storage-query-datafusion/src/table_macro.rs, crates/storage-query-datafusion/src/table_providers.rs, crates/storage-query-datafusion/src/table_util.rs, crates/types/src/net/remote_query_scanner.rs
Instead of hardcoding the produced batch size in the macro, we will now start adapting reactively to the df config (passing the value through the remote scanner if needed)
This allows us to a) keep produced batches in size with the configured df value b) play with that configured df value via env var or at runtime.
We also increase the default df batch size to 128 as this appears to lead to a significant performance gain both locally and in cloud.
=> Get batch sizes from global config

crates/invoker-impl/src/error.rs, crates/storage-api/src/protobuf_types.rs, crates/storage-query-datafusion/src/invocation_status/row.rs, crates/types/src/errors.rs, crates/worker/src/invoker_integration.rs
Two noticeable things in profiles:
1. We are calling `format_using` on rows we didn't actually project
2. We are copying failure messages unnecessarily. NB that these can be quite long. And in my testing every invocation failed so I particularly hammer this. The InvocationError type accepts an impl fmt::Display, which will always copy the message, even if we have it as an owned string. In the main case in the profile, we had it as a Bytes (ref count presumably 1) and we were turning it into a bytestring (free) then formatting it (copy). If we instead turn the Bytes into a Vec<u8> we should be able to avoid a copy. There are other cases of passing ByteString to InvocationError and it will probably copy, but unless those show up in a profile too I'll leave them for now.
=> Inv status deserialisation speedups

crates/ingress-http/src/handler/service_handler.rs, crates/ingress-http/src/handler/tracing.rs, crates/ingress-kafka/src/dispatcher.rs, crates/invoker-impl/src/invocation_task/service_protocol_runner.rs, crates/invoker-impl/src/invocation_task/service_protocol_runner_v4.rs, crates/storage-api/src/protobuf_types.rs, crates/tracing-instrumentation/src/lib.rs, crates/types/src/invocation/mod.rs, crates/worker/src/partition/rpc/restart_as_new_invocation.rs, crates/worker/src/partition/state_machine/mod.rs
The goal here is to keep tracestate as a string if we provided it as a string (eg, it came from storage) and only parse it to proper tracestate if someone asks for it.
=> Avoid parsing opentelemetry tracestate when reading inv status

crates/storage-query-datafusion/src/deployment/table.rs, crates/storage-query-datafusion/src/invocation_state/table.rs, crates/storage-query-datafusion/src/log/table.rs, crates/storage-query-datafusion/src/node/table.rs, crates/storage-query-datafusion/src/partition/table.rs, crates/storage-query-datafusion/src/partition_replica_set/table.rs, crates/storage-query-datafusion/src/partition_state/table.rs, crates/storage-query-datafusion/src/partition_store_scanner.rs, crates/storage-query-datafusion/src/service/table.rs, crates/storage-query-datafusion/src/table_macro.rs, crates/storage-query-datafusion/src/table_util.rs
The idea here is to make each batch with a capacity set to the length of the previous batch, to reduce how often we have to resize the arrays. 
For the primitive arrays, the capacity will just become 'batch size', and given that previously the arrays all defaulted to 1024 item capacity, this will lead to a nice memory reduction given our default batch size is 128. 
Care is needed for byte arrays as they have lens for both value (number of strs, again it will become the batch size) and data (total bytes across all str). Both of these defaulted to 1024 previously, which meant any string field with >4 chars on average led to 1 realloc, and any with > 8 chars led to two reallocs. Invocation IDs, which are 27 chars, led to three reallocs.
=> Re-use df batch array capacities

crates/storage-query-datafusion/src/table_providers.rs
get rid of unnecessary `CooperativeExec`
=> Set our execution plan as cooperative

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.98
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.98/ui-v0.0.98.zip
=> [Restate UI] Update to v0.0.98

Cargo.lock, crates/partition-store/src/keys.rs, crates/types/Cargo.toml, crates/types/benches/id_encoding.rs, crates/types/src/base62_util.rs, crates/types/src/deployment.rs, crates/types/src/id_util.rs, crates/types/src/identifiers.rs, crates/types/src/lib.rs, workspace-hack/Cargo.toml
Allocation free to_string and Display impls for all resource identifiers. While the previous version was great for pre-allocated buffers to Fmt into, it could perform better in `to_string()` scenario by being fully allocation free.
```console
~/w/r/restate ❯❯❯ cargo bench -p restate-types  --bench id_encoding
Finished `bench` profile [optimized + debuginfo] target(s) in 55.61s
Running benches/id_encoding.rs (target/release/deps/id_encoding-e2f9e9fd3134760e)
invocation-id-display   time:   [38.700 ns 38.745 ns 38.798 ns]
change: [-11.835% -11.510% -11.170%] (p = 0.00 < 0.05)
Performance has improved.
Found 13 outliers among 100 measurements (13.00%)
3 (3.00%) low severe
1 (1.00%) low mild
7 (7.00%) high mild
2 (2.00%) high severe
invocation-id-to_string time:   [44.330 ns 44.712 ns 45.320 …
```
=> [perf] Faster to_string for all resource identifiers

charts/restate-helm/templates/statefulset.yaml, charts/restate-helm/values.yaml
Needed if you want to deploy a non clustered instance on a specific node
=> Add nodeSelector support to statefulset

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.0.99
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.0.99/ui-v0.0.99.zip
=> [Restate UI] Update to v0.0.99

crates/partition-store/src/invocation_status_table/mod.rs, crates/storage-api/proto/dev/restate/storage/v1/domain.proto, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-api/src/protobuf_types.rs, crates/storage-query-datafusion/src/idempotency/table.rs, crates/storage-query-datafusion/src/inbox/table.rs, crates/storage-query-datafusion/src/invocation_status/row.rs, crates/storage-query-datafusion/src/invocation_status/table.rs, crates/storage-query-datafusion/src/journal/table.rs, crates/storage-query-datafusion/src/keyed_service_status/table.rs, crates/storage-query-datafusion/src/partition_store_scanner.rs, crates/storage-query-datafusion/src/promise/table.rs, crates/storage-query-datafusion/src/state/table.rs, crates/types/src/restate_version.rs, crates/worker/src/partition/cleaner.rs
This PR changes the status df table scanning to only do proto deserialisation and avoid most field transformations until the fields are needed. In addition, we create a new invocation status lazy shadow proto struct, which keeps strings as bytes, and keeps nested proto messages as bytes too. For all bytes fields, we do zero-copy deserialisation. 
Altogether this leads to a 2x speed up on topk(id)
We change the scanner interface slightly to make functions passed in to places like for_each_invocation_status fallible, so that they can produce conversion errors where previously they would have been produced up front before executing those functions.
Something to note is that we are now producing certain values in the df table in a totally different code path than how we'd produce them to put …
=> Simplified invocation status zero-copy accessor approach

crates/worker/src/partition/rpc/resume_invocation.rs
because the latest deployment will be used anyway.
=> If pin to latest, and no pinned deployment, there's no need to fail

crates/partition-store/src/invocation_status_table/mod.rs, crates/partition-store/src/partition_store.rs, crates/worker/src/partition/leadership/mod.rs
The in place iteration doesn't achieve much difference here, as we are building owned objects and we have to transfer them to the calling thread anyway. However, currently we also transfer millions of Nones via the blocking send, because most invocations are completed in a typical retention enabled environment. Those Nones just get filtered out by scan_invoked_invocations. So, by avoiding sending the None we get a big speedup
Before this PR, with 5m completed invocations in 8 partitions, no running invocations, on an 8 core node:
```
Leader partition resumed 0 invocations in 4.213329983s
Leader partition resumed 0 invocations in 4.223999323s
Leader partition resumed 0 invocations in 4.553144678s
Leader partition resumed 0 invocations in 4.599526967s
Leader partition resumed 0 invocations …
```
=> Avoid sending None invocations from the io thread

crates/invoker-impl/src/invocation_state_machine.rs, crates/invoker-impl/src/lib.rs, crates/partition-store/src/journal_events/mod.rs, crates/partition-store/src/keys.rs, crates/partition-store/src/tests/journal_events_table_test/mod.rs, crates/storage-api/proto/dev/restate/storage/v1/domain.proto, crates/storage-api/src/invocation_status_table/mod.rs, crates/storage-api/src/journal_events/mod.rs, crates/storage-api/src/protobuf_types.rs, crates/storage-query-datafusion/src/journal_events/row.rs, crates/storage-query-datafusion/src/journal_events/schema.rs, crates/storage-query-datafusion/src/journal_events/table.rs, crates/types/src/identifiers.rs, crates/types/src/journal_events/mod.rs, crates/types/src/journal_events/raw.rs, crates/worker/src/partition/cleaner.rs, crates/worker/src/partition/mod.rs, crates/worker/src/partition/state_machine/lifecycle/event.rs, crates/worker/src/partition/state_machine/lifecycle/paused.rs, crates/worker/src/partition/state_machine/lifecycle/purge.rs, crates/worker/src/partition/state_machine/lifecycle/purge_journal.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/matchers.rs, crates/worker/src/partition/state_machine/tests/mod.rs
Depends on #3676.
tl;dr
* The new key structure is `pk : inv uuid : ty : timestamp : lsn`.
* We don't deduplicate events anymore in PP, but we still read the invocation status to assign the total order index.
* The invoker still deduplicates, but just doing equality checks in memory. We don't deduplicate the first error event on leadership changes (this is fine from a DevEx POV)
=> New journal events key structure

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/commands/services/config/edit.rs, cli/src/commands/services/config/patch.rs, cli/src/commands/services/config/view.rs, crates/admin/Cargo.toml, crates/admin/src/service.rs, crates/ingress-http/Cargo.toml, crates/ingress-http/src/server.rs, crates/serde-util/Cargo.toml, crates/serde-util/src/duration.rs, crates/time-util/Cargo.toml, crates/time-util/src/duration.rs, crates/time-util/src/lib.rs
Introduces a crate for time utilities (`serde-time-util`). The crate currently provides a trait `DurationExt` which provides a `friendly()` method for formatting a `Duration` as a human-readable string. It also allows parsing a human-friendly duration into a string.
Additionally, this removes the helpers from `DurationString` and keeps `restate-serde-util`'s DurationString as a serialization helper only.
Minor but relevant changes:
- Fixed parsing "0" as a duration. Previously, it was required to write "0s" to parse a zero duration.
- Some debug traces that reported the response latency now use the `to_seconds_span()` since it's cheaper to compute.
- Fixed typos in restate CLI service config commands
- More efficient serialization for DurationString that avoids an extra String allocation. …
=> Extension trait for `Duration` for friendly display

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/commands/services/config/edit.rs, cli/src/commands/services/config/patch.rs, cli/src/commands/services/config/view.rs, crates/admin/Cargo.toml, crates/admin/src/service.rs, crates/ingress-http/Cargo.toml, crates/ingress-http/src/server.rs, crates/partition-store/src/keys.rs, crates/serde-util/Cargo.toml, crates/serde-util/src/duration.rs, crates/time-util/Cargo.toml, crates/time-util/src/duration.rs, crates/time-util/src/lib.rs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3743).
* #3745
* __->__ #3743
* #3738
=> [minor] Reduce allocations when decoding InvocationUuid

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/commands/services/config/edit.rs, cli/src/commands/services/config/patch.rs, cli/src/commands/services/config/view.rs, crates/admin/Cargo.toml, crates/admin/src/service.rs, crates/ingress-http/Cargo.toml, crates/ingress-http/src/server.rs, crates/partition-store/src/keys.rs, crates/serde-util/Cargo.toml, crates/serde-util/src/duration.rs, crates/time-util/Cargo.toml, crates/time-util/src/duration.rs, crates/time-util/src/lib.rs, crates/worker/Cargo.toml, crates/worker/src/partition_processor_manager.rs
Builds on top of DurationExt (#3738), we'll not print the delay period when the partition processor exists.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3745).
* __->__ #3745
* #3743
* #3738
=> [minor] Print next delay when processor crashes

crates/metadata-server/src/lib.rs, crates/node/src/init.rs, crates/types/src/nodes_config.rs
Set default `MetadataServerState` to `Provisioning`
Fixes #3554
=> Set default `MetadataServerState` to `Provisioning`

Cargo.lock, Cargo.toml, crates/log-server/src/rocksdb_logstore/record_format.rs, crates/log-server/src/rocksdb_logstore/writer.rs, crates/types/src/logs/record.rs, crates/types/src/storage.rs
This PR builds on top of https://github.com/restatedev/rust-rocksdb/pull/15 and allows the log-server to efficiently pass the payload to rocksdb after stitching the header. This removes an extra copy that was necessary to stitch the record header to the payload before writes.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3755).
* #3762
* #3758
* __->__ #3755
=> [LogServer] Reduce payload copies by using vectored write batch operations

cli/src/clients/admin_client.rs, cli/src/clients/datafusion_helpers/v2.rs, cli/src/clients/datafusion_http_client.rs, cli/src/commands/invocations/list.rs
Refactor the cli invocation list operations to use topk(id) instead of topk(*). Topk(id) is much better in terms of memory usage and also speed because of reduced projection.
We have to special case pre 1.5 as we had no efficient multipointread mechanism there, so a single scan is still faster.
For both pre and post 1.5 we can split out the counting logic to use a new count estimate behaviour based on scanning no more than 50k rows and then filtering the result. This is hopefully future proof as it still gives you a sense of scale but it doesn't need a full scan, which opens the door for dynamic filter pushdown optimisations
=> Use point reads for invocation ls & estimate counts

crates/types/src/config/invocation.rs, crates/types/src/schema/metadata/mod.rs, crates/types/src/schema/metadata/updater/mod.rs, crates/types/src/schema/service.rs
This aligns with the behavior of `ctx.run` retry policy.
* `max attempts = 1` -> no retries
* `max attempts = 2` -> 1 retry
* and so on
* `max attempts = 0` is a special case and silently converts it to `1` in the discovery logic. SDKs can introduce additional validation via typing and/or runtime check.
=> Clarify meaning of max_attempts in new retry policy configuration options.

Cargo.lock, crates/admin/Cargo.toml
[UI] Updating Restate UI to v0.1.8
published at https://github.com/restatedev/restate-web-ui/releases/download/v0.1.8/ui-v0.1.8.zip
=> [Restate UI] Update to v0.1.8

crates/cloud-tunnel-client/src/client.rs
I've been noticing some odd behaviour on my orbstack test tunnel client, where after my laptop network changes the tcp connection is somehow re-established but the tunnel isnt actually open. I doubt this can happen in production but still best if we can detect in the tunnel client if we have a bad tcp connection
=> Use server http2 keepalives in cloud tunnel client

crates/partition-store/src/service_status_table/mod.rs, crates/partition-store/src/tests/virtual_object_status_table_test/mod.rs, crates/storage-api/src/lib.rs, crates/storage-api/src/service_status_table/mod.rs, crates/worker/src/partition/rpc/get_invocation_output.rs, crates/worker/src/partition/rpc/mod.rs, crates/worker/src/partition/state_machine/lifecycle/notify_signal.rs, crates/worker/src/partition/state_machine/lifecycle/pinned_deployment.rs, crates/worker/src/partition/state_machine/lifecycle/purge.rs, crates/worker/src/partition/state_machine/lifecycle/restart_as_new.rs, crates/worker/src/partition/state_machine/mod.rs, crates/worker/src/partition/state_machine/tests/delayed_send.rs, crates/worker/src/partition/state_machine/tests/idempotency.rs, crates/worker/src/partition/state_machine/tests/mod.rs, crates/worker/src/partition/state_machine/tests/workflow.rs
[PartitionStore] Decouple read and write service status table traits
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3827).
* #3834
* #3833
* #3831
* #3830
* #3828
* __->__ #3827
=> [PartitionStore] Decouple read and write service status table traits
