restatedev/restate

docs/dev/release.md

Redo of https://github.com/restatedev/restate/pull/894

Update the release doc

---

Cargo.lock
cli/src/commands/services/describe.rs
cli/src/commands/services/discover.rs
cli/src/commands/services/list.rs
cli/src/commands/services/mod.rs
cli/src/meta_client/client.rs
cli/src/meta_client/meta_interface.rs
cli/src/meta_client/mod.rs
cli/src/ui/console.rs
cli/src/ui/mod.rs
cli/src/ui/render.rs
cli/src/ui/service_methods.rs
cli/src/ui/stylesheet.rs
crates/meta-rest-model/src/endpoints.rs
crates/meta/src/rest_api/endpoints.rs
crates/schema-api/src/lib.rs

[CLI] svc discover command initial implementation
A new cli command to discover services from an endpoint:
```sh
restate svc discover http://localhost:9080
```
For ARN discovery:
```sh
restate svc discover arn:....
```
```sh
restate svc discover --assume-role-arn="arn..."  arn:....
```
Custom headers:
```sh
restate svc discover --extra-header my-custom-header=123 --extra-header another-custom-header=345 http://localhost:9080
```
- Performs a dry-run discovery of the service prior to the actual discovery.
- Auto-detection of endpoint (ARN vs. URL).
- Performs basic comparison between the existing services and the freshly discovered, to faciliate visualising the differences to the user.
- Requires `--force` when re-registering the same endpoint. Prints a warning if `--force` will cause an …

[CLI] svc discover command initial implementation

---

crates/meta/src/rest_api/endpoints.rs

Remove superfluous warn

---

crates/storage-api/src/inbox_table/mod.rs
crates/storage-query-datafusion/src/inbox/mod.rs
crates/storage-query-datafusion/src/inbox/row.rs
crates/storage-query-datafusion/src/inbox/schema.rs
crates/storage-query-datafusion/src/inbox/table.rs
crates/storage-query-datafusion/src/options.rs
crates/storage-rocksdb/src/inbox_table/mod.rs

InboxTable in datafusion SQL interface

---

crates/meta/src/rest_api/endpoints.rs
crates/meta/src/rest_api/mod.rs
crates/schema-api/src/lib.rs
crates/schema-impl/src/endpoint.rs
crates/schema-impl/src/schemas_impl.rs

Add /endpoints/:endpoint/descriptors

---

Cargo.lock
cli/Cargo.toml
cli/src/clients/datafusion_helpers.rs
cli/src/commands/deployments/describe.rs
cli/src/commands/deployments/list.rs
cli/src/commands/services/describe.rs
cli/src/commands/services/list.rs
cli/src/commands/services/mod.rs
cli/src/commands/services/status.rs
cli/src/main.rs
cli/src/ui/console.rs
cli/src/ui/service_methods.rs
cli/src/ui/stylesheet.rs

[CLI] service status

---

Cargo.lock
cli/Cargo.toml
cli/src/app.rs
cli/src/clients/datafusion_helpers.rs
cli/src/commands/deployments/describe.rs
cli/src/commands/services/describe.rs
cli/src/commands/services/status/agg_status.rs
cli/src/commands/services/status/detailed_status.rs
cli/src/commands/services/status/mod.rs
cli/src/main.rs
cli/src/ui/console.rs

[CLI] detailed status for single service

[CLI] detailed status for single service

---

crates/schema-api/Cargo.toml
crates/storage-query-datafusion/Cargo.toml
crates/storage-query-datafusion/src/deployment/mod.rs
crates/storage-query-datafusion/src/deployment/row.rs
crates/storage-query-datafusion/src/deployment/schema.rs
crates/storage-query-datafusion/src/deployment/table.rs
crates/storage-query-datafusion/src/generic_table.rs
crates/storage-query-datafusion/src/options.rs
crates/storage-query-datafusion/src/service/mod.rs
crates/storage-query-datafusion/src/service/row.rs
crates/storage-query-datafusion/src/service/schema.rs
crates/storage-query-datafusion/src/service/table.rs
crates/worker/src/lib.rs

Add sys_endpoint and sys_service tables

---

crates/storage-query-datafusion/src/journal/row.rs
crates/storage-query-datafusion/src/journal/schema.rs

[DF] Add sleep wake up time in sys_journal

[DF] Add sleep wake up time in sys_journal

---

Cargo.lock
cli/Cargo.toml
cli/src/commands/deployments/describe.rs
cli/src/commands/deployments/list.rs
cli/src/commands/invocations/describe.rs
cli/src/commands/invocations/list.rs
cli/src/commands/services/describe.rs
cli/src/commands/services/list.rs
cli/src/commands/services/status/agg_status.rs
cli/src/commands/services/status/detailed_status.rs
cli/src/commands/services/status/mod.rs
cli/src/commands/sql.rs
cli/src/main.rs
cli/src/ui/console.rs
cli/src/ui/mod.rs
cli/src/ui/output.rs
cli/src/ui/watcher.rs

[CLI] Watch mode in most commands

---

.github/workflows/postrelease.yml

We could also use this file to do doc updates etc

Update homebrew tap version after releases are published

---

crates/errors/src/error_codes/META0003.md
crates/errors/src/error_codes/META0005.md
crates/errors/src/error_codes/RT0003.md

Update some error messages based on feedback

Update some error messages based on feedback

---

.cargo/config.toml
.github/workflows/binaries.yml
.github/workflows/npm.yml
.github/workflows/release.yml

Relies on https://github.com/restatedev/dev-tools/pull/6 for a proper musl toolchain to exist

Build musl linux binaries

---

crates/storage-query-datafusion/src/status/row.rs

Do not return invalid TraceIDs in datafusion

Do not return invalid TraceIDs in datafusion

---

crates/ingress-grpc/src/handler.rs
crates/ingress-grpc/src/metric_definitions.rs
crates/invoker-impl/src/lib.rs
crates/invoker-impl/src/metric_definitions.rs

Record completed invocation tasks

Record completed invocation tasks

---

docker/Dockerfile

https://discord.com/channels/1128210118216007792/1201873780788432926

Return to using gnu libc in docker containers

---

crates/bifrost/src/bifrost.rs
crates/bifrost/src/loglet.rs
crates/bifrost/src/loglets/file_loglet.rs
crates/bifrost/src/loglets/memory_loglet.rs
crates/bifrost/src/metadata.rs
crates/bifrost/src/types.rs

[Bifrost] read single record
- Some type-level changes
- New loglet APIs to get tail, trim point, and read single record
- Tests for memory loglet

[Bifrost] read single record

---

crates/bifrost/src/bifrost.rs
crates/bifrost/src/read_stream.rs

[Bifrost] Read stream
This fleshes out the basic ReadStream interface + tests. It enables future optimizations (e.g. current loglet caching).

[Bifrost] Read stream

---

Cargo.lock
crates/invoker-api/Cargo.toml
crates/invoker-api/src/effects.rs
crates/storage-api/Cargo.toml
crates/storage-api/src/outbox_table/mod.rs
crates/storage-api/src/status_table/mod.rs
crates/storage-api/src/timer_table/mod.rs
crates/types/Cargo.toml
crates/types/src/errors.rs
crates/types/src/identifiers.rs
crates/types/src/invocation.rs
crates/types/src/journal/enriched.rs
crates/types/src/state_mut.rs

Serde all the things

---

docs/dev/release.md

Also removed the tour repo, we don't need to release it anymore as now it's part of the examples repo.

Add pre-release step

---

Cargo.lock
Cargo.toml
crates/wal-protocol/Cargo.toml
crates/wal-protocol/src/control.rs
crates/wal-protocol/src/effects.rs
crates/wal-protocol/src/lib.rs
crates/wal-protocol/src/timer.rs

WAL protocol init
This defines a provisional envelope and WAL message types. Currently unused

WAL protocol init

---

Cargo.lock
Cargo.toml
crates/core/src/task_center_types.rs
crates/ingress-http/Cargo.toml
crates/ingress-http/src/handler.rs
crates/ingress-http/src/lib.rs
crates/ingress-http/src/metric_definitions.rs
crates/ingress-http/src/options.rs
crates/ingress-http/src/server.rs

Fix #1219, Based on #1229 
I left some issues as followup as they need support on the partition processor, and they can be easily added later:
* #1235 
* #1233

New Ingress

---

crates/ingress-http/Cargo.toml

This fixes a bug when building the docker image.
I'm not sure why though when i did the PR the first time this was not caught...

Add tokio feature to hyper-util

---

.github/workflows/helm.yml
.github/workflows/release.yml
charts/restate-helm/.helmignore
charts/restate-helm/Chart.yaml
charts/restate-helm/README.md
charts/restate-helm/templates/_helpers.tpl
charts/restate-helm/templates/service.yaml
charts/restate-helm/templates/serviceaccount.yaml
charts/restate-helm/templates/servicemonitor.yaml
charts/restate-helm/templates/statefulset.yaml
charts/restate-helm/values.yaml

Adds a simple helm chart that deploys restate as a single node statefulset

Add helm chart

---

crates/errors/src/error_codes/META0004.md
crates/errors/src/error_codes/META0006.md
crates/errors/src/error_codes/META0009.md
crates/errors/src/error_codes/RT0002.md
crates/errors/src/error_codes/RT0007.md

Update links in errors wrt new documentation structure

Update links in errors wrt new documentation structure

---

Cargo.lock
crates/ingress-dispatcher/src/dispatcher.rs
crates/ingress-dispatcher/src/lib.rs
crates/ingress-http/Cargo.toml
crates/ingress-http/src/handler/awakeables.rs
crates/ingress-http/src/handler/component_handler.rs
crates/ingress-http/src/handler/error.rs
crates/ingress-http/src/handler/tests.rs
crates/ingress-http/src/server.rs
crates/ingress-kafka/src/consumer_task.rs
crates/node-protocol/src/ingress.rs
crates/pb/src/lib.rs
crates/storage-proto/src/lib.rs
crates/types/src/identifiers.rs
crates/types/src/ingress.rs
crates/types/src/invocation.rs
crates/types/src/journal/entries.rs
crates/worker/src/partition/leadership/mod.rs
crates/worker/src/partition/services/deterministic/mod.rs
crates/worker/src/partition/services/non_deterministic/idempotent_invoker.rs
crates/worker/src/partition/services/non_deterministic/mod.rs
crates/worker/src/partition/state_machine/command_interpreter/mod.rs
crates/worker/src/partition/state_machine/command_interpreter/tests.rs
crates/worker/src/partition/state_machine/effects.rs
crates/worker/src/partition/state_machine/mod.rs
crates/worker/src/partition/types.rs

Part of #1324, depends on #1348
This PR wires up the new idempotency feature with the ingress.

Wire up the new idempotency implementation with ingress

---

crates/admin/src/rest_api/components.rs
crates/admin/src/schema_registry/mod.rs
crates/admin/src/schema_registry/updater.rs
crates/ingress-http/src/handler/component_handler.rs
crates/ingress-http/src/lib.rs
crates/meta-rest-model/src/components.rs
crates/schema-api/src/invocation_target.rs
crates/schema-api/src/lib.rs
crates/schema/src/component.rs

Part of #1324, Depends on #1355

Allow to configure the idempotency retention time on a component basis

---

Cargo.lock
crates/ingress-http/src/lib.rs
crates/meta-rest-model/src/components.rs
crates/schema-api/Cargo.toml
crates/schema-api/src/lib.rs
crates/schema/src/component.rs

This should fix the private service e2e test...

Idempotency retention should be a string

---

Cargo.lock
Cargo.toml
crates/bifrost/src/loglets/local_loglet/log_store.rs
crates/core/Cargo.toml
crates/node/Cargo.toml
crates/node/src/lib.rs
crates/node/src/network_server/handler/mod.rs
crates/node/src/network_server/prometheus_helpers.rs
crates/node/src/network_server/service.rs
crates/node/src/network_server/state.rs
crates/node/src/roles/worker.rs
crates/rocksdb/Cargo.toml
crates/rocksdb/src/db_manager.rs
crates/rocksdb/src/error.rs
crates/rocksdb/src/lib.rs
crates/rocksdb/src/rock_access.rs
crates/storage-rocksdb/src/lib.rs
crates/types/Cargo.toml
crates/types/src/arc_util.rs
crates/types/src/config/cli_option_overrides.rs
crates/types/src/config/common.rs
crates/types/src/config/mod.rs
crates/types/src/config/rocksdb.rs
crates/types/src/config/util.rs
server/Cargo.toml
server/src/config_loader.rs
server/src/main.rs

Introduction of RocksDbManager
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1380).
* #1382
* __->__ #1380

Introduction of RocksDbManager

---

Cargo.lock
crates/bifrost/Cargo.toml
crates/bifrost/src/loglet.rs
crates/bifrost/src/loglets/local_loglet/log_store.rs
crates/bifrost/src/loglets/local_loglet/provider.rs
crates/node/src/network_server/handler/mod.rs
crates/rocksdb/src/db_manager.rs
crates/rocksdb/src/error.rs
crates/rocksdb/src/lib.rs
crates/types/src/config/common.rs

Bifrost integration with rocksdb manager
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1382).
* #1383
* __->__ #1382

Bifrost integration with rocksdb manager

---

cli/src/clients/datafusion_helpers.rs
cli/src/commands/components/status/detailed_status.rs
cli/src/commands/invocations/list.rs
cli/src/ui/invocations.rs
crates/storage-query-datafusion/src/invocation_status/row.rs

Fix CLI inbox queries

---

Cargo.lock
crates/benchmarks/Cargo.toml
crates/benchmarks/benches/throughput_parallel.rs
crates/benchmarks/benches/throughput_sequential.rs
crates/benchmarks/src/lib.rs
crates/storage-rocksdb/benches/basic_benchmark.rs

Benchmark update
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1395).
* #1396
* __->__ #1395

Benchmark update

---

crates/admin/src/rest_api/invocations.rs
crates/storage-api/src/outbox_table/mod.rs
crates/storage-proto/proto/dev/restate/storage/v1/domain.proto
crates/storage-proto/src/lib.rs
crates/types/src/invocation.rs
crates/worker/src/partition/state_machine/command_interpreter/mod.rs
crates/worker/src/partition/state_machine/command_interpreter/tests.rs
crates/worker/src/partition/state_machine/effects.rs
crates/worker/src/partition/state_machine/mod.rs

Followup of https://github.com/restatedev/restate/pull/1390, another step towards #1329

Remove `MaybeFullInvocationId`

---

cli/src/app.rs
cli/src/clients/datafusion_helpers.rs
cli/src/commands/deployments/describe.rs
cli/src/commands/deployments/list.rs
cli/src/commands/deployments/register.rs
cli/src/commands/deployments/remove.rs
cli/src/commands/invocations/describe.rs
cli/src/commands/invocations/list.rs
cli/src/commands/mod.rs
cli/src/commands/services/describe.rs
cli/src/commands/services/list.rs
cli/src/commands/services/mod.rs
cli/src/commands/services/status/agg_status.rs
cli/src/commands/services/status/detailed_status.rs
cli/src/commands/services/status/mod.rs
cli/src/commands/state/edit.rs
cli/src/commands/state/get.rs
cli/src/ui/invocations.rs
cli/src/ui/mod.rs
cli/src/ui/service_handlers.rs
crates/storage-api/proto/dev/restate/storage/v1/domain.proto
crates/storage-api/src/invocation_status_table/mod.rs
crates/storage-api/src/storage.rs
crates/worker/src/partition/state_machine/mod.rs

* Started the renaming components -> services, this will probably need another pass after i rename the admin api
* Add StatusTimestamps to `InvocationStatus::Completed`
* Fix a case where `invocation list` would panic
* Remove `inboxed` status and add `completed` status

More improvements to CLI

---

Cargo.lock
cli/Cargo.toml
cli/src/clients/datafusion_http_client.rs
cli/src/commands/state/util.rs

This improves a bit the handling of sql queries.

Add mapping to rust structs for sql queries

---

Cargo.lock
Cargo.toml
crates/bifrost/src/loglets/local_loglet/log_store.rs
crates/rocksdb/Cargo.toml
crates/rocksdb/src/db_manager.rs
crates/rocksdb/src/db_spec.rs
crates/rocksdb/src/lib.rs
crates/rocksdb/src/rock_access.rs
crates/storage-rocksdb/src/lib.rs
crates/types/src/config/common.rs
crates/types/src/config/rocksdb.rs
crates/worker/src/lib.rs

[RocksDb] Support for CF name pattern matching
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1427).
* #1433
* #1432
* #1431
* __->__ #1427
* #1424

[RocksDb] Support for CF name pattern matching

---

Cargo.toml
crates/bifrost/src/loglets/local_loglet/log_store.rs
crates/bifrost/src/loglets/local_loglet/log_store_writer.rs
crates/bifrost/src/loglets/local_loglet/mod.rs
crates/metadata-store/src/local/store.rs
crates/rocksdb/src/rock_access.rs
crates/storage-rocksdb/src/lib.rs

Use multi-threaded-cf rocksdb
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1431).
* #1435
* #1433
* #1432
* __->__ #1431

Use multi-threaded-cf rocksdb

---

Cargo.lock
Cargo.toml
crates/bifrost/src/loglets/local_loglet/log_store.rs
crates/bifrost/src/loglets/local_loglet/log_store_writer.rs
crates/bifrost/src/loglets/local_loglet/mod.rs
crates/metadata-store/src/local/store.rs
crates/node/src/network_server/handler/mod.rs
crates/rocksdb/src/db_manager.rs
crates/rocksdb/src/db_spec.rs
crates/rocksdb/src/lib.rs
crates/rocksdb/src/rock_access.rs
crates/storage-rocksdb/src/lib.rs
crates/storage-rocksdb/src/writer.rs

Support dynamic opening of cfs in rocksdb manager
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1433).
* #1435
* __->__ #1433
* #1432
* #1431

Support dynamic opening of cfs in rocksdb manager

---

Cargo.lock
crates/metadata-store/Cargo.toml
crates/metadata-store/src/local/service.rs
crates/metadata-store/src/local/store.rs
crates/metadata-store/src/local/tests.rs
crates/node/src/lib.rs
crates/rocksdb/src/db_manager.rs

Integrate local metadata store with new RocksDbManager.

Integrate local metadata store with new RocksDbManager

---

Cargo.lock
crates/bifrost/Cargo.toml
crates/bifrost/src/loglets/local_loglet/log_state.rs
crates/bifrost/src/loglets/local_loglet/log_store.rs
crates/bifrost/src/loglets/local_loglet/log_store_writer.rs
crates/core/src/metadata_store/mod.rs
crates/core/src/network/message_router.rs
crates/core/src/network/network_sender.rs
crates/core/src/test_env.rs
crates/metadata-store/Cargo.toml
crates/metadata-store/src/local/store.rs
crates/network/src/connection.rs
crates/network/src/connection_manager.rs
crates/network/src/networking.rs
crates/node-protocol/Cargo.toml
crates/node-protocol/proto/common.proto
crates/node-protocol/src/codec.rs
crates/node-protocol/src/common.rs
crates/node-protocol/src/error.rs
crates/node-protocol/src/ingress.rs
crates/node-protocol/src/lib.rs
crates/node-protocol/src/metadata.rs
crates/node/Cargo.toml
crates/node/src/lib.rs
crates/node/src/roles/worker.rs
crates/types/src/storage.rs
crates/worker/Cargo.toml
crates/worker/src/partition/services/mod.rs

Replace bincode with StorageCodec and flexbuffers.
This fixes #1411.

Replace bincode with StorageCodec and flexbuffers

---

cli/src/clients/datafusion_helpers.rs
cli/src/ui/invocations.rs

Include server string for deployments in invocations list

---

crates/admin/src/schema_registry/updater.rs

See https://github.com/restatedev/service-protocol/blob/main/deployment_manifest_schema.json#L70 for more details.

Fix bad parsing of the descriptor for handler input validation rules

---

crates/metadata-store/src/local/tests.rs
crates/node/src/lib.rs

Use metadata store RocksDbOptions instead of common RocksDbOptions

Use metadata store RocksDbOptions instead of common RocksDbOptions

---

.github/workflows/binaries.yml
.github/workflows/docker.yml
.github/workflows/npm.yml
.github/workflows/release.yml
crates/service-protocol/service-protocol/.github/workflows/lint.yaml

Bump actions/upload-artifact to v4 and docker/build-push-action to v5

Bump actions/upload-artifact to v4 and docker/build-push-action to v5

---

crates/partition-store/src/partition_store.rs

use correct WriteOptions
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1487).
* #1488
* __->__ #1487

use correct WriteOptions

---

crates/bifrost/src/loglets/local_loglet/log_store.rs
crates/bifrost/src/loglets/local_loglet/log_store_writer.rs
crates/node/src/network_server/handler/mod.rs
crates/partition-store/src/partition_store.rs
crates/partition-store/src/partition_store_manager.rs
crates/rocksdb/src/db_manager.rs
crates/rocksdb/src/lib.rs

tx_batch and move sync db behind inner
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1488).
* __->__ #1488
* #1487

tx_batch and move sync db behind inner

---

Cargo.toml
crates/bifrost/benches/append_throughput.rs
crates/bifrost/src/loglets/local_loglet/log_store.rs
crates/bifrost/src/loglets/local_loglet/log_store_writer.rs
crates/metadata-store/src/local/store.rs
crates/node/src/network_server/handler/mod.rs
crates/node/src/network_server/metrics.rs
crates/partition-store/src/partition_store.rs
crates/partition-store/src/partition_store_manager.rs
crates/rocksdb/src/background.rs
crates/rocksdb/src/db_manager.rs
crates/rocksdb/src/db_spec.rs
crates/rocksdb/src/lib.rs
crates/rocksdb/src/metric_definitions.rs
crates/rocksdb/src/perf.rs
crates/rocksdb/src/rock_access.rs
crates/types/src/config/common.rs
crates/types/src/config/rocksdb.rs
crates/worker/src/metric_definitions.rs
crates/worker/src/partition/mod.rs

More metrics on PP loop.
I'll rework the async telemetry technique in a future follow PR to ensure we have correct understanding of latencies.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1497).
* #1514
* #1500
* #1511
* __->__ #1497
* #1493

More metrics on PP loop.

---

crates/ingress-http/src/handler/path_parsing.rs

Fix little bug where we didn't url encode the workflow key

Workflow key should be url encoded

---

Cargo.lock
Cargo.toml
tools/mock-service-endpoint/Cargo.toml
tools/mock-service-endpoint/src/main.rs

mock service endpoint
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1556).
* #1565
* #1563
* #1558
* #1557
* __->__ #1556

mock service endpoint

---

Cargo.lock
Cargo.toml
crates/bifrost/Cargo.toml
crates/bifrost/src/bifrost.rs
crates/bifrost/src/error.rs
crates/bifrost/src/lib.rs
crates/bifrost/src/loglet.rs
crates/bifrost/src/loglets/local_loglet/keys.rs
crates/bifrost/src/loglets/local_loglet/log_store.rs
crates/bifrost/src/loglets/local_loglet/mod.rs
crates/bifrost/src/loglets/local_loglet/provider.rs
crates/bifrost/src/loglets/local_loglet/read_stream.rs
crates/bifrost/src/loglets/local_loglet/utils.rs
crates/bifrost/src/loglets/memory_loglet.rs
crates/bifrost/src/read_stream.rs
crates/core/src/task_center.rs
crates/node/Cargo.toml
crates/partition-store/src/partition_store.rs
crates/rocksdb/src/db_manager.rs
crates/types/src/config/common.rs
crates/types/src/config/rocksdb.rs
crates/types/src/config/worker.rs
crates/worker/src/partition/mod.rs
tools/bifrost-benchpress/Cargo.toml
tools/bifrost-benchpress/src/write_to_read.rs
tools/mock-service-endpoint/Cargo.toml
tools/mock-service-endpoint/src/main.rs

[Bifrost] bifrost loglet tailing read streams
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1558).
* #1565
* #1563
* __->__ #1558
* #1557
* #1556

[Bifrost] bifrost loglet tailing read streams

---

Cargo.lock
Cargo.toml
crates/bifrost/Cargo.toml
crates/bifrost/src/bifrost.rs
crates/bifrost/src/error.rs
crates/bifrost/src/lib.rs
crates/bifrost/src/loglet.rs
crates/bifrost/src/loglets/local_loglet/keys.rs
crates/bifrost/src/loglets/local_loglet/log_store.rs
crates/bifrost/src/loglets/local_loglet/mod.rs
crates/bifrost/src/loglets/local_loglet/provider.rs
crates/bifrost/src/loglets/local_loglet/read_stream.rs
crates/bifrost/src/loglets/local_loglet/utils.rs
crates/bifrost/src/loglets/memory_loglet.rs
crates/bifrost/src/read_stream.rs
crates/core/src/task_center.rs
crates/node/Cargo.toml
crates/partition-store/src/partition_store.rs
crates/rocksdb/src/db_manager.rs
crates/types/src/config/common.rs
crates/types/src/config/rocksdb.rs
crates/types/src/config/worker.rs
crates/worker/src/partition/mod.rs
tools/bifrost-benchpress/Cargo.toml
tools/bifrost-benchpress/src/write_to_read.rs
tools/mock-service-endpoint/Cargo.toml
tools/mock-service-endpoint/src/main.rs

Reduce cost of TaskCenter atomics
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1563).
* #1565
* __->__ #1563
* #1558
* #1557
* #1556

Reduce cost of TaskCenter atomics

---

Cargo.lock
Cargo.toml
crates/benchmarks/src/lib.rs
crates/bifrost/src/loglets/local_loglet/log_store.rs
crates/bifrost/src/loglets/local_loglet/log_store_writer.rs
crates/bifrost/src/loglets/local_loglet/provider.rs
crates/metadata-store/src/local/service.rs
crates/metadata-store/src/local/store.rs
crates/metadata-store/src/local/tests.rs
crates/node/src/lib.rs
crates/node/src/network_server/handler/mod.rs
crates/partition-store/src/partition_store.rs
crates/partition-store/src/partition_store_manager.rs
crates/rocksdb/src/db_manager.rs
crates/types/src/arc_util.rs
crates/types/src/config/bifrost.rs
crates/types/src/config/cli_option_overrides.rs
crates/types/src/config/common.rs
crates/types/src/config/metadata_store.rs
crates/types/src/config/mod.rs
crates/types/src/config/rocksdb.rs
crates/types/src/config/worker.rs
server/src/config_loader.rs
server/src/signal.rs

Metadata store uses new memory budgeting
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1573).
* #1575
* __->__ #1573
* #1572

Metadata store uses new memory budgeting

---

Cargo.lock
Cargo.toml
crates/bifrost/src/loglets/local_loglet/read_stream.rs
server/Cargo.toml
server/src/main.rs

increase nofile limit on startup
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1575).
* __->__ #1575
* #1576

increase nofile limit on startup

---

crates/bifrost/src/loglets/local_loglet/log_store_writer.rs
crates/partition-store/src/partition_store.rs
crates/types/src/config/bifrost.rs
crates/types/src/config/worker.rs

allow changing io-mode for writes via hidden config

allow changing io-mode for writes via hidden config

---

crates/invoker-impl/src/invocation_task/mod.rs
crates/invoker-impl/src/metric_definitions.rs

Invoker task duration histogram

Invoker task duration histogram

---

crates/types/src/config/bifrost.rs
crates/types/src/config/worker.rs

tune defaults with new bench results

tune defaults with new bench results

---

.github/workflows/ci.yml
Cargo.lock
server/Cargo.toml

Add io-uring as feature

---

crates/partition-store/src/inbox_table/mod.rs
crates/rocksdb/src/perf.rs

[RocksDb] Fixing RocksDbPerfGuard's semantics and performance
RocksDBPerfGuard was `Send` and this was incorrect since the underlying stats collection happens on a thread-local. This PR addresses 2 issues:
1. Removes the use of Rust's _slow_ thread locals as the the underlying perfcontext is already thread-local. This _potentially_ reduces CPU overhead when stats are disabled (when enabled, thread-local's access cost is overshadowed by the cost of histogram! anyway)
2. Makes RocksDBPerfGuard `!Send` to avoid any potential misuse.
This also fixes the single instance where it was used across await points (despite being correct).

[RocksDb] Fixing RocksDbPerfGuard's semantics and performance

---

Cargo.lock
crates/storage-query-postgres/Cargo.toml
crates/storage-query-postgres/src/extended_query.rs
crates/storage-query-postgres/src/pgwire_server.rs
crates/storage-query-postgres/src/service.rs

pgwire author here. This patch just updates pgwire library and adopt its breaking API changes.

feat: update pgwire to latest release

---

Cargo.lock
crates/storage-query-postgres/Cargo.toml
crates/storage-query-postgres/src/extended_query.rs
crates/storage-query-postgres/src/pgwire_server.rs
crates/storage-query-postgres/src/service.rs

Backport of #1634 to `release-1.0`.

[BP] feat: update pgwire to latest release

---

crates/types/src/config/mod.rs
server/src/main.rs

Backport of #1630 to `release-1.0`.

[BP] Delete the node dir when wiping all

---

Cargo.lock
Cargo.toml

Update rocksdb dependency
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1653).
* #1652
* #1647
* #1645
* #1644
* #1643
* __->__ #1653

Update rocksdb dependency

---

Cargo.lock
Cargo.toml

Backport https://github.com/restatedev/restate/pull/1679

Remove two default imports from datafusion dependency (backport)

---

crates/cluster-controller/src/cluster_state.rs
crates/cluster-controller/src/service.rs
crates/node/src/lib.rs
crates/node/src/roles/admin.rs
crates/node/src/roles/worker.rs
crates/worker/src/lib.rs
deny.toml

Backport of #1686 to `release-1.0`.

[BP] Start ingress only after all partitions have a leader 

---

Cargo.lock
Cargo.toml
crates/admin/src/cluster_controller/service.rs
crates/bifrost/Cargo.toml
crates/bifrost/src/bifrost.rs
crates/bifrost/src/bifrost_admin.rs
crates/bifrost/src/error.rs
crates/bifrost/src/lib.rs
crates/bifrost/src/loglet/loglet_tests.rs
crates/bifrost/src/loglet/mod.rs
crates/bifrost/src/loglet/provider.rs
crates/bifrost/src/loglet/util.rs
crates/bifrost/src/loglet_wrapper.rs
crates/bifrost/src/providers/local_loglet/mod.rs
crates/bifrost/src/providers/local_loglet/provider.rs
crates/bifrost/src/providers/local_loglet/read_stream.rs
crates/bifrost/src/providers/memory_loglet.rs
crates/bifrost/src/providers/replicated_loglet/provider.rs
crates/bifrost/src/read_stream.rs
crates/bifrost/src/types.rs
crates/core/src/metadata/mod.rs
crates/core/src/metadata_store/mod.rs
crates/node/src/roles/admin.rs
crates/types/src/config/bifrost.rs
crates/types/src/logs/builder.rs
crates/types/src/logs/metadata.rs
crates/worker/src/partition/mod.rs
crates/worker/src/partition/shuffle.rs
tools/bifrost-benchpress/src/write_to_read.rs

[Bifrost] Remove pin projection from loglet impls
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1757).
* __->__ #1757
* #1753
* #1747
* #1744
* #1743
* #1742

[Bifrost] Remove pin projection from loglet impls

---

.github/workflows/binaries.yml

With these changes it works (https://github.com/restatedev/restate/pkgs/container/restate-cli)

Fixes for Docker CLI build

---

crates/bifrost/src/bifrost.rs
crates/bifrost/src/loglet/mod.rs
justfile

Run doctests using cargo test

---

Cargo.lock
crates/admin/src/rest_api/invocations.rs
crates/admin/src/rest_api/services.rs
crates/bifrost/Cargo.toml
crates/bifrost/src/bifrost.rs
crates/bifrost/src/loglet/loglet_tests.rs
crates/bifrost/src/providers/local_loglet/mod.rs
crates/bifrost/src/providers/memory_loglet.rs
crates/ingress-dispatcher/src/dispatcher.rs
crates/types/src/config/bifrost.rs
crates/types/src/logs/builder.rs
crates/types/src/logs/mod.rs
crates/wal-protocol/src/lib.rs
crates/worker/src/partition/action_effect_handler.rs
crates/worker/src/partition/shuffle.rs

[Bifrost] DRY loglet tests setup
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1775).
* #1776
* __->__ #1775
* #1772

[Bifrost] DRY loglet tests setup

---

.github/workflows/ci.yml
Cargo.lock

I do the mistake of forgetting to add the `Cargo.lock` updates all the times when committing to this repo :)

Make sure Cargo.lock is updated when committing

---

crates/admin/src/cluster_controller/service.rs

Until we can share partition processor snapshots between Restate nodes (e.g. by fetching them from S3), we can only trim the log if all known nodes have reached the trim point. Otherwise, we risk that a node that is currently not available needs log entries which were trimmed. One crucial assumption is that no new nodes will join the cluster once the first log trimming has happened. Otherwise for this to work, we also need the sharing of partition processor snapshots.
This fixes #1781.

Check if all nodes have reported a persisted lsn before trimming the log

---

crates/types/src/logs/mod.rs
crates/types/src/storage.rs

[Bifrost] Add WithKeys and BodyWithKeys helper types
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1808).
* #1816
* #1813
* #1809
* __->__ #1808

[Bifrost] Add WithKeys and BodyWithKeys helper types

---

Cargo.lock
crates/admin/src/cluster_controller/service.rs
crates/bifrost/src/bifrost.rs
crates/bifrost/src/loglet/loglet_tests.rs
crates/bifrost/src/loglet/mod.rs
crates/bifrost/src/loglet_wrapper.rs
crates/bifrost/src/payload.rs
crates/bifrost/src/providers/local_loglet/log_state.rs
crates/bifrost/src/providers/local_loglet/read_stream.rs
crates/bifrost/src/providers/memory_loglet.rs
crates/bifrost/src/read_stream.rs
crates/bifrost/src/record.rs
crates/metadata-store/src/local/store.rs
crates/storage-api/src/storage.rs
crates/types/Cargo.toml
crates/types/src/logs/mod.rs
crates/types/src/storage.rs
crates/worker/src/partition/mod.rs
crates/worker/src/partition/shuffle.rs
tools/bifrost-benchpress/src/write_to_read.rs

[Bifrost] Mechanical rename to prepare for new payload types
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1813).
* #1816
* __->__ #1813
* #1809
* #1808

[Bifrost] Mechanical rename to prepare for new payload types

---

cli/src/clients/datafusion_helpers.rs
cli/src/commands/services/status/mod.rs
cli/src/ui/invocations.rs
crates/storage-query-datafusion/src/context.rs
crates/storage-query-datafusion/src/invocation_status/schema.rs
crates/storage-query-datafusion/src/table_docs.rs

Parse the scheduled invocation variant in CLI

---

crates/bifrost/src/providers/local_loglet/mod.rs
crates/bifrost/src/providers/local_loglet/read_stream.rs

When the LocalLogletReadStream filters out a record, it needs to update the read pointer used in the inner loop. Otherwise it will go out of sync and panic on the next read. This commit fixes this problem.
This fixes #1859.

Update read_pointer when filtering out record

---

crates/worker/src/partition/state_machine/mod.rs
crates/worker/src/partition/state_machine/tests/delayed_send.rs
crates/worker/src/partition/state_machine/tests/idempotency.rs
crates/worker/src/partition/state_machine/tests/kill_cancel.rs
crates/worker/src/partition/state_machine/tests/mod.rs
crates/worker/src/partition/state_machine/tests/workflow.rs

Leftovers from previous PRs (in particular, the flatten effects PR)

Few improvements to state machine module

---

crates/storage-query-datafusion/src/context.rs
crates/storage-query-datafusion/src/invocation_status/row.rs
crates/storage-query-datafusion/src/invocation_status/schema.rs
crates/storage-query-datafusion/src/table_docs.rs

Expose new state transitions timestamps in SQL

---

Cargo.lock
crates/admin/src/cluster_controller/cluster_state.rs
crates/bifrost/src/background_appender.rs
crates/core/Cargo.toml
crates/core/src/error.rs
crates/core/src/lib.rs
crates/core/src/task_center.rs
crates/core/src/task_center_types.rs
crates/log-server/Cargo.toml
crates/node/Cargo.toml
crates/node/src/network_server/handler/mod.rs
crates/node/src/network_server/prometheus_helpers.rs
crates/tracing-instrumentation/Cargo.toml
crates/types/src/config/cli_option_overrides.rs
crates/types/src/logs/mod.rs
tools/bifrost-benchpress/Cargo.toml
tools/bifrost-benchpress/src/append_latency.rs
tools/bifrost-benchpress/src/lib.rs
tools/bifrost-benchpress/src/main.rs
tools/bifrost-benchpress/src/util.rs
tools/bifrost-benchpress/src/write_to_read.rs

[Bifrost] Benchpress minor improvements
- Support background appender
- Configurable base-dir, and other test parameters
- Uses the new unmanaged TC tasks
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1855).
* #1868
* #1867
* #1864
* #1863
* #1862
* #1861
* #1856
* __->__ #1855
* #1850

[Bifrost] Benchpress minor improvements

---

Cargo.lock
crates/core/src/network/connection_manager.rs
crates/types/src/config/worker.rs
crates/worker/Cargo.toml
crates/worker/src/lib.rs
crates/worker/src/partition_processor_manager.rs

Invoker per PP

---

crates/worker/src/partition_processor_manager.rs

remove un-necessary clone

---

crates/admin/src/cluster_controller/scheduler.rs
crates/admin/src/cluster_controller/service.rs
crates/bifrost/src/error.rs
crates/bifrost/src/loglet/error.rs
crates/bifrost/src/providers/local_loglet/log_store.rs
crates/core/src/metadata/manager.rs
crates/core/src/network/connection_manager.rs
crates/core/src/test_env.rs
crates/node/src/lib.rs
crates/types/src/config/common.rs
crates/types/src/errors.rs
crates/types/src/logs/metadata.rs
crates/types/src/nodes_config.rs

MaybeRetryableError as common utility
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1896).
* __->__ #1896
* #1895

MaybeRetryableError as common utility

---

Cargo.lock
crates/admin/src/rest_api/deployments.rs
crates/admin/src/schema_registry/mod.rs
crates/invoker-impl/src/invocation_task/service_protocol_runner.rs
crates/service-client/src/http.rs
crates/service-client/src/lib.rs
crates/service-protocol/Cargo.toml
crates/service-protocol/src/discovery.rs

HTTP 1.1 now works with ALPN

---

crates/worker/src/partition/state_machine/mod.rs
crates/worker/src/partition/state_machine/tests/kill_cancel.rs

When loading the journal, we were mistakenly filtering out promise journal entries. Just changed this code now to catch-all completable journal entries (which should be the normal behavior)

Fix bug wrt cancellation and promise-related entries

---

crates/storage-query-datafusion/src/idempotency/row.rs
crates/storage-query-datafusion/src/journal/row.rs
crates/storage-query-datafusion/src/table_util.rs

See https://github.com/restatedev/restate/pull/1919#discussion_r1743878444 for more details

Make sure filling datafusion rows won't panic the runtime

---

Cargo.lock
Cargo.toml

Upgrade tokio
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1926).
* #1929
* #1928
* #1927
* __->__ #1926

Upgrade tokio

---

crates/types/protobuf/restate/common.proto
crates/types/src/net/log_server.rs
crates/types/src/net/mod.rs
crates/types/src/net/replicated_loglet.rs

[ReplicatedLoglet] Define Append Messages
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1956).
* #1957
* __->__ #1956

[ReplicatedLoglet] Define Append Messages

---

crates/bifrost/src/loglet/mod.rs

implement defered loglet commit resolver
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1968).
* #1970
* #1971
* #1969
* __->__ #1968

implement defered loglet commit resolver

---

crates/core/src/network/net_util.rs

When remote clients disconnect, Restate sometimes logs a full backtrace for essentially benign "connection reset by peer" errors. With this change we silence this behavior, limiting it to a debug-level log only if Hyper reports an incomplete message.
Encountered this while testing some new `restatectl` subcommands. It only happens sometimes - I'm guessing it's a race condition when making gRPC requests between who hangs up the TCP connection first. Occasionally I was seeing these when making a simple `restatectl logs trim` call from localhost:
```
2024-09-16T10:25:48.154258Z ERROR restate_core::task_center
Task 69 failed with: failed handling hyper connection: connection error
Caused by:
0: connection error
1: connection reset
Stack backtrace:
0: …
```

Reduce noise on peer disconnect

---

crates/bifrost/src/providers/replicated_loglet/sequencer/mod.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/node.rs
crates/core/src/network/connection.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/1984).
* __->__ #1984
* #1971

Review + rebase on latest networking changes

---

crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/mod.rs
crates/bifrost/src/providers/replicated_loglet/network.rs
crates/bifrost/src/providers/replicated_loglet/provider.rs
crates/bifrost/src/providers/replicated_loglet/record_cache.rs
crates/bifrost/src/providers/replicated_loglet/rpc_routers.rs
crates/types/src/net/replicated_loglet.rs

This introduces a few more bits that happen during loglet instantiation.

[Bifrost] More Replicated Loglet Scaffolding

---

Cargo.lock
Cargo.toml
crates/bifrost/Cargo.toml
crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/mod.rs
crates/bifrost/src/providers/replicated_loglet/record_cache.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/append.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/mod.rs
crates/types/src/logs/mod.rs

[ReplicatedLoglet] Record Cache
Summary:
Initial implementation of a shared record cache

[ReplicatedLoglet] Record Cache

---

crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/mod.rs

[Sequencer] Renames for clarity

[Sequencer] Renames for clarity

---

.github/workflows/binaries.yml
docker/Dockerfile

- Add curl to the server image
- Use alpine in the CLI image so it has a shell

Dockerfile QoL improvements

---

crates/bifrost/src/providers/replicated_loglet/error.rs
crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/tasks/mod.rs
crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs
crates/types/src/config/bifrost.rs

Initial implementation for the seal task for the replicated loglet. The seal task is not responsible for repairing the tail, just executes seal on an f-majority of nodes of the nodeset.

[Bifrost] Seal task for replicated loglet

---

.github/workflows/ci.yml
.github/workflows/docker.yml

Leads to significant speedups. Still left to do is to update the e2e to also use 16x

Test 16x warp runner

---

crates/node/src/lib.rs
crates/node/src/roles/admin.rs

Admin role should talk to advertised node address

---

Cargo.lock
crates/bifrost/Cargo.toml
crates/bifrost/src/loglet/loglet_tests.rs
crates/bifrost/src/loglet/util.rs
crates/bifrost/src/providers/memory_loglet.rs
crates/bifrost/src/providers/replicated_loglet/log_server_manager.rs
crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/metric_definitions.rs
crates/bifrost/src/providers/replicated_loglet/mod.rs
crates/bifrost/src/providers/replicated_loglet/read_path/mod.rs
crates/bifrost/src/providers/replicated_loglet/read_path/read_stream.rs
crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs
crates/bifrost/src/providers/replicated_loglet/record_cache.rs
crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs
crates/bifrost/src/record.rs
crates/core/src/network/connection.rs
crates/core/src/network/networking.rs
crates/core/src/network/rpc_router.rs
crates/core/src/network/types.rs
crates/core/src/task_center_types.rs
crates/log-server/src/loglet_worker.rs
crates/types/src/replicated_loglet/params.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2028).
* #2039
* __->__ #2028

[Bifrost] ReplicatedLoglet read stream

---

crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs

[Sequencer] Notify commit of seal
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2041).
* #2024
* __->__ #2041

[Sequencer] Notify commit of seal

---

crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/metric_definitions.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/mod.rs
crates/types/src/replicated_loglet/params.rs
crates/types/src/replicated_loglet/spread.rs

[Sequencer] Add traces and metrics to the sequencer

[Sequencer] Add traces and metrics to the sequencer

---

crates/bifrost/src/providers/replicated_loglet/replication/checker.rs

Hit this condition writing tests for the replicated loglet controller.
Before:
```
START             restate-bifrost providers::replicated_loglet::replication::checker::tests::test_dont_panic
running 1 test
test providers::replicated_loglet::replication::checker::tests::test_dont_panic ... thread 'providers::replicated_loglet::replication::checker::tests::test_dont_panic' panicked at crates/bifrost/src/providers/replicated_loglet/replication/checker.rs:239:13:
attempt to subtract with overflow
stack backtrace:
0: rust_begin_unwind
at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
1: core::panicking::panic_fmt
at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
2: core::panicking::panic_const::panic_const_sub_overflow …
```

Fix NodeSetChecker underflow panic when NodeSet < Replication

---

crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/mod.rs
crates/types/src/time.rs

[Sequencer] Some code cleanup and improvments

[Sequencer] Some code cleanup and improvments

---

crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/network.rs
crates/bifrost/src/providers/replicated_loglet/provider.rs
crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs
crates/types/src/logs/metadata.rs
crates/types/src/net/replicated_loglet.rs

[ReplicatedLoglet] Handle Append messages
Summary:
Handle requests from remote loglets to append records

[ReplicatedLoglet] Handle Append messages

---

crates/bifrost/src/appender.rs
crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs
crates/bifrost/src/providers/replicated_loglet/replication/checker.rs
crates/bifrost/src/providers/replicated_loglet/replication/spread_selector.rs
crates/bifrost/src/providers/replicated_loglet/rpc_routers.rs
crates/bifrost/src/providers/replicated_loglet/tasks/digests.rs
crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs
crates/bifrost/src/providers/replicated_loglet/tasks/mod.rs
crates/bifrost/src/providers/replicated_loglet/tasks/repair_tail.rs
crates/core/src/metadata/manager.rs
crates/core/src/network/networking.rs
crates/log-server/src/rocksdb_logstore/builder.rs
crates/types/src/config/networking.rs
crates/types/src/net/metadata.rs
crates/types/src/replicated_loglet/params.rs
crates/types/src/replicated_loglet/spread.rs
crates/worker/src/partition_processor_manager.rs
tools/mock-service-endpoint/Cargo.toml

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2056).
* #2064
* __->__ #2056
* #2046

Random Fixes

---

crates/bifrost/src/providers/replicated_loglet/network.rs
crates/bifrost/src/providers/replicated_loglet/provider.rs

[ReplicatedLoglet] Sync to metadata version on append

[ReplicatedLoglet] Sync to metadata version on append

---

.github/workflows/docker.yml

This required a small fix to their cache impl

Enable warpbuild for sccache in docker build

---

Cargo.lock
crates/admin/protobuf/cluster_ctrl_svc.proto
crates/bifrost/src/bifrost_admin.rs
crates/node/src/lib.rs
crates/node/src/network_server/handler/cluster_ctrl.rs
crates/node/src/network_server/service.rs
crates/types/src/logs/metadata.rs
tools/restatectl/Cargo.toml
tools/restatectl/src/commands/log/mod.rs
tools/restatectl/src/commands/log/reconfigure.rs

Implement `restatectl logs reconfigure` command

Implement `restatectl logs reconfigure` command

---

crates/local-cluster-runner/src/node/mod.rs
server/tests/cluster.rs

Reenable replicated-loglet cluster test.

Reenable replicated-loglet cluster test

---

crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs
crates/core/src/metadata/manager.rs
crates/core/src/network/networking.rs
crates/worker/src/partition/leadership.rs
crates/worker/src/partition/mod.rs
crates/worker/src/partition_processor_manager.rs

- Detection of CatchingUp->Active fix.
- Retries for writing AnnounceLeader message
- Reducing logging verbosity in places
- Adding logs in others

Various fixes

---

crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs

[Sequencer] Graceful shutdown
Summary:
Handle shutdown error and give up on appends

[Sequencer] Graceful shutdown

---

crates/bifrost/src/providers/replicated_loglet/network.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2127).
* #2128
* __->__ #2127

Fix GetSequencerState

---

crates/ingress-http/src/handler/error.rs
crates/ingress-http/src/handler/invocation.rs
crates/ingress-http/src/handler/path_parsing.rs
crates/ingress-http/src/handler/service_handler.rs
crates/ingress-http/src/handler/workflow.rs

Make 404 error more verbose in obvious cases

---

crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/network.rs
crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs
crates/types/src/config/bifrost.rs
crates/types/src/net/replicated_loglet.rs

Adds a whole lot of logging temporarily as well.

[Bifrost] Fixing overload, among other things

---

crates/types/src/schema/invocation_target.rs

Make the input rules output less confusing

---

crates/types/service-protocol/dev/restate/service/protocol.proto
crates/types/src/journal/entries.rs
crates/types/src/service_protocol.rs
crates/worker/src/invoker_integration.rs
crates/worker/src/partition/state_machine/mod.rs
crates/worker/src/partition/state_machine/tests/mod.rs

Implement call/one way call from context using idempotency key

---

Cargo.lock
crates/bifrost/src/bifrost.rs
crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/network.rs
crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/mod.rs
crates/core/Cargo.toml
crates/core/src/network/connection_manager.rs
crates/core/src/network/types.rs
crates/tracing-instrumentation/src/lib.rs
crates/types/protobuf/restate/node.proto
crates/types/src/protobuf.rs

bifrost traces and instrumentations
Summary:
This is an example cross nodes traces to show
how this can easily work across nodes
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2168).
* __->__ #2168
* #2167

bifrost traces and instrumentations

---

Cargo.lock
crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
crates/core/src/network/types.rs
crates/ingress-http/src/handler/service_handler.rs
crates/log-server/src/loglet_worker.rs
crates/node/Cargo.toml
crates/node/src/lib.rs
crates/tracing-instrumentation/Cargo.toml
crates/tracing-instrumentation/src/exporter.rs
crates/tracing-instrumentation/src/lib.rs
crates/types/src/protobuf.rs
server/Cargo.toml

Even more instrumentations
Summary:
Adding more instrumentations that shows the internal operation
of bifrost and replicated loglet
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2171).
* __->__ #2171
* #2170

Even more instrumentations

---

cli/src/clients/datafusion_helpers.rs

[CLI] r/Side Effect/Run

---

.github/workflows/ci.yml

This feature doesn't exist anymore

Remove the neo invocation status CI run

---

crates/log-server/build.rs
crates/log-server/protobuf/log_server_svc.proto
crates/log-server/src/grpc_svc_handler.rs
crates/log-server/src/loglet_worker.rs
crates/log-server/src/logstore.rs
crates/log-server/src/metadata.rs
crates/log-server/src/network.rs
crates/log-server/src/rocksdb_logstore/store.rs
crates/log-server/src/service.rs
crates/types/build.rs
crates/types/protobuf/restate/log_server_common.proto
crates/types/src/net/log_server.rs
crates/types/src/protobuf.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2222).
* #2257
* #2256
* #2231
* #2230
* #2229
* __->__ #2222

Implementation of GetDigest and GetLogletInfo in LogServer gRPC

---

Cargo.lock
crates/core/protobuf/node_svc.proto
crates/node/src/network_server/grpc_svc_handler.rs
crates/types/protobuf/restate/node.proto
crates/types/src/net/log_server.rs
crates/types/src/net/metadata.rs
deny.toml
tools/restatectl/Cargo.toml
tools/restatectl/src/app.rs
tools/restatectl/src/commands/replicated_loglet/info.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2256).
* #2257
* __->__ #2256
* #2263

Exposes fetching metadata through NodeSvc

---

deny.toml

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2263).
* #2257
* #2256
* __->__ #2263

Ignore instant being unmaintained

---

crates/admin/src/cluster_controller/service.rs
crates/bifrost/src/providers/replicated_loglet/network.rs
crates/core/src/network/message_router.rs
crates/log-server/src/network.rs
crates/node/src/roles/base.rs
crates/storage-query-datafusion/src/remote_query_scanner_server.rs
crates/worker/src/partition_processor_manager.rs

A reusable MessageStream type alias #cleanup
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2249).
* #2252
* #2250
* __->__ #2249

A reusable MessageStream type alias #cleanup

---

crates/rocksdb/src/db_manager.rs
crates/types/src/config/rocksdb.rs

Configurable RocksDB info logs
Fixes #2216

Configurable RocksDB info logs

---

crates/admin/src/cluster_controller/scheduler.rs
crates/admin/src/cluster_controller/service.rs
crates/types/src/net/mod.rs
crates/worker/src/lib.rs
crates/worker/src/partition_processor_manager/mod.rs

Remove Attach rpc request
Fixes #2237
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2250).
* #2252
* __->__ #2250

Remove Attach rpc request

---

Cargo.lock
crates/admin/src/cluster_controller/cluster_state_refresher.rs
crates/admin/src/cluster_controller/service.rs
crates/bifrost/src/loglet/util.rs
crates/bifrost/src/loglet_wrapper.rs
crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/provider.rs
crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
crates/core/src/metadata/manager.rs
crates/core/src/network/connection.rs
crates/core/src/network/error.rs
crates/core/src/network/networking.rs
crates/core/src/network/rpc_router.rs
crates/core/src/network/types.rs
crates/invoker-impl/Cargo.toml
crates/invoker-impl/src/lib.rs
crates/log-server/src/loglet_worker.rs
crates/types/src/logs/tail.rs
crates/worker/src/partition/mod.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2281).
* __->__ #2281
* #2280
* #2282

ConnectionClosed now reports peer node id

---

Cargo.lock
crates/bifrost/src/loglet/util.rs
crates/bifrost/src/loglet_wrapper.rs
crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/provider.rs
crates/invoker-impl/Cargo.toml
crates/invoker-impl/src/lib.rs
crates/types/src/logs/tail.rs
crates/worker/src/partition/mod.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2280).
* #2281
* __->__ #2280
* #2282

Misc logging minor improvements

---

crates/local-cluster-runner/src/node/mod.rs
crates/node/src/network_server/service.rs
crates/types/src/config/common.rs
crates/types/src/config_loader.rs
crates/types/src/net/mod.rs
server/tests/common/replicated_loglet.rs

closes https://github.com/restatedev/restate/issues/1609
PS. I hope the previous attempted PRs didn't spam anyone

derive bind address from advertised address if not set

---

crates/bifrost/src/providers/replicated_loglet/tasks/seal.rs

As per title
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2321).
* #2330
* #2329
* #2323
* __->__ #2321

[Bifrost] Don't log error if sealing fails on a single node

---

.github/workflows/ci.yml
crates/admin/src/schema_registry/mod.rs
crates/admin/src/schema_registry/updater.rs
crates/admin/src/service.rs
crates/ingress-kafka/src/consumer_task.rs
crates/ingress-kafka/src/dispatcher.rs
crates/ingress-kafka/src/subscription_controller.rs
crates/node/src/roles/admin.rs
crates/types/src/config/ingress.rs
crates/types/src/schema/subscriptions.rs
tools/xtask/src/main.rs

Fix #2100. I've tested this manually on my locally machine and it works fine.

Support shared handlers in Kafka ingress

---

benchmarks/src/lib.rs
crates/bifrost/benches/util.rs
crates/core/derive/src/tc_test.rs
crates/core/src/metadata/manager.rs
crates/core/src/task_center.rs
crates/core/src/task_center/handle.rs
crates/core/src/task_center/task.rs
crates/node/Cargo.toml
crates/partition-store/benches/basic_benchmark.rs
server/src/main.rs
tools/bifrost-benchpress/src/main.rs
tools/restatectl/src/environment/task_center.rs
tools/xtask/src/main.rs

Minor follow ups from code review

[TaskCenter] minor followups

---

cli/src/clients/cloud/schema.json
cli/src/commands/cloud/environments/configure.rs
cli/src/commands/cloud/environments/tunnel/local.rs

Currently the tunnel and proxy url are not set by describe cluster result, so they will use the default which is a .us.

Support eu clusters in cloud env tunnel

---

crates/storage-query-postgres/src/pgwire_server.rs

Run postgres-query-connection on TaskCenter.

Run postgres-query-connection on TaskCenter

---

Cargo.lock
Cargo.toml
crates/tracing-instrumentation/Cargo.toml
crates/tracing-instrumentation/src/lib.rs

Bump opentelemetry tracing dependencies to 0.27.0 and enable tls.

Bump opentelemetry tracing dependencies to 0.27.0 and enable tls

---

crates/local-cluster-runner/src/node/mod.rs
crates/tracing-instrumentation/src/lib.rs

Possible fix for the unstable cluster test
Summary:
Possible fix for issue https://github.com/restatedev/restate/issues/2160#issuecomment-2522549064

Possible fix for the unstable cluster test

---

server/Cargo.toml

`_RJEM_MALLOC_CONF="prof_leak:true,lg_prof_sample:0,prof_final:true" cargo run --bin restate-server --`

Enable profiling feature on jemalloc

---

crates/rocksdb/src/background.rs
crates/rocksdb/src/lib.rs
crates/rocksdb/src/rock_access.rs
server/src/main.rs
server/src/signal.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2398).
* #2401
* #2400
* #2399
* __->__ #2398

Enable on-demand flush+compaction via SIGUSR2

---

charts/restate-helm/values.yaml

This is not a sensible default (my bad!)

Stop debug logging in the helm chart

---

crates/node/src/network_server/service.rs

Memory would leak if you don't scrape metrics

Fix memory leak due to lack of prometheus metrics upkeep

---

Cargo.lock
crates/bifrost/Cargo.toml
crates/bifrost/src/providers/replicated_loglet/log_server_manager.rs
crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/network.rs
crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs
crates/bifrost/src/providers/replicated_loglet/sequencer.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs
crates/core/Cargo.toml
crates/core/src/network/connection_manager.rs
crates/core/src/network/net_util.rs
crates/core/src/network/networking.rs
crates/core/src/network/transport_connector.rs
crates/core/src/task_center/task_kind.rs
crates/node/src/network_server/service.rs
crates/storage-query-postgres/src/pgwire_server.rs
crates/types/src/config/bifrost.rs
crates/types/src/config/networking.rs
crates/types/src/replicated_loglet/params.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2423).
* #2427
* #2426
* #2424
* __->__ #2423
* #2422

[Bifrost] Sequencer resilience against slow connect operations

---

docs/dev/local-development.md

Have been confused by RocksDB bindings-related errors when trying to build locally.
The relevant [Discord discussion](https://discord.com/channels/1128210118216007792/1319976421912875059)

Add a mention of RocksDB fork in the local-development guide

---

crates/types/src/config_loader.rs

Use RecommendedWatcher instead of INotifyWatcher
Summary:
Fixes issue on MacOS

Use RecommendedWatcher instead of INotifyWatcher

---

Cargo.lock
crates/storage-query-postgres/Cargo.toml
crates/storage-query-postgres/src/pgwire_server.rs

While troubleshooting a startup connection error on macOS, I tried updating the version. The root cause turned out to be something else but this is done now.
Upstream changelog: https://github.com/sunng87/pgwire/compare/v0.25.0...v0.28.0

Upgrade pgwire to 0.28

---

crates/bifrost/src/providers/local_loglet/log_store.rs
crates/log-server/src/rocksdb_logstore/builder.rs

This avoids the issue where the wal is kept around for a long time to keep a tiny amount of bytes from the metadata cf (which will generally only be flushed on shutdown)

Always use atomic flushes in local-loglet

---

docker/Dockerfile
docker/debug.Dockerfile

Add `restatectl` and `restate` to the docker image

Add `restatectl` and `restate` to the docker image

---

Cargo.lock
crates/admin/src/cluster_controller/logs_controller.rs
crates/admin/src/cluster_controller/logs_controller/nodeset_selection.rs
crates/bifrost/src/providers/replicated_loglet/nodeset_selector.rs
crates/bifrost/src/providers/replicated_loglet/provider.rs
crates/storage-query-datafusion/src/mocks.rs
crates/storage-query-datafusion/src/table_providers.rs
crates/types/Cargo.toml
crates/types/protobuf/restate/cluster.proto
crates/types/src/logs/metadata.rs
crates/types/src/partition_table.rs
server/tests/cluster.rs
tools/restatectl/src/commands/cluster/config.rs
tools/restatectl/src/commands/cluster/provision.rs

Drop `NodeSetSelectionStrategy`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2513).
* #2516
* #2514
* #2517
* __->__ #2513
* #2512

Drop `NodeSetSelectionStrategy`

---

crates/admin/src/cluster_controller/grpc_svc_handler.rs
crates/core/protobuf/node_ctl_svc.proto
crates/node/src/lib.rs
crates/node/src/network_server/grpc_svc_handler.rs
crates/types/protobuf/restate/cluster.proto
crates/types/src/logs/metadata.rs
tools/restatectl/src/commands/cluster/config.rs
tools/restatectl/src/commands/cluster/config/set.rs
tools/restatectl/src/commands/cluster/provision.rs

Rename `DefaultProvider` -> `BifrostProvider`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2517).
* #2514
* __->__ #2517

Rename `DefaultProvider` -> `BifrostProvider`

---

crates/metadata-store/src/raft/storage.rs

In Raft it can happen that we need to overwrite persisted entries if a leader didn't manage to commit them (reach majority quorum). Another leader might decide to commit different entries. That's why the underlying storage must tolerate to overwrite entries.
This fixes #2535.

Allow raft::RocksDbStorage to overwrite entries

---

crates/types/src/config/common.rs

Add backwards compatibility to configure embedded MetadataStoreClient from a single address
Fixes #2527
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2532).
* #2544
* __->__ #2532

Add backwards compatibility to configure embedded MetadataStoreClient from a single address

---

crates/worker/src/partition/state_machine/mod.rs

This should reduce the number of written tombstones.

Remove only the journal we're using for the given invocation

---

crates/metadata-server/src/grpc/client.rs

Include remote metadata-store address in error message
Summary:
Make sure that the address of the remote metadata-store node is included
in the error message.

Include remote metadata-store address in error message

---

crates/metadata-server/src/raft/store.rs

Don't return a random known leader if metadata server does not know it.

Don't return a random known leader if metadata server does not know it

---

cli/src/clients/datafusion_helpers/mod.rs
cli/src/clients/datafusion_helpers/v1.rs
cli/src/clients/datafusion_helpers/v2.rs
cli/src/ui/invocations.rs
crates/storage-query-datafusion/src/journal/row.rs
crates/types/src/identifiers.rs
crates/types/src/journal_v2/command.rs
crates/types/src/journal_v2/event.rs
crates/types/src/journal_v2/mod.rs
crates/types/src/journal_v2/notification.rs

Example:
This is a very basic support, we'll reiterate on this in followups.

[CLI] Basic support for journal v2

---

crates/admin/src/cluster_controller/logs_controller.rs

This commit changes the LogsController::find_logs_tail operation to run the find_tail operations per log concurrently instead of sequentially.

Make LogsController::find_logs_tail run concurrent find_tail operations

---

crates/admin/src/cluster_controller/service/state.rs

Open on behalf of @pcholakov to replace #2662

Avoid doing a trim first thing on startup

---

crates/log-server/src/loglet_worker.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2654).
* #2672
* #2670
* #2669
* #2665
* #2664
* __->__ #2654

[LogServer] GET_LOGLET_INFO is high priority and drain workers on shutdown

---

tools/restatectl/src/commands/config.rs
tools/restatectl/src/commands/log/gen_metadata.rs
tools/restatectl/src/commands/log/reconfigure.rs

Fixing conflicts with -s, updating a few doc strings and using ReplicationProperty where replication is specified.

Minor fixes in restatectl

---

crates/storage-query-postgres/src/pgwire_server.rs

PSQL fix + deprecation

---

cli/src/cli_env.rs

Give precedence to RESTATE_INGRESS_URL and RESTATE_ADMIN_URL over RESTATE_HOST

---

tools/service-protocol-wireshark-dissector/Cargo.toml
tools/service-protocol-wireshark-dissector/README.md

For the sake of making things just work, I prefer to manually edit the deps file rather than this having people need to deal with imports problems (see https://github.com/restatedev/restate/pull/2773)

Simplify wireshark package lua features

---

.github/workflows/docker-push-release.yml

Fix condition when to push a Restate docker container image.

Fix condition when to push a Restate docker container image

---

Cargo.lock
crates/core/src/task_center.rs
crates/core/src/task_center/extensions.rs
crates/core/src/task_center/handle.rs
crates/core/src/task_center/monitoring.rs
crates/core/src/task_center/runtime.rs
crates/core/src/task_center/task.rs
crates/types/Cargo.toml
crates/types/src/lib.rs
crates/worker/src/partition/mod.rs
crates/worker/src/partition_processor_manager.rs
crates/worker/src/partition_processor_manager/spawn_processor_task.rs

Also removing all occurrences of Box::leak

Task-center uses shared strings

---

crates/types/src/config/object_store.rs
crates/types/src/config/worker.rs

Related: https://github.com/restatedev/documentation/pull/554

Update snapshots and object store credentials docs

---

crates/types/src/config/common.rs

The problem seems to be that a tagged enum variant always requires the type field. It only works with metadata-client not specifying the type because we have a default value that fills this field in.
This fixes #2809.

Support metadata-store-client.address configuration w/o specifying the type

---

crates/local-cluster-runner/examples/three_nodes.rs
crates/local-cluster-runner/src/node/mod.rs
server/tests/cluster.rs
server/tests/common/replicated_loglet.rs
server/tests/raft_metadata_cluster.rs
server/tests/trim_gap_handling.rs

Make three_nodes example to accept configuration overrides.

Make three_nodes example to accept configuration overrides

---

crates/partition-store/proto/dev/restate/storage/v1/domain.proto
crates/partition-store/src/protobuf_types.rs

Fix GenerationalNodeId should still be written.

---

deny.toml

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/2897).
* #2898
* __->__ #2897

humantime is now maintained

---

.github/workflows/ci.yml
.github/workflows/release.yml
dist-workspace.toml

Needed transitively by CI's Jepsen Tests job
Fixes #2922

Add missing id-token permission to Release workflow

---

crates/core/src/network/net_util.rs

Revert running HTTP channel builder on TaskCenterExecutor

---

crates/partition-store/benches/basic_benchmark.rs

Fix: https://github.com/restatedev/restate/issues/2895

fix(2895): avoid no reactor running when bench

---

server/tests/raft_metadata_cluster.rs

This commit hardens the raft_metadata_cluster_chaos test by waiting for a successful
write to the metadata store before killing another node. Moreover, we assume that the
raft metadata cluster can recover within 10s. Otherwise the test fails.

Harden raft metadata cluster chaos test

---

crates/bifrost/src/bifrost_admin.rs
crates/core/src/metadata_store.rs
crates/log-server/src/service.rs
crates/metadata-server/src/grpc/client.rs
crates/node/src/lib.rs
crates/types/src/metadata.rs
server/tests/raft_metadata_cluster.rs

This reverts commit 883d009060e674ae0082b053f2d3840ee61091f1.

Revert "Introduce RetryingMetadataStoreClient"

---

crates/storage-query-datafusion/src/context.rs
crates/storage-query-datafusion/src/lib.rs
crates/storage-query-datafusion/src/partition/row.rs
crates/storage-query-datafusion/src/partition_state/mod.rs
crates/storage-query-datafusion/src/partition_state/row.rs
crates/storage-query-datafusion/src/partition_state/schema.rs
crates/storage-query-datafusion/src/partition_state/table.rs
crates/types/src/cluster/cluster_state.rs

Datafusion partition_state table
Summary:
The `partition_state` reflects the actual observed partition state
as seen by this cluster controller node
A quick view of the cluster partitions can be retrieved as
```
estatectl sql "select p.*,s.* from partitions as p left join partition_state s on p.partition_id=s.partition_id and p.plain_node_id=s.plain_node_id order by p.partition_id"
PARTITION_ID  PLAIN_NODE_ID  TARGET_MODE  START_KEY             END_KEY               METADATA_VER  PARTITION_ID  PLAIN_NODE_ID  GEN_NODE_ID  TARGET_MODE  EFFECTIVE_MODE  UPDATED_AT     LEADER_EPOCH  LEADER  APPLIED_LOG_LSN  LAST_RECORD_APPLIED_AT    SKIPPED_RECORDS  REPLAY_STATUS  PERSISTED_LOG_LSN  ARCHIVED_LOG_LSN  TARGET_TAIL_LSN
0             N3             follower     0 …
```

Datafusion partition_state table

---

crates/node/src/network_server/metrics.rs
crates/tracing-instrumentation/src/prometheus_metrics.rs

cc @tillrohrmann , PTAL
ref: https://github.com/restatedev/restate/pull/2978

chore(*): improve cluster and node name metrics label computation

---

crates/cli-util/src/opts.rs

Fix: https://github.com/restatedev/restate/issues/3003

fix(3003): rename --insecure-skip-tls-verify option

---

crates/admin/Cargo.toml
crates/admin/src/cluster_controller/grpc_svc_handler.rs
crates/admin/src/lib.rs
crates/admin/src/query_utils.rs
crates/admin/src/storage_query/mod.rs
crates/admin/src/storage_query/query.rs

fix `admin` crate dependency on `storage-query` flag
Summary:
cluster controller had a dependency on a non default `storage-query` feature.
Fixes #3002

fix `admin` crate dependency on `storage-query` flag

---

crates/ingress-http/src/handler/error.rs
crates/ingress-http/src/rpc_request_dispatcher.rs

Improve error message for non idempotent requests

---

crates/admin/src/service.rs
crates/types/src/config/admin.rs

Currently you can do it at build time, but not at runtime.

Make web ui serving configurable

---

Cargo.lock
Cargo.toml
crates/bifrost/src/providers/replicated_loglet/metric_definitions.rs
crates/core/src/network/grpc/connector.rs
crates/invoker-impl/src/lib.rs
crates/invoker-impl/src/metric_definitions.rs
crates/queue/Cargo.toml
crates/types/Cargo.toml
crates/types/src/nodes_config.rs
crates/types/src/storage.rs
crates/types/src/storage/decode.rs
crates/types/src/storage/encode.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3030).
* #3031
* __->__ #3030
* #3029
* #3028
* #3007

Fixes for metric names

---

crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/provider.rs
crates/bifrost/src/service.rs
crates/bifrost/src/watchdog.rs
crates/core/src/task_center.rs
crates/core/src/task_center/task_kind.rs
crates/futures-util/src/overdue.rs
crates/log-server/src/loglet_worker.rs
crates/log-server/src/network.rs
crates/log-server/src/rocksdb_logstore/writer.rs
crates/node/src/init.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3059).
* __->__ #3059
* #3058
* #3057

Retry joining the cluster every 1s max

---

crates/log-server/src/rocksdb_logstore/builder.rs
crates/log-server/src/rocksdb_logstore/writer.rs
crates/rocksdb/src/db_manager.rs
crates/types/src/config/log_server.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3071).
* __->__ #3071
* #3062
* #3070

[Rocksdb] Speed up DB opens

---

tools/restatectl/src/commands/replicated_loglet/info.rs

Handle removed nodes correctly in `replicated-loglet info`
Fixes #3081

Handle removed nodes correctly in `replicated-loglet info`

---

crates/node/Cargo.toml
server/Cargo.toml

Fix: `local-loglet` feature enables wrong features

Fix: `local-loglet` feature enables wrong features

---

benchmarks/src/lib.rs
crates/bifrost/src/providers/local_loglet/log_store.rs
crates/types/src/config/bifrost.rs
crates/types/src/config/metadata_server.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3102).
* __->__ #3102
* #3101

Enable WAL compression for local loglet

---

crates/invoker-impl/src/error.rs
crates/tracing-instrumentation/src/pretty.rs
crates/types/src/errors.rs

Fix https://github.com/restatedev/restate/issues/2949

Improve error for protocol negotiation

---

.github/workflows/ci.yml

This adds on commit checks that runs the new e2e tests.

Enable E2E on CI

---

Cargo.lock
crates/core/src/network/connection.rs
crates/core/src/protobuf.rs
crates/metadata-server/src/grpc/client.rs
crates/types/Cargo.toml
crates/types/src/errors.rs
tools/restatectl/src/commands/metadata/patch.rs
tools/restatectl/src/connection.rs

to resolve https://github.com/restatedev/restate/issues/2607

Don't log details and metadata when logging Status error

---

crates/types/src/config/common.rs
crates/types/src/config/mod.rs

Fix: https://github.com/restatedev/restate/issues/1461

feat(1461): use working directory to validate nodename

---

cli/src/commands/examples.rs

this is what most people want to download anyway.

[CLI] Re-order examples download to have hello world at the top.

---

cli/src/commands/deployments/describe.rs
cli/src/commands/deployments/list.rs
cli/src/commands/deployments/register.rs
cli/src/commands/deployments/remove.rs
cli/src/commands/services/describe.rs
cli/src/commands/services/list.rs
crates/admin-rest-model/src/converters.rs
crates/admin-rest-model/src/deployments.rs
crates/admin/src/rest_api/deployments.rs
crates/admin/src/rest_api/mod.rs
crates/admin/src/rest_api/subscriptions.rs

Improve Admin API OpenAPI

---

crates/bifrost/src/bifrost.rs
crates/bifrost/src/watchdog.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3158).
* #3165
* #3164
* #3163
* #3162
* #3159
* __->__ #3158

Remove unused bifrost watchdog metadata sync

---

crates/bifrost/src/providers/replicated_loglet/loglet.rs
crates/bifrost/src/providers/replicated_loglet/read_path/read_stream_task.rs
crates/core/src/network/io/reactor.rs
crates/core/src/network/types.rs
crates/types/src/config/bifrost.rs
server/tests/replicated_loglet.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3167).
* #3164
* #3162
* #3159
* #3165
* __->__ #3167
* #3163

[minor] PeerAddress should be generational id

---

crates/worker/src/partition/state_machine/entries/mod.rs
crates/worker/src/partition/state_machine/lifecycle/migrate_journal_table.rs
crates/worker/src/partition/state_machine/lifecycle/pinned_deployment.rs

Fix issue with incorrect command count

---

crates/service-protocol/src/discovery.rs

Deprecation notice for old protocol

---

Cargo.lock
Cargo.toml
crates/encoding/Cargo.toml
crates/encoding/derive/Cargo.toml
crates/encoding/derive/src/bilrost.rs
crates/encoding/derive/src/lib.rs
crates/encoding/derive/src/net.rs
crates/encoding/src/lib.rs
crates/encoding/tests/net_serde.rs
crates/types/Cargo.toml
crates/types/benches/network_serialization.rs
crates/types/src/cluster/cluster_state.rs
crates/types/src/identifiers.rs
crates/types/src/logs/mod.rs
crates/types/src/net/codec.rs
crates/types/src/net/dto.rs
crates/types/src/net/metadata.rs
crates/types/src/net/mod.rs
crates/types/src/net/node.rs
crates/types/src/node_id.rs
crates/types/src/time.rs
crates/types/src/version.rs
workspace-hack/Cargo.toml

Using Bilrost for GetNodeStatus messages
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3172).
* #3176
* __->__ #3172
* #3190

Using Bilrost for GetNodeStatus messages

---

.github/workflows/docker.yml

See https://github.com/reproducible-containers/buildkit-cache-dance/pull/45

Fix building docker

---

crates/metadata-server/src/raft/server.rs

Instead of waiting only for the NodesConfiguration to tell us when we switched from Member to Standby state, this commit directly reacts to a configuration change where we removed ourselves. Otherwise, we might still process responses from other nodes because updating of the NodesConfiguration in the Metadata happens asynchronously from the KvMemoryStorage. Processing messages after we have removed ourselves can result in panics from the Raft library which doesn't expect this to happen.
This fixes #3204.

Leave member state when removing yourself from Raft configuration

---

cli/src/commands/examples.rs
crates/cli-util/src/ui/console.rs

Fix: https://github.com/restatedev/restate/issues/1074

fix(1074): Do not panic in CLI example command if interrupted

---

crates/core/src/cluster_state.rs
crates/core/src/lib.rs
crates/core/src/task_center.rs
crates/core/src/task_center/handle.rs
crates/core/src/test_env.rs
crates/partition-store/src/protobuf_types.rs
crates/types/build.rs
crates/types/src/config/common.rs
crates/types/src/config/gossip.rs
crates/types/src/config/mod.rs
crates/types/src/health.rs
crates/types/src/net/node.rs
crates/types/src/node_id.rs
crates/types/src/nodes_config.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3229).
* #3230
* __->__ #3229
* #3228
* #3226

[minor] Misc cleanups

---

crates/core/src/cluster_state.rs
crates/core/src/lib.rs
crates/core/src/task_center.rs
crates/core/src/task_center/handle.rs
crates/types/src/config/common.rs
crates/types/src/config/gossip.rs
crates/types/src/config/mod.rs
crates/types/src/net/node.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3228).
* #3230
* #3229
* __->__ #3228
* #3226

[FailureDetector] Gossip Configuration and Network Messages

---

.github/workflows/ci.yml
crates/local-cluster-runner/README.md
crates/local-cluster-runner/src/cluster/mod.rs
server/tests/cluster.rs
server/tests/common/replicated_loglet.rs
server/tests/raft_metadata_cluster.rs
server/tests/replicated_loglet.rs
server/tests/trim_gap_handling.rs
tools/restatectl/src/main.rs

Fix: https://github.com/restatedev/restate/issues/3205

fix(3205): upload test logs when failed

---

crates/partition-store/src/partition_store_manager.rs

Updates the PartitionStoreManager store lookup table to use a read-write lock, and only requires a read-only lock for creating snapshot checkpoints. The maximum export concurrency is bounded by reusing the RocksDB background threads config option (though explicit snapshotting doesn't happen in the background).
Note that opening/closing stores still contends with snapshot creation. This is unlikely to cause much slow-down on startup as a new worker is unlikely to be creating snapshots right away. This might cause some delay when a partition processor is due to be replaced and is being drained, as it might be requested to perform snapshots for some partitions while trying to close others. More likely, we might delay opening partition stores when a worker is busy creating snapshots, as …

Enable concurrent PartitionStore snapshot creation

---

crates/log-server/src/service.rs
crates/worker/src/partition_processor_manager.rs

Because the inner closure moved references and the first_attempt variable is bool, it was copied into the inner closure. Therefore, repeated attempts to update the Storage/WorkerState would always see first_attempt == true. As a consequence the server would panic when retrying and still thinking that it was the first attempt to update these values.
This problem manifested as some e2e tests failing with a panic.

Fix first_attempt detection when updating the Storage- and WorkerState

---

crates/admin/src/cluster_controller/scheduler.rs
crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs
crates/bifrost/src/providers/replicated_loglet/sequencer/appender.rs
crates/core/src/network/io/egress_stream.rs
crates/core/src/network/io/reactor.rs
crates/core/src/worker_api/partition_processor_rpc_client.rs
crates/log-server/src/loglet_worker.rs
crates/worker/src/partition_processor_manager.rs
crates/worker/src/partition_processor_manager/processor_state.rs

While debugging #3279 these I added a few more trace logs for better understanding the system.

Improve trace logging of various components

---

crates/bifrost/src/watchdog.rs

The idea would be that we have at most one trim r-w-u loop going at a time, with it instructed to handle all the trims we want to process. we ensure we have a loop kicked off whenever there are trims to handle. If more trims come in while we are handling the current one then they'll be handled as a group

Batch bifrost watchdog trim operations

---

crates/log-server-grpc/Cargo.toml
crates/metadata-server-grpc/Cargo.toml
crates/metadata-store/Cargo.toml

Set the features for tonic used in grpc crates

[chore] Set the features for tonic used in grpc crates

---

crates/bifrost/src/providers/local_loglet/provider.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3335).
* #3339
* #3330
* __->__ #3335

Fix local-loglet params generation

---

crates/bifrost/benches/replicated_loglet_serde.rs
crates/bifrost/src/providers/replicated_loglet/network.rs
crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs
crates/types/src/logs/metadata.rs
crates/types/src/logs/mod.rs
crates/types/src/net/replicated_loglet.rs

Fix: https://github.com/restatedev/restate/issues/3239

fix(3239): migrate replicated loglet message to bilrost

---

crates/invoker-impl/src/invocation_task/service_protocol_runner_v4.rs
crates/invoker-impl/src/lib.rs
crates/service-protocol-v4/src/entry_codec.rs
crates/types/src/journal_v2/command.rs
crates/types/src/journal_v2/encoding.rs
crates/types/src/journal_v2/event.rs
crates/types/src/journal_v2/mod.rs
crates/types/src/journal_v2/notification.rs
crates/types/src/journal_v2/raw.rs

As per title
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3368).
* #3361
* __->__ #3368

Reducing Clones in journal_v2 encode path

---

crates/admin/src/storage_query/query.rs

Before:
```
$ restate inv ls
Error: error decoding response body
Caused by:
├─ request or response body error
├─ error reading a body from connection
└─ unexpected EOF during chunk size line
```
After:
```
$ restate inv ls
Error: <UNKNOWN> datafusion failed: External error: Resources exhausted: Additional allocation failed with top memory consumers (across reservations) as: AggregateStream[0] consumed 0 bytes, RepartitionExec[1] consumed 0 bytes, AggregateStream[1] consumed 0 bytes, RepartitionExec[0] consumed 0 bytes. Error: Failed to allocate additional 16752 bytes for RepartitionExec[0] with 0 bytes already allocated for this reservation - 1 bytes remain available for the total pool
-> Http status code 500 Internal Server Error at 'http://localhost:9070/v2/query'
```

Return errors when datafusion runs out of memory

---

crates/bifrost/src/providers/replicated_loglet/network.rs
crates/bifrost/src/providers/replicated_loglet/remote_sequencer.rs
crates/bifrost/src/providers/replicated_loglet/tasks/find_tail.rs
crates/types/src/net/replicated_loglet.rs

SequencerStatus refactor
**This is a "folded" version of @mumbleskates work at https://github.com/restatedev/restate/pull/3365**
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3391).
* #3390
* __->__ #3391

SequencerStatus refactor

---

crates/service-client/src/http.rs
crates/types/src/config/http.rs

Configurable HTTP2 inital max send streams

Configurable HTTP2 inital max send streams

---

Cargo.lock
Cargo.toml
benchmarks/Cargo.toml
benchmarks/src/lib.rs
cli/Cargo.toml
crates/bifrost/Cargo.toml
crates/bifrost/benches/replicated_loglet_serde.rs
crates/invoker-impl/src/lib.rs
crates/local-cluster-runner/src/cluster/mod.rs
crates/metadata-server/src/raft/tests.rs
crates/queue/benches/queue_benchmark.rs
crates/types/Cargo.toml
crates/types/benches/network_serialization.rs
crates/types/src/config/mod.rs
crates/worker/src/partition/snapshots/repository.rs
deny.toml
workspace-hack/Cargo.toml

Updated a bunch of our dependencies to their latest versions.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3412).
* #3415
* __->__ #3412

[chore] Key dependencies update

---

Cargo.lock
crates/partition-store/src/idempotency_table/mod.rs
crates/partition-store/src/inbox_table/mod.rs
crates/partition-store/src/journal_table/mod.rs
crates/partition-store/src/journal_table_v2/mod.rs
crates/partition-store/src/promise_table/mod.rs
crates/storage-api/Cargo.toml
crates/storage-api/src/deduplication_table/mod.rs
crates/storage-api/src/idempotency_table/mod.rs
crates/storage-api/src/inbox_table/mod.rs
crates/storage-api/src/invocation_status_table/mod.rs
crates/storage-api/src/journal_table/mod.rs
crates/storage-api/src/journal_table_v2/mod.rs
crates/storage-api/src/outbox_table/mod.rs
crates/storage-api/src/promise_table/mod.rs
crates/storage-api/src/service_status_table/mod.rs
crates/storage-api/src/state_table/mod.rs
crates/storage-api/src/timer_table/mod.rs
crates/storage-query-datafusion/Cargo.toml
crates/storage-query-datafusion/src/idempotency/table.rs
crates/storage-query-datafusion/src/inbox/table.rs
crates/storage-query-datafusion/src/journal/table.rs
crates/storage-query-datafusion/src/promise/table.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3431).
* #3436
* #3433
* #3432
* __->__ #3431
* #3429

[DataFusion] Move promise and inbox tables to background iterators

---

.cargo/config.toml
.github/workflows/release.yml
.github/workflows/steps/release-build-setup.yml

This reverts commit 0d32fa2703a4ce688aa86990538bb219884f786e.
This fixes #3178.

Disable debug assertions in release builds

---

tools/restatectl/src/commands/metadata_server/nodes.rs

Show `metadata-server remove-node` errors
Summary:
Make sure to show the failure reason
```
Failed removing node 'N1' from the metadata cluster
├─ N2: Operation is not implemented or not supported
├─ N4: Internal error. command needs to be processed by the metadata cluster leader
├─ N3: Operation is not implemented or not supported
├─ N1: Operation is not implemented or not supported
```

Show `metadata-server remove-node` errors

---

crates/cloud-tunnel-client/Cargo.toml

hakari makes it hard to notice this stuff!

cloud-tunnel-client needs hyper server feature

---

crates/partition-store/src/fsm_table/mod.rs
crates/partition-store/src/tests/durable_lsn_tracking_test.rs
crates/storage-api/proto/dev/restate/storage/v1/domain.proto
crates/storage-api/src/fsm_table/mod.rs
crates/storage-api/src/protobuf_types.rs
crates/wal-protocol/src/control.rs
crates/wal-protocol/src/lib.rs
crates/worker/src/partition/mod.rs
crates/worker/src/partition/state_machine/mod.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3497).
* #3501
* __->__ #3497

Adds support for PartitionDurability in FSM

---

crates/types/src/partition_table.rs
crates/worker/src/partition/leadership/mod.rs
crates/worker/src/partition/mod.rs
crates/worker/src/partition_processor_manager.rs
crates/worker/src/partition_processor_manager/spawn_processor_task.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3501).
* #3526
* #3525
* #3524
* __->__ #3501

PP cleanup of passing config and partition table information

---

crates/admin/src/schema_registry/updater.rs

Fix issues when overwriting service and changing the type

---

Cargo.lock
crates/core/src/task_center.rs
crates/metadata-server/src/local/storage.rs
crates/metadata-server/src/raft/server.rs
crates/metadata-server/src/raft/storage/rocksdb_builder.rs
crates/node/src/network_server/metrics.rs
crates/partition-store/benches/basic_benchmark.rs
crates/partition-store/src/partition_store.rs
crates/partition-store/src/partition_store_manager.rs
crates/partition-store/src/tests/barrier_test.rs
crates/partition-store/src/tests/durable_lsn_tracking_test.rs
crates/partition-store/src/tests/mod.rs
crates/rocksdb/Cargo.toml
crates/rocksdb/src/db_manager.rs
crates/rocksdb/src/lib.rs
crates/rocksdb/src/rock_access.rs
crates/storage-query-datafusion/src/mocks.rs
crates/worker/src/lib.rs
crates/worker/src/partition/leadership/mod.rs
crates/worker/src/partition/state_machine/tests/mod.rs
crates/worker/src/partition_processor_manager.rs
server/src/main.rs
server/src/signal.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3540).
* #3542 (3 commits)
* __->__ #3540
* #3539 (3 commits)

[minor] Initial set of partitions is not needed any more in PSM

---

crates/types/src/epoch.rs

Name epoch field correctly in EpochMetadataShadow.

Name epoch field correctly in EpochMetadataShadow

---

tools/restatectl/src/commands/node/list_nodes.rs

Include location in restatectl node ls output.

Include location in restatectl node ls output

---

crates/admin/src/cluster_controller/service/scheduler.rs

By comparing the next version of the current epoch metadata with itself, we were always completing a reconfiguration. This could have led to completing a reconfiguration prematurely (while it did not fulfill the should_complete_reconfiguration criteria). Additionally, this commit improves the logging when transitioning from one partition configuration to another.

Fix bug in Scheduler::complete_reconfiguration which compared the wrong version

---

Cargo.lock
tools/mock-service-endpoint/Cargo.toml
tools/mock-service-endpoint/src/handler.rs
tools/mock-service-endpoint/src/listener.rs

Updated mock service endpoint to use protocol V5

Mock service endpoint uses protocol v5

---

crates/bifrost/src/bifrost.rs

The PR introduces two changes:
- `Bifrost::find_tail()` will only attempt to seal the chain if FindTailOpts asks for consistent result; we don't need to cripple the fast path for find-tail.
- Find tail will eagerly seal the chain without grace period. This is to avoid unnecessary startup delays for single-node setups.
The fact that chain sealing is idempotent makes it lighterweight to perform as it'll coalesce nicely with other reconfigurations that might be happening concurrently.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3595).
* #3599
* #3598
* #3597
* #3596
* __->__ #3595

[Bifrost] Eagerly seal the chain on find_tail that require consistency

---

crates/admin/src/cluster_controller/grpc_svc_handler.rs
crates/admin/src/cluster_controller/service.rs
crates/bifrost/src/bifrost.rs
crates/bifrost/src/bifrost_admin.rs
crates/bifrost/src/log_chain_extender.rs
crates/bifrost/src/read_stream.rs
crates/bifrost/src/service.rs
crates/bifrost/src/watchdog.rs
crates/core/protobuf/cluster_ctrl_svc.proto
crates/types/src/logs/metadata.rs
tools/restatectl/src/commands/log/describe_log.rs
tools/restatectl/src/commands/log/seal.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3598).
* #3599
* __->__ #3598
* #3597
* #3596
* #3595

[Bifrost] LogChainExtender is managed by watchdog

---

Cargo.toml
crates/core/src/task_center.rs
crates/core/src/task_center/builder.rs
crates/core/src/task_center/handle.rs
crates/core/src/task_center/task_kind.rs
crates/local-cluster-runner/examples/three_nodes.rs
crates/rocksdb/src/db_manager.rs
crates/types/src/net/node.rs
crates/worker/src/partition_processor_manager.rs
server/src/main.rs
tools/xtask/src/main.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3612).
* #3620
* #3619
* #3613
* __->__ #3612
* #3611
* #3618

[TaskCenter] spawn_unmanaged_child and scoped cancellations

---

Cargo.toml
crates/bifrost/src/background_appender.rs
crates/bifrost/src/watchdog.rs
crates/core/src/task_center.rs
crates/core/src/task_center/builder.rs
crates/core/src/task_center/handle.rs
crates/core/src/task_center/task_kind.rs
crates/local-cluster-runner/examples/three_nodes.rs
crates/log-server/src/loglet_worker.rs
crates/log-server/src/network.rs
crates/log-server/src/service.rs
crates/metadata-server/src/raft/network/networking.rs
crates/metadata-server/src/raft/tests.rs
crates/node/src/lib.rs
crates/node/src/roles/admin.rs
crates/node/src/roles/ingress.rs
crates/rocksdb/src/db_manager.rs
crates/types/src/net/node.rs
crates/worker/src/partition_processor_manager.rs
crates/worker/src/partition_processor_manager/spawn_processor_task.rs
server/src/main.rs
tools/restatectl/src/commands/log/dump_log.rs
tools/xtask/src/main.rs

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3613).
* #3620
* #3619
* __->__ #3613
* #3612
* #3611
* #3618

[Core] Use scoped cancellations and work towards clean graceful shutdown

---

crates/admin/src/schema_registry/updater.rs
crates/types/src/schema/service.rs

https://github.com/restatedev/restate/pull/3625 without everything else. For 1.4.4

Admin API workflow retention now displays correctly 

---

tools/restatectl/src/connection.rs

Adds a new mode which bypasses cluster node enumeration, and instead talks only to a single specified address. This is helpful when the target nodes are behind a load balancer. In the fullness of time we'll move more of the intra-cluster comms behind the cluster control service, so direct connectivity won't be required, but this is a useful workaround to have in the meantime.
```
~/restate/restatectl % cargo run --bin restatectl -- -S restate-XXXXXXXX.elb.eu-central-1.amazonaws.com status
...
Node Configuration (v13)
NODE-ID  NAME                                                                                               UPTIME   METADATA  LEADER  FOLLOWER  NODESET-MEMBER  SEQUENCER  ROLES
N1:2     arn:aws:ecs:eu-central-1:663487780041:task/restate-cluster-pavel/4b7b306b6c4e491ab9f15f397 …
```

[restatectl] Add single-address mode

---

crates/cloud-tunnel-client/src/client.rs

There is a failure mode of the tunnel server NLBs where the tcp conn opens fine, but we don't receive a HTTP2 handshake down it. In this scenario, cancellation doesn't lead the client to exit, because h2 graceful shutdown only kicks in after the HTTP2 handshake. So we end up hanging until the server closes the TCP conn. Instead, if we cancel before handshake is completed, we want to close the conn and return a clientclosed error
In addition, make the handshake timeout more robust. Previously it was really a 'trailers timeout' and didn't fire if the http2 handshake never starts. Now we do the timeout if for any reason we don't get a start result within 5s.

Handle shutdown while handshaking

---

Cargo.lock
Cargo.toml
charts/restate-helm/Chart.yaml

Bump version to v1.5.0-dev

---

cli/src/commands/cloud/environments/tunnel/local.rs
cli/src/commands/cloud/environments/tunnel/mod.rs

This is the logical destination of a set of changes:
1. Restate can now send http1.1 to https destinations, so --use-http1.1 can work even for tunnel servers (which are https)
2. Tunnel servers are now able to store whether the incoming request version was http1.1 as a header, so tunnel clients can initiate http1.1 over the final hop.
3. Therefore, the basic tunnel client in the CLI should respect this header. We already do so in the standalone tunnel client which lives outside this repo.
This change will allow you to, for example, use `restate cloud env tunnel` with local cf worker `wrangler dev` servers. However, it also necessitates Restate 1.5, which isn't in cloud yet.

Support use-http1.1 through tunneled connections

---

.github/workflows/ci.yml

Update just version
Summary:
Fix a CI error
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3654).
* #3651
* __->__ #3654

Update just version

---

Cargo.lock
Cargo.toml
crates/admin-rest-model/src/deployments.rs
crates/admin/src/rest_api/deployments.rs
crates/admin/src/schema_registry/mod.rs
crates/invoker-impl/src/invocation_task/service_protocol_runner.rs
crates/invoker-impl/src/invocation_task/service_protocol_runner_v4.rs
crates/service-client/Cargo.toml
crates/service-client/src/lambda.rs
crates/service-client/src/lib.rs
crates/service-protocol/src/discovery.rs
crates/types/src/config/aws.rs
crates/types/src/config/common.rs
crates/types/src/schema/deployment.rs
crates/types/src/service_discovery.rs
service-protocol/dev/restate/service/discovery.proto
service-protocol/endpoint_manifest_schema.json

Fix #3477, depends on https://github.com/restatedev/restate/pull/3671

Lambda compression support

---

crates/bifrost/src/providers/local_loglet/read_stream.rs
crates/log-server/src/rocksdb_logstore/store.rs

Thanks for catching the regression, @AhmedSoliman! I misread the comment initially - is this a more accurate explanation of what's going on in the local loglet reader?

Restore ignore-range-deletions option for local loglet DB

---

crates/core/src/lib.rs
crates/worker/src/metric_definitions.rs
crates/worker/src/partition/leadership/leader_state.rs

Re-add actions_total metric, with action label

---

Cargo.lock
Cargo.toml
workspace-hack/Cargo.toml

This is a default feature, but we have defaults off

Datafusion recursion protection

---

crates/errors/src/error_codes/RT0016.md

from conversation in https://github.com/restatedev/restate/issues/3656, this gives a better indication to what to do to the user.

Improve RT0016 description

---

crates/worker/src/partition/cleaner.rs

The cleaner is quite expensive and currently runs on all partitions at startup
The risk with this change is that a restate server that crashes repeatedly before it hits the 12 minute mark will never clean up its old invocations. Imo this is a worthwhile risk to take given the benefits to CPU usage at startup.

Jitter and delay cleaner on startup

---

Cargo.lock
Cargo.toml
charts/restate-helm/Chart.yaml

Creating release v1.5.0

---

crates/partition-store/src/journal_table/mod.rs
crates/partition-store/src/tests/journal_table_test/mod.rs
crates/storage-api/src/journal_table/mod.rs
crates/storage-api/src/lib.rs
crates/storage-query-datafusion/src/journal/tests.rs
crates/worker/src/partition/invoker_storage_reader.rs
crates/worker/src/partition/state_machine/entries/mod.rs
crates/worker/src/partition/state_machine/lifecycle/cancel.rs
crates/worker/src/partition/state_machine/lifecycle/migrate_journal_table.rs
crates/worker/src/partition/state_machine/lifecycle/notify_get_invocation_output_response.rs
crates/worker/src/partition/state_machine/lifecycle/notify_invocation_response.rs
crates/worker/src/partition/state_machine/lifecycle/notify_signal.rs
crates/worker/src/partition/state_machine/lifecycle/notify_sleep_completion.rs
crates/worker/src/partition/state_machine/lifecycle/pinned_deployment.rs
crates/worker/src/partition/state_machine/lifecycle/purge.rs
crates/worker/src/partition/state_machine/lifecycle/purge_journal.rs
crates/worker/src/partition/state_machine/lifecycle/restart_as_new.rs
crates/worker/src/partition/state_machine/mod.rs
crates/worker/src/partition/state_machine/tests/kill_cancel.rs
crates/worker/src/partition/state_machine/tests/mod.rs

[PartitionStore] Decouple read and write v1 journal traits
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3823).
* #3834
* #3833
* #3831
* #3830
* #3828
* #3827
* #3826
* #3825
* #3824
* __->__ #3823

[PartitionStore] Decouple read and write v1 journal traits

---

crates/partition-store/src/journal_table_v2/mod.rs
crates/partition-store/src/tests/journal_table_v2_test/mod.rs
crates/storage-api/src/journal_table_v2/mod.rs
crates/storage-api/src/lib.rs
crates/worker/src/partition/invoker_storage_reader.rs
crates/worker/src/partition/rpc/mod.rs
crates/worker/src/partition/rpc/restart_as_new_invocation.rs
crates/worker/src/partition/state_machine/entries/mod.rs
crates/worker/src/partition/state_machine/entries/notification.rs
crates/worker/src/partition/state_machine/lifecycle/cancel.rs
crates/worker/src/partition/state_machine/lifecycle/migrate_journal_table.rs
crates/worker/src/partition/state_machine/lifecycle/notify_get_invocation_output_response.rs
crates/worker/src/partition/state_machine/lifecycle/notify_invocation_response.rs
crates/worker/src/partition/state_machine/lifecycle/notify_signal.rs
crates/worker/src/partition/state_machine/lifecycle/notify_sleep_completion.rs
crates/worker/src/partition/state_machine/lifecycle/pinned_deployment.rs
crates/worker/src/partition/state_machine/lifecycle/purge.rs
crates/worker/src/partition/state_machine/lifecycle/purge_journal.rs
crates/worker/src/partition/state_machine/lifecycle/restart_as_new.rs
crates/worker/src/partition/state_machine/lifecycle/suspend.rs
crates/worker/src/partition/state_machine/mod.rs
crates/worker/src/partition/state_machine/tests/mod.rs

[PartitionStore] Decouple read and write v2 journal traits
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3824).
* #3834
* #3833
* #3831
* #3830
* #3828
* #3827
* #3826
* #3825
* __->__ #3824

[PartitionStore] Decouple read and write v2 journal traits

---

crates/partition-store/src/state_table/mod.rs
crates/partition-store/src/tests/state_table_test/mod.rs
crates/storage-api/src/lib.rs
crates/storage-api/src/state_table/mod.rs
crates/worker/src/partition/invoker_storage_reader.rs
crates/worker/src/partition/state_machine/entries/clear_all_state_command.rs
crates/worker/src/partition/state_machine/entries/clear_state_command.rs
crates/worker/src/partition/state_machine/entries/complete_awakeable_command.rs
crates/worker/src/partition/state_machine/entries/complete_promise_command.rs
crates/worker/src/partition/state_machine/entries/get_lazy_state_command.rs
crates/worker/src/partition/state_machine/entries/get_lazy_state_keys_command.rs
crates/worker/src/partition/state_machine/entries/mod.rs
crates/worker/src/partition/state_machine/entries/send_signal_command.rs
crates/worker/src/partition/state_machine/entries/set_state_command.rs
crates/worker/src/partition/state_machine/lifecycle/cancel.rs
crates/worker/src/partition/state_machine/lifecycle/notify_get_invocation_output_response.rs
crates/worker/src/partition/state_machine/lifecycle/notify_invocation_response.rs
crates/worker/src/partition/state_machine/lifecycle/notify_signal.rs
crates/worker/src/partition/state_machine/lifecycle/notify_sleep_completion.rs
crates/worker/src/partition/state_machine/lifecycle/pinned_deployment.rs
crates/worker/src/partition/state_machine/lifecycle/purge.rs
crates/worker/src/partition/state_machine/mod.rs
crates/worker/src/partition/state_machine/tests/mod.rs

[PartitionStore] Decouple read and write service state table traits
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/restatedev/restate/pull/3828).
* #3834
* #3833
* #3831
* #3830
* __->__ #3828

[PartitionStore] Decouple read and write service state table traits

---

crates/ingress-kafka/src/consumer_task.rs
crates/ingress-kafka/src/metric_definitions.rs

track kafka consumer lag, possible implementation for #3780

(chore): track kafka consumer lag
